[package]
name = "jet-driver"
version = "1.0.0"
edition = "2021"

[lib]
name = "jet_driver"
path = "src/lib.rs"

[dependencies]
jet-foundation = { path = "../jet-foundation" }
jet-lexer = { path = "../jet-lexer" }
jet-parser = { path = "../jet-parser" }
jet-comptime = { path = "../jet-comptime" }
jet-sema = { path = "../jet-sema" }
jet-codegen = { path = "../jet-codegen" }
