//! Canonical AOT projection rows for Core calls.
//!
//! D-ONCE-LAW1=A: each plain Core call states its module, member, Prelude
//! symbol, symbol scope, and argument borrow mask once here. AOT emission
//! looks the row up; it does not keep a second list.

/// Where AOT resolves a Core call's Rust symbol.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AotCoreCallSymbol {
    /// Prefix the symbol with the generated program's Prelude root.
    Prelude(&'static str),
    /// Emit the Rust symbol as written.
    Rust(&'static str),
}

impl AotCoreCallSymbol {
    pub const fn name(self) -> &'static str {
        match self {
            Self::Prelude(name) | Self::Rust(name) => name,
        }
    }
}

/// One plain AOT Core-call projection.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AotCoreCall {
    pub module: &'static str,
    pub member: &'static str,
    pub symbol: AotCoreCallSymbol,
    pub borrow_mask: &'static [bool],
}

impl AotCoreCall {
    const fn new(
        module: &'static str,
        member: &'static str,
        symbol: &'static str,
        prelude: bool,
        borrow_mask: &'static [bool],
    ) -> Self {
        Self {
            module,
            member,
            symbol: if prelude {
                AotCoreCallSymbol::Prelude(symbol)
            } else {
                AotCoreCallSymbol::Rust(symbol)
            },
            borrow_mask,
        }
    }
}

/// Every Core call whose AOT form is a plain symbol call.
pub const AOT_CORE_CALLS: &[AotCoreCall] = &[
    AotCoreCall::new("core.mem", "volatile_read", "std::ptr::read_volatile", false, &[false]),
    AotCoreCall::new("core.mem", "volatile_write", "std::ptr::write_volatile", false, &[false, false]),
    AotCoreCall::new("core.tasks", "interval", "jet_std::interval", true, &[false]),
    AotCoreCall::new("core.tasks", "yield_now", "jet_std::jet_task_yield", true, &[]),
    AotCoreCall::new("core.tasks", "current_task", "jet_std::jet_task_current_trace", true, &[]),
    AotCoreCall::new("core.reactive", "signal", "jet_std::JetSignal::new", true, &[false]), // D-REACT1=B: `reactive.signal(initial)` producer → a `JetSignal<T>`.
    AotCoreCall::new("core.event", "scope", "jet_std::JetEventScope::new", true, &[]), // D-EVENT1=D: first-party typed Event/Hook constructors.
    AotCoreCall::new("core.event", "policy_sync", "jet_std::JetEventPolicy::sync", true, &[]),
    AotCoreCall::new("core.science.measurement", "from", "jet_std::JetMeasurement::new", true, &[false, false]), // D-HONESTNUM1=A: `M.from(value, uncertainty)` → a `JetMeasurement<f64>`.
    AotCoreCall::new("core.math", "fraction", "jet_fraction_new", true, &[false, false]), // D-CORE-NUMERIC1=A: `core.math.decimal(s)` → exact parse.
    AotCoreCall::new("core.math", "decimal", "jet_decimal_from_str", true, &[true]),
    AotCoreCall::new("core.files", "read", "jet_std_fs_read", true, &[true]), // D-FILES-WRITE1 (merge, was `core.fs`): whole-file convenience helpers now // live in `core.files` alongside the streaming handle constructors below. // D-FILES-APPEND1=A: whole-file one-shot is `append_all`, not `append` — // that name stays reserved for the streaming handle's `.append(text)`.
    AotCoreCall::new("core.files", "read_bytes", "jet_std_fs_read_bytes", true, &[true]),
    AotCoreCall::new("core.files", "write", "jet_std_fs_write", true, &[true, true]),
    AotCoreCall::new("core.files", "append_all", "jet_std_fs_append", true, &[true, true]),
    AotCoreCall::new("core.files", "exists", "jet_std_fs_exists", true, &[true]),
    AotCoreCall::new("core.files", "remove", "jet_std_fs_remove", true, &[true]),
    AotCoreCall::new("core.files", "remove_dir", "jet_std_fs_remove_dir", true, &[true]),
    AotCoreCall::new("core.files", "remove_all", "jet_std_fs_remove_all", true, &[true]),
    AotCoreCall::new("core.files", "list_dir", "jet_std_fs_list_dir", true, &[true]),
    AotCoreCall::new("core.files", "create_dir", "jet_std_fs_create_dir", true, &[true]),
    AotCoreCall::new("core.files", "create_dir_all", "jet_std_fs_create_dir_all", true, &[true]),
    AotCoreCall::new("core.files", "is_dir", "jet_std_fs_is_dir", true, &[true]),
    AotCoreCall::new("core.files", "copy", "jet_std_fs_copy", true, &[true, true]),
    AotCoreCall::new("core.files", "copy_dir", "jet_std_fs_copy_dir", true, &[true, true]),
    AotCoreCall::new("core.files", "rename", "jet_std_fs_rename", true, &[true, true]),
    AotCoreCall::new("core.files", "symlink", "jet_std_fs_symlink", true, &[true, true]),
    AotCoreCall::new("core.files", "read_link", "jet_std_fs_read_link", true, &[true]),
    AotCoreCall::new("core.files", "hard_link", "jet_std_fs_hard_link", true, &[true, true]),
    AotCoreCall::new("core.files", "stat", "jet_std_fs_stat", true, &[true]),
    AotCoreCall::new("core.files", "canonicalize", "jet_std_fs_canonicalize", true, &[true]),
    AotCoreCall::new("core.files", "absolute", "jet_std_fs_absolute", true, &[true]),
    AotCoreCall::new("core.files", "walk", "jet_std_fs_walk", true, &[true]),
    AotCoreCall::new("core.files", "glob", "jet_std_fs_glob", true, &[true]),
    AotCoreCall::new("core.files", "read_at", "jet_std_fs_read_at", true, &[true, false, false]),
    AotCoreCall::new("core.files", "write_at", "jet_std_fs_write_at", true, &[true, false, true]),
    AotCoreCall::new("core.files", "fsync", "jet_std_fs_fsync", true, &[true]),
    AotCoreCall::new("core.files", "write_atomic", "jet_std_fs_write_atomic", true, &[true, true]),
    AotCoreCall::new("core.files", "temp_dir", "jet_std_fs_temp_dir", true, &[true]),
    AotCoreCall::new("core.files", "temp_file", "jet_std_fs_temp_file", true, &[true]),
    AotCoreCall::new("core.files", "lock", "jet_std_fs_lock", true, &[true]),
    AotCoreCall::new("core.watcher", "files", "jet_watcher_files", true, &[true]),
    AotCoreCall::new("core.watcher", "process_pid", "jet_watcher_process_pid", true, &[false]),
    AotCoreCall::new("core.watcher", "port", "jet_watcher_port", true, &[true, false]),
    AotCoreCall::new("core.watcher", "set", "jet_watcher_set", true, &[]),
    AotCoreCall::new("core.io", "args", "jet_std_io_args", true, &[]),
    AotCoreCall::new("core.args", "spec", "jet_args_spec", true, &[]), // D-ARGS1: `args.spec()` → empty builder.
    AotCoreCall::new("core.io", "confirm", "jet_std_io_confirm", true, &[true]),
    AotCoreCall::new("core.io", "choose", "jet_std_io_choose", true, &[true, true]),
    AotCoreCall::new("core.io", "input_secret", "jet_std_io_input_secret", true, &[true]),
    AotCoreCall::new("core.io", "read_all_input", "jet_std_io_read_all_input", true, &[]),
    AotCoreCall::new("core.io", "readline", "jet_std_io_readline", true, &[]),
    AotCoreCall::new("core.io", "read_until", "jet_std_io_read_until", true, &[true]),
    AotCoreCall::new("core.io", "take", "jet_std_io_take", true, &[false]),
    AotCoreCall::new("core.io", "buffered", "jet_std_io_buffered", true, &[]),
    AotCoreCall::new("core.io", "sprint", "jet_std_io_sprint", true, &[true]),
    AotCoreCall::new("core.io", "repr", "jet_std_io_repr", true, &[true]),
    AotCoreCall::new("core.io", "binread", "jet_std_io_binread", true, &[true]),
    AotCoreCall::new("core.io", "binwrite", "jet_std_io_binwrite", true, &[true, true]),
    AotCoreCall::new("core.io", "stdin", "jet_std_io_stdin", true, &[]), // D-STDIN1=A: io.stdin() → JetStdinReader handle.
    AotCoreCall::new("core.io", "stdout", "jet_std_io_stdout", true, &[]),
    AotCoreCall::new("core.io", "stderr", "jet_std_io_stderr", true, &[]),
    AotCoreCall::new("core.io", "terminal_width", "jet_std_io_terminal_width", true, &[]),
    AotCoreCall::new("core.io", "terminal_height", "jet_std_io_terminal_height", true, &[]),
    AotCoreCall::new("core.io", "style", "jet_std_io_style", true, &[true, true]),
    AotCoreCall::new("core.io", "style_force", "jet_std_io_style_force", true, &[true, true]),
    AotCoreCall::new("core.env", "get", "jet_std_env_get", true, &[true]),
    AotCoreCall::new("core.env", "set", "jet_std_env_set", true, &[true, true]),
    AotCoreCall::new("core.env", "unset", "jet_std_env_unset", true, &[true]),
    AotCoreCall::new("core.env", "vars", "jet_std_env_vars", true, &[]),
    AotCoreCall::new("core.env", "current_dir", "jet_std_env_current_dir", true, &[]),
    AotCoreCall::new("core.env", "home_dir", "jet_std_env_home_dir", true, &[]),
    AotCoreCall::new("core.os", "name", "jet_std_os_name", true, &[]),
    AotCoreCall::new("core.os", "family", "jet_std_os_family", true, &[]),
    AotCoreCall::new("core.os", "arch", "jet_std_os_arch", true, &[]),
    AotCoreCall::new("core.os", "cpu_count", "jet_std_os_cpu_count", true, &[]),
    AotCoreCall::new("core.os", "temp_dir", "jet_std_os_temp_dir", true, &[]),
    AotCoreCall::new("core.os", "executable", "jet_std_os_executable", true, &[]),
    AotCoreCall::new("core.os", "pid", "jet_std_os_pid", true, &[]),
    AotCoreCall::new("core.os", "getpid", "jet_std_os_pid", true, &[]),
    AotCoreCall::new("core.os", "hostname", "jet_std_os_hostname", true, &[]),
    AotCoreCall::new("core.os", "username", "jet_std_os_username", true, &[]),
    AotCoreCall::new("core.os", "release", "jet_std_os_release", true, &[]),
    AotCoreCall::new("core.os", "version", "jet_std_os_version", true, &[]),
    AotCoreCall::new("core.os", "expand", "jet_std_os_expand", true, &[true]),
    AotCoreCall::new("core.os", "getppid", "jet_std_os_getppid", true, &[]),
    AotCoreCall::new("core.os", "getuid", "jet_std_os_getuid", true, &[]),
    AotCoreCall::new("core.os", "geteuid", "jet_std_os_geteuid", true, &[]),
    AotCoreCall::new("core.os", "getgid", "jet_std_os_getgid", true, &[]),
    AotCoreCall::new("core.os", "getegid", "jet_std_os_getegid", true, &[]),
    AotCoreCall::new("core.os", "getgroups", "jet_std_os_getgroups", true, &[]),
    AotCoreCall::new("core.os", "getpgrp", "jet_std_os_getpgrp", true, &[]),
    AotCoreCall::new("core.os", "uptime", "jet_std_os_uptime", true, &[]),
    AotCoreCall::new("core.os", "loadavg", "jet_std_os_loadavg", true, &[]),
    AotCoreCall::new("core.os", "times", "jet_std_os_times", true, &[]),
    AotCoreCall::new("core.os", "sync", "jet_std_os_sync", true, &[]),
    AotCoreCall::new("core.os", "getpgid", "jet_std_os_getpgid", true, &[false]),
    AotCoreCall::new("core.os", "getsid", "jet_std_os_getsid", true, &[false]),
    AotCoreCall::new("core.os", "exitcode", "jet_std_os_exitcode", true, &[false]),
    AotCoreCall::new("core.os", "success", "jet_std_os_success", true, &[false]),
    AotCoreCall::new("core.os", "umask", "jet_std_os_umask", true, &[false]),
    AotCoreCall::new("core.os", "getpriority", "jet_std_os_getpriority", true, &[false]),
    AotCoreCall::new("core.os", "setpriority", "jet_std_os_setpriority", true, &[false, false]),
    AotCoreCall::new("core.os", "utime", "jet_std_os_utime", true, &[true, false, false]),
    AotCoreCall::new("core.os", "stop", "jet_std_os_stop", true, &[false]),
    AotCoreCall::new("core.os", "set_current_dir", "jet_std_os_set_current_dir", true, &[true]),
    AotCoreCall::new("core.os", "on_interrupt", "jet_std_os_on_interrupt", true, &[false]),
    AotCoreCall::new("core.os", "atexit", "jet_std_os_atexit", true, &[false]),
    AotCoreCall::new("core.os", "fork", "jet_std_os_fork", true, &[]),
    AotCoreCall::new("core.os", "setuid", "jet_std_os_setuid", true, &[false]),
    AotCoreCall::new("core.os", "setgid", "jet_std_os_setgid", true, &[false]),
    AotCoreCall::new("core.os", "setpgid", "jet_std_os_setpgid", true, &[false, false]),
    AotCoreCall::new("core.os", "setpgrp", "jet_std_os_setpgrp", true, &[]),
    AotCoreCall::new("core.os", "setsid", "jet_std_os_setsid", true, &[]),
    AotCoreCall::new("core.os", "initgroups", "jet_std_os_initgroups", true, &[true, false]),
    AotCoreCall::new("core.os", "kill", "jet_std_os_kill", true, &[false, false]),
    AotCoreCall::new("core.os", "wait", "jet_std_os_wait", true, &[]),
    AotCoreCall::new("core.os", "waitpid", "jet_std_os_waitpid", true, &[false, false]),
    AotCoreCall::new("core.os", "pipe", "jet_std_os_pipe", true, &[]),
    AotCoreCall::new("core.os", "close_fd", "jet_std_os_close_fd", true, &[false]),
    AotCoreCall::new("core.os", "mkfifo", "jet_std_os_mkfifo", true, &[true, false]),
    AotCoreCall::new("core.process", "exit", "jet_std_process_exit", true, &[false]),
    AotCoreCall::new("core.process", "run", "jet_std_process_run", true, &[true]),
    AotCoreCall::new("core.process", "cmd", "jet_std_process_cmd", true, &[true]),
    AotCoreCall::new("core.process", "pipeline", "jet_std_process_pipeline", true, &[true]),
    AotCoreCall::new("core.testing", "snap", "jet_testing_snap", true, &[true, true]),
    AotCoreCall::new("core.testing", "golden", "jet_testing_golden", true, &[true, true]),
    AotCoreCall::new("core.testing", "fixture", "jet_testing_fixture", true, &[true]),
    AotCoreCall::new("core.testing", "temp_dir", "jet_testing_temp_dir", true, &[true]),
    AotCoreCall::new("core.testing", "corpus", "jet_testing_corpus", true, &[true]),
    AotCoreCall::new("core.testing", "fake_clock", "jet_std_clock_new", true, &[false]),
    AotCoreCall::new("core.testing", "fake_rng", "jet_std_rng_new", true, &[false]),
    AotCoreCall::new("core.math", "round", "jet_std_math_round", true, &[false]),
    AotCoreCall::new("core.math", "isqrt", "jet_std_math_isqrt", true, &[false]),
    AotCoreCall::new("core.math", "factorial", "jet_std_math_factorial", true, &[false]),
    AotCoreCall::new("core.math", "erf", "jet_std_math_erf", true, &[false]),
    AotCoreCall::new("core.math", "erfc", "jet_std_math_erfc", true, &[false]),
    AotCoreCall::new("core.math", "gamma", "jet_std_math_gamma", true, &[false]),
    AotCoreCall::new("core.math", "lgamma", "jet_std_math_lgamma", true, &[false]),
    AotCoreCall::new("core.math", "logb", "jet_std_math_logb", true, &[false]),
    AotCoreCall::new("core.math", "significand", "jet_std_math_significand", true, &[false]),
    AotCoreCall::new("core.math", "ulp", "jet_std_math_ulp", true, &[false]),
    AotCoreCall::new("core.math", "cmp", "jet_std_math_cmp", true, &[false, false]),
    AotCoreCall::new("core.math", "next_after", "jet_std_math_next_after", true, &[false, false]),
    AotCoreCall::new("core.math", "ldexp", "jet_std_math_ldexp", true, &[false, false]),
    AotCoreCall::new("core.math", "scaleb", "jet_std_math_ldexp", true, &[false, false]),
    AotCoreCall::new("core.math", "ilogb", "jet_std_math_ilogb", true, &[false]),
    AotCoreCall::new("core.math", "leading_ones", "jet_std_math_leading_ones", true, &[false]),
    AotCoreCall::new("core.math", "trailing_ones", "jet_std_math_trailing_ones", true, &[false]),
    AotCoreCall::new("core.math", "digits", "jet_std_math_digits", true, &[false]),
    AotCoreCall::new("core.math", "binomial", "jet_std_math_binomial", true, &[false, false]),
    AotCoreCall::new("core.math", "checked_pow", "jet_std_math_checked_pow", true, &[false, false]),
    AotCoreCall::new("core.math", "int_pow", "jet_std_math_int_pow", true, &[false, false]),
    AotCoreCall::new("core.math", "gcd", "jet_std_math_gcd", true, &[false, false]),
    AotCoreCall::new("core.math", "lcm", "jet_std_math_lcm", true, &[false, false]),
    AotCoreCall::new("core.random", "int", "jet_std_random_int", true, &[false, false]),
    AotCoreCall::new("core.random", "float", "jet_std_random_float", true, &[]),
    AotCoreCall::new("core.random", "float_range", "jet_std_random_float_range", true, &[false, false]),
    AotCoreCall::new("core.random", "bool", "jet_std_random_bool", true, &[false]),
    AotCoreCall::new("core.random", "normal", "jet_std_random_normal", true, &[false, false]),
    AotCoreCall::new("core.random", "exponential", "jet_std_random_exponential", true, &[false]),
    AotCoreCall::new("core.random", "seed", "jet_std_random_seed", true, &[false]),
    AotCoreCall::new("core.random", "bytes", "jet_std_random_bytes", true, &[false]), // D-RANDSPLIT1=A: PRNG bytes — fast, NOT crypto-safe.
    AotCoreCall::new("core.crypto.random", "bytes", "jet_std_crypto_random_bytes", true, &[false]), // D-CRYPTO-RNG1=A: shared fail-closed OS CSPRNG provider.
    AotCoreCall::new("core.random", "rng", "jet_std_rng_new", true, &[false]), // D-DET1: deterministic injected RNG capability constructor.
    AotCoreCall::new("core.random", "split", "jet_std_random_split", true, &[false]),
    AotCoreCall::new("core.time", "now", "jet_std_time_now", true, &[]),
    AotCoreCall::new("core.time", "sleep", "jet_std_time_sleep", true, &[false]),
    AotCoreCall::new("core.time", "start", "jet_std_time_start", true, &[]),
    AotCoreCall::new("core.time", "instant", "jet_time_instant_now", true, &[]),
    AotCoreCall::new("core.time", "now_utc", "jet_time_now_utc", true, &[]),
    AotCoreCall::new("core.time", "from_unix_ms", "JetDateTime::from_unix_ms", false, &[false]),
    AotCoreCall::new("core.time", "today", "jet_time_today", true, &[]),
    AotCoreCall::new("core.time", "parse_rfc3339", "jet_time_parse_rfc3339", true, &[true]),
    AotCoreCall::new("core.time", "datetime", "jet_time_datetime", true, &[false, false, false, false, false, false]),
    AotCoreCall::new("core.time", "time", "JetLocalTime::new", false, &[false, false, false]),
    AotCoreCall::new("core.time", "local_time", "JetLocalTime::new", false, &[false, false, false]),
    AotCoreCall::new("core.time", "days_in_month", "jet_time_days_in_month", true, &[false, false]),
    AotCoreCall::new("core.time", "is_leap_year", "jet_time_is_leap_year", true, &[false]),
    AotCoreCall::new("core.time", "period", "jet_time_period", true, &[false, false, false]),
    AotCoreCall::new("core.time", "period_days", "jet_time_period_days", true, &[false]),
    AotCoreCall::new("core.time", "period_months", "jet_time_period_months", true, &[false]),
    AotCoreCall::new("core.time", "period_years", "jet_time_period_years", true, &[false]),
    AotCoreCall::new("core.time", "zone", "jet_time_zone_named", true, &[true]),
    AotCoreCall::new("core.time", "utc", "jet_time_zone_utc", true, &[]),
    AotCoreCall::new("core.time", "zoned", "jet_time_zoned", true, &[true, true]),
    AotCoreCall::new("core.time", "zoned_local", "jet_time_zoned_local", true, &[true, true, true]),
    AotCoreCall::new("core.time", "clock", "jet_std_clock_new", true, &[false]), // D-DET1: deterministic injected Clock capability constructor.
    AotCoreCall::new("core.encoding.json", "parse", "jet_std_json_parse", true, &[true]), // D-ENC1 + D-JSONVERB1 + D-SERDE6: unified `core.encoding.*`. The dynamic forms // (`JSON` tree / `[[String]]` / `Map`) keep their existing helpers; the typed // forms route through the Encode/Decode model, distinguished by the lowered arg // type (encode) or the resolved return type (decode). `is_json_value` etc. read // those total facts — codegen never re-infers (I3).
    AotCoreCall::new("core.encoding.json", "events", "jet_std_json_events", true, &[true]),
    AotCoreCall::new("core.encoding.jsonl", "parse", "jet_std_jsonl_parse", true, &[true]),
    AotCoreCall::new("core.encoding.jsonl", "to_string", "jet_std_jsonl_render", true, &[true]),
    AotCoreCall::new("core.encoding.csv", "parse", "jet_ring_csv_parse", true, &[true]),
    AotCoreCall::new("core.data", "count", "jet_data_count", true, &[true]),
    AotCoreCall::new("core.compute", "zeros", "jet_compute_zeros", true, &[true]), // D-COMPUTE1=D (#443): Tensor CPU oracle — one Prelude symbol per call.
    AotCoreCall::new("core.compute", "ones", "jet_compute_ones", true, &[true]),
    AotCoreCall::new("core.compute", "full", "jet_compute_full", true, &[true, false]),
    AotCoreCall::new("core.compute", "from_list", "jet_compute_from_list", true, &[true]),
    AotCoreCall::new("core.compute", "matrix", "jet_compute_matrix", true, &[false, false, false]),
    AotCoreCall::new("core.compute", "vec", "jet_compute_vec", true, &[false, false]),
    AotCoreCall::new("core.compute", "add", "jet_compute_add", true, &[true, true]),
    AotCoreCall::new("core.compute", "mul", "jet_compute_mul", true, &[true, true]),
    AotCoreCall::new("core.compute", "matmul", "jet_compute_matmul", true, &[true, true]),
    AotCoreCall::new("core.compute", "reshape", "jet_compute_reshape", true, &[true, true]),
    AotCoreCall::new("core.compute", "get", "jet_compute_get", true, &[true, true]),
    AotCoreCall::new("core.compute", "shape", "jet_compute_tensor_shape", true, &[true]),
    AotCoreCall::new("core.compute", "rank", "jet_compute_tensor_rank", true, &[true]),
    AotCoreCall::new("core.compute", "numel", "jet_compute_tensor_numel", true, &[true]),
    AotCoreCall::new("core.compute", "to_list", "jet_compute_tensor_to_list", true, &[true]),
    AotCoreCall::new("core.compute", "device", "jet_compute_tensor_device", true, &[true]),
    AotCoreCall::new("core.compute", "placement", "jet_compute_tensor_placement", true, &[true]),
    AotCoreCall::new("core.compute", "device_cpu", "jet_compute_device_cpu", true, &[]),
    AotCoreCall::new("core.compute", "device_auto", "jet_compute_device_auto", true, &[]),
    AotCoreCall::new("core.compute", "on_device", "jet_compute_on_device", true, &[true, false]),
    AotCoreCall::new("core.compute", "broadcast_to", "jet_compute_broadcast_to", true, &[true, true]),
    AotCoreCall::new("core.compute", "transpose", "jet_compute_transpose", true, &[true]),
    AotCoreCall::new("core.compute", "sum_axis", "jet_compute_sum_axis", true, &[true, false]),
    AotCoreCall::new("core.compute", "eye", "jet_compute_eye", true, &[false]),
    AotCoreCall::new("core.compute", "det", "jet_compute_det", true, &[true]),
    AotCoreCall::new("core.compute", "inv", "jet_compute_inv", true, &[true]),
    AotCoreCall::new("core.compute", "fft", "jet_compute_fft", true, &[true]),
    AotCoreCall::new("core.compute", "solve", "jet_compute_solve", true, &[true, true]),
    AotCoreCall::new("core.compute", "stream_new", "jet_compute_stream_new", true, &[]),
    AotCoreCall::new("core.compute", "stream_sync", "jet_compute_stream_sync", true, &[true]),
    AotCoreCall::new("core.compute", "stream_show", "jet_compute_stream_show", true, &[true]),
    AotCoreCall::new("core.compute", "transfer", "jet_compute_transfer", true, &[true, false]),
    AotCoreCall::new("core.compute", "transfer_show", "jet_compute_transfer_show", true, &[true]),
    AotCoreCall::new("core.compute", "kernel_bounds_ok", "jet_compute_kernel_bounds_ok", true, &[true, true]),
    AotCoreCall::new("core.compute", "mse_loss", "jet_compute_mse_loss", true, &[true, true]),
    AotCoreCall::new("core.compute", "sgd_step", "jet_compute_sgd_step", true, &[true, true, false]),
    AotCoreCall::new("core.compute", "serialize", "jet_compute_serialize", true, &[true]),
    AotCoreCall::new("core.compute", "deserialize", "jet_compute_deserialize", true, &[true]),
    AotCoreCall::new("core.compute", "to_sparse", "jet_compute_to_sparse", true, &[true]),
    AotCoreCall::new("core.compute", "sparse_nnz", "jet_compute_sparse_nnz", true, &[true]),
    AotCoreCall::new("core.compute", "sparse_mv", "jet_compute_sparse_mv", true, &[true, true]),
    AotCoreCall::new("core.compute", "sparse_show", "jet_compute_sparse_show", true, &[true]),
    AotCoreCall::new("core.compute", "matmul_f32_tile", "jet_compute_matmul_f32_tile", true, &[true, true]),
    AotCoreCall::new("core.compute", "profile_f32_strict", "jet_compute_profile_f32_strict", true, &[]),
    AotCoreCall::new("core.compute", "profile_show", "jet_compute_profile_show", true, &[]),
    AotCoreCall::new("core.services", "restart_one_for_one", "jet_services_restart_one_for_one", true, &[]),
    AotCoreCall::new("core.services", "restart_one_for_all", "jet_services_restart_one_for_all", true, &[]),
    AotCoreCall::new("core.services", "restart_rest_for_one", "jet_services_restart_rest_for_one", true, &[]),
    AotCoreCall::new("core.services", "delivery_at_most_once", "jet_services_delivery_at_most_once", true, &[]),
    AotCoreCall::new("core.services", "delivery_durable", "jet_services_delivery_durable", true, &[]),
    AotCoreCall::new("core.services", "mailbox_depth", "jet_services_mailbox_depth", true, &[true, true]),
    AotCoreCall::new("core.services", "restarts", "jet_services_restarts", true, &[true, true]),
    AotCoreCall::new("core.services", "dead_letter_count", "jet_services_dead_letter_count", true, &[true]),
    AotCoreCall::new("core.services", "restore_snapshot", "jet_services_restore_snapshot", true, &[true]),
    AotCoreCall::new("core.services", "event_count", "jet_services_event_count", true, &[true]),
    AotCoreCall::new("core.services", "replay_events", "jet_services_replay_events", true, &[true]),
    AotCoreCall::new("core.services", "workflow_history", "jet_services_workflow_history", true, &[true, false]),
    AotCoreCall::new("core.services", "directory_resolve", "jet_services_directory_resolve", true, &[true, true]),
    AotCoreCall::new("core.services", "directory_generation", "jet_services_directory_generation", true, &[true]),
    AotCoreCall::new("core.services", "upgrade_receipt", "jet_services_upgrade_receipt", true, &[true]),
    AotCoreCall::new("core.services", "observe", "jet_services_observe", true, &[true]),
    AotCoreCall::new("core.services", "endpoint_show", "jet_services_endpoint_show", true, &[true]),
    AotCoreCall::new("core.services", "tree_show", "jet_services_tree_show", true, &[true]),
    AotCoreCall::new("core.data", "table", "jet_data_table", true, &[true]),
    AotCoreCall::new("core.data", "rows", "jet_data_rows", true, &[true]),
    AotCoreCall::new("core.data", "series", "jet_data_series", true, &[true]),
    AotCoreCall::new("core.data", "values", "jet_data_series_values", true, &[true]),
    AotCoreCall::new("core.data", "missing_count", "jet_data_missing_count", true, &[true]),
    AotCoreCall::new("core.data", "lazy", "jet_data_lazy", true, &[true]),
    AotCoreCall::new("core.data", "plan", "jet_data_plan", true, &[true]),
    AotCoreCall::new("core.data", "filter", "jet_data_filter", true, &[true, false]),
    AotCoreCall::new("core.data", "lazy_filter", "jet_data_lazy_filter", true, &[true, false]),
    AotCoreCall::new("core.data", "lazy_sort_by", "jet_data_lazy_sort_by", true, &[true, false]),
    AotCoreCall::new("core.data", "status", "jet_data_status", true, &[]),
    AotCoreCall::new("core.data", "require_bridge", "jet_data_require_bridge", true, &[true]),
    AotCoreCall::new("core.data", "csv_reader", "jet_data_csv_reader", true, &[false, false]),
    AotCoreCall::new("core.data", "json_reader", "jet_data_json_reader", true, &[false, false]),
    AotCoreCall::new("core.fmt", "number", "jet_fmt_number", true, &[false]),
    AotCoreCall::new("core.fmt", "decimal", "jet_fmt_decimal", true, &[false, false]),
    AotCoreCall::new("core.fmt", "percent", "jet_fmt_percent", true, &[false, false]),
    AotCoreCall::new("core.fmt", "bytes", "jet_fmt_bytes", true, &[false]),
    AotCoreCall::new("core.fmt", "duration", "jet_fmt_duration", true, &[false]),
    AotCoreCall::new("core.fmt", "ordinal", "jet_fmt_ordinal", true, &[false]),
    AotCoreCall::new("core.fmt", "plural", "jet_fmt_plural", true, &[false, true, true]),
    AotCoreCall::new("core.fmt", "pad_left", "jet_fmt_pad_left", true, &[true, false, true]),
    AotCoreCall::new("core.fmt", "pad_right", "jet_fmt_pad_right", true, &[true, false, true]),
    AotCoreCall::new("core.fmt", "pad_center", "jet_fmt_pad_center", true, &[true, false, true]),
    AotCoreCall::new("core.encoding.toml", "parse", "jet_std_toml_parse", true, &[true]),
    AotCoreCall::new("core.encoding.yaml", "parse", "jet_std_yaml_parse", true, &[true]),
    AotCoreCall::new("core.encoding.xml", "parse", "jet_std_xml_parse", true, &[true]),
    AotCoreCall::new("core.encoding.xml", "parse_with", "jet_std_xml_parse_with", true, &[true, true]),
    AotCoreCall::new("core.encoding.xml", "to_string", "jet_std_xml_render", true, &[true]),
    AotCoreCall::new("core.encoding.xml", "canonical", "jet_std_xml_canonical", true, &[true, true]),
    AotCoreCall::new("core.encoding.xml", "root", "jet_std_xml_root", true, &[true]),
    AotCoreCall::new("core.encoding.xml", "attribute", "jet_std_xml_attribute", true, &[true, true]),
    AotCoreCall::new("core.encoding.xml", "content", "jet_std_xml_content", true, &[true]),
    AotCoreCall::new("core.encoding.cbor", "to_bytes", "jet_enc_cbor_to_bytes", true, &[true]),
    AotCoreCall::new("core.encoding.cbor", "to_bytes_canonical", "jet_enc_cbor_to_bytes_canonical", true, &[true]),
    AotCoreCall::new("core.encoding.hex", "encode", "jet_std_hex_encode", true, &[true]), // D-UUIDENC1=A: hex and base64 encode/decode.
    AotCoreCall::new("core.encoding.hex", "decode", "jet_std_hex_decode", true, &[true]),
    AotCoreCall::new("core.encoding.base64", "encode", "jet_std_b64_encode", true, &[true]),
    AotCoreCall::new("core.encoding.base64", "decode", "jet_std_b64_decode", true, &[true]),
    AotCoreCall::new("core.encoding.base64", "encode_url", "jet_std_b64url_encode", true, &[true]),
    AotCoreCall::new("core.encoding.base64", "decode_url", "jet_std_b64url_decode", true, &[true]),
    AotCoreCall::new("core.encoding.base32", "encode", "jet_std_base32_encode", true, &[true]),
    AotCoreCall::new("core.encoding.base32", "decode", "jet_std_base32_decode", true, &[true]),
    AotCoreCall::new("core.uuid", "v4", "jet_std_uuid_v4", true, &[]), // D-UUIDENC1=A: UUID v4 (CSPRNG) and v7 (injectable Clock).
    AotCoreCall::new("core.uuid", "v7", "jet_std_uuid_v7", true, &[true]),
    AotCoreCall::new("core.uuid", "v5", "jet_std_uuid_v5", true, &[true, true]), // #1481: `v5` (namespace+name, deterministic) and `parse` (validate // + normalize) — pure std, same UUID-as-String shape as v4/v7.
    AotCoreCall::new("core.uuid", "parse", "jet_std_uuid_parse", true, &[true]),
    AotCoreCall::new("core.files", "open", "jet_std_files_open", true, &[true]),
    AotCoreCall::new("core.files", "create", "jet_std_files_create", true, &[true]),
    AotCoreCall::new("core.files", "append", "jet_std_files_append", true, &[true]),
    AotCoreCall::new("core.path", "join", "jet_std_path_join", true, &[true, true]), // E2-M7: std.path helpers (D-IO1).
    AotCoreCall::new("core.path", "parent", "jet_std_path_parent", true, &[true]),
    AotCoreCall::new("core.path", "extension", "jet_std_path_extension", true, &[true]),
    AotCoreCall::new("core.path", "normalize", "jet_std_path_normalize", true, &[true]),
    AotCoreCall::new("core.url", "parse", "jet_url_parse", true, &[true]),
    AotCoreCall::new("core.url", "from_parts", "jet_url_from_parts", true, &[true, true, true, true, true]),
    AotCoreCall::new("core.url", "file", "jet_url_file", true, &[true]),
    AotCoreCall::new("core.url", "data", "jet_url_data", true, &[true, true]),
    AotCoreCall::new("core.url", "query", "jet_url_query", true, &[true]),
    AotCoreCall::new("core.url", "percent_encode", "jet_url_percent_encode_component", true, &[true]),
    AotCoreCall::new("core.url", "percent_decode", "jet_url_percent_decode_component", true, &[true]),
    AotCoreCall::new("core.mime", "parse", "jet_mime_parse", true, &[true]),
    AotCoreCall::new("core.mime", "from_extension", "jet_mime_from_extension", true, &[true]),
    AotCoreCall::new("core.mime", "extension", "jet_mime_extension", true, &[true]),
    AotCoreCall::new("core.email", "address", "jet_email::address", true, &[true]),
    AotCoreCall::new("core.email", "attachment", "jet_email::attachment", true, &[true, true, true]),
    AotCoreCall::new("core.email", "message", "jet_email::message", true, &[true, true, true, true, true, true, true]),
    AotCoreCall::new("core.email", "envelope", "jet_email::envelope", true, &[true, true]),
    AotCoreCall::new("core.email", "serialize", "jet_email::serialize", true, &[true]),
    AotCoreCall::new("core.text.unicode", "scalar_count", "jet_text_unicode_scalar_count", true, &[true]), // D-TEXTUNICODE1: std-only Unicode scalar helpers.
    AotCoreCall::new("core.text.unicode", "byte_count", "jet_text_unicode_byte_count", true, &[true]),
    AotCoreCall::new("core.text.unicode", "is_ascii", "jet_text_unicode_is_ascii", true, &[true]),
    AotCoreCall::new("core.text.unicode", "lower", "jet_text_unicode_lower", true, &[true]),
    AotCoreCall::new("core.text.unicode", "upper", "jet_text_unicode_upper", true, &[true]),
    AotCoreCall::new("core.text.unicode", "scalars", "jet_text_unicode_scalars", true, &[true]),
    AotCoreCall::new("core.text", "nfc", "jet_text_nfc", true, &[true]),
    AotCoreCall::new("core.text", "nfd", "jet_text_nfd", true, &[true]),
    AotCoreCall::new("core.text", "nfkc", "jet_text_nfkc", true, &[true]),
    AotCoreCall::new("core.text", "nfkd", "jet_text_nfkd", true, &[true]),
    AotCoreCall::new("core.text", "casefold", "jet_text_casefold", true, &[true]),
    AotCoreCall::new("core.text", "caseless_eq", "jet_text_caseless_eq", true, &[true, true]),
    AotCoreCall::new("core.text", "lower", "jet_text_lower", true, &[true]),
    AotCoreCall::new("core.text", "upper", "jet_text_upper", true, &[true]),
    AotCoreCall::new("core.text", "graphemes", "jet_text_graphemes", true, &[true]),
    AotCoreCall::new("core.text", "words", "jet_text_words", true, &[true]),
    AotCoreCall::new("core.text", "sentences", "jet_text_sentences", true, &[true]),
    AotCoreCall::new("core.text", "scalar_count", "jet_text_unicode_scalar_count", true, &[true]),
    AotCoreCall::new("core.text", "byte_count", "jet_text_unicode_byte_count", true, &[true]),
    AotCoreCall::new("core.text", "is_alphabetic", "jet_text_is_alphabetic", true, &[true]),
    AotCoreCall::new("core.text", "is_numeric", "jet_text_is_numeric", true, &[true]),
    AotCoreCall::new("core.text", "is_whitespace", "jet_text_is_whitespace", true, &[true]),
    AotCoreCall::new("core.text", "is_ascii", "jet_text_unicode_is_ascii", true, &[true]),
    AotCoreCall::new("core.text", "scalars", "jet_text_unicode_scalars", true, &[true]),
    AotCoreCall::new("core.text", "splitn", "jet_text_splitn", true, &[true, true, false]),
    AotCoreCall::new("core.text", "rsplitn", "jet_text_rsplitn", true, &[true, true, false]),
    AotCoreCall::new("core.text", "trim", "jet_text_trim", true, &[true]),
    AotCoreCall::new("core.text", "trim_start", "jet_text_trim_start", true, &[true]),
    AotCoreCall::new("core.text", "trim_end", "jet_text_trim_end", true, &[true]),
    AotCoreCall::new("core.text", "pad_start", "jet_text_pad_start", true, &[true, false, true]),
    AotCoreCall::new("core.text", "pad_end", "jet_text_pad_end", true, &[true, false, true]),
    AotCoreCall::new("core.text", "center", "jet_text_center", true, &[true, false, true]),
    AotCoreCall::new("core.text", "starts_any", "jet_text_starts_any", true, &[true, true]),
    AotCoreCall::new("core.text", "ends_any", "jet_text_ends_any", true, &[true, true]),
    AotCoreCall::new("core.text", "char_indices", "jet_text_char_indices", true, &[true]),
    AotCoreCall::new("core.log", "info", "jet_ring_log_info", true, &[true]), // E2-M9: first-party ring packages.
    AotCoreCall::new("core.log", "warn", "jet_ring_log_warn", true, &[true]),
    AotCoreCall::new("core.log", "error", "jet_ring_log_error", true, &[true]),
    AotCoreCall::new("core.log", "debug", "jet_ring_log_debug", true, &[true]),
    AotCoreCall::new("core.log", "critical", "jet_ring_log_critical", true, &[true]),
    AotCoreCall::new("core.log", "fatal", "jet_ring_log_fatal", true, &[true]),
    AotCoreCall::new("core.log", "disable", "jet_ring_log_disable", true, &[]),
    AotCoreCall::new("core.log", "flush", "jet_ring_log_flush", true, &[]),
    AotCoreCall::new("core.log", "enabled", "jet_ring_log_enabled", true, &[true]),
    AotCoreCall::new("core.log", "field", "jet_ring_log_field", true, &[true, true]),
    AotCoreCall::new("core.log", "int", "jet_ring_log_int", true, &[true, false]),
    AotCoreCall::new("core.log", "float", "jet_ring_log_float", true, &[true, false]),
    AotCoreCall::new("core.log", "bool", "jet_ring_log_bool", true, &[true, false]),
    AotCoreCall::new("core.log", "redact", "jet_ring_log_redact", true, &[true]),
    AotCoreCall::new("core.log", "info_fields", "jet_ring_log_info_fields", true, &[true, true]),
    AotCoreCall::new("core.log", "warn_fields", "jet_ring_log_warn_fields", true, &[true, true]),
    AotCoreCall::new("core.log", "error_fields", "jet_ring_log_error_fields", true, &[true, true]),
    AotCoreCall::new("core.log", "debug_fields", "jet_ring_log_debug_fields", true, &[true, true]),
    AotCoreCall::new("core.log", "span", "jet_ring_log_span", true, &[true]),
    AotCoreCall::new("core.log", "enter", "jet_ring_log_enter", true, &[true]),
    AotCoreCall::new("core.log", "close", "jet_ring_log_close", true, &[true]),
    AotCoreCall::new("core.log", "set_sink", "jet_ring_log_set_sink", true, &[true, true]),
    AotCoreCall::new("core.log", "sample_every", "jet_ring_log_sample_every", true, &[false]),
    AotCoreCall::new("core.log", "counter", "jet_ring_log_counter", true, &[true, false]),
    AotCoreCall::new("core.log", "otlp_file", "jet_ring_log_otlp_file", true, &[true]),
    AotCoreCall::new("core.log", "set_level", "jet_ring_log_set_level", true, &[true]),
    AotCoreCall::new("core.log", "set_trace_id", "jet_ring_log_set_trace_id", true, &[true]), // E2-M12 D-OBS3: trace context for structured log records.
    AotCoreCall::new("core.log", "setup", "jet_ring_log_setup", true, &[true]), // D-LOGFMT1=A: explicit log format override.
    AotCoreCall::new("core.crypto", "sha256_bytes", "jet_ring_crypto_sha256_bytes", true, &[true]),
    AotCoreCall::new("core.auth", "session_validate", "jet_auth_session_validate", true, &[true, false]),
    AotCoreCall::new("core.auth", "session_show", "jet_auth_session_show", true, &[true]),
    AotCoreCall::new("core.auth", "session_user", "jet_auth_session_user", true, &[true]),
    AotCoreCall::new("core.auth", "session_cookie", "jet_auth_session_cookie", true, &[true]),
    AotCoreCall::new("core.auth", "session_id", "jet_auth_session_id", true, &[true]),
    AotCoreCall::new("core.sync", "text_merge", "jet_sync_text_merge", true, &[true, true]),
    AotCoreCall::new("core.sync", "text_show", "jet_sync_text_show", true, &[true]),
    AotCoreCall::new("core.sync", "text_metadata", "jet_sync_text_metadata", true, &[true]),
    AotCoreCall::new("core.sync", "counter_merge", "jet_sync_counter_merge", true, &[true, true]),
    AotCoreCall::new("core.sync", "counter_value", "jet_sync_counter_value", true, &[true]),
    AotCoreCall::new("core.sync", "map_new", "jet_sync_map_new", true, &[]),
    AotCoreCall::new("core.sync", "map_get", "jet_sync_map_get", true, &[true, true]),
    AotCoreCall::new("core.sync", "map_merge", "jet_sync_map_merge", true, &[true, true]),
    AotCoreCall::new("core.sync", "map_show", "jet_sync_map_show", true, &[true]),
    AotCoreCall::new("core.sync", "list_new", "jet_sync_list_new", true, &[]),
    AotCoreCall::new("core.sync", "list_merge", "jet_sync_list_merge", true, &[true, true]),
    AotCoreCall::new("core.sync", "list_show", "jet_sync_list_show", true, &[true]),
    AotCoreCall::new("core.sync", "policy_allows", "jet_db_policy_allows", true, &[true, true, true]),
    AotCoreCall::new("core.sync", "policy_show", "jet_db_policy_show", true, &[true]),
    AotCoreCall::new("core.net", "ip_addr", "jet_net_ip_addr", true, &[true]), // D-NETSOCKET1=A: core.net — typed addresses, TCP/UDP/Unix/DNS, TLS handle.
    AotCoreCall::new("core.net", "ip_to_string", "jet_net_ip_to_string", true, &[true]),
    AotCoreCall::new("core.net", "ip_is_ipv4", "jet_net_ip_is_ipv4", true, &[true]),
    AotCoreCall::new("core.net", "socket_addr", "jet_net_socket_addr", true, &[true, false]),
    AotCoreCall::new("core.net", "socket_addr_parse", "jet_net_socket_addr_parse", true, &[true]),
    AotCoreCall::new("core.net", "socket_host", "jet_net_socket_host", true, &[true]),
    AotCoreCall::new("core.net", "socket_port", "jet_net_socket_port", true, &[true]),
    AotCoreCall::new("core.net", "socket_to_string", "jet_net_socket_to_string", true, &[true]),
    AotCoreCall::new("core.net", "tcp_listen", "jet_net_tcp_listen", true, &[true]),
    AotCoreCall::new("core.net", "tcp_listen_addr", "jet_net_tcp_listen_addr", true, &[true]),
    AotCoreCall::new("core.net", "tcp_accept", "jet_net_tcp_accept", true, &[true]),
    AotCoreCall::new("core.net", "tcp_connect", "jet_net_tcp_connect", true, &[true]),
    AotCoreCall::new("core.net", "tcp_connect_addr", "jet_net_tcp_connect_addr", true, &[true]),
    AotCoreCall::new("core.net", "tcp_connect_timeout", "jet_net_tcp_connect_timeout", true, &[true, false]),
    AotCoreCall::new("core.net", "tcp_connect_happy", "jet_net_tcp_connect_happy", true, &[true, false, false]),
    AotCoreCall::new("core.net", "ready_readable", "jet_net_ready_readable", true, &[true]),
    AotCoreCall::new("core.net", "ready_writable", "jet_net_ready_writable", true, &[true]),
    AotCoreCall::new("core.net", "error_operation", "jet_net_error_operation", true, &[true]),
    AotCoreCall::new("core.net", "error_address", "jet_net_error_address", true, &[true]),
    AotCoreCall::new("core.net", "error_name", "jet_net_error_name", true, &[true]),
    AotCoreCall::new("core.net", "error_message", "jet_net_error_message", true, &[true]),
    AotCoreCall::new("core.net", "error_os_code", "jet_net_error_os_code", true, &[true]),
    AotCoreCall::new("core.net", "tcp_local_addr", "jet_net_tcp_local_addr", true, &[true]),
    AotCoreCall::new("core.net", "tcp_peer_addr", "jet_net_tcp_peer_addr", true, &[true]),
    AotCoreCall::new("core.net", "tcp_local_socket_addr", "jet_net_tcp_local_socket_addr", true, &[true]),
    AotCoreCall::new("core.net", "tcp_peer_socket_addr", "jet_net_tcp_peer_socket_addr", true, &[true]),
    AotCoreCall::new("core.net", "listener_local_socket_addr", "jet_net_listener_local_socket_addr", true, &[true]),
    AotCoreCall::new("core.net", "nodelay", "jet_net_nodelay", true, &[true]),
    AotCoreCall::new("core.net", "set_nodelay", "jet_net_set_nodelay", true, &[true, false]),
    AotCoreCall::new("core.net", "ttl", "jet_net_ttl", true, &[true]),
    AotCoreCall::new("core.net", "set_ttl", "jet_net_set_ttl", true, &[true, false]),
    AotCoreCall::new("core.net", "socket_type", "jet_net_socket_type", true, &[true]),
    AotCoreCall::new("core.net", "tcp_reply", "jet_net_tcp_reply", true, &[false, true, true]),
    AotCoreCall::new("core.net", "udp_bind", "jet_net_udp_bind", true, &[true]),
    AotCoreCall::new("core.net", "udp_bind_addr", "jet_net_udp_bind_addr", true, &[true]),
    AotCoreCall::new("core.net", "udp_local_addr", "jet_net_udp_local_addr", true, &[true]),
    AotCoreCall::new("core.net", "udp_set_timeout", "jet_net_udp_set_timeout", true, &[true, false]),
    AotCoreCall::new("core.net", "udp_send_to", "jet_net_udp_send_to", true, &[true, true, true]),
    AotCoreCall::new("core.net", "udp_recv_from", "jet_net_udp_recv_from", true, &[true, false]),
    AotCoreCall::new("core.net", "udp_send_bytes_to", "jet_net_udp_send_bytes_to", true, &[true, true, true]),
    AotCoreCall::new("core.net", "udp_receive", "jet_net_udp_receive", true, &[true, false]),
    AotCoreCall::new("core.net", "udp_packet_data", "jet_net_udp_packet_data", true, &[true]),
    AotCoreCall::new("core.net", "udp_packet_addr", "jet_net_udp_packet_addr", true, &[true]),
    AotCoreCall::new("core.net", "udp_packet_bytes", "jet_net_udp_packet_bytes", true, &[true]),
    AotCoreCall::new("core.net", "udp_packet_original_len", "jet_net_udp_packet_original_len", true, &[true]),
    AotCoreCall::new("core.net", "udp_packet_truncated", "jet_net_udp_packet_truncated", true, &[true]),
    AotCoreCall::new("core.net", "unix_listen", "jet_net_unix_listen", true, &[true]),
    AotCoreCall::new("core.net", "unix_accept", "jet_net_unix_accept", true, &[true]),
    AotCoreCall::new("core.net", "getservbyname", "jet_net_getservbyname", true, &[true]),
    AotCoreCall::new("core.net", "getservbyport", "jet_net_getservbyport", true, &[false]),
    AotCoreCall::new("core.net", "dns_srv_target", "jet_net_dns_srv_target", true, &[true]),
    AotCoreCall::new("core.net", "dns_srv_port", "jet_net_dns_srv_port", true, &[true]),
    AotCoreCall::new("core.net", "dns_srv_priority", "jet_net_dns_srv_priority", true, &[true]),
    AotCoreCall::new("core.net", "dns_srv_weight", "jet_net_dns_srv_weight", true, &[true]),
    AotCoreCall::new("core.http", "router", "jet_http_router_new", true, &[]), // c109 Phase 25: HTTPRouter producer + parse/dispatch (D-ROUTE1=A). `router()` is arg-free; `parse(raw)` borrows the raw string; `dispatch(router, req)` borrows the router and passes the request by value.
    AotCoreCall::new("core.http", "parse", "jet_http_parse_request", true, &[true]),
    AotCoreCall::new("core.http", "dispatch", "jet_http_router_dispatch", true, &[true, false]),
    AotCoreCall::new("core.regex", "flags", "jet_std::jet_regex_flags", true, &[false, false, false]), // D-REGEXENGINE1=A: core.regex — std-only runtime in jet_std, no bridge dep.
    AotCoreCall::new("core.regex", "escape", "jet_std::jet_regex_escape", true, &[true]),
    AotCoreCall::new("core.regex", "compile", "jet_std::jet_regex_compile", true, &[true]),
    AotCoreCall::new("core.regex", "compile_with", "jet_std::jet_regex_compile_with", true, &[true, true]),
    AotCoreCall::new("core.regex", "literal", "jet_std::jet_regex_literal", true, &[true]),
    AotCoreCall::new("core.regex", "is_match", "jet_std::jet_regex_is_match", true, &[true, true]),
    AotCoreCall::new("core.regex", "match", "jet_std::jet_regex_match", true, &[true, true]),
    AotCoreCall::new("core.regex", "find", "jet_std::jet_regex_find", true, &[true, true]),
    AotCoreCall::new("core.regex", "find_all", "jet_std::jet_regex_find_all", true, &[true, true]),
    AotCoreCall::new("core.regex", "matches", "jet_std::jet_regex_matches", true, &[true, true]),
    AotCoreCall::new("core.regex", "split", "jet_std::jet_regex_split", true, &[true, true]),
    AotCoreCall::new("core.regex", "split_limit", "jet_std::jet_regex_split_limit", true, &[true, true, false]),
    AotCoreCall::new("core.regex", "replace", "jet_std::jet_regex_replace", true, &[true, true, true]),
    AotCoreCall::new("core.regex", "replace_all", "jet_std::jet_regex_replace_all", true, &[true, true, true]),
    AotCoreCall::new("core.raylib", "window_open", "jet_raylib_window_open", true, &[false, false, true]), // D-RAYLIB1=A / D-FLAGSHIP-RAYLIB1=A: typed graphics bridge.
    AotCoreCall::new("core.raylib", "window_should_close", "jet_raylib_window_should_close", true, &[true]),
    AotCoreCall::new("core.raylib", "window_ready", "jet_raylib_window_ready", true, &[true]),
    AotCoreCall::new("core.raylib", "begin_drawing", "jet_raylib_begin_drawing", true, &[true]),
    AotCoreCall::new("core.raylib", "clear_background", "jet_raylib_clear_background", true, &[true]),
    AotCoreCall::new("core.raylib", "draw_text", "jet_raylib_draw_text", true, &[true, false, false, false, true]),
    AotCoreCall::new("core.raylib", "draw_rectangle", "jet_raylib_draw_rectangle", true, &[false, false, false, false, true]),
    AotCoreCall::new("core.raylib", "end_drawing", "jet_raylib_end_drawing", true, &[]),
    AotCoreCall::new("core.raylib", "close_window", "jet_raylib_close_window", true, &[true]),
    AotCoreCall::new("core.raylib", "key_down", "jet_raylib_key_down", true, &[true]),
    AotCoreCall::new("core.raylib", "set_target_fps", "jet_raylib_set_target_fps", true, &[false]),
    AotCoreCall::new("core.raylib", "load_sound", "jet_raylib_load_sound", true, &[true]),
    AotCoreCall::new("core.raylib", "play_sound", "jet_raylib_play_sound", true, &[true]),
    AotCoreCall::new("core.raylib", "color", "jet_raylib_color", true, &[false, false, false, false]),
    AotCoreCall::new("core.db", "params", "jet_std::jet_db_params_from_sql", true, &[true]),
    AotCoreCall::new("core.db", "row_value", "jet_std::jet_db_row_value", true, &[true, true]),
    AotCoreCall::new("core.db", "row_int", "jet_std::jet_db_row_int", true, &[true, true]),
    AotCoreCall::new("core.db", "row_float", "jet_std::jet_db_row_float", true, &[true, true]),
    AotCoreCall::new("core.db", "row_text", "jet_std::jet_db_row_text", true, &[true, true]),
    AotCoreCall::new("core.db", "row_bool", "jet_std::jet_db_row_bool", true, &[true, true]),
    AotCoreCall::new("core.db", "transaction", "jet_db_scope_transaction", false, &[true, true, true]),
    AotCoreCall::new("core.db", "migrate", "jet_db_scope_migrate", false, &[true, true, true]),
    AotCoreCall::new("core.random", "pick", "jet_std_random_pick", true, &[true]),
    AotCoreCall::new("core.random", "weighted_pick", "jet_std_random_weighted_pick", true, &[true, true]),
    AotCoreCall::new("core.random", "sample", "jet_std_random_sample", true, &[true, false]),
    AotCoreCall::new("core.term", "read_key", "jet_term_read_key", true, &[]), // D-TERM1 (ratified 2026-06-22): terminal direct-input.
    AotCoreCall::new("core.perf", "fidelity", "jet_perf_fidelity", false, &[]), // D-FIDELITY-API1=A: runtime-global fidelity signal.
    AotCoreCall::new("core.perf", "default_fidelity", "jet_perf_default_fidelity", false, &[]),
    AotCoreCall::new("core.perf", "override_fidelity", "jet_perf_override_fidelity", false, &[false]),
    AotCoreCall::new("core.perf", "reset_fidelity", "jet_perf_reset_fidelity", false, &[]),
    AotCoreCall::new("core.ui", "null_backend", "jet_ui_null", true, &[]), // D-RENDERTGT2=A (c133 M1): UI backend seam constructors.
    AotCoreCall::new("core.ui", "tui_backend", "jet_ui_tui", true, &[]),
    AotCoreCall::new("core.ui", "gtk_backend", "jet_ui_gtk", true, &[]), // D-UIDEVSHELL1=A (c134 Phase 8): native Linux GTK4 backend constructor.
    AotCoreCall::new("core.ui", "point", "jet_ui_point", true, &[false, false]),
    AotCoreCall::new("core.ui", "size", "jet_ui_size", true, &[false, false]),
    AotCoreCall::new("core.ui", "rect", "jet_ui_rect", true, &[false, false, false, false]),
    AotCoreCall::new("core.ui", "constraint", "jet_ui_constraint", true, &[false, false, false, false]),
    AotCoreCall::new("core.ui", "node", "jet_ui_node", true, &[true, false, false]),
    AotCoreCall::new("core.ui", "text", "jet_ui_text", true, &[true]),
    AotCoreCall::new("core.ui", "button", "jet_ui_button", true, &[true]),
    AotCoreCall::new("core.ui", "key_event", "jet_ui_key_event", true, &[true]),
    AotCoreCall::new("core.ui", "resize_event", "jet_ui_resize_event", true, &[false, false]),
    AotCoreCall::new("core.ui", "node_role", "jet_ui_node_role", true, &[true, false, false, false]), // D-A11YGATE1=B (c134 Phase 6): accessible-role node + role constants.
    AotCoreCall::new("core.ui", "node_color", "jet_ui_node_color", true, &[true, false, false, true]), // D-STYLESHAPE1=A wiring: a node carrying an explicit fill color.
    AotCoreCall::new("core.ui", "aria_role_button", "jet_ui_aria_role_button", true, &[]),
    AotCoreCall::new("core.ui", "aria_role_text_input", "jet_ui_aria_role_text_input", true, &[]),
    AotCoreCall::new("core.ui", "aria_role_label", "jet_ui_aria_role_label", true, &[]),
    AotCoreCall::new("core.ui", "aria_role_container", "jet_ui_aria_role_container", true, &[]),
    AotCoreCall::new("core.web", "app", "jet_web_app", true, &[]), // D-WEBAPP1=D: application builder + page helper.
    AotCoreCall::new("app", "live_get", "jet_app_live_get", true, &[true]),
    AotCoreCall::new("core.web", "live_get", "jet_app_live_get", true, &[true]),
    AotCoreCall::new("app", "live_show", "jet_app_live_show", true, &[true]),
    AotCoreCall::new("core.web", "live_show", "jet_app_live_show", true, &[true]),
    AotCoreCall::new("app", "live_stats", "jet_app_live_stats", true, &[]),
    AotCoreCall::new("core.web", "live_stats", "jet_app_live_stats", true, &[]),
    AotCoreCall::new("app", "auth_routes", "jet_app_auth_routes", true, &[true]),
    AotCoreCall::new("core.web", "auth_routes", "jet_app_auth_routes", true, &[true]),
    AotCoreCall::new("app", "auth_show", "jet_app_auth_show", true, &[true]),
    AotCoreCall::new("core.web", "auth_show", "jet_app_auth_show", true, &[true]),
    AotCoreCall::new("core.web.devserver", "for_app", "jet_devserver_for_app", true, &[true]), // c-devserver (owner-directed 2026-07-01): `devserver.for_app(file)` // constructor — the builder methods dispatch through // `THandleOp::DevServerMethod` above, not here.
    AotCoreCall::new("core.web.devserver", "app", "jet_devserver_app", true, &[]),
    AotCoreCall::new("core.sketch.hll", "new", "JetHyperLogLog::new", false, &[]), // D-APPROX1=A: sketch constructors.
    AotCoreCall::new("core.sketch.tdigest", "new", "JetTDigest::new", false, &[]),
    AotCoreCall::new("core.sketch.cms", "new", "JetCountMinSketch::new", false, &[]),
    AotCoreCall::new("core.sketch.reservoir", "new", "JetReservoirSampler::new", false, &[false]),
    AotCoreCall::new("core.browser", "profile", "jet_browser_profile", false, &[true]), // D-BROWSER-AUTO1=A: native versioned BiDi entry points.
    AotCoreCall::new("core.browser", "timeout", "jet_browser_timeout", false, &[false]),
    AotCoreCall::new("core.browser", "locked", "jet_browser_locked", false, &[true]),
    AotCoreCall::new("core.browser", "connect", "jet_browser_connect", false, &[true]),
    AotCoreCall::new("core.browser", "connect_profile", "jet_browser_connect_profile", false, &[true, true, false]),
    AotCoreCall::new("core.http.server", "mux", "jet_http_mux_new", false, &[]),
    AotCoreCall::new("core.http.server", "response", "jet_http_srv_response", false, &[false, true]),
    AotCoreCall::new("core.http.server", "tls", "jet_http_srv_tls", false, &[true, true]),
    AotCoreCall::new("core.http.server", "sse", "jet_http_srv_sse", false, &[true]),
    AotCoreCall::new("core.http.server", "json", "jet_http_srv_json", false, &[false, true]), // D-HTTP-JSON1=A: one JSON response with its content type set.
    AotCoreCall::new("core.http.server", "cors", "jet_http_srv_install_cors", false, &[true, true]),
    AotCoreCall::new("core.http.server", "access_log", "jet_http_srv_access_log", false, &[true, false]),
    AotCoreCall::new("core.http.server", "request_id", "jet_http_srv_install_request_id", false, &[true]),
    AotCoreCall::new("core.ws", "connect", "jet_ws_connect", false, &[true]), // D-WS1=B: cleartext WebSocket client/server.
    AotCoreCall::new("core.ws", "upgrade", "jet_ws_upgrade", false, &[true]),
    AotCoreCall::new("core.time.date", "new", "JetDate::new", false, &[false, false, false]), // D-TIMEDEPTH1=A: civil-time constructors.
    AotCoreCall::new("core.time.date", "today", "JetDate::today_utc", false, &[]),
    AotCoreCall::new("core.time.datetime", "from_timestamp", "JetDateTime::from_timestamp", false, &[false]),
    AotCoreCall::new("core.time.datetime", "now", "JetDateTime::now", false, &[]),
];

/// Find one plain AOT projection by its canonical Core key.
pub fn aot_core_call(module: &str, member: &str) -> Option<&'static AotCoreCall> {
    AOT_CORE_CALLS
        .iter()
        .find(|row| row.module == module && row.member == member)
}
