# CMake functions for native Jet Library outputs.

if(NOT DEFINED Jet_MODULE_DIR)
    set(Jet_MODULE_DIR "${CMAKE_CURRENT_LIST_DIR}")
endif()

include(CMakeParseArguments)

function(jet_library TARGET)
    set(options STATIC SHARED LOADABLE)
    set(one_value_args ENTRY OUTPUT LIBRARY PROFILE)
    set(multi_value_args DEPENDS)
    cmake_parse_arguments(JET "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

    if(NOT JET_ENTRY OR NOT JET_OUTPUT OR NOT JET_LIBRARY)
        message(FATAL_ERROR "JET-HOST-INPUT: jet_library requires ENTRY, OUTPUT, and LIBRARY")
    endif()
    if(JET_STATIC AND JET_SHARED)
        message(FATAL_ERROR "JET-HOST-ABI: choose one of STATIC or SHARED")
    endif()
    if(NOT JET_STATIC AND NOT JET_SHARED)
        set(JET_STATIC TRUE)
    endif()
    if(WIN32 AND JET_SHARED)
        message(FATAL_ERROR "JET-HOST-ABI: the current Jet Windows export has no MSVC import library; use STATIC with a GNU-compatible host toolchain")
    endif()
    set(_jet_compiler_id "${CMAKE_C_COMPILER_ID}")
    if(NOT _jet_compiler_id AND CMAKE_CXX_COMPILER_ID)
        set(_jet_compiler_id "${CMAKE_CXX_COMPILER_ID}")
    endif()
    if(WIN32 AND JET_STATIC AND _jet_compiler_id MATCHES "MSVC")
        message(FATAL_ERROR "JET-HOST-ABI: Jet emits a GNU .a archive on Windows; configure MinGW or another GNU-compatible C toolchain")
    endif()

    set(_jet_toolchain "${CMAKE_C_COMPILER}")
    if(NOT _jet_toolchain OR _jet_toolchain MATCHES "-NOTFOUND$")
        set(_jet_toolchain "${CMAKE_CXX_COMPILER}")
    endif()
    if(NOT _jet_toolchain OR _jet_toolchain MATCHES "-NOTFOUND$")
        message(FATAL_ERROR "JET-HOST-TOOL: CMake did not select a C or CXX compiler for the Jet host linker")
    endif()

    get_filename_component(_entry_abs "${JET_ENTRY}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    file(RELATIVE_PATH _entry_rel "${CMAKE_CURRENT_SOURCE_DIR}" "${_entry_abs}")
    if(_entry_rel MATCHES "^\\.\\.")
        message(FATAL_ERROR "JET-HOST-INPUT: ENTRY must stay inside the CMake project")
    endif()

    set(_dest "${CMAKE_CURRENT_BINARY_DIR}/jet/${TARGET}")
    set(_stamp "${_dest}/jet-host.stamp")
    set(_static "${_dest}/lib${JET_LIBRARY}.a")
    set(_header "${_dest}/${JET_LIBRARY}.h")
    set(_kind static)
    set(_artifact "${_static}")
    if(JET_SHARED)
        set(_kind shared)
        if(APPLE)
            set(_shared "${_dest}/lib${JET_LIBRARY}.dylib")
        elseif(WIN32)
            set(_shared "${_dest}/lib${JET_LIBRARY}.dll")
        else()
            set(_shared "${_dest}/lib${JET_LIBRARY}.so")
        endif()
        set(_artifact "${_shared}")
    endif()

    set(_dependency_rels)
    set(_jet_deps "${CMAKE_CURRENT_SOURCE_DIR}/package.jet" "${CMAKE_CURRENT_SOURCE_DIR}/.jet/lock" "${_entry_abs}")
    foreach(_dependency IN LISTS JET_DEPENDS)
        get_filename_component(_dependency_abs "${_dependency}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        file(RELATIVE_PATH _dependency_rel "${CMAKE_CURRENT_SOURCE_DIR}" "${_dependency_abs}")
        if(_dependency_rel MATCHES "^\\.\\.")
            message(FATAL_ERROR "JET-HOST-INPUT: DEPENDS path '${_dependency}' escapes the CMake project")
        endif()
        list(APPEND _dependency_rels "${_dependency_rel}")
        list(APPEND _jet_deps "${_dependency_abs}")
    endforeach()
    set(_loadable_args)
    if(JET_LOADABLE)
        list(APPEND _loadable_args --loadable)
    endif()
    set(_outputs "${_stamp}" "${_artifact}" "${_header}" "${_dest}/jet-host.receipt")
    if(JET_LOADABLE)
        list(APPEND _outputs "${_dest}/${JET_LIBRARY}.jetlib")
    endif()
    if(NOT JET_PROFILE)
        set(JET_PROFILE dev)
    endif()

    if(WIN32)
        set(_runner_command powershell -NoProfile -ExecutionPolicy Bypass -File "${Jet_MODULE_DIR}/../jet-library.ps1")
        set(_runner_script "${Jet_MODULE_DIR}/../jet-library.ps1")
        set(_arg_jet -Jet)
        set(_arg_project -Project)
        set(_arg_entry -Entry)
        set(_arg_output -Output)
        set(_arg_library -Library)
        set(_arg_dest -Dest)
        set(_arg_kind -Kind)
        set(_arg_profile -Profile)
        set(_arg_toolchain -Toolchain)
        set(_runner_input_value "package.jet|.jet\\lock|${_entry_rel}")
        foreach(_dependency_rel IN LISTS _dependency_rels)
            string(APPEND _runner_input_value "|${_dependency_rel}")
        endforeach()
        set(_runner_inputs -InputPath "${_runner_input_value}")
        set(_loadable_args)
        if(JET_LOADABLE)
            list(APPEND _loadable_args -Loadable)
        endif()
    else()
        find_program(Jet_HOST_BASH NAMES bash)
        if(NOT Jet_HOST_BASH)
            message(FATAL_ERROR "JET-HOST-TOOL: bash is required to run the Jet host adapter")
        endif()
        set(_runner_command "${Jet_HOST_BASH}" "${Jet_MODULE_DIR}/../jet-library.sh")
        set(_runner_script "${Jet_MODULE_DIR}/../jet-library.sh")
        set(_arg_jet --jet)
        set(_arg_project --project)
        set(_arg_entry --entry)
        set(_arg_output --output)
        set(_arg_library --library)
        set(_arg_dest --dest)
        set(_arg_kind --kind)
        set(_arg_profile --profile)
        set(_arg_toolchain --toolchain)
        set(_runner_inputs --input package.jet --input .jet/lock --input "${_entry_rel}")
        foreach(_dependency_rel IN LISTS _dependency_rels)
            list(APPEND _runner_inputs --input "${_dependency_rel}")
        endforeach()
    endif()
    add_custom_command(
        OUTPUT ${_outputs}
        COMMAND ${_runner_command}
            ${_arg_jet} "${Jet_EXECUTABLE}"
            ${_arg_project} "${CMAKE_CURRENT_SOURCE_DIR}"
            ${_arg_entry} "${_entry_rel}"
            ${_arg_output} "${JET_OUTPUT}"
            ${_arg_library} "${JET_LIBRARY}"
            ${_arg_dest} "${_dest}"
            ${_arg_kind} "${_kind}"
            ${_arg_profile} "${JET_PROFILE}"
            ${_arg_toolchain} "${_jet_toolchain}"
            ${_loadable_args}
            ${_runner_inputs}
        DEPENDS ${_runner_script} "${Jet_EXECUTABLE}" "${_jet_toolchain}" "${Jet_MODULE_DIR}/Jet.cmake" ${_jet_deps}
        VERBATIM
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
    )
    add_custom_target("${TARGET}_jet" DEPENDS ${_outputs})

    if(JET_SHARED)
        add_library("${TARGET}__jet_artifact" SHARED IMPORTED GLOBAL)
    else()
        add_library("${TARGET}__jet_artifact" STATIC IMPORTED GLOBAL)
    endif()
    set_target_properties("${TARGET}__jet_artifact" PROPERTIES
        IMPORTED_LOCATION "${_artifact}"
        INTERFACE_INCLUDE_DIRECTORIES "${_dest}"
    )
    if(JET_STATIC AND UNIX)
        find_package(Threads REQUIRED)
        set(_jet_runtime Threads::Threads m)
        if(NOT APPLE)
            list(APPEND _jet_runtime dl)
        endif()
        set_property(TARGET "${TARGET}__jet_artifact" PROPERTY INTERFACE_LINK_LIBRARIES "${_jet_runtime}")
    endif()
    add_library("${TARGET}" INTERFACE)
    target_link_libraries("${TARGET}" INTERFACE "${TARGET}__jet_artifact")
    target_include_directories("${TARGET}" INTERFACE "${_dest}")
    add_dependencies("${TARGET}" "${TARGET}_jet")
endfunction()
