mod common;

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn scratch(name: &str) -> PathBuf {
    let path = common::unique_tmp(&format!("jet-bind-{name}"));
    fs::create_dir_all(&path).unwrap();
    path
}

fn generated(
    format: &str,
    path: &str,
    input: &str,
    root: Option<&str>,
    command: &str,
) -> String {
    let dir = scratch(&format!("generated-{format}"));
    let input_path = dir.join(path);
    if let Some(parent) = input_path.parent().filter(|path| !path.as_os_str().is_empty()) {
        fs::create_dir_all(parent).unwrap();
    }
    fs::write(&input_path, input).unwrap();
    let source = run_public_data_bind(&dir, format, path, root, command);
    let _ = fs::remove_dir_all(dir);
    source
}

fn escape_provenance(value: &str) -> String {
    value
        .chars()
        .flat_map(|ch| match ch {
            '\\' => "\\\\".chars().collect::<Vec<_>>(),
            '\n' => "\\n".chars().collect(),
            '\r' => "\\r".chars().collect(),
            '\t' => "\\t".chars().collect(),
            ch if ch.is_control() || matches!(ch, '\u{2028}' | '\u{2029}') => {
                format!("\\u{:04x}", ch as u32).chars().collect()
            }
            ch => vec![ch],
        })
        .collect()
}

fn run_public_data_bind(
    dir: &Path,
    format: &str,
    input_path: &str,
    root: Option<&str>,
    command: &str,
) -> String {
    let mut args = vec![
        "inspect".to_string(),
        "bind".to_string(),
        format.to_string(),
        input_path.to_string(),
    ];
    if let Some(root) = root {
        args.extend(["--type".to_string(), root.to_string()]);
    }
    let output = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args(&args)
        .current_dir(dir)
        .env("NO_COLOR", "1")
        .output()
        .unwrap();
    assert_success(&output);
    let stdout = String::from_utf8_lossy(&output.stdout);
    let output_path = stdout
        .lines()
        .find_map(|line| line.split_once(" → ").map(|(_, path)| path.trim()))
        .unwrap_or_else(|| panic!("public `jet inspect bind` did not report an output path:\n{stdout}"));
    let source = fs::read_to_string(dir.join(output_path)).unwrap();
    let expected_provenance = format!("// generated by: {}", escape_provenance(command));
    assert!(
        source.contains(&expected_provenance),
        "public `jet inspect bind` changed provenance:\n{source}"
    );
    source
}

fn assert_success(output: &std::process::Output) {
    assert!(
        output.status.success(),
        "status={:?}\nstderr={}",
        output.status.code(),
        String::from_utf8_lossy(&output.stderr)
    );
}

/// Run generated source as part of a real project. The typed field reads make
/// a parser-only or fallback implementation fail before either execution tier
/// can report the expected output.
fn assert_generated_project(
    name: &str,
    format: &str,
    input_path: &str,
    input: &str,
    root: &str,
    command: &str,
    program: &str,
    expected_stdout: &str,
    source_markers: &[&str],
) {
    let dir = scratch(&format!("project-{name}"));
    let input_file = dir.join(input_path);
    if let Some(parent) = input_file.parent().filter(|path| !path.as_os_str().is_empty()) {
        fs::create_dir_all(parent).unwrap();
    }
    fs::write(&input_file, input).unwrap();
    let generated = run_public_data_bind(&dir, format, input_path, Some(root), command);
    for marker in source_markers {
        assert!(
            generated.contains(marker),
            "{format} generated source lost required schema marker {marker:?}:\n{generated}"
        );
    }
    assert_generated_source_parses(&generated);
    assert!(
        !generated.contains("DataTree"),
        "{format} project would exercise the dynamic fallback instead of typed generated fields:\n{generated}"
    );

    let main_path = dir.join("main.jet");
    let project_source = format!("{generated}\n{program}");
    fs::write(&main_path, &project_source).unwrap();
    let shown = main_path.to_string_lossy().into_owned();
    let compiled = jet::compile_with_path(&project_source, &shown).unwrap_or_else(|diagnostics| {
        panic!(
            "semantic analysis rejected generated {format} project:\n{}",
            jet::render_diagnostics(&shown, &project_source, &diagnostics)
        )
    });
    let generated_rust_type = jet::Syntax::generated_name(root);
    assert!(
        compiled
            .rust
            .contains(&format!("pub struct {generated_rust_type}")),
        "codegen omitted generated {root} instead of using a fallback project:\n{}",
        compiled.rust
    );

    let rust_path = dir.join("main.rs");
    let binary_path = dir.join("main");
    fs::write(&rust_path, &compiled.rust).unwrap();
    let aot = Command::new("rustc")
        .args(["--edition", "2021"])
        .arg(&rust_path)
        .arg("-o")
        .arg(&binary_path)
        .output()
        .unwrap();
    assert_success(&aot);
    let aot_run = Command::new(&binary_path).current_dir(&dir).output().unwrap();
    assert_success(&aot_run);
    assert_eq!(
        String::from_utf8_lossy(&aot_run.stdout),
        expected_stdout,
        "AOT output did not use generated {format} fields"
    );

    let jit_run = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args(["run", "main.jet"])
        .current_dir(&dir)
        .env("JET_CACHE_DIR", dir.join("run-cache"))
        .env("NO_COLOR", "1")
        .output()
        .unwrap();
    assert_success(&jit_run);
    assert_eq!(
        String::from_utf8_lossy(&jit_run.stdout),
        expected_stdout,
        "default `jet run` output did not use generated {format} fields"
    );
    let _ = fs::remove_dir_all(dir);
}

fn assert_generated_source_parses(source: &str) {
    let (tokens, diagnostics) = jet::Lexer::lex_generated(source);
    assert!(diagnostics.is_empty(), "generated source lexed with diagnostics: {diagnostics:#?}");
    assert!(
        jet::Parser::parse(&tokens).is_ok(),
        "generated source did not parse:\n{source}"
    );
}

fn check_cli_snapshot(name: &str, actual: &str) {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/cli")
        .join(name);
    if std::env::var("UPDATE_EXPECT").is_ok() {
        fs::write(&path, actual).unwrap();
        return;
    }
    let expected = fs::read_to_string(&path).unwrap_or_else(|_| {
        panic!(
            "missing snapshot {}; run UPDATE_EXPECT=1 cargo test",
            path.display()
        )
    });
    assert_eq!(actual, expected, "snapshot mismatch for {}", name);
}

fn scrub_cli_path(output: &str, file: &Path) -> String {
    output.replace(&file.display().to_string(), "BAD.jet")
}

#[test]
fn data_bind_generates_all_formats() {
    let json = generated(
        "json",
        "fixtures/json_repo.json",
        r#"{"repo-name":"jet","stars":4,"active":true,"owner":{"name":"Ada"},"tags":["lang","safe"],"note":null}"#,
        Some("Repo"),
        "jet inspect bind json fixtures/json_repo.json --type Repo",
    );
    assert!(json.contains("#Codable"));
    assert!(json.contains("struct Repo"));
    assert!(json.contains(r#"#Rename("repo-name") repo_name: String"#));
    assert!(json.contains("owner: RepoOwner"));
    assert!(json.contains("tags: [String]"));
    assert!(json.contains("note: DataTree?"));

    let csv = generated(
        "csv",
        "fixtures/csv_people.csv",
        "name,age,active,notes\n\"Ada, Lovelace\",36,true,\"said \"\"hi\"\"\"\nLin,,false,\"line 1\nline 2\"\n",
        Some("Person"),
        "jet inspect bind csv fixtures/csv_people.csv --type Person",
    );
    assert!(csv.contains("struct Person"));
    assert!(csv.contains("name: String"));
    assert!(csv.contains("age: Int?"));
    assert!(csv.contains("active: Bool"));
    assert!(csv.contains("notes: String"));

    let sql = generated(
        "sql",
        "sql_schema.sql",
        "CREATE TABLE users (id INTEGER PRIMARY KEY, price DECIMAL(10,2), active BOOLEAN NOT NULL, born DATE, opened TIME, created TIMESTAMP, data BLOB);\nCREATE TABLE audit (event TEXT NOT NULL);",
        Some("Root"),
        "jet inspect bind sql sql_schema.sql --type Root",
    );
    assert!(sql.contains("struct Users"));
    assert!(sql.contains("id: Int"));
    assert!(sql.contains("price: Decimal?"));
    assert!(sql.contains("active: Bool"));
    assert!(sql.contains("born: LocalDate?"));
    assert!(sql.contains("opened: LocalTime?"));
    assert!(sql.contains("created: DateTime?"));
    assert!(sql.contains("data: [U8]?"));
    assert!(sql.contains("struct Audit"));
    assert!(!sql.contains("struct Root"));

    let xml = generated(
        "xml",
        "xml_catalog.xml",
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?><?catalog generated?><catalog><!-- comment --><book id=\"1\"><title><![CDATA[<A]]></title></book><book id=\"2\"><title>B</title></book></catalog>",
        Some("Catalog"),
        "jet inspect bind xml xml_catalog.xml --type Catalog",
    );
    assert!(xml.contains("struct Catalog"));
    assert!(xml.contains("book: [CatalogBook]"));
    assert!(xml.contains(r#"#Rename("@id") id: String"#));
    assert!(xml.contains("title: String"));

    let proto = generated(
        "proto",
        "proto_repo.proto",
        "syntax = \"proto3\";\nmessage Repo { string name = 1; repeated Tag tags = 2; optional int64 stars = 3; }\nmessage Tag { string value = 1; }\n",
        Some("Repo"),
        "jet inspect bind proto proto_repo.proto --type Repo",
    );
    assert!(proto.contains("struct Repo"));
    assert!(proto.contains("tags: [Tag]"));
    assert!(proto.contains("stars: Int?"));
    assert!(proto.contains("// proto field number: 2"));
    assert!(proto.contains("#Codable"));
}

#[test]
fn retired_top_level_bind_forms_teach_the_grouped_route() {
    let dir = scratch("retired-bind");
    let cases = vec![
        vec!["bind", "missing.h"],
        vec!["--json", "bind", "missing.h"],
        vec!["-v", "bind", "missing.h"],
        vec!["--color=never", "bind", "missing.h"],
    ];
    for args in cases {
        let output = Command::new(env!("CARGO_BIN_EXE_jet"))
            .args(args)
            .current_dir(&dir)
            .env("NO_COLOR", "1")
            .output()
            .unwrap();
        let rendered = format!(
            "{}\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        assert!(!output.status.success(), "retired bind unexpectedly succeeded: {rendered}");
        assert!(rendered.contains("E2101"), "retired bind lost its teaching diagnostic: {rendered}");
        assert!(rendered.contains("inspect bind"), "retired bind lost its canonical fix: {rendered}");
        assert!(!rendered.contains("jet bind"), "retired bind kept a top-level alias: {rendered}");
        assert!(!rendered.contains("E3208"), "retired bind reached the binder: {rendered}");
    }
    let _ = fs::remove_dir_all(dir);
}

#[test]
fn json_bind_generated_project_executes_typed_fields() {
    assert_generated_project(
        "json",
        "json",
        "fixtures/repo.json",
        r#"{"repo-name":"jet","stars":4,"active":true,"exact":9007199254740993}"#,
        "Repo",
        "jet inspect bind json fixtures/repo.json --type Repo",
        r#"
fn run() {
    repo :: Repo.{ repo_name: "jet", stars: 4, active: true, exact: 9007199254740993 }
    print(repo.repo_name)
    print(repo.stars)
    print(repo.active)
    print(repo.exact)
}
"#,
        "jet\n4\ntrue\n9007199254740993\n",
        &[
            "#Rename(\"repo-name\") repo_name: String",
            "stars: Int",
            "active: Bool",
            "exact: Int",
        ],
    );
}

#[test]
fn csv_bind_generated_project_executes_typed_fields() {
    assert_generated_project(
        "csv",
        "csv",
        "fixtures/people.csv",
        "name,age,active\nAda,36,true\n",
        "Person",
        "jet inspect bind csv fixtures/people.csv --type Person",
        r#"
fn run() {
    person :: Person.{ name: "Ada", age: 36, active: true }
    print(person.name)
    print(person.age)
    print(person.active)
}
"#,
        "Ada\n36\ntrue\n",
        &["name: String", "age: Int", "active: Bool"],
    );
}

#[test]
fn sql_bind_generated_project_executes_typed_fields() {
    assert_generated_project(
        "sql",
        "sql",
        "schema.sql",
        "CREATE TABLE users (id INTEGER PRIMARY KEY, name VARCHAR(32) NOT NULL, active BOOLEAN NOT NULL, born DATE, opened TIME, created TIMESTAMP, data BLOB NOT NULL);",
        "User",
        "jet inspect bind sql schema.sql --type User",
        r#"
fn run() {
    user :: User.{ id: 7, name: "Ada", active: true, born: .None, opened: .None, created: .None, data: [U8].{ 65, 66 } }
    print(user.id)
    print(user.name)
    print(user.active)
    print(user.data[0])
    print(user.data.len())
    if user.born == .None { print("born-none") }
    if user.opened == .None { print("opened-none") }
    if user.created == .None { print("created-none") }
}
"#,
        "7\nAda\ntrue\n65\n2\nborn-none\nopened-none\ncreated-none\n",
        &[
            "id: Int",
            "name: String",
            "active: Bool",
            "born: LocalDate?",
            "opened: LocalTime?",
            "created: DateTime?",
            "data: [U8]",
        ],
    );
}

#[test]
fn xml_bind_generated_project_executes_typed_fields() {
    assert_generated_project(
        "xml",
        "xml",
        "catalog.xml",
        "<catalog><book id=\"7\"><title>Jet</title></book></catalog>",
        "Catalog",
        "jet inspect bind xml catalog.xml --type Catalog",
        r#"
fn run() {
    book :: CatalogBook.{ id: "7", title: "Jet" }
    catalog :: Catalog.{ book: book }
    print(catalog.book.id)
    print(catalog.book.title)
}
"#,
        "7\nJet\n",
        &["book: CatalogBook", "#Rename(\"@id\") id: String", "title: String"],
    );
}

#[test]
fn xml_bind_resolves_namespaces_omits_declarations_and_keeps_collisions() {
    let input = r#"<root xmlns="urn:root" xmlns:a="urn:one" xmlns:b="urn_one" a:id="left" b:id="right" id="plain" xml:lang="en"><a:item>one</a:item><b:item>two</b:item><a:record><value>left</value></a:record><b:record><value>right</value></b:record><nested xmlns="urn:nested"><leaf>three</leaf></nested></root>"#;
    let command = "jet inspect bind xml namespaced.xml --type Root";
    let first = generated("xml", "namespaced.xml", input, Some("Root"), command);
    let second = generated("xml", "namespaced.xml", input, Some("Root"), command);
    assert_eq!(first, second, "XML namespace naming must be deterministic");
    assert!(first.contains("generated by: jet inspect bind xml namespaced.xml --type Root"));
    assert!(first.contains("input: namespaced.xml"));
    assert!(first.contains(&format!(
        "sha256: {}",
        jet::SHA256::sha256_hex(input.as_bytes())
    )));
    assert!(!first.contains("xmlns"), "namespace declarations are not wire fields");

    let field_marker = |wire: &str, name: &str, ty: &str| {
        let escaped = format!("{wire:?}").replace('{', "{{").replace('}', "}}");
        format!("#Rename({escaped}) {name}: {ty}")
    };
    let id_base = jet::Syntax::sanitize_generated_name(
        "{urn:one}id",
        jet::Syntax::NameCase::Snake,
        "field",
    );
    assert_eq!(
        id_base,
        jet::Syntax::sanitize_generated_name(
            "{urn_one}id",
            jet::Syntax::NameCase::Snake,
            "field",
        )
    );
    assert!(first.contains(&field_marker("@id", "id", "String")));
    assert!(first.contains(&field_marker("@{urn:one}id", &id_base, "String")));
    assert!(first.contains(&field_marker("@{urn_one}id", &format!("{id_base}_2"), "String")));
    assert!(first.contains(&field_marker(
        "@{http://www.w3.org/XML/1998/namespace}lang",
        &jet::Syntax::sanitize_generated_name(
            "@{http://www.w3.org/XML/1998/namespace}lang",
            jet::Syntax::NameCase::Snake,
            "field",
        ),
        "String",
    )));

    let item_base = jet::Syntax::sanitize_generated_name(
        "{urn:one}item",
        jet::Syntax::NameCase::Snake,
        "field",
    );
    assert_eq!(
        item_base,
        jet::Syntax::sanitize_generated_name(
            "{urn_one}item",
            jet::Syntax::NameCase::Snake,
            "field",
        )
    );
    assert!(first.contains(&field_marker("{urn:one}item", &item_base, "String")));
    assert!(first.contains(&field_marker("{urn_one}item", &format!("{item_base}_2"), "String")));
    let record_base = jet::Syntax::sanitize_generated_name(
        &format!(
            "Root{}",
            jet::Syntax::sanitize_generated_name(
                "{urn:one}record",
                jet::Syntax::NameCase::Pascal,
                "Schema",
            )
        ),
        jet::Syntax::NameCase::Pascal,
        "Schema",
    );
    assert_eq!(
        record_base,
        jet::Syntax::sanitize_generated_name(
            &format!(
                "Root{}",
                jet::Syntax::sanitize_generated_name(
                    "{urn_one}record",
                    jet::Syntax::NameCase::Pascal,
                    "Schema",
                )
            ),
            jet::Syntax::NameCase::Pascal,
            "Schema",
        )
    );
    let record_field = jet::Syntax::sanitize_generated_name(
        "{urn:one}record",
        jet::Syntax::NameCase::Snake,
        "field",
    );
    assert!(first.contains(&field_marker(
        "{urn:one}record",
        &record_field,
        &record_base,
    )));
    assert!(first.contains(&field_marker(
        "{urn_one}record",
        &format!("{record_field}_2"),
        &format!("{record_base}_2"),
    )));
    assert!(first.contains(&format!("struct {record_base} {{")));
    assert!(first.contains(&format!("struct {record_base}_2 {{")));
    let nested_leaf = jet::Syntax::sanitize_generated_name(
        "{urn:nested}leaf",
        jet::Syntax::NameCase::Snake,
        "field",
    );
    assert!(first.contains(&field_marker(
        "{urn:nested}leaf",
        &nested_leaf,
        "String",
    )));
    assert_generated_source_parses(&first);
}

#[test]
fn proto_bind_generated_project_executes_typed_fields() {
    assert_generated_project(
        "proto",
        "proto",
        "repo.proto",
        "syntax = \"proto3\"; import \"google/protobuf/timestamp.proto\"; import \"google/protobuf/duration.proto\"; message Repo { string name = 1; int64 stars = 2; bool active = 3; bytes payload = 4; optional google.protobuf.Timestamp created = 5; optional google.protobuf.Duration ttl = 6; }",
        "Repo",
        "jet inspect bind proto repo.proto --type Repo",
        r#"
fn run() {
    repo :: Repo.{ name: "jet", stars: 4, active: true, payload: [U8].{ 74, 101, 116 }, created: .None, ttl: .None }
    print(repo.name)
    print(repo.stars)
    print(repo.active)
    print(repo.payload.len())
    print(repo.payload[0])
    if repo.created == .None { print("created-none") }
    if repo.ttl == .None { print("ttl-none") }
}
"#,
        "jet\n4\ntrue\n3\n74\ncreated-none\nttl-none\n",
        &[
            "name: String",
            "// proto field number: 2",
            "active: Bool",
            "payload: [U8]",
            "created: DateTime?",
            "ttl: Duration?",
        ],
    );
}

#[test]
fn data_bind_uses_canonical_names_and_exact_json_number_lexemes() {
    let source = generated(
        "json",
        "hostile.json",
        r#"{"match":1,"a-b":2,"a_b":9007199254740993,"huge":1e9999,"precise":0.0000000000000000000000000000000000000000000000001,"__hidden":true}"#,
        Some("String"),
        "jet inspect bind json hostile.json --type String",
    );
    assert!(source.contains("struct StringType"));
    assert!(source.contains("match_field: Int"));
    assert!(source.contains("a_b: Int"));
    assert!(source.contains("a_b_2: Int"));
    assert!(source.contains("huge: Float"));
    assert!(source.contains("precise: Float"));
    assert!(!source.contains("a_b_2: Float"));
    assert_generated_source_parses(&source);

    assert_generated_project(
        "json-exact-lexeme",
        "json",
        "exact.json",
        r#"{"exact":9007199254740993,"decimal":9007199254740993.0}"#,
        "Exact",
        "jet inspect bind json exact.json --type Exact",
        r#"
use core.encoding.json as json

fn run() {
    exact :: json.decode<Exact>("{{\"exact\":9007199254740993,\"decimal\":9007199254740993.0}}") ?? panic("decode")
    print(exact.exact)
}
"#,
        "9007199254740993\n",
        &["exact: Int", "decimal: Float"],
    );

    let provenance = generated(
        "json",
        "records\nname\u{0001}.json",
        "{\"ok\":true}",
        Some("Record"),
        "jet inspect bind json records\nname\u{0001}.json --type Record",
    );
    assert!(provenance.contains("generated by: jet inspect bind json records\\nname\\u0001.json --type Record"));
    assert!(provenance.contains("input: records\\nname\\u0001.json"));
    assert!(!provenance.contains("generated by: jet inspect bind json records\nname"));
    assert_generated_source_parses(&provenance);
}

#[test]
fn c_bind_sanitizes_hostile_function_and_parameter_names_with_collisions() {
    let result = jet::CBind::generate(
        "int match(int match); int foo_bar(int value); int foo__bar(int value); int String(int String);",
        "hostile-lib",
    )
    .unwrap();
    assert!(result.source.contains("fn match_field(match_field: Int)"));
    assert!(result.source.contains("fn foo_bar(value: Int)"));
    assert!(result.source.contains("fn foo_bar_2(value: Int)"));
    assert!(result.source.contains("#Bindgen module c.hostile_lib.__bindgen__"));
    assert_generated_source_parses(&result.source);
}

#[test]
fn public_c_bind_writes_parseable_hashed_cache_and_regenerates_idempotently() {
    let dir = scratch("c-cli");
    let header = dir.join("hostile.h");
    let source = "int match(int match); int foo_bar(int value); int foo__bar(int value);\n";
    fs::write(&header, source).unwrap();
    let output = dir.join("generated.jet");
    let args = [
        "inspect",
        "bind",
        header.to_str().unwrap(),
        "--pkg",
        "hostile-lib",
        "-o",
        output.to_str().unwrap(),
    ];
    let first = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args(args)
        .current_dir(&dir)
        .env("NO_COLOR", "1")
        .output()
        .unwrap();
    assert_success(&first);
    let before = fs::read_to_string(&output).unwrap();
    assert_generated_source_parses(&before);
    let hash = fs::read_to_string(output.with_extension("hash")).unwrap();
    assert_eq!(hash, jet::CBind::compute_bind_hash(source, ""));
    let second = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args(args)
        .current_dir(&dir)
        .env("NO_COLOR", "1")
        .output()
        .unwrap();
    assert_success(&second);
    assert_eq!(before, fs::read_to_string(&output).unwrap());
    let _ = fs::remove_dir_all(dir);
}

#[test]
fn bind_missing_header_is_e3208() {
    let missing = std::env::temp_dir().join("jet_missing_bind_header.h");
    let _ = fs::remove_file(&missing);
    let output = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args(["inspect", "bind"])
        .arg(&missing)
        .env("NO_COLOR", "1")
        .output()
        .unwrap();
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert_eq!(output.status.code(), Some(1), "unexpected stderr:\n{stderr}");
    assert!(stderr.contains("Error [E3208]:"), "missing bind diagnostic:\n{stderr}");
    assert!(stderr.contains("Why:"), "missing E3208 reason:\n{stderr}");
    assert!(stderr.contains("Fix:"), "missing E3208 fix:\n{stderr}");
    check_cli_snapshot("bind_missing_e3208.txt", &scrub_cli_path(&stderr, &missing));
}

#[test]
fn data_bind_invalid_is_registered_e3208_snapshot() {
    let dir = scratch("data_bind_invalid_e3208");
    let input = dir.join("bad.json");
    fs::write(&input, "{").unwrap();
    let output = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args(["inspect", "bind", "json"])
        .arg(&input)
        .args(["--type", "Bad"])
        .current_dir(&dir)
        .env("NO_COLOR", "1")
        .output()
        .unwrap();
    assert_eq!(output.status.code(), Some(1));
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("Error [E3208]:"));
    assert!(stderr.contains("Why:") && stderr.contains("Fix:"));
    check_cli_snapshot(
        "bind_data_invalid_e3208.txt",
        &scrub_cli_path(&stderr, &input),
    );
}

#[test]
fn data_bind_rejects_malformed_inputs() {
    let dir = scratch("malformed-public");
    let malformed = [
        ("json", "bad.json", "[]"),
        ("json", "bad.json", "{\"x\":"),
        ("csv", "bad.csv", "a,a\n1,2\n"),
        ("csv", "bad.csv", "a,b\n1\n"),
        ("csv", "bad.csv", "a,b\n\"unterminated,2\n"),
        ("sql", "bad.sql", "CREATE TABLE x (id UNKNOWN);"),
        ("sql", "bad.sql", "CREATE TABLE x (id INT"),
        ("sql", "bad.sql", "CREATE TABLE x (id INTEGER PRIMARY KEY trailing);"),
        ("sql", "bad.sql", "CREATE TABLE x (id VARCHAR(4) UNSIGNED);"),
        ("xml", "bad.xml", "<a><b></a>"),
        ("xml", "bad.xml", "<!-- unclosed"),
        ("xml", "bad.xml", "<a><![CDATA[unclosed</a>"),
        ("xml", "bad.xml", "<?xml?><a/>"),
        ("xml", "bad.xml", "<a/><?xml version=\"1.0\"?>"),
        ("xml", "bad.xml", "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"maybe\"?><a/>"),
        ("xml", "bad.xml", "<a attr=\"&unknown;\"/>"),
        ("proto", "bad.proto", "message A { string x = 1; string x = 2; }"),
        ("proto", "bad.proto", "message A { string x = 1;"),
        ("proto", "bad.proto", "syntax = \"proto4\"; message A { string x = 1; }"),
        ("proto", "bad.proto", "message A { string x = 19000; }"),
        ("proto", "bad.proto", "message A { reserved 1 to 5; string x = 1; }"),
        ("proto", "bad.proto", "message A { string Child = 1; enum Child { ZERO = 0; } }"),
    ];
    for (format, filename, input) in malformed {
        let path = dir.join(filename);
        fs::write(&path, input).unwrap();
        let output = Command::new(env!("CARGO_BIN_EXE_jet"))
            .args(["inspect", "bind", format])
            .arg(&path)
            .args(["--type", "Bad"])
            .current_dir(&dir)
            .env("NO_COLOR", "1")
            .output()
            .unwrap();
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert_eq!(output.status.code(), Some(1), "{format} unexpectedly succeeded: {stderr}");
        assert!(stderr.contains("Error [E3208]:"), "{format} missing E3208: {stderr}");
        assert!(stderr.contains("Why:") && stderr.contains("Fix:"), "{format}: {stderr}");
    }
    let _ = fs::remove_dir_all(dir);
}

#[test]
fn json_bind_rejects_non_json_unicode_whitespace() {
    let dir = scratch("json-unicode-space");
    let input = dir.join("space.json");
    fs::write(&input, "{\u{00a0}\"name\":\"jet\"}").unwrap();
    let output = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args(["inspect", "bind", "json"])
        .arg(&input)
        .args(["--type", "Record"])
        .current_dir(&dir)
        .env("NO_COLOR", "1")
        .output()
        .unwrap();
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert_eq!(output.status.code(), Some(1));
    assert!(stderr.contains("Error [E3208]:"), "strict JSON rejection lost E3208: {stderr}");
    assert!(stderr.contains("JSON"), "strict JSON rejection lost its format context: {stderr}");
    let _ = fs::remove_dir_all(dir);
}

#[test]
fn data_bind_filesystem_errors_use_e2105() {
    let dir = scratch("data-bind-io");
    let missing = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args(["inspect", "bind", "json", "missing.json", "--type", "Missing"])
        .current_dir(&dir)
        .env("NO_COLOR", "1")
        .output()
        .unwrap();
    let missing_stderr = String::from_utf8_lossy(&missing.stderr);
    assert_eq!(missing.status.code(), Some(1));
    assert!(missing_stderr.contains("Error [E2105]:"), "missing input lost E2105: {missing_stderr}");
    assert!(!missing_stderr.contains("E3208"), "missing input was mislabeled as a schema error: {missing_stderr}");

    fs::write(dir.join("blocked"), "not a directory").unwrap();
    fs::write(dir.join("valid.json"), "{\"ok\":true}").unwrap();
    let blocked = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args([
            "inspect",
            "bind",
            "json",
            "valid.json",
            "--type",
            "Valid",
            "-o",
            "blocked/generated.jet",
        ])
        .current_dir(&dir)
        .env("NO_COLOR", "1")
        .output()
        .unwrap();
    let blocked_stderr = String::from_utf8_lossy(&blocked.stderr);
    assert_eq!(blocked.status.code(), Some(1));
    assert!(blocked_stderr.contains("Error [E2105]:"), "output IO failure lost E2105: {blocked_stderr}");
    assert!(!blocked_stderr.contains("E3208"), "output IO failure was mislabeled as a schema error: {blocked_stderr}");
    let _ = fs::remove_dir_all(dir);
}

#[test]
fn data_bind_sanitized_filename_collision_does_not_overwrite() {
    let dir = scratch("data-bind-collision");
    fs::write(dir.join("a b.json"), "{\"first\":true}").unwrap();
    fs::write(dir.join("a_b.json"), "{\"second\":true}").unwrap();

    let first = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args(["inspect", "bind", "json", "a b.json", "--type", "First"])
        .current_dir(&dir)
        .env("NO_COLOR", "1")
        .output()
        .unwrap();
    assert_success(&first);
    let output_path = dir.join("bindings/a_b.jet");
    let before = fs::read_to_string(&output_path).unwrap();

    let second = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args(["inspect", "bind", "json", "a_b.json", "--type", "Second"])
        .current_dir(&dir)
        .env("NO_COLOR", "1")
        .output()
        .unwrap();
    let stderr = String::from_utf8_lossy(&second.stderr);
    assert_eq!(second.status.code(), Some(1));
    assert!(stderr.contains("Error [E2104]:"), "filename collision lost E2104: {stderr}");
    assert!(!stderr.contains("E3208"), "filename collision was mislabeled as a schema error: {stderr}");
    assert_eq!(before, fs::read_to_string(&output_path).unwrap(), "collision overwrote the first binding");
    let _ = fs::remove_dir_all(dir);
}

#[test]
fn proto_accepts_strict_options_enums_and_reserved_forms() {
    let source = generated(
        "proto",
        "valid.proto",
        r#"syntax = "proto3";
package sample.api;
option java_package = "sample.api";
message Repo {
  reserved "retired", 10 to 12;
  string name = 1 [deprecated = true];
  State state = 2;
}
enum State {
  option allow_alias = true;
  reserved -3 to -1;
  UNKNOWN = 0;
  READY = 1;
  ALSO_READY = 1;
}
"#,
        Some("Repo"),
        "jet inspect bind proto valid.proto --type Repo",
    );
    assert!(source.contains("state: Int"));
    assert_generated_source_parses(&source);
}

#[test]
fn data_bind_provenance_is_hashed_and_stable() {
    let input = "{\"name\":\"jet\",\"count\":2}";
    let first = generated(
        "json",
        "fixtures/stable.json",
        input,
        Some("Stable"),
        "jet inspect bind json fixtures/stable.json --type Stable",
    );
    let second = generated(
        "json",
        "fixtures/stable.json",
        input,
        Some("Stable"),
        "jet inspect bind json fixtures/stable.json --type Stable",
    );
    assert_eq!(first, second);
    let hash = jet::SHA256::sha256_hex(input.as_bytes());
    assert!(first.contains("input: fixtures/stable.json"));
    assert!(first.contains(&format!("sha256: {hash}")));
    assert!(first.contains("generated by: jet inspect bind json fixtures/stable.json --type Stable"));
    assert!(first.contains("format: json"));
    assert!(first.contains("inference: JSON object fields become #Codable fields"));

    let changed = generated(
        "json",
        "fixtures/stable.json",
        "{\"name\":\"jet\",\"count\":3}",
        Some("Stable"),
        "jet inspect bind json fixtures/stable.json --type Stable",
    );
    assert_ne!(first, changed);
}

#[test]
fn public_cli_covers_each_data_format_parse_hash_and_idempotence() {
    let dir = scratch("all-formats");
    let cases = [
        (
            "json",
            "json_repo.json",
            r#"{"name":"jet","count":9007199254740993,"scale":1e9999}"#,
            "Repo",
            "json_repo.jet",
        ),
        (
            "csv",
            "csv_people.csv",
            "name,age\nAda,36\nLin,37\n",
            "Person",
            "csv_people.jet",
        ),
        (
            "sql",
            "sql_schema.sql",
            "CREATE TABLE users (id INTEGER PRIMARY KEY, name VARCHAR(32) NOT NULL, created TIMESTAMP(0));",
            "Users",
            "sql_schema.jet",
        ),
        (
            "xml",
            "xml_catalog.xml",
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><catalog><book id=\"1\"/></catalog>",
            "Catalog",
            "xml_catalog.jet",
        ),
        (
            "proto",
            "proto_repo.proto",
            "syntax = \"proto3\"; message Repo { string name = 1; }",
            "Repo",
            "proto_repo.jet",
        ),
    ];
    for (format, filename, input, root, output_filename) in cases {
        let input_path = dir.join(filename);
        fs::write(&input_path, input).unwrap();
        let input_text = input_path.to_str().unwrap();
        let output_path = dir.join("bindings").join(output_filename);
        let output_text = output_path.to_str().unwrap();
        let args = ["inspect", "bind", format, input_text, "--type", root, "-o"];
        let first = Command::new(env!("CARGO_BIN_EXE_jet"))
            .args(args)
            .arg(output_text)
            .current_dir(&dir)
            .env("NO_COLOR", "1")
            .output()
            .unwrap();
        assert_success(&first);
        let before = fs::read_to_string(&output_path).unwrap();
        assert!(before.contains("#Codable"));
        assert!(before.contains(&format!("sha256: {}", jet::SHA256::sha256_hex(input.as_bytes()))));
        assert_generated_source_parses(&before);

        let second = Command::new(env!("CARGO_BIN_EXE_jet"))
            .args(args)
            .arg(output_text)
            .current_dir(&dir)
            .env("NO_COLOR", "1")
            .output()
            .unwrap();
        assert_success(&second);
        assert_eq!(before, fs::read_to_string(&output_path).unwrap());
    }

    let malformed = [
        ("json", "bad.json", "{"),
        ("csv", "bad.csv", "a,a\n1,2\n"),
        ("sql", "bad.sql", "CREATE TABLE x (id UNKNOWN);"),
        ("xml", "bad.xml", "<a attr=\"&bad;\"/>"),
        ("proto", "bad.proto", "message A { string x = 19000; }"),
    ];
    for (format, filename, input) in malformed {
        let path = dir.join(filename);
        fs::write(&path, input).unwrap();
        let output = Command::new(env!("CARGO_BIN_EXE_jet"))
            .args(["inspect", "bind", format, path.to_str().unwrap(), "--type", "Bad"])
            .current_dir(&dir)
            .env("NO_COLOR", "1")
            .output()
            .unwrap();
        assert_eq!(output.status.code(), Some(1));
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(stderr.contains("Error [E3208]:"), "{format} missing E3208: {stderr}");
        assert!(stderr.contains("Why:") && stderr.contains("Fix:"), "{format}: {stderr}");
    }
    let _ = fs::remove_dir_all(dir);
}

#[test]
fn data_bind_cli_writes_visible_output_and_regeneration_diff() {
    let dir = scratch("cli");
    let input = dir.join("records.json");
    fs::write(&input, "{\"name\":\"first\",\"count\":1}").unwrap();
    let input_text = input.to_str().unwrap();

    let first = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args(["inspect", "bind", "json", input_text, "--type", "Record"])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert_success(&first);
    let default_output = dir.join("bindings/records.jet");
    assert!(default_output.is_file());
    let before = fs::read_to_string(&default_output).unwrap();
    assert!(before.contains("#Codable"));
    assert!(before.contains("struct Record"));
    assert!(before.contains(input_text));

    fs::write(&input, "{\"name\":\"second\",\"count\":2,\"active\":true}").unwrap();
    let stale = fs::read_to_string(&default_output).unwrap();
    assert_eq!(before, stale);

    let regenerated = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args(["inspect", "bind", "json", input_text, "--type", "Record"])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert_success(&regenerated);
    let regenerated_output = fs::read_to_string(&default_output).unwrap();
    assert_ne!(before, regenerated_output);
    assert!(regenerated_output.contains("active: Bool"));

    let explicit = dir.join("generated/record.jet");
    let explicit_text = explicit.to_str().unwrap();
    let second = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args([
            "inspect",
            "bind",
            "json",
            input_text,
            "--type",
            "Record",
            "-o",
            explicit_text,
        ])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert_success(&second);
    let after = fs::read_to_string(&explicit).unwrap();
    assert_ne!(before, after);
    assert!(after.contains("active: Bool"));
    assert!(after.contains(explicit_text));
    assert!(Path::new(explicit_text).is_file());

    let _ = fs::remove_dir_all(dir);
}
