mod common;

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn scratch(name: &str) -> PathBuf {
    let path = std::env::temp_dir().join(format!("jet-bind-{name}-{}", std::process::id()));
    let _ = fs::remove_dir_all(&path);
    fs::create_dir_all(&path).unwrap();
    path
}

fn generated(
    format: &str,
    path: &str,
    input: &str,
    root: Option<&str>,
    command: &str,
) -> String {
    jet::CBind::generate_data(format, path, input, root, command)
        .unwrap()
        .source
}

fn assert_success(output: std::process::Output) {
    assert!(
        output.status.success(),
        "status={:?}\nstderr={}",
        output.status.code(),
        String::from_utf8_lossy(&output.stderr)
    );
}

fn assert_generated_source_parses(source: &str) {
    let (tokens, diagnostics) = jet::Lexer::lex_generated(source);
    assert!(diagnostics.is_empty(), "generated source lexed with diagnostics: {diagnostics:#?}");
    assert!(
        jet::Parser::parse(&tokens).is_ok(),
        "generated source did not parse:\n{source}"
    );
}

#[test]
fn data_bind_generates_all_formats() {
    let json = generated(
        "json",
        "fixtures/repo.json",
        r#"{"repo-name":"jet","stars":4,"active":true,"owner":{"name":"Ada"},"tags":["lang","safe"],"note":null}"#,
        Some("Repo"),
        "jet bind json fixtures/repo.json --type Repo",
    );
    assert!(json.contains("#Codable"));
    assert!(json.contains("struct Repo"));
    assert!(json.contains(r#"#Rename("repo-name") repo_name: String"#));
    assert!(json.contains("owner: RepoOwner"));
    assert!(json.contains("tags: [String]"));
    assert!(json.contains("note: DataTree?"));

    let csv = generated(
        "csv",
        "fixtures/people.csv",
        "name,age,active,notes\n\"Ada, Lovelace\",36,true,\"said \"\"hi\"\"\"\nLin,,false,\"line 1\nline 2\"\n",
        Some("Person"),
        "jet bind csv fixtures/people.csv --type Person",
    );
    assert!(csv.contains("struct Person"));
    assert!(csv.contains("name: String"));
    assert!(csv.contains("age: Int?"));
    assert!(csv.contains("active: Bool"));
    assert!(csv.contains("notes: String"));

    let sql = generated(
        "sql",
        "schema.sql",
        "CREATE TABLE users (id INTEGER PRIMARY KEY, price DECIMAL(10,2), active BOOLEAN NOT NULL, created TIMESTAMP, data BLOB);\nCREATE TABLE audit (event TEXT NOT NULL);",
        Some("Root"),
        "jet bind sql schema.sql --type Root",
    );
    assert!(sql.contains("struct Users"));
    assert!(sql.contains("id: Int"));
    assert!(sql.contains("price: Decimal?"));
    assert!(sql.contains("active: Bool"));
    assert!(sql.contains("created: DateTime?"));
    assert!(sql.contains("data: Bytes?"));
    assert!(sql.contains("struct Audit"));
    assert!(!sql.contains("struct Root"));

    let xml = generated(
        "xml",
        "catalog.xml",
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?><?catalog generated?><catalog><!-- comment --><book id=\"1\"><title><![CDATA[<A]]></title></book><book id=\"2\"><title>B</title></book></catalog>",
        Some("Catalog"),
        "jet bind xml catalog.xml --type Catalog",
    );
    assert!(xml.contains("struct Catalog"));
    assert!(xml.contains("book: [CatalogBook]"));
    assert!(xml.contains(r#"#Rename("@id") id: String"#));
    assert!(xml.contains("title: String"));

    let proto = generated(
        "proto",
        "repo.proto",
        "syntax = \"proto3\";\nmessage Repo { string name = 1; repeated Tag tags = 2; optional int64 stars = 3; }\nmessage Tag { string value = 1; }\n",
        Some("Repo"),
        "jet bind proto repo.proto --type Repo",
    );
    assert!(proto.contains("struct Repo"));
    assert!(proto.contains("tags: [Tag]"));
    assert!(proto.contains("stars: Int?"));
    assert!(proto.contains("// proto field number: 2"));
    assert!(proto.contains("#Codable"));
}

#[test]
fn data_bind_uses_canonical_names_and_exact_json_number_lexemes() {
    let source = generated(
        "json",
        "hostile.json",
        r#"{"match":1,"a-b":2,"a_b":9007199254740993,"huge":1e9999,"precise":0.0000000000000000000000000000000000000000000000001,"__hidden":true}"#,
        Some("String"),
        "jet bind json hostile.json --type String",
    );
    assert!(source.contains("struct StringType"));
    assert!(source.contains("match_field: Int"));
    assert!(source.contains("a_b: Int"));
    assert!(source.contains("a_b_2: Int"));
    assert!(source.contains("huge: Float"));
    assert!(source.contains("precise: Float"));
    assert!(!source.contains("9007199254740992"));
    assert_generated_source_parses(&source);

    let provenance = generated(
        "json",
        "records\nname\u{0001}.json",
        "{\"ok\":true}",
        Some("Record"),
        "jet bind json records\nname\u{0001}.json --type Record\r\n",
    );
    assert!(provenance.contains("generated by: jet bind json records\\nname\\u0001.json --type Record\\r\\n"));
    assert!(provenance.contains("input: records\\nname\\u0001.json"));
    assert!(!provenance.contains("generated by: jet bind json records\nname"));
    assert_generated_source_parses(&provenance);
}

#[test]
fn c_bind_sanitizes_hostile_function_and_parameter_names_with_collisions() {
    let result = jet::CBind::generate(
        "int match(int match); int foo_bar(int value); int foo__bar(int value); int String(int String);",
        "hostile-lib",
    )
    .unwrap();
    assert!(result.source.contains("fn match_field(match_field: Int)"));
    assert!(result.source.contains("fn foo_bar(value: Int)"));
    assert!(result.source.contains("fn foo_bar_2(value: Int)"));
    assert!(result.source.contains("#Bindgen module c.hostile_lib.__bindgen__"));
    assert_generated_source_parses(&result.source);
}

#[test]
fn public_c_bind_writes_parseable_hashed_cache_and_regenerates_idempotently() {
    let dir = scratch("c-cli");
    let header = dir.join("hostile.h");
    let source = "int match(int match); int foo_bar(int value); int foo__bar(int value);\n";
    fs::write(&header, source).unwrap();
    let output = dir.join("generated.jet");
    let args = [
        "bind",
        header.to_str().unwrap(),
        "--pkg",
        "hostile-lib",
        "-o",
        output.to_str().unwrap(),
    ];
    let first = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args(args)
        .current_dir(&dir)
        .env("NO_COLOR", "1")
        .output()
        .unwrap();
    assert_success(first);
    let before = fs::read_to_string(&output).unwrap();
    assert_generated_source_parses(&before);
    let hash = fs::read_to_string(output.with_extension("hash")).unwrap();
    assert_eq!(hash, jet::CBind::compute_bind_hash(source, ""));
    let second = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args(args)
        .current_dir(&dir)
        .env("NO_COLOR", "1")
        .output()
        .unwrap();
    assert_success(second);
    assert_eq!(before, fs::read_to_string(&output).unwrap());
    let _ = fs::remove_dir_all(dir);
}

#[test]
fn data_bind_rejects_malformed_inputs() {
    assert!(jet::CBind::generate_data("json", "bad.json", "[]", None, "").is_err());
    assert!(jet::CBind::generate_data("json", "bad.json", "{\"x\":", None, "").is_err());
    assert!(jet::CBind::generate_data("csv", "bad.csv", "a,a\n1,2\n", None, "").is_err());
    assert!(jet::CBind::generate_data("csv", "bad.csv", "a,b\n1\n", None, "").is_err());
    assert!(jet::CBind::generate_data("csv", "bad.csv", "a,b\n\"unterminated,2\n", None, "").is_err());
    assert!(jet::CBind::generate_data("sql", "bad.sql", "CREATE TABLE x (id UNKNOWN);", None, "").is_err());
    assert!(jet::CBind::generate_data("sql", "bad.sql", "CREATE TABLE x (id INT", None, "").is_err());
    assert!(jet::CBind::generate_data("xml", "bad.xml", "<a><b></a>", None, "").is_err());
    assert!(jet::CBind::generate_data("xml", "bad.xml", "<!-- unclosed", None, "").is_err());
    assert!(jet::CBind::generate_data("xml", "bad.xml", "<a><![CDATA[unclosed</a>", None, "").is_err());
    assert!(jet::CBind::generate_data("xml", "bad.xml", "<?xml?><a/>", None, "").is_err());
    assert!(jet::CBind::generate_data(
        "xml",
        "bad.xml",
        "<a/><?xml version=\"1.0\"?>",
        None,
        "",
    )
    .is_err());
    assert!(jet::CBind::generate_data(
        "proto",
        "bad.proto",
        "message A { string x = 1; string x = 2; }",
        None,
        "",
    ).is_err());
    assert!(jet::CBind::generate_data(
        "proto",
        "bad.proto",
        "message A { string x = 1;",
        None,
        "",
    ).is_err());
    assert!(jet::CBind::generate_data(
        "sql",
        "bad.sql",
        "CREATE TABLE x (id INTEGER PRIMARY KEY trailing);",
        None,
        "",
    ).is_err());
    assert!(jet::CBind::generate_data(
        "sql",
        "bad.sql",
        "CREATE TABLE x (id VARCHAR(4) UNSIGNED);",
        None,
        "",
    ).is_err());
    assert!(jet::CBind::generate_data(
        "xml",
        "bad.xml",
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"maybe\"?><a/>",
        None,
        "",
    ).is_err());
    assert!(jet::CBind::generate_data(
        "xml",
        "bad.xml",
        "<a attr=\"&unknown;\"/>",
        None,
        "",
    ).is_err());
    assert!(jet::CBind::generate_data(
        "proto",
        "bad.proto",
        "syntax = \"proto4\"; message A { string x = 1; }",
        None,
        "",
    ).is_err());
    assert!(jet::CBind::generate_data(
        "proto",
        "bad.proto",
        "message A { string x = 19000; }",
        None,
        "",
    ).is_err());
    assert!(jet::CBind::generate_data(
        "proto",
        "bad.proto",
        "message A { reserved 1 to 5; string x = 1; }",
        None,
        "",
    ).is_err());
    assert!(jet::CBind::generate_data(
        "proto",
        "bad.proto",
        "message A { string Child = 1; enum Child { ZERO = 0; } }",
        None,
        "",
    ).is_err());
}

#[test]
fn proto_accepts_strict_options_enums_and_reserved_forms() {
    let source = generated(
        "proto",
        "valid.proto",
        r#"syntax = "proto3";
package sample.api;
option java_package = "sample.api";
message Repo {
  reserved "retired", 10 to 12;
  string name = 1 [deprecated = true];
  State state = 2;
}
enum State {
  option allow_alias = true;
  reserved -3 to -1;
  UNKNOWN = 0;
  READY = 1;
  ALSO_READY = 1;
}
"#,
        Some("Repo"),
        "jet bind proto valid.proto --type Repo",
    );
    assert!(source.contains("state: Int"));
    assert_generated_source_parses(&source);
}

#[test]
fn data_bind_provenance_is_hashed_and_stable() {
    let input = "{\"name\":\"jet\",\"count\":2}";
    let first = generated(
        "json",
        "fixtures/stable.json",
        input,
        Some("Stable"),
        "jet bind json fixtures/stable.json --type Stable",
    );
    let second = generated(
        "json",
        "fixtures/stable.json",
        input,
        Some("Stable"),
        "jet bind json fixtures/stable.json --type Stable",
    );
    assert_eq!(first, second);
    let hash = jet::SHA256::sha256_hex(input.as_bytes());
    assert!(first.contains("input: fixtures/stable.json"));
    assert!(first.contains(&format!("sha256: {hash}")));
    assert!(first.contains("generated by: jet bind json fixtures/stable.json --type Stable"));
    assert!(first.contains("format: json"));
    assert!(first.contains("inference: JSON object fields become #Codable fields"));

    let changed = generated(
        "json",
        "fixtures/stable.json",
        "{\"name\":\"jet\",\"count\":3}",
        Some("Stable"),
        "jet bind json fixtures/stable.json --type Stable",
    );
    assert_ne!(first, changed);
}

#[test]
fn public_cli_covers_each_data_format_parse_hash_and_idempotence() {
    let dir = scratch("all-formats");
    let cases = [
        (
            "json",
            "repo.json",
            r#"{"name":"jet","count":9007199254740993,"scale":1e9999}"#,
            "Repo",
        ),
        (
            "csv",
            "people.csv",
            "name,age\nAda,36\nLin,37\n",
            "Person",
        ),
        (
            "sql",
            "schema.sql",
            "CREATE TABLE users (id INTEGER PRIMARY KEY, name VARCHAR(32) NOT NULL, created TIMESTAMP(0));",
            "Users",
        ),
        (
            "xml",
            "catalog.xml",
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><catalog><book id=\"1\"/></catalog>",
            "Catalog",
        ),
        (
            "proto",
            "repo.proto",
            "syntax = \"proto3\"; message Repo { string name = 1; }",
            "Repo",
        ),
    ];
    for (format, filename, input, root) in cases {
        let input_path = dir.join(filename);
        fs::write(&input_path, input).unwrap();
        let input_text = input_path.to_str().unwrap();
        let args = ["bind", format, input_text, "--type", root];
        let first = Command::new(env!("CARGO_BIN_EXE_jet"))
            .args(args)
            .current_dir(&dir)
            .env("NO_COLOR", "1")
            .output()
            .unwrap();
        assert_success(first);
        let stem = filename.rsplit_once('.').map(|(stem, _)| stem).unwrap();
        let output_path = dir.join("bindings").join(format!("{stem}.jet"));
        let before = fs::read_to_string(&output_path).unwrap();
        assert!(before.contains("#Codable"));
        assert!(before.contains(&format!("sha256: {}", jet::SHA256::sha256_hex(input.as_bytes()))));
        assert_generated_source_parses(&before);

        let second = Command::new(env!("CARGO_BIN_EXE_jet"))
            .args(args)
            .current_dir(&dir)
            .env("NO_COLOR", "1")
            .output()
            .unwrap();
        assert_success(second);
        assert_eq!(before, fs::read_to_string(&output_path).unwrap());
    }

    let malformed = [
        ("json", "bad.json", "{"),
        ("csv", "bad.csv", "a,a\n1,2\n"),
        ("sql", "bad.sql", "CREATE TABLE x (id UNKNOWN);"),
        ("xml", "bad.xml", "<a attr=\"&bad;\"/>"),
        ("proto", "bad.proto", "message A { string x = 19000; }"),
    ];
    for (format, filename, input) in malformed {
        let path = dir.join(filename);
        fs::write(&path, input).unwrap();
        let output = Command::new(env!("CARGO_BIN_EXE_jet"))
            .args(["bind", format, path.to_str().unwrap(), "--type", "Bad"])
            .current_dir(&dir)
            .env("NO_COLOR", "1")
            .output()
            .unwrap();
        assert_eq!(output.status.code(), Some(1));
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(stderr.contains("Error [E3208]:"), "{format} missing E3208: {stderr}");
        assert!(stderr.contains("Why:") && stderr.contains("Fix:"), "{format}: {stderr}");
    }
    let _ = fs::remove_dir_all(dir);
}

#[test]
fn data_bind_cli_writes_visible_output_and_regeneration_diff() {
    let dir = scratch("cli");
    let input = dir.join("records.json");
    fs::write(&input, "{\"name\":\"first\",\"count\":1}").unwrap();
    let input_text = input.to_str().unwrap();

    let first = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args(["bind", "json", input_text, "--type", "Record"])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert_success(first);
    let default_output = dir.join("bindings/records.jet");
    assert!(default_output.is_file());
    let before = fs::read_to_string(&default_output).unwrap();
    assert!(before.contains("#Codable"));
    assert!(before.contains("struct Record"));
    assert!(before.contains(input_text));

    fs::write(&input, "{\"name\":\"second\",\"count\":2,\"active\":true}").unwrap();
    let stale = fs::read_to_string(&default_output).unwrap();
    assert_eq!(before, stale);

    let regenerated = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args(["bind", "json", input_text, "--type", "Record"])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert_success(regenerated);
    let regenerated_output = fs::read_to_string(&default_output).unwrap();
    assert_ne!(before, regenerated_output);
    assert!(regenerated_output.contains("active: Bool"));

    let explicit = dir.join("generated/record.jet");
    let explicit_text = explicit.to_str().unwrap();
    let second = Command::new(env!("CARGO_BIN_EXE_jet"))
        .args([
            "bind",
            "json",
            input_text,
            "--type",
            "Record",
            "-o",
            explicit_text,
        ])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert_success(second);
    let after = fs::read_to_string(&explicit).unwrap();
    assert_ne!(before, after);
    assert!(after.contains("active: Bool"));
    assert!(after.contains(explicit_text));
    assert!(Path::new(explicit_text).is_file());

    let _ = fs::remove_dir_all(dir);
}
