//! Generate and check one `site/dist/e/<CODE>/index.html` page for every
//! diagnostic row.
//!
//! The normal check compares committed pages with the typed registry. The
//! snapshot blessing command runs this test in the same invocation:
//!
//!     UPDATE_EXPECT=1 UPDATE_EXPECT_REASON="diagnostic page refresh" \
//!       cargo test --test diagnostic_snapshots --test diagnostic_pages
//!
//! `UPDATE_EXPECT` writes the generated pages. Without it, any missing, extra,
//! or changed page fails the build.

use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

const GENERATED_DIR: &str = "site/dist/e";
const SNAPSHOT_DIRS: &[&str] = &["tests/ui", "tests/ui_lint"];

struct Snapshot {
    path: String,
    text: String,
}

fn html_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
        .replace('\0', "&#0;")
}

fn collect_snapshot_paths(dir: &Path, out: &mut Vec<PathBuf>) {
    let mut entries: Vec<PathBuf> = fs::read_dir(dir)
        .unwrap_or_else(|error| panic!("cannot read {}: {error}", dir.display()))
        .map(|entry| entry.unwrap().path())
        .collect();
    entries.sort();
    for path in entries {
        if path.is_dir() {
            collect_snapshot_paths(&path, out);
        } else if matches!(
            path.extension().and_then(|extension| extension.to_str()),
            Some("stderr") | Some("warn")
        ) {
            out.push(path);
        }
    }
}

fn snapshots(root: &Path) -> Vec<Snapshot> {
    let mut paths = Vec::new();
    for directory in SNAPSHOT_DIRS {
        collect_snapshot_paths(&root.join(directory), &mut paths);
    }
    paths.sort();
    paths
        .into_iter()
        .map(|path| Snapshot {
            path: path
                .strip_prefix(root)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/"),
            text: fs::read_to_string(&path)
                .unwrap_or_else(|error| panic!("cannot read {}: {error}", path.display())),
        })
        .collect()
}

fn first_snapshot<'a>(snapshots: &'a [Snapshot], code: &str) -> Option<&'a Snapshot> {
    let marker = format!("[{code}]");
    snapshots.iter().find(|snapshot| snapshot.text.contains(&marker))
}

fn collect_html_paths(dir: &Path, root: &Path, out: &mut BTreeSet<PathBuf>) {
    let mut entries: Vec<PathBuf> = fs::read_dir(dir)
        .unwrap_or_else(|error| panic!("cannot read {}: {error}", dir.display()))
        .map(|entry| entry.unwrap().path())
        .collect();
    entries.sort();
    for path in entries {
        if path.is_dir() {
            collect_html_paths(&path, root, out);
        } else if path.extension().and_then(|extension| extension.to_str()) == Some("html") {
            out.insert(path.strip_prefix(root).unwrap().to_path_buf());
        }
    }
}

fn sorted_rows() -> Vec<&'static jet_foundation::Registry::DiagnosticRow> {
    let mut rows: Vec<_> = jet_foundation::Registry::diagnostic_rows().iter().collect();
    rows.sort_by(|left, right| left.code.cmp(right.code));
    rows
}

fn render_page(
    row: &jet_foundation::Registry::DiagnosticRow,
    example: Option<&Snapshot>,
) -> String {
    let code = html_escape(row.code);
    let what = html_escape(row.what);
    let why = html_escape(row.why);
    let fix = html_escape(row.fix);
    let description = html_escape(row.what);
    let example = match example {
        Some(snapshot) => format!(
            "<p>First UI snapshot mentioning <code>{code}</code>: <code>{}</code>.</p>\n<pre class=\"diag\">{}</pre>",
            html_escape(&snapshot.path),
            html_escape(&snapshot.text),
        ),
        None => "<p>No UI snapshot currently mentions this code.</p>".to_string(),
    };

    format!(
        "<!-- Generated by tests/diagnostic_pages.rs; do not edit. -->\n\
         <!doctype html>\n\
         <html lang=\"en\">\n\
         <head>\n\
         <meta charset=\"utf-8\">\n\
         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\
         <title>{code} — Jet diagnostic</title>\n\
         <meta name=\"description\" content=\"{description}\">\n\
         <meta property=\"og:title\" content=\"{code} — Jet diagnostic\">\n\
         <meta property=\"og:description\" content=\"{description}\">\n\
         <link rel=\"icon\" type=\"image/svg+xml\" href=\"../../assets/favicon.svg\">\n\
         <link rel=\"stylesheet\" href=\"../../assets/site.css\">\n\
         </head>\n\
         <body>\n\
         <header class=\"wrap nav\">\n\
           <a class=\"nav-brand\" href=\"../../index.html\" aria-label=\"Jet home\"><span class=\"word\">jet</span></a>\n\
           <nav><ul class=\"nav-links\">\n\
             <li><a href=\"../../tour.html\">Tour</a></li>\n\
             <li><a href=\"../../install.html\">Install</a></li>\n\
             <li><a href=\"../index.html\" aria-current=\"page\">Error codes</a></li>\n\
           </ul></nav>\n\
         </header>\n\
         <main>\n\
         <section class=\"wrap page\">\n\
           <div class=\"page-header\">\n\
             <p class=\"eyebrow\">// diagnostic</p>\n\
             <h1>{code}</h1>\n\
             <p>{what}</p>\n\
           </div>\n\
         </section>\n\
         <article class=\"wrap article\">\n\
           <h2>What</h2>\n\
           <p class=\"diag-copy what\" data-registry-field=\"what\">{what}</p>\n\
           <h2>Why</h2>\n\
           <p class=\"diag-copy why\" data-registry-field=\"why\">{why}</p>\n\
           <h2>Fix</h2>\n\
           <p class=\"diag-copy fix\" data-registry-field=\"fix\">{fix}</p>\n\
           <h2>Worked example</h2>\n\
           {example}\n\
           <p><a href=\"../index.html\">Back to all error codes</a></p>\n\
         </article>\n\
         </main>\n\
         <footer class=\"footer\">\n\
           <div class=\"wrap footer-grid\">\n\
             <a class=\"nav-brand\" href=\"../../index.html\" aria-label=\"Jet home\"><span class=\"word\">jet</span></a>\n\
             <p class=\"made\">Generated from Jet's diagnostic registry and UI snapshots.</p>\n\
           </div>\n\
         </footer>\n\
         </body>\n\
         </html>\n",
    )
}

fn line_diff(expected: &str, actual: &str) -> String {
    let expected_lines: Vec<_> = expected.lines().collect();
    let actual_lines: Vec<_> = actual.lines().collect();
    let first = expected_lines
        .iter()
        .zip(&actual_lines)
        .position(|(left, right)| left != right)
        .unwrap_or(expected_lines.len().min(actual_lines.len()));
    format!(
        "first differing line {}\n- {}\n+ {}",
        first + 1,
        expected_lines.get(first).copied().unwrap_or("<missing>"),
        actual_lines.get(first).copied().unwrap_or("<missing>"),
    )
}

#[test]
fn diagnostic_pages_match_registry_and_snapshots() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let output = root.join(GENERATED_DIR);
    let snapshot_files = snapshots(&root);
    let rows = sorted_rows();
    let expected_codes: BTreeSet<&str> = rows.iter().map(|row| row.code).collect();
    assert_eq!(
        expected_codes.len(),
        rows.len(),
        "diagnostic registry contains duplicate codes"
    );

    let update = std::env::var_os("UPDATE_EXPECT").is_some()
        || std::env::var_os("UPDATE_DIAGNOSTIC_PAGES").is_some();
    if update {
        fs::create_dir_all(&output).unwrap();
    }

    let mut generated = 0usize;
    for row in rows {
        let page = render_page(row, first_snapshot(&snapshot_files, row.code));
        for (field, value) in [("what", row.what), ("why", row.why), ("fix", row.fix)] {
            let marker = format!(
                "<p class=\"diag-copy {field}\" data-registry-field=\"{field}\">{}</p>",
                html_escape(value)
            );
            assert!(
                page.contains(&marker),
                "{} page lost registry {field} text",
                row.code
            );
        }

        let path = output.join(row.code).join("index.html");
        if update {
            fs::create_dir_all(path.parent().unwrap()).unwrap();
            fs::write(&path, &page)
                .unwrap_or_else(|error| panic!("cannot write {}: {error}", path.display()));
        } else {
            let actual = fs::read_to_string(&path).unwrap_or_else(|error| {
                panic!(
                    "missing generated page {}: {error}; run with UPDATE_EXPECT=1",
                    path.display()
                )
            });
            assert_eq!(
                actual,
                page,
                "{} drifted:\n{}",
                path.display(),
                line_diff(&page, &actual)
            );
        }
        generated += 1;
    }

    let expected_pages: BTreeSet<PathBuf> = expected_codes
        .iter()
        .map(|code| PathBuf::from(code).join("index.html"))
        .collect();
    let mut actual_pages = BTreeSet::new();
    if output.is_dir() {
        collect_html_paths(&output, &output, &mut actual_pages);
    }
    actual_pages.remove(Path::new("index.html"));
    assert_eq!(
        actual_pages, expected_pages,
        "generated diagnostic page set drifted; hand-authored or stale pages exist"
    );

    println!(
        "diagnostic pages: generated {generated} / registry {}",
        expected_codes.len()
    );
    assert_eq!(generated, expected_codes.len());
}
