//! `workspace.lock` — generated lock file for the common workspace case
//! (D-WORKSPACE1=B).
//!
//! The lock is written as a simple TOML-like format under `.jet/workspace.lock`
//! at the workspace root. External tools that need a static index (IDEs, CI
//! scripts) can read this file without evaluating Jet.
//!
//! Format:
//! ```toml
//! # .jet/workspace.lock — generated by jetpack; do not edit
//! version = 1
//!
//! [[member]]
//! name = "hello"
//! path = "packages/hello"
//!
//! [[member]]
//! name = "ranker"
//! path = "packages/ranker"
//! ```

use crate::Syntax;
use std::path::Path;

use super::WorkspaceFile::WorkspacePlan;

/// The lock file path within the workspace root.
pub const WORKSPACE_LOCK: &str = ".jet/workspace.lock";

/// Write `.jet/workspace.lock` from a freshly evaluated `WorkspacePlan`.
/// Creates `.jet/` if it doesn't exist. Silently ignores write failures
/// (the lock is best-effort; the source of truth is `workspace.jet`).
pub fn write(workspace_root: &Path, plan: &WorkspacePlan) {
    let lock_dir = workspace_root.join(".jet");
    if std::fs::create_dir_all(&lock_dir).is_err() {
        return;
    }
    let mut out = String::new();
    out.push_str(&format!(
        "# {} — generated by jetpack; do not edit\n",
        WORKSPACE_LOCK
    ));
    out.push_str("version = 1\n");
    for member in &plan.members {
        out.push('\n');
        out.push_str("[[member]]\n");
        out.push_str(&format!("name = {:?}\n", member.name));
        out.push_str(&format!("path = {:?}\n", member.path));
    }
    let lock_path = workspace_root.join(WORKSPACE_LOCK);
    let _ = std::fs::write(lock_path, out);
}

/// Load and parse `.jet/workspace.lock` from `workspace_root`. Returns `None`
/// when the file is absent. Returns an empty plan on parse failure (the lock is
/// best-effort; callers should fall back to evaluating `workspace.jet`).
pub fn load(workspace_root: &Path) -> Option<WorkspacePlan> {
    let lock_path = workspace_root.join(WORKSPACE_LOCK);
    let src = std::fs::read_to_string(&lock_path).ok()?;
    Some(parse_lock(&src))
}

/// Parse the `.jet/workspace.lock` TOML-like format into a `WorkspacePlan`.
fn parse_lock(src: &str) -> WorkspacePlan {
    use super::WorkspaceFile::WorkspaceMember;

    let mut members = Vec::new();
    let mut cur_name: Option<String> = None;
    let mut cur_path: Option<String> = None;

    for line in src.lines() {
        let line = line.trim();
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        if line == "[[member]]" {
            // Commit the previous member if complete.
            if let (Some(name), Some(path)) = (cur_name.take(), cur_path.take()) {
                members.push(WorkspaceMember { name, path });
            }
            continue;
        }
        if let Some(rest) = line.strip_prefix("name = ") {
            cur_name = Some(unquote(rest));
        } else if let Some(rest) = line.strip_prefix("path = ") {
            cur_path = Some(unquote(rest));
        }
        // Ignore `version = …` and unknown keys.
    }
    // Flush the last member.
    if let (Some(name), Some(path)) = (cur_name, cur_path) {
        members.push(WorkspaceMember { name, path });
    }
    WorkspacePlan { members }
}

/// Strip surrounding `"…"` from a TOML string value.
fn unquote(s: &str) -> String {
    let s = s.trim();
    if s.starts_with('"') && s.ends_with('"') && s.len() >= 2 {
        // Unescape minimal Rust/TOML escapes used in our writer (`\n`, `\\`, `\"`).
        let inner = &s[1..s.len() - 1];
        let mut out = String::with_capacity(inner.len());
        let mut chars = inner.chars();
        while let Some(c) = chars.next() {
            if c == '\\' {
                match chars.next() {
                    Some('n') => out.push('\n'),
                    Some('t') => out.push('\t'),
                    Some('\\') => out.push('\\'),
                    Some('"') => out.push('"'),
                    Some(c) => {
                        out.push('\\');
                        out.push(c);
                    }
                    None => out.push('\\'),
                }
            } else {
                out.push(c);
            }
        }
        out
    } else {
        s.to_string()
    }
}

// ── check that Syntax::PAYLOAD_FILE is accessible (used for doc purposes) ─────
const _: &str = Syntax::WORKSPACE_FILE;

#[cfg(test)]
mod tests {
    use super::super::WorkspaceFile::WorkspaceMember;
    use super::*;

    fn member(name: &str, path: &str) -> WorkspaceMember {
        WorkspaceMember {
            name: name.to_string(),
            path: path.to_string(),
        }
    }

    #[test]
    fn roundtrip_empty() {
        let plan = WorkspacePlan { members: vec![] };
        let tmp = std::env::temp_dir().join(format!(
            "wlock-empty-{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .subsec_nanos()
        ));
        std::fs::create_dir_all(&tmp).unwrap();
        write(&tmp, &plan);
        let loaded = load(&tmp).unwrap();
        assert!(loaded.members.is_empty());
        std::fs::remove_dir_all(&tmp).ok();
    }

    #[test]
    fn roundtrip_with_members() {
        let plan = WorkspacePlan {
            members: vec![
                member("hello", "packages/hello"),
                member("ranker", "packages/ranker"),
            ],
        };
        let tmp = std::env::temp_dir().join(format!(
            "wlock-members-{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .subsec_nanos()
        ));
        std::fs::create_dir_all(&tmp).unwrap();
        write(&tmp, &plan);
        let loaded = load(&tmp).unwrap();
        assert_eq!(loaded.members.len(), 2);
        assert_eq!(loaded.members[0].name, "hello");
        assert_eq!(loaded.members[0].path, "packages/hello");
        assert_eq!(loaded.members[1].name, "ranker");
        assert_eq!(loaded.members[1].path, "packages/ranker");
        std::fs::remove_dir_all(&tmp).ok();
    }

    #[test]
    fn parse_lock_ignores_comments_and_blanks() {
        let src =
            "# header\nversion = 1\n\n[[member]]\nname = \"hello\"\npath = \"packages/hello\"\n";
        let plan = parse_lock(src);
        assert_eq!(plan.members.len(), 1);
        assert_eq!(plan.members[0].name, "hello");
    }
}
