name = "Jet"
grammar = "jet"
path_suffixes = ["jet"]
line_comments = ["// ", "/// "]
tab_size = 4
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
