//! FreePascal cdecl binder with bounded owned handles (D-FFI-PASCAL1=A).

use std::collections::BTreeSet;
use std::io::Read;
use std::path::{Path,PathBuf};
use std::process::{Command,Stdio};
use std::time::{Duration,Instant};

#[derive(Debug,Clone,PartialEq,Eq)]
pub struct BindResult { pub source:String,pub bound:Vec<String>,pub archive:PathBuf,pub runtime:PathBuf,pub provenance:String }
#[derive(Debug,Clone,PartialEq,Eq)]
pub enum BindError { Source(String),ToolMissing(&'static str),ToolFailed(&'static str,String),Io(String) }
impl std::fmt::Display for BindError { fn fmt(&self,f:&mut std::fmt::Formatter<'_>)->std::fmt::Result { match self { Self::Source(v)|Self::Io(v)=>f.write_str(v),Self::ToolMissing(v)=>write!(f,"the provisioned `{v}` tool was not found"),Self::ToolFailed(t,v)=>write!(f,"`{t}` rejected the Pascal binding source: {v}") } } }

#[derive(Clone,Copy,PartialEq,Eq)] enum Scalar { Int,Float,Pointer,Void }
impl Scalar { fn jet(self)->&'static str {match self{Self::Int=>"Int",Self::Float=>"Float",Self::Pointer=>"Int",Self::Void=>""}}fn c(self)->&'static str{match self{Self::Int=>"int64_t",Self::Float=>"double",Self::Pointer=>"void*",Self::Void=>"void"}} }
#[derive(Clone)] struct Param { name:String,kind:Scalar }
#[derive(Clone)] struct Routine { name:String,params:Vec<Param>,result:Scalar }
struct Handle { group:String,ctor:Routine,close:Routine,methods:Vec<Routine> }
struct Surface { plain:Vec<Routine>,handle:Handle }

pub fn bind(path:&Path,source:&str,lib:&str,cache:&Path)->Result<BindResult,BindError>{
    if !ident(lib){return Err(BindError::Source(format!("`{lib}` is not a valid Jet library name")))}
    let surface=parse(source)?;std::fs::create_dir_all(cache).map_err(|e|BindError::Io(format!("could not create Pascal binding cache: {e}")))?;
    let build=cache.join(format!(".pascal-build-{lib}"));let _=std::fs::remove_dir_all(&build);std::fs::create_dir_all(&build).map_err(|e|BindError::Io(format!("could not create Pascal build directory: {e}")))?;
    let runtime=cache.join(format!("libjet_pascal_{lib}_runtime{}",shared_ext()));let _=std::fs::remove_file(&runtime);
    run(Command::new("fpc").args(["-Mobjfpc","-Cg","-O2",&format!("-FU{}",build.display()),&format!("-FE{}",cache.display()),&format!("-o{}",runtime.display())]).arg(path),"fpc")?;
    if !runtime.is_file(){return Err(BindError::Source("FreePascal did not produce the requested shared library".into()))}
    let bridge=build.join(format!("jet_pascal_{lib}.c"));let object=build.join(format!("jet_pascal_{lib}.o"));std::fs::write(&bridge,render_c(lib,&surface)).map_err(|e|BindError::Io(format!("could not write Pascal handle bridge: {e}")))?;
    run(Command::new("cc").args(["-std=c11","-fPIC","-c"]).arg(&bridge).arg("-o").arg(&object),"cc")?;
    let archive=cache.join(format!("libjet_pascal_{lib}.a"));let _=std::fs::remove_file(&archive);run(Command::new("ar").arg("rcs").arg(&archive).arg(&object),"ar")?;
    let compiler=tool_path("fpc").ok_or(BindError::ToolMissing("fpc"))?;let mut identity=b"jet-pascal-bind-v1\0".to_vec();identity.extend_from_slice(source.as_bytes());identity.push(0);identity.extend_from_slice(compiler.to_string_lossy().as_bytes());
    let mut bound=surface.plain.iter().map(|v|v.name.clone()).collect::<Vec<_>>();bound.push(surface.handle.ctor.name.clone());bound.extend(surface.handle.methods.iter().map(|v|v.name.clone()));bound.push(format!("{}_close",surface.handle.group));
    let generated=render_jet(lib,&surface);let _=std::fs::remove_dir_all(&build);Ok(BindResult{source:generated,bound,archive,runtime,provenance:format!("schema=jet-pascal-bind-v1\nsha256={}\n",crate::SHA256::sha256_hex(&identity))})
}

fn parse(source:&str)->Result<Surface,BindError>{let text=strip_comments(source);let lower=text.to_ascii_lowercase();if !lower.trim_start().starts_with("library "){return Err(BindError::Source("the Pascal binder requires a `library` source".into()))}
    let export_at=lower.rfind("exports ").ok_or_else(||BindError::Source("the Pascal library has no `exports` list".into()))?;let export_tail=&lower[export_at+8..];let export_end=export_tail.find(';').ok_or_else(||BindError::Source("the Pascal `exports` list is not terminated".into()))?;let exports=export_tail[..export_end].split(',').map(|v|v.split_whitespace().next().unwrap_or("").trim()).filter(|v|ident(v)).map(str::to_string).collect::<BTreeSet<_>>();
    let class=class_name(&lower).ok_or_else(||BindError::Source("no Object Pascal class declaration was found".into()))?;let group=class.trim_start_matches('t').to_string();if group.is_empty(){return Err(BindError::Source("the Pascal class name cannot form a handle name".into()))}
    let mut routines=Vec::new();let mut cursor=0;while cursor<lower.len(){let f=lower[cursor..].find("function ").map(|v|(cursor+v,false));let p=lower[cursor..].find("procedure ").map(|v|(cursor+v,true));let next=match(f,p){(Some(a),Some(b))=>Some(if a.0<b.0{a}else{b}),(Some(a),None)=>Some(a),(None,Some(b))=>Some(b),(None,None)=>None};let Some((start,is_proc))=next else{break};let after=start+1;let next_f=lower[after..].find("function ").map(|v|after+v);let next_p=lower[after..].find("procedure ").map(|v|after+v);let next_decl=match(next_f,next_p){(Some(a),Some(b))=>Some(a.min(b)),(Some(a),None)|(None,Some(a))=>Some(a),(None,None)=>None};let Some(cdecl_rel)=lower[start..].find("cdecl;")else{cursor=next_decl.unwrap_or(lower.len());continue};let end=start+cdecl_rel;if next_decl.is_some_and(|v|v<end){cursor=next_decl.unwrap();continue}let header=&lower[start..end];let routine=parse_routine(header,is_proc)?;cursor=end+6;if exports.contains(&routine.name)&&!routines.iter().any(|v: &Routine|v.name==routine.name){routines.push(routine)}}
    let ctor_name=format!("{group}_new");let close_names=[format!("{group}_free"),format!("{group}_close")];let ctor=routines.iter().find(|v|v.name==ctor_name&&v.result==Scalar::Pointer).cloned().ok_or_else(||BindError::Source(format!("class `{class}` needs exported cdecl `{ctor_name}` returning Pointer")))?;let close=routines.iter().find(|v|close_names.contains(&v.name)&&v.result==Scalar::Void&&v.params.first().is_some_and(|p|p.kind==Scalar::Pointer)).cloned().ok_or_else(||BindError::Source(format!("class `{class}` needs exported cdecl `{group}_free(handle: Pointer)`")))?;
    let methods=routines.iter().filter(|v|v.name.starts_with(&format!("{group}_"))&&v.name!=ctor.name&&v.name!=close.name&&v.params.first().is_some_and(|p|p.kind==Scalar::Pointer)&&matches!(v.result,Scalar::Int|Scalar::Float)).cloned().collect::<Vec<_>>();if methods.is_empty(){return Err(BindError::Source(format!("class `{class}` has no exported scalar cdecl method wrapper")))}
    let plain=routines.into_iter().filter(|v|!v.params.iter().any(|p|p.kind==Scalar::Pointer)&&matches!(v.result,Scalar::Int|Scalar::Float)).collect();Ok(Surface{plain,handle:Handle{group,ctor,close,methods}})}

fn parse_routine(header:&str,is_proc:bool)->Result<Routine,BindError>{let keyword=if is_proc{"procedure "}else{"function "};let rest=header.strip_prefix(keyword).ok_or_else(||BindError::Source("malformed cdecl routine".into()))?;let open=rest.find('(').ok_or_else(||BindError::Source("cdecl routine needs an explicit parameter list".into()))?;let name=rest[..open].trim().to_string();if !ident(&name){return Err(BindError::Source(format!("`{name}` is not a bindable Pascal export")))}let close=matching_close(rest,open).ok_or_else(||BindError::Source(format!("routine `{name}` has no closed parameter list")))?;let mut params=Vec::new();for group in rest[open+1..close].split(';'){if group.trim().is_empty(){continue}let Some((names,kind))=group.split_once(':')else{return Err(BindError::Source(format!("routine `{name}` has a malformed parameter")))};let kind=scalar(kind).ok_or_else(||BindError::Source(format!("routine `{name}` uses unsupported parameter type `{}`",kind.trim())))?;for item in names.split(','){let item=item.trim().trim_start_matches("const ").trim_start_matches("var ").to_string();if !ident(&item){return Err(BindError::Source(format!("routine `{name}` has invalid parameter `{item}`")))}params.push(Param{name:item,kind})}}
    let result=if is_proc{Scalar::Void}else{let tail=rest[close+1..].trim();let kind=tail.strip_prefix(':').ok_or_else(||BindError::Source(format!("function `{name}` has no result type")))?.split(';').next().unwrap_or("");scalar(kind).ok_or_else(||BindError::Source(format!("function `{name}` uses unsupported result type `{}`",kind.trim())))?};Ok(Routine{name,params,result})}
fn scalar(value:&str)->Option<Scalar>{match value.trim().to_ascii_lowercase().as_str(){"int64"|"qword"|"ptrint"|"ptruint"=>Some(Scalar::Int),"double"=>Some(Scalar::Float),"pointer"=>Some(Scalar::Pointer),_=>None}}

fn render_jet(lib:&str,s:&Surface)->String{let abi=format!("jet_pascal_{lib}");let ty=pascal_case(&s.handle.group);let mut o=format!("@Extern module c.{abi} {{\n    fn take_error() -> Int = \"{abi}_take_error\"\n");for r in &s.plain{raw_jet(&mut o,&abi,r,&r.name)}raw_jet(&mut o,&abi,&s.handle.ctor,&s.handle.ctor.name);for r in &s.handle.methods{raw_jet(&mut o,&abi,r,&r.name)}raw_jet(&mut o,&abi,&s.handle.close,&format!("{}_close",s.handle.group));o.push_str("}\nuse c.");o.push_str(&abi);o.push_str(" as abi\n\npub enum PascalError { InvalidHandle Foreign }\npub struct ");o.push_str(&ty);o.push_str(" { value: Int }\n\n");for r in &s.plain{o.push_str("pub fn ");o.push_str(&r.name);params_jet(&mut o,&r.params,0);o.push_str(" -> ");o.push_str(r.result.jet());o.push_str(" { return abi.");o.push_str(&r.name);call_args(&mut o,&r.params,0,None);o.push_str(" }\n\n")}
    o.push_str("pub fn ");o.push_str(&s.handle.ctor.name);params_jet(&mut o,&s.handle.ctor.params,0);o.push_str(" -> ");o.push_str(&ty);o.push_str(" ? PascalError {\n    raw_handle :: abi.");o.push_str(&s.handle.ctor.name);call_args(&mut o,&s.handle.ctor.params,0,None);o.push_str("\n    code :: abi.take_error()\n    if code == 1 { return Err(PascalError.InvalidHandle) }\n    if code != 0 { return Err(PascalError.Foreign) }\n    return Ok(");o.push_str(&ty);o.push_str(".{ value: raw_handle })\n}\n\n");for r in &s.handle.methods{o.push_str("pub fn ");o.push_str(&r.name);o.push_str("(handle: ");o.push_str(&ty);for p in r.params.iter().skip(1){o.push_str(", ");o.push_str(&p.name);o.push_str(": ");o.push_str(p.kind.jet())}o.push_str(") -> ");o.push_str(r.result.jet());o.push_str(" ? PascalError {\n    result_value :: abi.");o.push_str(&r.name);call_args(&mut o,&r.params,1,Some("handle.value"));o.push_str("\n    code :: abi.take_error()\n    if code == 1 { return Err(PascalError.InvalidHandle) }\n    if code != 0 { return Err(PascalError.Foreign) }\n    return Ok(result_value)\n}\n\n")}
    o.push_str("impl ");o.push_str(&ty);o.push_str(".Close {\n    fn close(^self) {\n        abi.");o.push_str(&format!("{}_close",s.handle.group));o.push_str("(self.value)\n        if abi.take_error() != 0 { panic(\"invalid Pascal handle\") }\n    }\n}\n");o}
fn raw_jet(out:&mut String,abi:&str,r:&Routine,name:&str){out.push_str("    fn ");out.push_str(name);params_jet(out,&r.params,0);if r.result!=Scalar::Void{out.push_str(" -> ");out.push_str(r.result.jet())}out.push_str(" = \"");out.push_str(&format!("{abi}_{name}\"\n"))}
fn params_jet(out:&mut String,params:&[Param],skip:usize){out.push('(');for(i,p)in params.iter().skip(skip).enumerate(){if i>0{out.push_str(", ")}out.push_str(&p.name);out.push_str(": ");out.push_str(p.kind.jet())}out.push(')')}
fn call_args(out:&mut String,params:&[Param],skip:usize,first:Option<&str>){out.push('(');let mut any=false;if let Some(v)=first{out.push_str(v);any=true}for p in params.iter().skip(skip){if any{out.push_str(", ")}out.push_str(&p.name);any=true}out.push(')')}

fn render_c(lib:&str,s:&Surface)->String{let abi=format!("jet_pascal_{lib}");let h=&s.handle;let mut o="#include <stdint.h>\n#include <pthread.h>\n#include <stdlib.h>\nstatic void* slots[64];static pthread_mutex_t lock=PTHREAD_MUTEX_INITIALIZER;static pthread_once_t once=PTHREAD_ONCE_INIT;static _Thread_local int64_t failed;\n".to_string();for r in &s.plain{raw_c_decl(&mut o,r)}raw_c_decl(&mut o,&h.ctor);for r in &h.methods{raw_c_decl(&mut o,r)}raw_c_decl(&mut o,&h.close);o.push_str("static void finish(void){for(int i=0;i<64;i++)if(slots[i]){");o.push_str(&h.close.name);o.push_str("(slots[i]);slots[i]=0;}}\nstatic void init(void){atexit(finish);}\nstatic void* get(int64_t h){if(h<1||h>64){failed=1;return 0;}pthread_mutex_lock(&lock);void*p=slots[h-1];pthread_mutex_unlock(&lock);if(!p)failed=1;return p;}\n");o.push_str(&format!("int64_t {abi}_take_error(void){{int64_t v=failed;failed=0;return v;}}\n"));for r in &s.plain{wrapper_c(&mut o,&abi,r,&r.name,None)}
    o.push_str(&format!("int64_t {abi}_{}(",h.ctor.name));c_params(&mut o,&h.ctor.params,0);o.push_str("){failed=0;pthread_once(&once,init);void*p=");o.push_str(&h.ctor.name);c_args(&mut o,&h.ctor.params,0,None);o.push_str(";if(!p){failed=2;return 0;}pthread_mutex_lock(&lock);for(int i=0;i<64;i++)if(!slots[i]){slots[i]=p;pthread_mutex_unlock(&lock);return i+1;}pthread_mutex_unlock(&lock);");o.push_str(&h.close.name);o.push_str("(p);failed=2;return 0;}\n");for r in &h.methods{wrapper_c(&mut o,&abi,r,&r.name,Some("p"))}
    o.push_str(&format!("void {abi}_{}_close(int64_t h){{failed=0;if(h<1||h>64){{failed=1;return;}}pthread_mutex_lock(&lock);void*p=slots[h-1];if(p)slots[h-1]=0;pthread_mutex_unlock(&lock);if(!p){{failed=1;return;}}",h.group));o.push_str(&h.close.name);o.push_str("(p);}\n");o}
fn raw_c_decl(out:&mut String,r:&Routine){out.push_str("extern ");out.push_str(r.result.c());out.push(' ');out.push_str(&r.name);out.push('(');c_params(out,&r.params,0);out.push_str(");\n")}
fn wrapper_c(out:&mut String,abi:&str,r:&Routine,name:&str,handle:Option<&str>){out.push_str(r.result.c());out.push(' ');out.push_str(&format!("{abi}_{name}("));if handle.is_some(){out.push_str("int64_t handle");if r.params.len()>1{out.push(',')}c_params(out,&r.params,1)}else{c_params(out,&r.params,0)}out.push_str("){failed=0;");if let Some(v)=handle{out.push_str("void*");out.push_str(v);out.push_str("=get(handle);if(!");out.push_str(v);out.push_str(")return 0;")}out.push_str("return ");out.push_str(&r.name);c_args(out,&r.params,usize::from(handle.is_some()),handle);out.push_str(";}\n")}
fn c_params(out:&mut String,params:&[Param],skip:usize){if params.len()==skip{out.push_str("void")}for(i,p)in params.iter().skip(skip).enumerate(){if i>0{out.push(',')}out.push_str(p.kind.c());out.push(' ');out.push_str(&p.name)}}
fn c_args(out:&mut String,params:&[Param],skip:usize,first:Option<&str>){out.push('(');let mut any=false;if let Some(v)=first{out.push_str(v);any=true}for p in params.iter().skip(skip){if any{out.push(',')}out.push_str(&p.name);any=true}out.push(')')}

fn strip_comments(source:&str)->String{let mut out=String::new();let mut chars=source.chars().peekable();let mut brace=false;let mut paren=false;while let Some(c)=chars.next(){if brace{if c=='}'{brace=false}continue}if paren{if c=='*'&&chars.peek()==Some(&')'){chars.next();paren=false}continue}if c=='{'{brace=true;continue}if c=='('&&chars.peek()==Some(&'*'){chars.next();paren=true;continue}if c=='/'&&chars.peek()==Some(&'/'){for n in chars.by_ref(){if n=='\n'{out.push('\n');break}}continue}out.push(c)}out}
fn class_name(lower:&str)->Option<String>{let at=lower.find("= class")?;lower[..at].split_whitespace().last().filter(|v|ident(v)).map(str::to_string)}
fn matching_close(text:&str,open:usize)->Option<usize>{let mut depth=0;for(i,c)in text.char_indices().skip_while(|(i,_)|*i<open){match c{'('=>depth+=1,')'=>{depth-=1;if depth==0{return Some(i)}},_=>{}}}None}
fn tool_path(tool:&str)->Option<PathBuf>{let path=std::env::var_os("PATH")?;std::env::split_paths(&path).map(|v|v.join(tool)).find(|v|v.is_file()).and_then(|v|std::fs::canonicalize(v).ok())}
fn run(command:&mut Command,tool:&'static str)->Result<(),BindError>{const CAP:usize=64*1024;command.stdout(Stdio::piped()).stderr(Stdio::piped());let mut child=command.spawn().map_err(|e|if e.kind()==std::io::ErrorKind::NotFound{BindError::ToolMissing(tool)}else{BindError::Io(format!("could not start `{tool}`: {e}"))})?;let stdout=child.stdout.take().ok_or_else(||BindError::Io(format!("could not supervise `{tool}` stdout")))?;let stderr=child.stderr.take().ok_or_else(||BindError::Io(format!("could not supervise `{tool}` stderr")))?;let out=std::thread::spawn(move||drain(stdout,CAP));let err=std::thread::spawn(move||drain(stderr,CAP));let deadline=Instant::now()+Duration::from_secs(60);let status=loop{match child.try_wait().map_err(|e|BindError::Io(format!("could not supervise `{tool}`: {e}")))?{Some(v)=>break v,None if Instant::now()>=deadline=>{let _=child.kill();let _=child.wait();let _=out.join();let _=err.join();return Err(BindError::ToolFailed(tool,"the tool exceeded the 60 second limit".into()))},None=>std::thread::sleep(Duration::from_millis(10))}};let stdout=out.join().map_err(|_|BindError::Io(format!("`{tool}` stdout reader failed")))??;let stderr=err.join().map_err(|_|BindError::Io(format!("`{tool}` stderr reader failed")))??;if status.success(){Ok(())}else{let detail=if stderr.is_empty(){&stdout}else{&stderr};Err(BindError::ToolFailed(tool,launder(detail)))}}
fn drain(mut input:impl Read,limit:usize)->Result<Vec<u8>,BindError>{let mut out=Vec::new();let mut buf=[0u8;8192];loop{let n=input.read(&mut buf).map_err(|e|BindError::Io(format!("could not read foreign tool output: {e}")))?;if n==0{break}let keep=(limit-out.len()).min(n);out.extend_from_slice(&buf[..keep]);}Ok(out)}
fn launder(v:&[u8])->String{let text=String::from_utf8_lossy(v);if text.lines().any(|v|v.contains("Fatal:")){return "compilation failed".into()}text.lines().map(str::trim).find(|v|!v.is_empty()).map(|v|v.chars().take(160).collect()).unwrap_or_else(||"the foreign tool returned a failure status".into())}
fn pascal_case(v:&str)->String{let mut chars=v.chars();match chars.next(){Some(c)=>c.to_ascii_uppercase().to_string()+chars.as_str(),None=>"Handle".into()}}
fn ident(v:&str)->bool{let mut c=v.chars();matches!(c.next(),Some(x)if x.is_ascii_alphabetic()||x=='_')&&c.all(|x|x.is_ascii_alphanumeric()||x=='_')}
#[cfg(target_os="linux")]fn shared_ext()->&'static str{".so"}
#[cfg(target_os="macos")]fn shared_ext()->&'static str{".dylib"}
#[cfg(target_os="windows")]fn shared_ext()->&'static str{".dll"}
