use super::*;
use crate::Diagnostics::{Diagnostic, Span};
use crate::Sema::Effects::Effect;
use crate::Syntax;
use crate::AST::{AccessConvention, Expr, Type};

include!("CheckerCoreLib/imports.rs");
include!("CheckerCoreLib/fields_ptrs.rs");
include!("CheckerCoreLib/serde.rs");
include!("CheckerCoreLib/reactive.rs");
include!("CheckerCoreLib/core_call.rs");
include!("CheckerCoreLib/a11y.rs");
include!("CheckerCoreLib/core_literals.rs");
include!("CheckerCoreLib/arg_expect.rs");
include!("CheckerCoreLib/db_methods.rs");
include!("CheckerCoreLib/db_returns.rs");
include!("CheckerCoreLib/plugin_checks.rs");
include!("CheckerCoreLib/plugin_returns.rs");
include!("CheckerCoreLib/core_types.rs");
include!("CheckerCoreLib/math_layout.rs");
include!("CheckerCoreLib/net_text_time.rs");
include!("CheckerCoreLib/alloc_ptrs.rs");
include!("CheckerCoreLib/fixed_sigs.rs");
include!("CheckerCoreLib/process_ui.rs");
include!("CheckerCoreLib/module_items.rs");
include!("CheckerCoreLib/serde_diags.rs");
include!("CheckerCoreLib/data_reflect.rs");
include!("CheckerCoreLib/tests.rs");
