//! Private current-format compiler-image envelope and metadata primitives.
//!
//! Source/native MIR conversion is generated from `RuntimeMirCodec.rs`; the native
//! payload codec is schema-generated by `jet-foundation/build/MirImageCodec.rs`.
//! This module binds those bytes to checked source authority, artifact, private
//! factory root, and full execution identity.

use crate::compiler_bootstrap_host::AuthorizedSourceSnapshot;
use jet_foundation::MIR::{
    MirAccess, MirArtifactId, MirArtifactTarget, MirExecutionIdentity, MirFunction,
    MirFunctionForm, MirFunctionId, MirFunctionKind, MirOwnershipMode, MirProgram,
    MIR_SCHEMA_VERSION,
};

pub(crate) const MAGIC: &[u8; 8] = b"JETCIMG\0";
pub(crate) const FORMAT_VERSION: u16 = 3;
const CHECKSUM_BYTES: usize = 32;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct CompilerImageHeader {
    pub(crate) format_version: u16,
    pub(crate) mir_schema_version: u16,
    pub(crate) source_authority_digest: [u8; 32],
    pub(crate) artifact: MirArtifactId,
    /// Checked private factory root; independent of the public artifact entry.
    pub(crate) entry_function: MirFunctionId,
    pub(crate) identity: MirExecutionIdentity,
}

struct EncodedCompilerImageHeader {
    format_version: u16,
    mir_schema_version: u16,
    source_authority_digest: [u8; 32],
    artifact: MirArtifactId,
    entry_function: MirFunctionId,
}

/// Envelope fields read from the archive prefix without decoding the MIR
/// payload: what callers that only select the compiler artifact or compare
/// source authority need.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct CompilerImageEnvelope {
    pub(crate) source_authority_digest: [u8; 32],
    pub(crate) artifact: MirArtifactId,
    pub(crate) entry_function: MirFunctionId,
}

pub(crate) struct RestoredCompilerImage {
    pub(crate) header: CompilerImageHeader,
    pub(crate) program: MirProgram,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct CompilerImageError(pub(crate) String);

impl std::fmt::Display for CompilerImageError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl std::error::Error for CompilerImageError {}

/// Field encoder shared by compiler-image metadata and identity hashing.
#[doc(hidden)]
pub(crate) struct CompilerImageMetadataWriter {
    bytes: Vec<u8>,
}

impl CompilerImageMetadataWriter {
    pub(crate) fn new() -> Self {
        Self { bytes: Vec::new() }
    }

    pub(crate) fn write_u8(&mut self, value: u8) {
        self.bytes.push(value);
    }

    pub(crate) fn write_u16(&mut self, value: u16) {
        self.bytes.extend_from_slice(&value.to_le_bytes());
    }

    pub(crate) fn write_u64(&mut self, value: u64) {
        self.bytes.extend_from_slice(&value.to_le_bytes());
    }

    pub(crate) fn write_raw(&mut self, value: &[u8]) {
        self.bytes.extend_from_slice(value);
    }

    pub(crate) fn write_len(&mut self, value: usize) -> Result<(), String> {
        let value = u64::try_from(value)
            .map_err(|_| "compiler-image length exceeds u64".to_string())?;
        self.write_u64(value);
        Ok(())
    }

    pub(crate) fn write_bytes(&mut self, value: &[u8]) -> Result<(), String> {
        self.write_len(value.len())?;
        self.write_raw(value);
        Ok(())
    }

    pub(crate) fn write_string(&mut self, value: &str) -> Result<(), String> {
        self.write_bytes(value.as_bytes())
    }

    pub(crate) fn finish(self) -> Vec<u8> {
        self.bytes
    }
}

/// Reader for private compiler-image envelope metadata.
#[doc(hidden)]
pub(crate) struct CompilerImageMetadataReader<'a> {
    bytes: &'a [u8],
    cursor: usize,
}

impl<'a> CompilerImageMetadataReader<'a> {
    pub(crate) fn new(bytes: &'a [u8]) -> Self {
        Self { bytes, cursor: 0 }
    }

    pub(crate) fn read_u16(&mut self) -> Result<u16, String> {
        let bytes = self.read_raw(2)?;
        Ok(u16::from_le_bytes([bytes[0], bytes[1]]))
    }

    pub(crate) fn read_u64(&mut self) -> Result<u64, String> {
        let bytes = self.read_raw(8)?;
        Ok(u64::from_le_bytes([
            bytes[0], bytes[1], bytes[2], bytes[3], bytes[4], bytes[5], bytes[6], bytes[7],
        ]))
    }

    pub(crate) fn read_raw(&mut self, length: usize) -> Result<&'a [u8], String> {
        let end = self
            .cursor
            .checked_add(length)
            .ok_or_else(|| "compiler-image cursor overflow".to_string())?;
        let bytes = self
            .bytes
            .get(self.cursor..end)
            .ok_or_else(|| "truncated compiler-image archive".to_string())?;
        self.cursor = end;
        Ok(bytes)
    }

    pub(crate) fn read_len(&mut self) -> Result<usize, String> {
        let raw = self.read_u64()?;
        let length = usize::try_from(raw)
            .map_err(|_| "compiler-image length exceeds the host address space".to_string())?;
        if length > self.bytes.len().saturating_sub(self.cursor).saturating_add(1) {
            return Err("compiler-image length exceeds the remaining archive".to_string());
        }
        Ok(length)
    }

    pub(crate) fn read_bytes(&mut self) -> Result<&'a [u8], String> {
        let length = self.read_len()?;
        self.read_raw(length)
    }

    pub(crate) fn read_string(&mut self) -> Result<String, String> {
        String::from_utf8(self.read_bytes()?.to_vec())
            .map_err(|_| "compiler-image string is not valid UTF-8".to_string())
    }

    pub(crate) fn finish(self) -> Result<(), String> {
        if self.cursor != self.bytes.len() {
            return Err("compiler-image archive has trailing bytes".to_string());
        }
        Ok(())
    }
}

/// Serialize a complete, checked compiler MIR image using the canonical native
/// MIR image codec. The private factory root is selected from checked bindings;
/// user-result MIR must not be passed here.
pub(crate) fn archive_compiler_image<SourceProgram>(
    source_program: &SourceProgram,
    program: &MirProgram,
    artifact: MirArtifactId,
    entry_function: MirFunctionId,
    source_authority: &AuthorizedSourceSnapshot,
    source_to_native: impl FnOnce(&SourceProgram) -> Result<MirProgram, String>,
) -> Result<Vec<u8>, CompilerImageError> {
    program
        .validate()
        .map_err(|error| CompilerImageError(format!("invalid compiler-image MIR: {error}")))?;
    check_factory_root(program, artifact, entry_function)?;
    let identity = program
        .execution_identity(Some(artifact))
        .map_err(|error| CompilerImageError(format!("invalid compiler-image identity: {error}")))?;
    let source_native = source_to_native(source_program).map_err(CompilerImageError)?;
    let payload =
        jet_foundation::MIR::mir_program_image_bytes(&source_native).map_err(CompilerImageError)?;
    let native_payload =
        jet_foundation::MIR::mir_program_image_bytes(program).map_err(CompilerImageError)?;
    if payload != native_payload {
        let differences = mir_program_field_differences(program, &source_native);
        return Err(CompilerImageError(format!(
            "Source MIR compiler image does not preserve every canonical native MIR field \
             ({} differing field paths; `path xCOUNT: first sample: native | restored`):\n{}",
            differences.len(),
            differences.join("\n")
        )));
    }
    let header = CompilerImageHeader {
        format_version: FORMAT_VERSION,
        mir_schema_version: MIR_SCHEMA_VERSION,
        source_authority_digest: compiler_image_source_authority_digest(source_authority),
        artifact,
        entry_function,
        identity,
    };
    encode_archive(&header, &payload)
}

/// Read the envelope of one private compiler image for the exact source
/// authority, artifact, and checked factory root selected by the caller.
///
/// Only the fixed-size prefix is read: magic, format, MIR schema, artifact,
/// entry, and source authority are checked exactly as
/// `restore_compiler_image` checks them, so the returned fields equal the
/// caller's expectations. The archive checksum, execution identity, and
/// factory root are verified when the program itself is restored; no MIR is
/// decoded or digested here.
pub(crate) fn read_compiler_image_envelope(
    bytes: &[u8],
    expected_source_authority_digest: [u8; 32],
    expected_artifact: MirArtifactId,
    expected_entry_function: MirFunctionId,
) -> Result<CompilerImageEnvelope, CompilerImageError> {
    if bytes.len() < MAGIC.len() + 2 + 2 + 8 + 8 + 32 + 8 + 8 + CHECKSUM_BYTES {
        return Err(CompilerImageError("truncated compiler-image archive".into()));
    }
    let mut reader = CompilerImageMetadataReader::new(bytes);
    let raw_header = decode_envelope_prefix(&mut reader)?;
    check_envelope(
        &raw_header,
        expected_source_authority_digest,
        expected_artifact,
        expected_entry_function,
    )?;
    Ok(CompilerImageEnvelope {
        source_authority_digest: raw_header.source_authority_digest,
        artifact: raw_header.artifact,
        entry_function: raw_header.entry_function,
    })
}

/// Restore one private compiler image for the exact source authority, artifact,
/// and checked factory root selected by the caller.
///
/// The image was legality-checked, identity-sealed and Source-round-trip
/// checked when it was archived, and its SHA-256 checksum covers every byte,
/// so restore verifies the checksum (linear in the bytes) and the factory
/// root, takes the program digest from the optimizer seal, and never
/// re-verifies, re-encodes or re-digests the whole compiler program. The
/// Source-typed projection of the program is not built here: the one reader
/// that needs it converts it for the duration of its use.
pub(crate) fn restore_compiler_image(
    bytes: &[u8],
    expected_source_authority_digest: [u8; 32],
    expected_artifact: MirArtifactId,
    expected_entry_function: MirFunctionId,
) -> Result<RestoredCompilerImage, CompilerImageError> {
    let (raw_header, payload, identity_bytes) = decode_archive(bytes)?;
    check_envelope(
        &raw_header,
        expected_source_authority_digest,
        expected_artifact,
        expected_entry_function,
    )?;
    let program =
        jet_foundation::MIR::mir_program_from_image_bytes(payload).map_err(CompilerImageError)?;
    check_factory_root(&program, expected_artifact, expected_entry_function)?;
    let identity = program
        .sealed_execution_identity(Some(expected_artifact))
        .map_err(|error| CompilerImageError(format!("invalid compiler-image identity: {error}")))?;
    if encode_identity(&identity)? != identity_bytes {
        return Err(CompilerImageError(
            "compiler-image execution identity does not match its MIR payload".into(),
        ));
    }
    let header = CompilerImageHeader {
        format_version: raw_header.format_version,
        mir_schema_version: raw_header.mir_schema_version,
        source_authority_digest: raw_header.source_authority_digest,
        artifact: raw_header.artifact,
        entry_function: raw_header.entry_function,
        identity,
    };
    Ok(RestoredCompilerImage { header, program })
}

fn check_envelope(
    raw_header: &EncodedCompilerImageHeader,
    expected_source_authority_digest: [u8; 32],
    expected_artifact: MirArtifactId,
    expected_entry_function: MirFunctionId,
) -> Result<(), CompilerImageError> {
    if raw_header.mir_schema_version != MIR_SCHEMA_VERSION {
        return Err(CompilerImageError(format!(
            "compiler-image MIR schema {} does not match current schema {}",
            raw_header.mir_schema_version, MIR_SCHEMA_VERSION
        )));
    }
    if raw_header.source_authority_digest != expected_source_authority_digest {
        return Err(CompilerImageError(
            "compiler-image source authority does not match the authorized source snapshot".into(),
        ));
    }
    if raw_header.artifact != expected_artifact {
        return Err(CompilerImageError(
            "compiler-image artifact identity does not match the requested artifact".into(),
        ));
    }
    if raw_header.entry_function != expected_entry_function {
        return Err(CompilerImageError(
            "compiler-image entry function does not match the requested entry".into(),
        ));
    }
    Ok(())
}

/// The compiler program with every row and every function signature but no
/// function bodies (blocks, locals, values, places, scopes and drops are
/// empty). Host type-shape queries read only nominal, field, Core-owner and
/// handle rows, so they answer identically on this projection, while its
/// Source conversion skips the bodies that make up most of the program.
pub(crate) fn compiler_image_signature_program(program: &MirProgram) -> MirProgram {
    MirProgram {
        cffi: program.cffi.clone(),
        schema_version: program.schema_version,
        package_identity: program.package_identity.clone(),
        facts: program.facts.clone(),
        names: program.names.clone(),
        modules: program.modules.clone(),
        imports: program.imports.clone(),
        types: program.types.clone(),
        traits: program.traits.clone(),
        core_owners: program.core_owners.clone(),
        impls: program.impls.clone(),
        constants: program.constants.clone(),
        fields: program.fields.clone(),
        source_files: program.source_files.clone(),
        functions: program.functions.iter().map(function_signature).collect(),
        foreign: program.foreign.clone(),
        links: program.links.clone(),
        callbacks: program.callbacks.clone(),
        handles: program.handles.clone(),
        jobs: program.jobs.clone(),
        tests: program.tests.clone(),
        harnesses: program.harnesses.clone(),
        artifacts: program.artifacts.clone(),
        core_calls: program.core_calls.clone(),
        prelude_calls: program.prelude_calls.clone(),
        type_instances: program.type_instances.clone(),
        codec_migrations: program.codec_migrations.clone(),
        unreachable: program.unreachable.clone(),
    }
}

fn function_signature(function: &MirFunction) -> MirFunction {
    MirFunction {
        id: function.id,
        module_id: function.module_id,
        source_file: function.source_file,
        key: function.key.clone(),
        module: function.module.clone(),
        name: function.name.clone(),
        span: function.span.clone(),
        kind: function.kind,
        form: function.form.clone(),
        visibility: function.visibility,
        target_applicability: function.target_applicability.clone(),
        web_bucket: function.web_bucket.clone(),
        web_marker: function.web_marker.clone(),
        generic_params: function.generic_params.clone(),
        capture_params: function.capture_params.clone(),
        params: function.params.clone(),
        declared_return: function.declared_return.clone(),
        return_type: function.return_type.clone(),
        failure: function.failure.clone(),
        effects: function.effects.clone(),
        captures: function.captures.clone(),
        generator: function.generator.clone(),
        optimization: function.optimization.clone(),
        is_unsafe: function.is_unsafe,
        unsafe_gate: function.unsafe_gate.clone(),
        is_pure: function.is_pure,
        memo_bound: function.memo_bound,
        is_reactive: function.is_reactive,
        reactive_upgrades: function.reactive_upgrades.clone(),
        is_inline: function.is_inline,
        is_inline_always: function.is_inline_always,
        is_scalar: function.is_scalar,
        kernel_proof: function.kernel_proof.clone(),
        gc_return: function.gc_return,
        return_view_provenance: function.return_view_provenance.clone(),
        web_param_reconstructions: function.web_param_reconstructions.clone(),
        blocks: Vec::new(),
        entry: function.entry,
        locals: Vec::new(),
        values: Vec::new(),
        places: Vec::new(),
        scopes: Vec::new(),
        drops: Vec::new(),
        foreign_language: function.foreign_language.clone(),
    }
}

fn check_factory_root(
    program: &MirProgram,
    artifact: MirArtifactId,
    entry_function: MirFunctionId,
) -> Result<(), CompilerImageError> {
    let artifact_plan = program
        .artifacts
        .iter()
        .find(|row| row.id == artifact)
        .ok_or_else(|| CompilerImageError("compiler-image artifact is absent from MIR".into()))?;
    if artifact_plan.target != MirArtifactTarget::RustAot {
        return Err(CompilerImageError(
            "compiler-image artifact is not a Rust AOT target".into(),
        ));
    }
    let factory = program
        .functions
        .iter()
        .find(|function| function.id == entry_function)
        .ok_or_else(|| {
            CompilerImageError("compiler-image factory function is absent from MIR".into())
        })?;
    if !artifact_plan.modules.contains(&factory.module_id) {
        return Err(CompilerImageError(
            "compiler-image factory module is outside the selected artifact closure".into(),
        ));
    }
    if factory.name != "jet_bootstrap_compile"
        || factory.kind != MirFunctionKind::Jet
        || !matches!(&factory.form, MirFunctionForm::TopLevel)
        || !factory.target_applicability.rust_aot
        || !factory.generic_params.is_empty()
        || !factory.capture_params.is_empty()
        || factory.params.len() != 1
    {
        return Err(CompilerImageError(
            "compiler-image root is not the checked Rust AOT jet_bootstrap_compile factory"
                .into(),
        ));
    }
    let request = &factory.params[0];
    if request.index != 0
        || request.access != MirAccess::Move
        || !matches!(
            request.ownership.mode,
            MirOwnershipMode::Owned | MirOwnershipMode::Move
        )
        || request.variadic
        || request.default_present
    {
        return Err(CompilerImageError(
            "compiler-image factory must take one owned compile request".into(),
        ));
    }
    let request = request
        .ty
        .nominal_id()
        .and_then(|id| program.types.iter().find(|definition| definition.id == id))
        .ok_or_else(|| {
            CompilerImageError(
                "compiler-image factory request is not a checked nominal type".into(),
            )
        })?;
    let result = factory
        .return_type
        .nominal_id()
        .and_then(|id| program.types.iter().find(|definition| definition.id == id))
        .ok_or_else(|| {
            CompilerImageError(
                "compiler-image factory result is not a checked nominal type".into(),
            )
        })?;
    if !artifact_plan.modules.contains(&request.module)
        || !artifact_plan.modules.contains(&result.module)
    {
        return Err(CompilerImageError(
            "compiler-image factory request/result types are outside the selected artifact closure"
                .into(),
        ));
    }
    if request.name != "JetDriverCompileRequest" || result.name != "JetDriverCompileResult" {
        return Err(CompilerImageError(
            "compiler-image factory signature is not JetDriverCompileRequest -> JetDriverCompileResult"
                .into(),
        ));
    }
    Ok(())
}

/// Content identity of an authorized compiler source snapshot: which bytes
/// were compiled, under which root-relative paths. The physical facts of the
/// open (absolute root paths, device, inode, mtime) are deliberately left out:
/// they differ between two assemblies of the same tree, and this digest is
/// embedded in every generated compiler and decides whether a self-compile is
/// compiling the compiler's own source, so it must not depend on the build
/// directory or on when the files were written.
pub(crate) fn compiler_image_source_authority_digest(
    source: &AuthorizedSourceSnapshot,
) -> [u8; 32] {
    let mut writer = CompilerImageMetadataWriter::new();
    let entry_root = source
        .roots
        .iter()
        .position(|root| root.identity == source.entry_root_identity);
    writer.write_u64(entry_root.map_or(u64::MAX, |index| index as u64));
    let entry = entry_root
        .and_then(|index| {
            source.entry_path.strip_prefix(&source.roots[index].canonical_path)
        })
        .map_or(source.entry_path.as_str(), |relative| relative.trim_start_matches('/'));
    writer
        .write_string(entry)
        .expect("source authority string length fits u64");
    writer
        .write_len(source.roots.len())
        .expect("source root count fits u64");
    for root in &source.roots {
        writer.write_u8(u8::from(root.allow_hardlinks));
        write_authorized_files(&mut writer, &root.files);
        write_authorized_files(&mut writer, &root.foreign_cache_files);
    }
    jet_foundation::SHA256::sha256(&writer.finish())
}

fn write_authorized_files(
    writer: &mut CompilerImageMetadataWriter,
    files: &[crate::compiler_bootstrap_host::AuthorizedSourceFile],
) {
    writer.write_len(files.len()).expect("source file count fits u64");
    for file in files {
        writer
            .write_string(&file.relative_path)
            .expect("source authority string length fits u64");
        writer
            .write_len(file.source.len())
            .expect("source file length fits u64");
        writer.write_raw(&jet_foundation::SHA256::sha256(file.source.as_bytes()));
    }
}

fn encode_archive(
    header: &CompilerImageHeader,
    payload: &[u8],
) -> Result<Vec<u8>, CompilerImageError> {
    let identity = encode_identity(&header.identity)?;
    let identity_len = u64::try_from(identity.len())
        .map_err(|_| CompilerImageError("compiler-image identity is too large".into()))?;
    let payload_len = u64::try_from(payload.len())
        .map_err(|_| CompilerImageError("compiler-image MIR payload is too large".into()))?;
    let capacity = MAGIC
        .len()
        .checked_add(2 + 2 + 8 + 8 + 32 + 8 + 8 + CHECKSUM_BYTES)
        .and_then(|length| length.checked_add(identity.len()))
        .and_then(|length| length.checked_add(payload.len()))
        .ok_or_else(|| CompilerImageError("compiler-image size overflows usize".into()))?;
    let mut bytes = Vec::new();
    bytes
        .try_reserve_exact(capacity)
        .map_err(|_| CompilerImageError("compiler-image is too large to allocate".into()))?;
    bytes.extend_from_slice(MAGIC);
    bytes.extend_from_slice(&header.format_version.to_le_bytes());
    bytes.extend_from_slice(&header.mir_schema_version.to_le_bytes());
    bytes.extend_from_slice(&header.artifact.0.to_le_bytes());
    bytes.extend_from_slice(&header.entry_function.0.to_le_bytes());
    bytes.extend_from_slice(&header.source_authority_digest);
    bytes.extend_from_slice(&identity_len.to_le_bytes());
    bytes.extend_from_slice(&identity);
    bytes.extend_from_slice(&payload_len.to_le_bytes());
    bytes.extend_from_slice(payload);
    let checksum = jet_foundation::SHA256::sha256(&bytes);
    bytes.extend_from_slice(&checksum);
    Ok(bytes)
}

fn decode_archive(
    bytes: &[u8],
) -> Result<(EncodedCompilerImageHeader, &[u8], Vec<u8>), CompilerImageError> {
    if bytes.len() < MAGIC.len() + 2 + 2 + 8 + 8 + 32 + 8 + 8 + CHECKSUM_BYTES {
        return Err(CompilerImageError("truncated compiler-image archive".into()));
    }
    let content_end = bytes
        .len()
        .checked_sub(CHECKSUM_BYTES)
        .ok_or_else(|| CompilerImageError("truncated compiler-image checksum".into()))?;
    let expected_checksum = &bytes[content_end..];
    if jet_foundation::SHA256::sha256(&bytes[..content_end]).as_slice() != expected_checksum {
        return Err(CompilerImageError(
            "compiler-image archive checksum mismatch".into(),
        ));
    }
    let mut reader = CompilerImageMetadataReader::new(&bytes[..content_end]);
    let header = decode_envelope_prefix(&mut reader)?;
    let identity_len = reader.read_len().map_err(CompilerImageError)?;
    let identity = reader
        .read_raw(identity_len)
        .map_err(CompilerImageError)?
        .to_vec();
    let payload_len = reader.read_len().map_err(CompilerImageError)?;
    let payload = reader
        .read_raw(payload_len)
        .map_err(CompilerImageError)?;
    reader.finish().map_err(CompilerImageError)?;
    Ok((header, payload, identity))
}

/// Decode the fixed-size archive prefix (magic through source authority).
fn decode_envelope_prefix(
    reader: &mut CompilerImageMetadataReader<'_>,
) -> Result<EncodedCompilerImageHeader, CompilerImageError> {
    if reader.read_raw(MAGIC.len()).map_err(CompilerImageError)? != MAGIC {
        return Err(CompilerImageError("invalid compiler-image magic".into()));
    }
    let format_version = reader.read_u16().map_err(CompilerImageError)?;
    if format_version != FORMAT_VERSION {
        return Err(CompilerImageError(format!(
            "unsupported private compiler-image format {format_version}"
        )));
    }
    let mir_schema_version = reader.read_u16().map_err(CompilerImageError)?;
    let artifact = MirArtifactId(reader.read_u64().map_err(CompilerImageError)?);
    let entry_function = MirFunctionId(reader.read_u64().map_err(CompilerImageError)?);
    if artifact.0 == 0 || entry_function.0 == 0 {
        return Err(CompilerImageError(
            "compiler-image contains a zero artifact or entry identity".into(),
        ));
    }
    let source_authority_digest: [u8; 32] = reader
        .read_raw(32)
        .map_err(CompilerImageError)?
        .try_into()
        .map_err(|_| CompilerImageError("invalid compiler-image authority digest".into()))?;
    Ok(EncodedCompilerImageHeader {
        format_version,
        mir_schema_version,
        source_authority_digest,
        artifact,
        entry_function,
    })
}

fn encode_identity(identity: &MirExecutionIdentity) -> Result<Vec<u8>, CompilerImageError> {
    let mut writer = CompilerImageMetadataWriter::new();
    writer.write_u16(identity.schema_version);
    let artifact = &identity.artifact;
    writer.write_u16(artifact.schema_version);
    writer.write_u16(artifact.mir_schema_version);
    writer.write_raw(&artifact.program_digest);
    writer
        .write_string(&artifact.package_identity)
        .map_err(CompilerImageError)?;
    writer.write_u64(artifact.artifact.0);
    writer
        .write_string(&artifact.name)
        .map_err(CompilerImageError)?;
    writer
        .write_string(artifact.kind.as_str())
        .map_err(CompilerImageError)?;
    writer
        .write_string(artifact.target.as_str())
        .map_err(CompilerImageError)?;
    writer
        .write_string(artifact.mode.as_str())
        .map_err(CompilerImageError)?;
    writer
        .write_string(&artifact.provider_identity)
        .map_err(CompilerImageError)?;
    writer
        .write_string(&artifact.closure_identity)
        .map_err(CompilerImageError)?;
    writer
        .write_string(&artifact.artifact_identity)
        .map_err(CompilerImageError)?;
    let program = &artifact.program_identity;
    writer
        .write_string(&program.semantic_hash)
        .map_err(CompilerImageError)?;
    writer
        .write_string(&program.optimized_hash)
        .map_err(CompilerImageError)?;
    write_u64_values(&mut writer, &program.function_ids)?;
    write_u64_values(&mut writer, &program.core_ids)?;
    writer
        .write_len(program.target_facts.len())
        .map_err(CompilerImageError)?;
    for (key, value) in &program.target_facts {
        writer.write_string(key).map_err(CompilerImageError)?;
        writer.write_string(value).map_err(CompilerImageError)?;
    }
    writer
        .write_len(program.source_map.len())
        .map_err(CompilerImageError)?;
    for source in &program.source_map {
        writer.write_u64(source.id);
        writer.write_string(&source.path).map_err(CompilerImageError)?;
        writer
            .write_string(&source.digest)
            .map_err(CompilerImageError)?;
    }
    Ok(writer.finish())
}

fn write_u64_values(
    writer: &mut CompilerImageMetadataWriter,
    values: &[u64],
) -> Result<(), CompilerImageError> {
    writer
        .write_len(values.len())
        .map_err(CompilerImageError)?;
    for value in values {
        writer.write_u64(*value);
    }
    Ok(())
}


/// Every field path where `restored` differs from `native`, one line per
/// index-free path with its occurrence count and the first concrete sample,
/// so one failed restore names the whole lossy set instead of a bool.
/// Elements are compared through their `Debug` rendering (streamed into a
/// digest; only differing elements are rendered and walked).
fn mir_program_field_differences(native: &MirProgram, restored: &MirProgram) -> Vec<String> {
    let MirProgram {
        cffi,
        schema_version,
        package_identity,
        facts,
        names,
        modules,
        imports,
        types,
        traits,
        core_owners,
        impls,
        constants,
        fields,
        source_files,
        functions,
        foreign,
        links,
        callbacks,
        handles,
        jobs,
        tests,
        harnesses,
        artifacts,
        core_calls,
        prelude_calls,
        type_instances,
        codec_migrations,
        unreachable,
    } = native;
    let mut diff = DebugFieldDiff::default();
    diff.value("cffi".into(), cffi, &restored.cffi);
    diff.value("schema_version".into(), schema_version, &restored.schema_version);
    diff.value("package_identity".into(), package_identity, &restored.package_identity);
    diff.value("facts".into(), facts, &restored.facts);
    diff.value("names".into(), names, &restored.names);
    diff.list("modules", modules, &restored.modules, |row| row.name.clone());
    diff.list("imports", imports, &restored.imports, |_| String::new());
    diff.list("types", types, &restored.types, |row| row.name.clone());
    diff.list("traits", traits, &restored.traits, |row| row.name.clone());
    diff.list("core_owners", core_owners, &restored.core_owners, |_| String::new());
    diff.list("impls", impls, &restored.impls, |_| String::new());
    diff.list("constants", constants, &restored.constants, |row| row.name.clone());
    diff.list("fields", fields, &restored.fields, |_| String::new());
    diff.list("source_files", source_files, &restored.source_files, |_| String::new());
    diff.list("functions", functions, &restored.functions, |row| row.name.clone());
    diff.list("foreign", foreign, &restored.foreign, |_| String::new());
    diff.list("links", links, &restored.links, |_| String::new());
    diff.list("callbacks", callbacks, &restored.callbacks, |_| String::new());
    diff.list("handles", handles, &restored.handles, |_| String::new());
    diff.list("jobs", jobs, &restored.jobs, |_| String::new());
    diff.list("tests", tests, &restored.tests, |_| String::new());
    diff.list("harnesses", harnesses, &restored.harnesses, |_| String::new());
    diff.list("artifacts", artifacts, &restored.artifacts, |row| row.name.clone());
    diff.list("core_calls", core_calls, &restored.core_calls, |_| String::new());
    diff.list("prelude_calls", prelude_calls, &restored.prelude_calls, |_| String::new());
    diff.list("type_instances", type_instances, &restored.type_instances, |_| String::new());
    let native_migrations = codec_migrations.iter().collect::<std::collections::BTreeMap<_, _>>();
    let restored_migrations =
        restored.codec_migrations.iter().collect::<std::collections::BTreeMap<_, _>>();
    diff.value("codec_migrations".into(), &native_migrations, &restored_migrations);
    diff.list("unreachable", unreachable, &restored.unreachable, |_| String::new());
    diff.finish()
}

#[derive(Default)]
struct DebugFieldDiff {
    /// Index-free path -> (occurrences, first concrete sample).
    classes: std::collections::BTreeMap<String, (usize, String)>,
    /// Total recorded differences, so a value can tell whether its walk found any.
    records: usize,
}

struct DebugDigest(std::collections::hash_map::DefaultHasher);

impl std::fmt::Write for DebugDigest {
    fn write_str(&mut self, text: &str) -> std::fmt::Result {
        std::hash::Hasher::write(&mut self.0, text.as_bytes());
        Ok(())
    }
}

fn debug_digest<T: std::fmt::Debug>(value: &T) -> u64 {
    let mut digest = DebugDigest(Default::default());
    let _ = std::fmt::Write::write_fmt(&mut digest, format_args!("{value:?}"));
    std::hash::Hasher::finish(&digest.0)
}

/// One node of a pretty `{:#?}` rendering: a leaf line or an opened
/// struct/tuple/list/map with its children keyed by field name or position.
struct DebugNode<'a> {
    label: &'a str,
    compound: bool,
    children: Vec<(String, DebugNode<'a>)>,
}

impl DebugNode<'_> {
    fn summary(&self) -> String {
        let mut text = if self.compound {
            format!("{} {{{} children}}", self.label, self.children.len())
        } else {
            self.label.to_string()
        };
        if text.len() > 200 {
            let mut end = 200;
            while !text.is_char_boundary(end) {
                end -= 1;
            }
            text.truncate(end);
            text.push('…');
        }
        text
    }
}

/// Split `key: rest` where key is a field name or a quoted map key.
fn split_debug_key(line: &str) -> (Option<&str>, &str) {
    let bytes = line.as_bytes();
    let end = if bytes.first() == Some(&b'"') {
        let mut index = 1;
        while index < bytes.len() && bytes[index] != b'"' {
            index += if bytes[index] == b'\\' { 2 } else { 1 };
        }
        (index < bytes.len()).then_some(index + 1)
    } else {
        let length = bytes
            .iter()
            .take_while(|byte| byte.is_ascii_alphanumeric() || **byte == b'_')
            .count();
        (length > 0 && !bytes[0].is_ascii_uppercase()).then_some(length)
    };
    match end {
        Some(end) if line[end..].starts_with(": ") => (Some(&line[..end]), &line[end + 2..]),
        _ => (None, line),
    }
}

fn parse_debug_children<'a>(lines: &mut std::str::Lines<'a>) -> Vec<(String, DebugNode<'a>)> {
    let mut children = Vec::new();
    while let Some(raw) = lines.next() {
        let line = raw.trim();
        if line.starts_with(['}', ']', ')']) {
            break;
        }
        let (key, rest) = split_debug_key(line);
        let key = key.map_or_else(|| format!("[{}]", children.len()), |key| format!(".{key}"));
        let node = match rest.strip_suffix(['{', '(', '[']) {
            Some(label) => DebugNode {
                label: label.trim_end(),
                compound: true,
                children: parse_debug_children(lines),
            },
            None => DebugNode {
                label: rest.strip_suffix(',').unwrap_or(rest),
                compound: false,
                children: Vec::new(),
            },
        };
        children.push((key, node));
    }
    children
}

fn parse_debug_tree(text: &str) -> DebugNode<'_> {
    let mut lines = text.lines();
    let mut root = parse_debug_children(&mut lines);
    if root.len() == 1 {
        root.pop().expect("one root").1
    } else {
        DebugNode { label: "", compound: true, children: root }
    }
}

impl DebugFieldDiff {
    fn record(&mut self, path: String, native: String, restored: String) {
        let mut class = String::with_capacity(path.len());
        let mut in_index = false;
        for character in path.chars() {
            match character {
                '[' => {
                    in_index = true;
                    class.push_str("[*]");
                }
                ']' => in_index = false,
                _ if !in_index => class.push(character),
                _ => {}
            }
        }
        let entry = self
            .classes
            .entry(class)
            .or_insert_with(|| (0, format!("{path}: {native} | {restored}")));
        entry.0 += 1;
        self.records += 1;
    }

    fn value<T: std::fmt::Debug>(&mut self, path: String, native: &T, restored: &T) {
        if debug_digest(native) == debug_digest(restored) {
            return;
        }
        let native_text = format!("{native:#?}");
        let restored_text = format!("{restored:#?}");
        let before = self.records;
        self.node(&path, &parse_debug_tree(&native_text), &parse_debug_tree(&restored_text));
        if self.records == before && native_text != restored_text {
            self.record(path, "<Debug text differs>".into(), "<unparsed>".into());
        }
    }

    fn list<T: std::fmt::Debug>(
        &mut self,
        path: &str,
        native: &[T],
        restored: &[T],
        name: impl Fn(&T) -> String,
    ) {
        if native.len() != restored.len() {
            self.record(
                format!("{path}.len"),
                native.len().to_string(),
                restored.len().to_string(),
            );
        }
        for (index, (native, restored)) in native.iter().zip(restored).enumerate() {
            self.value(format!("{path}[{index} {}]", name(native)), native, restored);
        }
    }

    fn node(&mut self, path: &str, native: &DebugNode<'_>, restored: &DebugNode<'_>) {
        if native.compound != restored.compound || native.label != restored.label {
            self.record(path.to_string(), native.summary(), restored.summary());
            return;
        }
        if !native.compound {
            return;
        }
        if native.children.len() != restored.children.len() {
            self.record(
                format!("{path}.len"),
                native.children.len().to_string(),
                restored.children.len().to_string(),
            );
        }
        for ((native_key, native_child), (restored_key, restored_child)) in
            native.children.iter().zip(&restored.children)
        {
            if native_key != restored_key {
                self.record(format!("{path}{native_key}"), native_key.clone(), restored_key.clone());
                continue;
            }
            self.node(&format!("{path}{native_key}"), native_child, restored_child);
        }
    }

    fn finish(self) -> Vec<String> {
        let mut lines = self
            .classes
            .into_iter()
            .map(|(class, (count, sample))| format!("  {class} x{count}: {sample}"))
            .collect::<Vec<_>>();
        if lines.is_empty() {
            lines.push(
                "  <none>: every field renders equal; the canonical image bytes differ only in encoding"
                    .to_string(),
            );
        }
        lines
    }
}
