[package]
name = "jet-devserver"
version = "1.0.0"
edition = "2021"

[lib]
name = "jet_devserver"
path = "src/lib.rs"

[dependencies]
jet-canvas = { path = "../jet-canvas" }
jet-debug = { path = "../jet-debug" }
jet-driver = { path = "../jet-driver" }
jet-env-model = { path = "../jet-env-model" }
jet-impact = { path = "../jet-impact" }
jet-semindex = { path = "../jet-semindex" }
jetpack = { path = "../jetpack" }
