[package]
name = "jetpack"
version = "1.0.0"
edition = "2021"

[lib]
name = "jetpack"
path = "src/lib.rs"

[dependencies]
jet-foundation = { path = "../jet-foundation" }
jet-lexer = { path = "../jet-lexer" }
jet-parser = { path = "../jet-parser" }
jet-comptime = { path = "../jet-comptime" }
jet-sema = { path = "../jet-sema" }
jet-codegen = { path = "../jet-codegen" }
jet-pkg-model = { path = "../jet-pkg-model" }
jet-env-model = { path = "../jet-env-model" }
jet-nix-eval = { path = "../jet-nix-eval" }
