//! Codegen is deliberately dumb (invariant I3): no checking happens here.
//! If a Program reaches this module, emission must always succeed and the
//! resulting Rust must always compile.
//!
//! Type-alignment rules (so emitted Rust always typechecks):
//!   - scalar params (Int/Float/Bool) pass by value, String by `&String`;
//!     `mut` params are `&mut T`; `take` params are `T` by value
//!   - a name bound to a `&T`/`&mut T` parameter is always emitted as the
//!     place `(*user_x)`, so every name has its plain Jet type
//!   - every printed/interpolated value goes through the `JetShow` trait
//!     in the prelude (Float keeps its decimal part there, S21)
//!   - every operator result is fully parenthesized

use crate::AST::{
    Item,
    Program, ProgramBundle, TestDef,
};
use crate::FFI::FfiLink;
use crate::M9;
use crate::Sema::CompileMode;
use crate::Syntax;
use std::collections::HashMap;


mod CModule;
mod Context;
mod Expression;
mod Imports;
mod Items;
mod Statement;
mod Tuples;
mod Utils;

pub(crate) use CModule::*;
pub(crate) use Context::*;
pub(crate) use Expression::*;
pub(crate) use Imports::*;
pub(crate) use Items::*;
pub(crate) use Statement::*;
pub(crate) use Tuples::*;
pub(crate) use Utils::*;

/// Emitted at the top of every program: core runtime helpers used by generated Rust.
const PRELUDE: &str = include_str!("../Prelude/Core.rs");

/// Extra helpers for `jet test` harnesses only (M6/S43, E2-M11 D-TOOL4).
const TEST_PRELUDE: &str = r#"
/// D-TOOL4 (E2-M11): snapshot wrapper — records or compares a golden snapshot.
struct JetExpect { value: String }
fn jet_expect(s: String) -> JetExpect { JetExpect { value: s } }
impl JetExpect {
    fn snapshot(&self, snap_path: &str) -> Result<(), String> {
        let update = std::env::var("JET_UPDATE_SNAPSHOTS").is_ok();
        if update {
            std::fs::create_dir_all(std::path::Path::new(snap_path).parent().unwrap_or(std::path::Path::new("."))).ok();
            std::fs::write(snap_path, &self.value).map_err(|e| format!("could not write snapshot {snap_path}: {e}"))?;
            return Ok(());
        }
        match std::fs::read_to_string(snap_path) {
            Ok(expected) => {
                if expected == self.value {
                    Ok(())
                } else {
                    Err(format!("snapshot mismatch at {snap_path}\n  expected: {}\n  got:      {}", expected.trim(), self.value.trim()))
                }
            }
            Err(_) => {
                Err(format!("missing snapshot {snap_path}; run `jet test --update-snapshots` to create it"))
            }
        }
    }
}
"#;
const STD_PRELUDE: &str = include_str!("../Prelude/Std.rs");

pub(crate) fn mangle(name: &str) -> String {
    if name == "main" {
        "main".to_string()
    } else {
        format!("user_{}", name)
    }
}

pub fn emit(prog: &Program, src: &str, file: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "// Generated by {} — do not edit. Edit the .{} source instead.\n",
        Syntax::BINARY_NAME,
        Syntax::FILE_EXT
    ));
    out.push_str(&format!(
        "// If rustc rejects this file, that is a bug in {} (invariant I2).\n",
        Syntax::BINARY_NAME
    ));
    // E2-M12 D-OBS1: source-map marker lets tooling resolve generated Rust back to
    // the originating Jet file. Panic reports carry Jet file+line directly via
    // jet_panic/jet_panic_rich, so runtime error messages already show Jet terms.
    out.push_str(&format!("// jet:source-map source={}\n", file));
    out.push_str("#![allow(warnings)]\n\n");
    out.push_str(PRELUDE);
    out.push('\n');

    let cx = build_cx(prog, src, file);
    let tuple_shapes = collect_tuple_shapes(&prog.items);
    emit_tuple_structs(&cx, &tuple_shapes, &mut out);

    for item in &prog.items {
        match item {
            Item::Trait(t) => M9::emit_trait_def(t, &mut out),
            Item::Struct(s) => emit_struct(&cx, s, &mut out),
            Item::Enum(e) => emit_enum(&cx, e, &mut out),
            Item::Const(c) => emit_const(c, &mut out),
            Item::CModule(cm) => emit_c_module(cm, &mut out),
            Item::Func(_) | Item::Impl(_) | Item::Test(_) | Item::ExternRust(_)
            | Item::Module(_) | Item::CodeModule(_) => {}
        }
    }

    for item in &prog.items {
        match item {
            Item::Struct(s) => {
                emit_type_impl(&cx, &s.name, &s.type_params, &s.methods, &mut out);
                for block in &s.trait_impls {
                    emit_trait_impl(&cx, &s.name, &s.type_params, block, &mut out);
                }
            }
            Item::Enum(e) => {
                emit_type_impl(&cx, &e.name, &e.type_params, &e.methods, &mut out);
                for block in &e.trait_impls {
                    emit_trait_impl(&cx, &e.name, &e.type_params, block, &mut out);
                }
            }
            Item::Impl(i) => {
                if i.trait_name.is_some() {
                    emit_external_trait_impl(&cx, i, &mut out);
                } else {
                    emit_type_impl(&cx, &i.type_name, &[], &i.methods, &mut out);
                }
            }
            _ => {}
        }
    }

    for item in &prog.items {
        if let Item::Func(f) = item {
            emit_func(&cx, f, &mut out);
        }
    }
    out
}

/// Emit a test harness binary: all definitions plus one `main` that runs
/// every `test "…" { }` block (M6 phase 2).
pub fn emit_tests(prog: &Program, src: &str, file: &str) -> String {
    let tests: Vec<&TestDef> = prog
        .items
        .iter()
        .filter_map(|i| match i {
            Item::Test(t) => Some(t),
            _ => None,
        })
        .collect();
    assert!(!tests.is_empty(), "emit_tests called with no test blocks");

    let mut out = String::new();
    out.push_str(&format!(
        "// Generated by {} test harness — do not edit.\n",
        Syntax::BINARY_NAME
    ));
    out.push_str("#![allow(warnings)]\n\n");
    out.push_str(PRELUDE);
    out.push_str(TEST_PRELUDE);
    out.push('\n');

    let mut cx = build_cx(prog, src, file);
    cx.test_mode = true;
    let tuple_shapes = collect_tuple_shapes(&prog.items);
    emit_tuple_structs(&cx, &tuple_shapes, &mut out);

    for item in &prog.items {
        match item {
            Item::Trait(t) => M9::emit_trait_def(t, &mut out),
            Item::Struct(s) => emit_struct(&cx, s, &mut out),
            Item::Enum(e) => emit_enum(&cx, e, &mut out),
            Item::Const(c) => emit_const(c, &mut out),
            Item::CModule(cm) => emit_c_module(cm, &mut out),
            Item::Func(_) | Item::Impl(_) | Item::Test(_) | Item::ExternRust(_)
            | Item::Module(_) | Item::CodeModule(_) => {}
        }
    }

    for item in &prog.items {
        match item {
            Item::Struct(s) => {
                emit_type_impl(&cx, &s.name, &s.type_params, &s.methods, &mut out);
                for block in &s.trait_impls {
                    emit_trait_impl(&cx, &s.name, &s.type_params, block, &mut out);
                }
            }
            Item::Enum(e) => {
                emit_type_impl(&cx, &e.name, &e.type_params, &e.methods, &mut out);
                for block in &e.trait_impls {
                    emit_trait_impl(&cx, &e.name, &e.type_params, block, &mut out);
                }
            }
            Item::Impl(i) => {
                if i.trait_name.is_some() {
                    emit_external_trait_impl(&cx, i, &mut out);
                } else {
                    emit_type_impl(&cx, &i.type_name, &[], &i.methods, &mut out);
                }
            }
            _ => {}
        }
    }

    for item in &prog.items {
        if let Item::Func(f) = item {
            if f.name != "main" {
                emit_func(&cx, f, &mut out);
            }
        }
    }

    for (i, test) in tests.iter().enumerate() {
        out.push_str(&format!("fn jet_test_{}() -> Result<(), String> {{\n", i));
        let mut env: HashMap<String, Slot> = HashMap::new();
        emit_stmts(&cx, &test.body, &mut env, &mut out, 1, false);
        out.push_str("    Ok(())\n");
        out.push_str("}\n\n");
    }

    out.push_str("fn main() {\n");
    out.push_str("    let mut passed = 0usize;\n");
    out.push_str("    let mut failed = 0usize;\n");
    for (i, test) in tests.iter().enumerate() {
        let name = escape_rust_str(&test.name);
        out.push_str(&format!("    match jet_test_{}() {{\n", i));
        out.push_str("        Ok(()) => {\n");
        out.push_str(&format!(
            "            println!(\"{{}}: pass\", {});\n",
            name
        ));
        out.push_str("            passed += 1;\n");
        out.push_str("        }\n");
        out.push_str("        Err(msg) => {\n");
        out.push_str(&format!(
            "            println!(\"{{}}: FAIL\", {});\n",
            name
        ));
        out.push_str("            eprintln!(\"  {}\", msg);\n");
        out.push_str("            failed += 1;\n");
        out.push_str("        }\n");
        out.push_str("    }\n");
    }
    out.push_str("    println!(\"{} passed, {} failed\", passed, failed);\n");
    out.push_str("    if failed > 0 { std::process::exit(1); }\n");
    out.push_str("}\n");
    out
}

pub fn emit_bundle(bundle: &ProgramBundle, _mode: CompileMode, link: Option<&FfiLink>) -> String {
    let entry = &bundle.modules[bundle.entry];
    let mut out = String::new();
    out.push_str(&format!(
        "// Generated by {} — do not edit. Edit the .{} source instead.\n",
        Syntax::BINARY_NAME,
        Syntax::FILE_EXT
    ));
    // E2-M12 D-OBS1: source-map marker for tooling and debuggers.
    out.push_str(&format!("// jet:source-map source={}\n", entry.display));
    out.push_str("#![allow(warnings)]\n\n");
    if let Some(ffi) = link {
        out.push_str(&format!("extern crate {};\n\n", ffi.crate_name));
    }
    out.push_str(PRELUDE);
    if !bundle.used_std.is_empty() {
        out.push_str(STD_PRELUDE);
    }
    out.push('\n');

    let import_mods = import_mod_map(bundle, bundle.entry);
    let extern_funcs = bundle_extern_funcs(bundle);

    for (i, module) in bundle.modules.iter().enumerate() {
        if i == bundle.entry {
            continue;
        }
        let ns = module.alias.clone();
        out.push_str(&format!("mod user_{ns} {{\n"));
        out.push_str(MOD_USE);
        let mut cx = build_cx_items(
            &module.items,
            &module.source,
            &module.display,
            link,
            &extern_funcs,
        );
        cx.import_mods = import_mod_map(bundle, i);
        cx.foreign_types = foreign_type_map(bundle, i);
        register_foreign_enum_variants(&mut cx, bundle, i);
        update_cloneability_with_foreign_types(&mut cx, &module.items);
        cx.reexport_calls = reexport_call_map(bundle, i);
        cx.import_sigs = import_sig_map(bundle, i);
        cx.std_imports = std_import_map(bundle, i);
        cx.used_std = bundle.used_std.clone();
        cx.root_prefix = "super::".to_string();
        let (uinline, ufile) = unqualified_import_maps(bundle, i);
        cx.unqualified_inline = uinline;
        cx.unqualified_file = ufile;
        emit_program_items(&cx, &module.items, &mut out, true);
        out.push_str("}\n\n");
    }

    let mut cx = build_cx_items(
        &entry.items,
        &entry.source,
        &entry.display,
        link,
        &extern_funcs,
    );
    cx.import_mods = import_mods;
    cx.foreign_types = foreign_type_map(bundle, bundle.entry);
    register_foreign_enum_variants(&mut cx, bundle, bundle.entry);
    update_cloneability_with_foreign_types(&mut cx, &entry.items);
    cx.reexport_calls = reexport_call_map(bundle, bundle.entry);
    cx.import_sigs = import_sig_map(bundle, bundle.entry);
    cx.std_imports = std_import_map(bundle, bundle.entry);
    cx.used_std = bundle.used_std.clone();
    let (uinline, ufile) = unqualified_import_maps(bundle, bundle.entry);
    cx.unqualified_inline = uinline;
    cx.unqualified_file = ufile;
    emit_program_items(&cx, &entry.items, &mut out, true);
    out
}

pub fn emit_bundle_tests(bundle: &ProgramBundle, link: Option<&FfiLink>) -> String {
    let entry = &bundle.modules[bundle.entry];
    let tests: Vec<&TestDef> = entry
        .items
        .iter()
        .filter_map(|i| match i {
            Item::Test(t) => Some(t),
            _ => None,
        })
        .collect();
    assert!(
        !tests.is_empty(),
        "emit_bundle_tests called with no test blocks"
    );

    let mut out = String::new();
    out.push_str(&format!(
        "// Generated by {} test harness — do not edit.\n",
        Syntax::BINARY_NAME
    ));
    out.push_str("#![allow(warnings)]\n\n");
    if let Some(ffi) = link {
        out.push_str(&format!("extern crate {};\n\n", ffi.crate_name));
    }
    out.push_str(PRELUDE);
    out.push_str(TEST_PRELUDE);
    if !bundle.used_std.is_empty() {
        out.push_str(STD_PRELUDE);
    }
    out.push('\n');

    let import_mods = import_mod_map(bundle, bundle.entry);
    let extern_funcs = bundle_extern_funcs(bundle);

    for (i, module) in bundle.modules.iter().enumerate() {
        if i == bundle.entry {
            continue;
        }
        let ns = module.alias.clone();
        out.push_str(&format!("mod user_{ns} {{\n"));
        out.push_str(MOD_USE);
        let mut cx = build_cx_items(
            &module.items,
            &module.source,
            &module.display,
            link,
            &extern_funcs,
        );
        cx.test_mode = true;
        cx.import_mods = import_mod_map(bundle, i);
        cx.foreign_types = foreign_type_map(bundle, i);
        register_foreign_enum_variants(&mut cx, bundle, i);
        update_cloneability_with_foreign_types(&mut cx, &module.items);
        cx.reexport_calls = reexport_call_map(bundle, i);
        cx.import_sigs = import_sig_map(bundle, i);
        cx.std_imports = std_import_map(bundle, i);
        cx.used_std = bundle.used_std.clone();
        cx.root_prefix = "super::".to_string();
        let (uinline, ufile) = unqualified_import_maps(bundle, i);
        cx.unqualified_inline = uinline;
        cx.unqualified_file = ufile;
        emit_program_items(&cx, &module.items, &mut out, false);
        out.push_str("}\n\n");
    }

    let mut cx = build_cx_items(
        &entry.items,
        &entry.source,
        &entry.display,
        link,
        &extern_funcs,
    );
    cx.test_mode = true;
    cx.import_mods = import_mods;
    cx.foreign_types = foreign_type_map(bundle, bundle.entry);
    register_foreign_enum_variants(&mut cx, bundle, bundle.entry);
    update_cloneability_with_foreign_types(&mut cx, &entry.items);
    cx.reexport_calls = reexport_call_map(bundle, bundle.entry);
    cx.import_sigs = import_sig_map(bundle, bundle.entry);
    cx.std_imports = std_import_map(bundle, bundle.entry);
    cx.used_std = bundle.used_std.clone();
    let (uinline, ufile) = unqualified_import_maps(bundle, bundle.entry);
    cx.unqualified_inline = uinline;
    cx.unqualified_file = ufile;
    emit_program_items(&cx, &entry.items, &mut out, false);

    for (i, test) in tests.iter().enumerate() {
        out.push_str(&format!("fn jet_test_{}() -> Result<(), String> {{\n", i));
        let mut env: HashMap<String, Slot> = HashMap::new();
        emit_stmts(&cx, &test.body, &mut env, &mut out, 1, false);
        out.push_str("    Ok(())\n");
        out.push_str("}\n\n");
    }

    out.push_str("fn main() {\n");
    out.push_str("    let mut passed = 0usize;\n");
    out.push_str("    let mut failed = 0usize;\n");
    for (i, test) in tests.iter().enumerate() {
        let name = escape_rust_str(&test.name);
        out.push_str(&format!("    match jet_test_{}() {{\n", i));
        out.push_str("        Ok(()) => {\n");
        out.push_str(&format!(
            "            println!(\"{{}}: pass\", {});\n",
            name
        ));
        out.push_str("            passed += 1;\n");
        out.push_str("        }\n");
        out.push_str("        Err(msg) => {\n");
        out.push_str(&format!(
            "            println!(\"{{}}: FAIL\", {});\n",
            name
        ));
        out.push_str("            eprintln!(\"  {}\", msg);\n");
        out.push_str("            failed += 1;\n");
        out.push_str("        }\n");
        out.push_str("    }\n");
    }
    out.push_str("    println!(\"{} passed, {} failed\", passed, failed);\n");
    out.push_str("    if failed > 0 { std::process::exit(1); }\n");
    out.push_str("}\n");
    out
}
