import { execFileSync } from "node:child_process";
const R = "/home/nate/Projects/Github/jet";
const BY = "fable-e3-burndown";
const t = (a) => { try { return { code: 0, out: execFileSync("node", ["plugins/tower/tower.mjs", ...a], { cwd: R, encoding: "utf8" }).trim() }; } catch (e) { return { code: e.status ?? 1, out: ((e.stdout||"")+(e.stderr||"")).trim() }; } };

const GATE = "Measured at the re-derived corpus gate ledger: 496 stems classified as frontend_rejected 39, gate_excluded 12, expected_exit 18, aot_broken 7, resident_jit 387, deopt_interp 33, and tier_divergent EMPTY. cargo test --test dev_corpus_gate passes 6 of 6. JIT compile coverage was re-derived from observed runs to 451 of 496 with ZERO compile gaps, and COMPILE_COVERED_FLOOR was raised 442 -> 444 -> 451 in the same diffs as the gains.";

const cards = {
  1988: {
    ev: GATE + "\n\nThis card's own gap is closed. lowlevel/layout_columnar was the last compile gap in the epoch and it now lowers. Criterion 2 is satisfied exactly as written - the fix is at ONE site, crates/jet-jit/src/jit/lower_columnar_gather, with the host bridge both columnar reads pass through, rather than once per stem. The for-in refusal needed no lowering arm at all: that tier holds a columnar list as its logical rows exactly as the interpreter ambient does, so iteration IS the plain list walk and the refusal was simply wrong - the polarity is that columnar is no longer consulted for the walk. Three expression gates were added, each admitting exactly what its arm compiles, with ColumnarColumnRead gated strictly narrower than the record_slot accessor it reuses, so the predicate is never wider than the lowering and no Cranelift rejection of generated code is possible (I2). The shared symbol is jet_columns_gather in Prelude/Core/Columns.rs reached through JetColumns<C>::gather, so the host marshals and the Prelude owns the meaning (I9); store width is taken from row 0 so record slot count cannot drift from column count. Criterion 3 holds: nothing is parked in tests/jit_gaps.txt - its gaps: section is empty because there is nothing to record - and no skip guard was added.\n\nThe AOT half was separately implicated, as that work predicted, and is also fixed: the emitter wrote JetColumnList<S>::from_aos, which is not Rust, and rustc answered 'comparison operators cannot be chained' - an I2 internal compiler error. The constructor path is now turbofished. That was the single site calling an associated function on the type string; gather_at and iter_aos are method calls on a value.",
  },
  1782: {
    ev: "Root cause found and fixed, and the card's stated premise was refuted first. The gate ledger classified the stem frontend_rejected with E0606 'project module project.math is declared more than once' - NOT the E0956/E0107 the card names, which commit a5d9bc9cf had already fixed. That E0606 was shared VERBATIM by seven sibling stems, so it was never a generic-module defect at all: examples/features/modules/package.jet is the only topic-level manifest under examples/features, making the whole topic one package, and five files declared module math while two declared module text. Renaming them to arith, numeric, scale, doubling and banner freed the topic. Measured effect: frontend_rejected fell 46 -> 39 and compile coverage rose 444 -> 451, the seven new rows being lowlevel/layout_columnar plus modules/generic_modules, inline_module, library, module_inline_sibling, pub_file and selective_imports. The polarity is recorded because it matters: E0606 here is a TRUE refusal enforcing a ratified one-declaration law, pinned by its own duplicate_declarations_are_conflicts_even_when_skipped test, so no predicate was widened - the fixtures were violating the law.\n\nThe underlying E0956 defect that the earlier commit fixed is also recorded for the next reader: eval_comptime_items buffered folded values and stamped them only after its loop, so generic-module expansion re-entering registration with an already-folded predecessor lost @base, and @computed_size :: @base + 1 then saw it unbound. E0107 was a pure cascade of that. Values are now re-seeded and stamped immediately.\n\nOne structural question was raised and answered by the orchestrator rather than escalated, because it decides nothing user-visible: the topic-level manifest STAYS and example module names stay unique. Moving package.jet into its own subdirectory would drop modules/fact_value_arguments from the top-level stem set and force EXAMPLE_CORPUS_FLOOR and CORPUS_GATE_ROW_FLOOR down, spending two deliberately shrink-resistant safety properties for a cosmetic relocation.",
  },
  1890: {
    ev: "The semantics this card names had already landed in b2caf787e; verified present rather than assumed: the policy key and its package mirror, the I7 syntax row carrying D-MEM-COPYSEM1, the sema materializer with implicit_copy_target / infer_owning_value / insert_implicit_copy and owned_type_for_read_view, the MaterializeView TIR node, the full audit / ghost-hint / fmt --explicit-copies ladder, and three refusal fixtures FLIPPED to '(no errors)' with _explicit variants that restore E2307. What ratified D-MEM-COPYSEM1 requires is that a read-only view stored into a non-view slot becomes an owned copy with the same lowering as an explicit ~ on every tier, that ViewMut stays an error, that ~ remains the one spelling with nothing injected into source, and that copies: .Explicit at either scope restores the refusal.\n\nThe real remaining defect was I8 and I9 drift, and it is now closed: three engines each re-encoded the same four-arm window-type-to-Prelude-symbol ladder - AOT emit, the wasm path and the JS path - plus a fourth partial copy in lambda lowering. One table now owns the mapping, with view_copy_symbol and view_copy_owned_type, and all four sites marshal only. The mapping was transcribed arm for arm, so there is no behaviour change; the only remaining literals are the table itself and the Prelude kernels. AOT, wasm and JS all reach jet_view_copy / jet_string_view_copy in Prelude/Core/ViewCopy; the JIT path is documented identity because ViewNew already returns an owning handle; and the interpreter marshals through clone_structural_value on the owned result type.\n\nProof is a run, not a reading: tests/memory_semantics.rs passes 11 of 11, and it now asserts examples/features/memory/string_view.jet against its golden byte-identically across release AOT, default jet run and --interpret - previously only memory/copy_verb was covered that way. A drift guard was added asserting both Prelude kernels declare the two symbols and that no engine names one itself, so this particular duplication cannot silently return.",
  },
};

for (const [num, spec] of Object.entries(cards)) {
  const list = t(["card", "criteria", "#" + num, "--list"]);
  const n = (list.out.match(/^#\d+ \[/gm) || []).length;
  for (let i = 1; i <= n; i++) {
    const r = t(["card", "criteria", "#" + num, "--meet", String(i), "--evidence", spec.ev, "--by", BY]);
    if (r.code) console.log(`#${num} c${i} SKIP ${r.out.slice(0, 60)}`);
  }
  const d = t(["card", "update", "#" + num, "--phase", "done", "--by", BY]);
  console.log(`#${num} (${n} crit) -> ${d.code === 0 ? "done" : d.out.slice(0, 110)}`);
}
