import { execFileSync } from "node:child_process";
const R = "/home/nate/Projects/Github/jet";
const BY = "fable-e3-burndown";
const t = (a) => { try { return { code: 0, out: execFileSync("node", ["plugins/tower/tower.mjs", ...a], { cwd: R, encoding: "utf8" }).trim() }; } catch (e) { return { code: e.status ?? 1, out: ((e.stdout||"")+(e.stderr||"")).trim() }; } };

const E1757 = "Measured at the re-derived ledger, not implemented as written. There is no blanket core.compute rejection: safety.rs delegates to resident_safe_compute_call, a roughly 30-arm allowlist, and crates/jet-jit/src/Compute.rs includes Prelude/CoreLib/Top/Compute.rs so the host and AOT share one body. compute_device, compute_kernel, compute_linalg, compute_ml, compute_ndarray, compute_simd and compute_tensor all record resident_jit, and NONE appears in tier_divergent - so the Placement and reason wording this card said diverges (requested=Auto vs CPU plus an extra selected=cpu) is byte-identical across tiers now, which is what criteria 2 and 6 demand. compute_autodiff records deopt_interp: it runs and its output matches AOT, so it is a dev-loop performance gap rather than an I9 violation. The ledger rows the card asked to delete are gone: jit_gaps.txt gaps: and run_gaps: are both empty, and compile coverage was re-derived from observed runs to 444 of 496 with the floor raised in the same diff. One residue is recorded rather than absorbed: the curried transform form compute.gradient(f) with a single argument is refused, and the refusal is CONSISTENT on both sides - safety.rs requires args.len() >= 2 and the lowering refuses the same shape - so it is an honest refusal, not a divergence. Closing it needs the closure-across-host-boundary design and is carried on its own card.";

const E1585 = "Measured at the re-derived ledger. collections/set records resident_jit, which in this gate is an observed parity proof rather than a label: classify_corpus_stem diverts a stem to TierDivergent unless the JIT and AOT outputs are identical, separately asserts interpreter equals AOT, and requires both that no deopt occurred and that Cranelift actually executed - so criterion 4's byte-identical output under jet run and jet run --release is what that row means. The gap line this card asked to remove is gone: jit_gaps.txt gaps: and run_gaps: are both empty. Set's all, filter, each, fold, map and flat_map were already admitted through the Set arm of jit_closure_elem_type_for plus lower_closure_source. What landed extends the family with each admitted method's lowering arm changed in the same slice: TakeWhile and SkipWhile, and Position, through lower_iter_take_skip_while and lower_iter_position, which now bind the element type instead of hardcoding Int; MinBy and MaxBy through lower_iter_min_max_by, where the element travels only as the packed-Option payload; and CountBy through lower_iter_count_by. Two polarity corrections went the OTHER way and are recorded because a wrong refusal and a wrong admission are both bugs: TakeWhile, SkipWhile and Position now REQUIRE a Bool callback body in both tables, because the lowerings compare the result with an I8 icmp and a non-Bool body handed Cranelift mismatched operand types - an I2 internal compiler error rather than a deopt - and sema types both predicates Bool so no live case is lost; and CountBy's predicate had checked the element while its lowering demanded both element and key, so a receiver the predicate admitted was refused one step later and the function deopted anyway. Set receivers are deliberately excluded from all four positional walks, because a hash Set publishes no position per D-SET-DECLINE1=C and max_by keeps the last tie over an AOT Set order that is unspecified. Criterion 5 holds: only crates/jet-jit/src/jit/safety.rs and lower_ctx.rs changed, no sema, TIR or Prelude file. One I8 deletion came with it - six copies of the args.first() to lambda to body-type ladder collapsed into one resident_safe_expr_callback, and resident_safe_binary_lambda lost its last caller and was deleted.";

for (const [num, ev] of [["1757", E1757], ["1585", E1585]]) {
  const list = t(["card", "criteria", "#" + num, "--list"]);
  const n = (list.out.match(/^#\d+ /gm) || []).length;
  for (let i = 1; i <= n; i++) {
    const r = t(["card", "criteria", "#" + num, "--meet", String(i), "--evidence", ev, "--by", BY]);
    if (r.code) console.log(`#${num} c${i} SKIP ${r.out.slice(0, 70)}`);
  }
  const d = t(["card", "update", "#" + num, "--phase", "done", "--by", BY]);
  console.log(`#${num} (${n} crit) -> ${d.code === 0 ? "done" : d.out.slice(0, 110)}`);
}

const add = t(["card", "add",
  "--title", "Curried compute transforms need the closure-across-host-boundary design",
  "--body", "core.compute exposes transforms such as compute.gradient. Called with two or more arguments they lower natively. Called in the CURRIED form - compute.gradient(f) with a single function argument - they are refused, and the refusal is consistent on both sides: resident_safe_compute_call requires args.len() >= 2 and the lowering refuses the same shape. So this is an honest refusal today, not a tier divergence, and compute_autodiff runs correctly by deopting to the interpreter with output matching AOT.\n\nWhat blocks it is a real design question rather than a wire-up: a curried transform returns a callable that must survive being handed across the host boundary, which is why the arity guard exists in the first place. Closing it means deciding how a Jet closure crosses into and back out of a Cranelift host frame, and per I9 the answer has to be one mechanism that AOT, the JIT hosts and the interpreter ambient all marshal to rather than three private conventions.\n\nSplit off #1757 during the epoch-3 burndown so that card could close on its measured evidence - every other compute stem records resident_jit with byte-identical cross-tier output - without absorbing an unsolved design problem into a closed card.",
  "--kind", "task", "--epoch", "e3", "--milestone", "e3-m16-compute", "--priority", "P2", "--track", "epoch", "--by", BY]);
console.log("mint ->", add.out.slice(0, 60));
const m = add.out.match(/#(\d+)/);
if (m) for (const c of [
  "One mechanism carries a Jet closure across the host boundary, owned by the Prelude, with AOT, the Cranelift hosts and the interpreter ambient all marshalling to it rather than each holding a convention",
  "compute.gradient(f) in its curried single-argument form lowers natively, and the arity guard that currently refuses it is narrowed in the same diff as the lowering arm that handles it",
  "compute_autodiff runs on default jet run without deopting to the interpreter, with output byte-identical to AOT and to the interpreter",
]) t(["card", "criteria", "#" + m[1], "--add", c, "--by", BY]);
