import { execFileSync } from "node:child_process";
const R = "/home/nate/Projects/Github/jet";
const BY = "fable-e3-burndown";
const t = (a) => { try { return { code: 0, out: execFileSync("node", ["plugins/tower/tower.mjs", ...a], { cwd: R, encoding: "utf8" }).trim() }; } catch (e) { return { code: e.status ?? 1, out: ((e.stdout||"")+(e.stderr||"")).trim() }; } };

const cards = {
  2013: [
    "Every one of the 496 corpus stems now appears in exactly one section, and the row count is pinned against the corpus stem count. Verified at 404bfb6fc by reading the committed ledger: 496 rows across frontend_rejected 46, gate_excluded 12, non_runnable 0, expected_exit 27, resident_jit 368, deopt_interp 34, run_tier_broken 9. CORPUS_GATE_ROW_FLOOR is 496 and may only grow; CORPUS_GATE_UNCLASSIFIED_CEILING is 0 and may only shrink; both rest on an asserted classified + unclassified == corpus identity plus corpus >= EXAMPLE_CORPUS_FLOOR, so a stem cannot leave the accounting.",
    "The rows were re-derived from an observed run, never hand-added. Command: JET_DUMP_CORPUS_GATE=1 JET_WRITE_CORPUS_GATE=1 cargo test --test dev_corpus_gate example_corpus_strict_jit_aot_differential_gate -- --exact --nocapture, run twice (374 -> 496, then again after serde/json_coerce started type-checking). Hand-editing was refused deliberately: the sibling ledger tests/jit_gaps.txt has been falsified three times and a classification typed by hand is the same mistake. Two caveats are recorded for future regenerations: dump mode returns BEFORE every ratchet so a regeneration cannot self-check, and stems file as expected_exit when rustc is absent, so regenerate only on a Cranelift-supported host with rustc.",
    "A stem that leaves a section fails a test rather than disappearing. corpus_gate_manifest_accounts_for_every_example parses the ledger and walks examples/features/<topic>/ with no Cranelift host, no rustc and no run, so the check is cheap and host-independent; corpus_gate_ledger_audit_fires_on_a_missing_row is a negative control proving the audit names a missing row, a duplicate, a ghost and a reasonless exclusion. The strict gate's own duplicate ghost/unlisted check was deleted and now calls that one law (I8).",
    "tooling/data_plot specifically has a row and a section: it is recorded under resident_jit, so the stem the card named as appearing in NO section is now classified and running on the resident tier.",
    "No card's evidence still cites a classification this file no longer supports. Two consumers were corrected in the same work: serde_jit_parity_manifest_pins had asserted serde/encoding_breadth must remain compile-covered while the coverage oracle could not see the stem at all, and the ledger cross-check flagged types/no_any_alternatives as compile-covered while the gate recorded it frontend_rejected - that stem's example was repaired (a panic-to-error conversion had hoisted a DataTree literal out of one expression and broken sema) and it now runs, printing 3 / typed / present / jet. The re-derivation also exposed a NEW and sharper finding the stale ledger had hidden: 9 AOT-green stems sit in run_tier_broken, and the gate's own law asserts that section must stay empty. That is recorded and assigned rather than absorbed.",
  ],
  2012: [
    "jit_covered_example_stems no longer exists. It had a single caller, so rather than wrapping it the function was DELETED and cranelift_three_way_differential_battery now reads the shared memoised observation directly. Its three silent drops are therefore gone by construction: the Err(_) => continue on Loader failure, the bare continue on any Sema error, and a third implicit drop where a stem failing either resident_jit_safe_bundle or try_compile_bundle was pushed nowhere and counted nowhere.",
    "There is one oracle, not two. classify_jit_compile feeds observe_jit_coverage, memoised once per test binary by collect_jit_coverage, and both jit_coverage_audit_inner and cranelift_three_way_differential_battery_inner destructure that same value. The generalization was made to the existing helper rather than beside it: JitCompileVerdict::Covered became a struct variant carrying resident_refusal, and the second question is asked only in the try_compile Ok arm, so the audit's covered, gaps and out_of_universe sets are byte-for-byte unchanged. A source audit confirmed no second corpus walk remains in tests/: all 21 other try_compile_bundle callers are single fixtures.",
    "The battery states the universe it is scoped to, before and after the walk, and cannot report success while that universe is incomplete. It prints the scope line before the loop so a differential failure inside cannot suppress it, then buckets every universe stem into ran / no_golden / held_back and asserts ran + no_golden + held_back == resident_safe.len(), so no code path leaves a stem uncounted. The previously anonymous web/app_hello skip became a counted row with its reason, and is now held back by a DERIVED service predicate rather than by name.",
    "The universe size is pinned outside the files it guards: EXAMPLE_CORPUS_FLOOR = 496 and OUT_OF_UNIVERSE_CEILING moved from function-local to module scope so both readers assert them, plus RESIDENT_SAFE_FLOOR and THREE_WAY_RAN_FLOOR for the battery's own denominator. Recorded honestly for the next agent: an audit found the resident-safe and ran floors are slack by roughly 90 stems because they were set on a smaller corpus, so they hold but weakly until raised to observed counts; and a FOURTH silent-drop site was found in print_jit_op_report, which is report-only and cannot false-green but still re-derives coverage from its own walk.",
  ],
  2021: [
    "The lint no longer fires on tooling/data_plot, and the span problem is fixed at its cause rather than suppressed. Root cause: the warning fired on COMPILER-GENERATED code. Sema/Registration/Derives.rs builds the auto-derive Equatable.equal body as field_read(self, f, s.name_span) == field_read(rhs, f, s.name_span) for every non-computed field, so a Float field hands infer_binary a BinOp::Eq at the STRUCT'S NAME SPAN. Any struct with a Float field therefore warned at its own declaration, and no derive marker was needed because the package auto-derive default puts every local struct in auto_equatable. The enum arm had the same defect via equality_expression.",
    "Whether a real float comparison exists was established, not assumed: examples/features/tooling/data_json.jet contains ZERO == and != tokens. The nearest thing is a Float >= at line 24, and L0502 covers only BinOp::Eq and BinOp::Ne per its registered text, so relational float comparison is not the lint's subject. The correct behaviour for that file is therefore silence.",
    "The lint is not tier-dependent, and the distinction was worth recording: the FACT is tier-independent because sema runs once per compile with no per-tier lint path, but the SURFACING was tier-dependent because only the AOT/native command renders out.lints to stderr, while default jet run and --interpret return earlier. So AOT wrote the warning and the other tiers wrote nothing, which made a spurious lint look like a tier divergence on the tooling/data_plot differential.",
    "A committed snapshot had BLESSED the wrong behaviour and was corrected: tests/ui_lint/float_money.warn pinned an L0502 at `struct Invoice` (line 1, column 8, caret length 7) for a file that is a struct with a Float field plus an empty run - no comparison of any kind. That file is the direct measured evidence for the diagnosis, and its stale rows were removed.",
    "The stderr difference this lint caused on the tooling/data_plot cross-tier differential is gone: that stem now records as resident_jit in the re-derived corpus gate ledger, and the strict gate reports no classification failure for it.",
  ],
};

for (const [num, rows] of Object.entries(cards)) {
  for (let i = 0; i < rows.length; i++) {
    const r = t(["card", "criteria", "#" + num, "--meet", String(i + 1), "--evidence", rows[i], "--by", BY]);
    if (r.code) console.log(`#${num} c${i + 1} SKIP ${r.out.slice(0, 60)}`);
  }
  const d = t(["card", "update", "#" + num, "--phase", "done", "--by", BY]);
  console.log(`#${num} -> ${d.code === 0 ? "done" : d.out.slice(0, 100)}`);
}
