#!/usr/bin/env node
// Regenerate the ratified-decision index in docs/spec/syntax-decisions.md.
//
// Why this exists: AGENTS.md tells every agent that the spec is authority #3,
// above this file and above the code. But a decision is ratified in Tower, and
// only some ratifications ever got hand-written prose here. Measured on
// 2026-08-20: 268 of the 1124 decision ids cited in `crates/` and `Source/`
// appeared nowhere in this spec, so a worker reading the spec as law could not
// find the outcome its own code depended on — and twice this epoch a worker
// re-raised an already-ratified ballot for exactly that reason.
//
// The decision itself still lives in exactly one place: the Tower store. This
// writes a derived index, never a second source of truth, and
// tests/decisions.rs::every_code_cited_decision_is_findable_in_the_spec keeps
// it from drifting again.
//
// Usage:  node scripts/agent/decision-index.mjs [--check]

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

const SPEC = "docs/spec/syntax-decisions.md";
const OPEN = "<!-- BEGIN GENERATED RATIFIED INDEX -->";
const CLOSE = "<!-- END GENERATED RATIFIED INDEX -->";

const check = process.argv.includes("--check");

const raw = execFileSync(
  "node",
  ["plugins/tower/tower.mjs", "decision", "list", "--json"],
  { encoding: "utf8", maxBuffer: 1 << 30 },
);
const parsed = JSON.parse(raw);
const decisions = parsed.decisions ?? parsed;

const ratified = decisions
  .filter((d) => d.status === "ratified")
  .map((d) => ({
    id: d.id,
    outcome: String(d.outcome ?? d.chosen ?? "").trim(),
    card: d.card ?? d.cardId ?? "",
  }))
  .sort((a, b) => a.id.localeCompare(b.id));

// A verdict's outcome is a paragraph, not a letter. Keep the row scannable and
// let the reader follow the card for the wording.
const cell = (text) => {
  const flat = text.replace(/\s+/g, " ").replace(/\|/g, "\\|");
  return flat.length > 96 ? `${flat.slice(0, 93)}…` : flat;
};

const body = [
  OPEN,
  "",
  `Generated by \`scripts/agent/decision-index.mjs\` from the Tower store: ${ratified.length} ratified decisions.`,
  "Do not hand-edit these rows. The decision lives in Tower; this is a lookup so that reading this",
  "spec is enough to know the law. Sections above carry the teaching prose for decisions that changed",
  "user-typeable syntax; a row here with no prose above it is still binding.",
  "",
  "| Decision | Outcome | Card |",
  "| --- | --- | --- |",
  ...ratified.map((d) => `| \`${d.id}\` | ${cell(d.outcome) || "—"} | \`${d.card}\` |`),
  "",
  CLOSE,
].join("\n");

const spec = readFileSync(SPEC, "utf8");
const start = spec.indexOf(OPEN);
const end = spec.indexOf(CLOSE);

let next;
if (start === -1 || end === -1) {
  const heading = "\n## Ratified decision index\n\n";
  next = `${spec.replace(/\s*$/, "\n")}${heading}${body}\n`;
} else {
  next = spec.slice(0, start) + body + spec.slice(end + CLOSE.length);
}

if (next === spec) {
  console.log(`decision index up to date (${ratified.length} ratified)`);
  process.exit(0);
}
if (check) {
  console.error(
    `decision index is stale; run: node scripts/agent/decision-index.mjs`,
  );
  process.exit(1);
}
writeFileSync(SPEC, next);
console.log(`wrote decision index: ${ratified.length} ratified decisions`);
