#!/usr/bin/env node

import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, isAbsolute, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const DEFAULT_INPUT = resolve(ROOT, "docs/audits/devtools-dogfood-2026-09-03.json");
const DEFAULT_REPORT = resolve(ROOT, "docs/audits/devtools-dogfood-2026-09-03.md");
const SCHEMA = "jet.devtools-dogfood.v1";
const REPORT_MARKER = "<!-- generated by scripts/agent/devtools-dogfood.mjs; do not edit -->";
const TOP_LEVEL_KEYS = ["schema", "card", "campaign", "portfolio", "program", "findings", "duplicates"];
const PROGRAM_KEYS = ["package_path", "source_sha256", "toolchain"];
const FINDING_KEYS = [
  "id",
  "domain",
  "command",
  "expected",
  "actual",
  "source",
  "receipt",
  "severity",
  "action",
  "owning_card",
  "workaround",
  "status",
];
const DUPLICATE_KEYS = ["id", "duplicate_of", "receipt"];
const SEVERITIES = new Set(["P0", "P1", "P2", "P3", "critical", "high", "medium", "low"]);
const STATUSES = new Set(["open", "closed"]);
const CARD_RE = /^#[1-9][0-9]*$/u;
const FINDING_ID_RE = /^DEV-2497-[A-Za-z0-9][A-Za-z0-9._-]*$/u;
const SHA256_RE = /^[0-9a-f]{64}$/u;
const UNSUPPORTED_RE = /\b(?:unsupported|not supported|unavailable|not implemented|missing seam|does not support|cannot run|can't run|E\d{4})\b/iu;
const FALLBACK_PATTERNS = [
  /\bhidden\s+fallback\b/iu,
  /\bsilent(?:ly)?\s+fallback\b/iu,
  /\bfallback\s+(?:path|implementation|mode)\b/iu,
  /\b(?:shim|stub|mock|fake|no[- ]op|noop|compatibility\s+alias)\b/iu,
];
const NON_ACTION_VALUES = new Set(["", "none", "n/a", "na", "tbd", "todo", "pending", "deferred"]);

function usage() {
  return [
    "usage: node scripts/agent/devtools-dogfood.mjs [MODE] [OPTIONS]",
    "",
    "Read, validate, update, and report the canonical Jet devtools dogfood ledger.",
    "This command never runs Jet commands or mutates Tower.",
    "",
    "Modes:",
    "  --check                Validate the ledger and require a current report (default).",
    "  --json                 Validate and emit the canonical sorted ledger as JSON.",
    "  --write                Canonicalize the ledger and regenerate its report.",
    "  --append ROW           Append one complete finding JSON object and regenerate.",
    "  --update ID PATCH      Merge a finding patch by stable ID and regenerate.",
    "  --generate-report      Alias for --write.",
    "",
    "Options:",
    "  --input PATH           Ledger path (default: docs/audits/devtools-dogfood-2026-09-03.json).",
    "  --report PATH          Generated report path (default: docs/audits/devtools-dogfood-2026-09-03.md).",
    "  --help                 Show this help and exit.",
    "",
    "ROW and PATCH may be inline JSON or a path to a JSON file. Updates cannot change an ID.",
  ].join("\n");
}

function isRecord(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function exactKeys(value, expected, path, errors) {
  if (!isRecord(value)) {
    errors.push(`${path} must be an object`);
    return false;
  }
  const actual = Object.keys(value);
  const expectedSet = new Set(expected);
  for (const key of expected) {
    if (!Object.hasOwn(value, key)) errors.push(`${path}.${key} is required`);
  }
  for (const key of actual) {
    if (!expectedSet.has(key)) errors.push(`${path}.${key} is unsupported; schema is exact`);
  }
  return actual.every((key) => expectedSet.has(key)) && expected.every((key) => actual.includes(key));
}

function text(value, path, errors) {
  if (typeof value !== "string" || value.trim().length === 0) {
    errors.push(`${path} must be a non-empty string`);
    return null;
  }
  if (value !== value.trim()) errors.push(`${path} must not have leading or trailing whitespace`);
  return value;
}

function card(value, path, errors) {
  const result = text(value, path, errors);
  if (result !== null && !CARD_RE.test(result)) errors.push(`${path} must match #N`);
  return result;
}

function compareIds(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

function sortedById(rows, path, errors) {
  const ids = rows.map((row) => row?.id);
  for (let index = 1; index < ids.length; index += 1) {
    if (typeof ids[index - 1] === "string" && typeof ids[index] === "string" && compareIds(ids[index - 1], ids[index]) > 0) {
      errors.push(`${path} must be sorted by id (${ids[index - 1]} appears before ${ids[index]})`);
      break;
    }
  }
}

function duplicateIds(rows, path, errors) {
  const seen = new Set();
  for (let index = 0; index < rows.length; index += 1) {
    const id = rows[index]?.id;
    if (typeof id !== "string") continue;
    if (seen.has(id)) errors.push(`${path}[${index}].id duplicates ${id}`);
    seen.add(id);
  }
  return seen;
}

function fallbackMarkers(value) {
  return FALLBACK_PATTERNS.filter((pattern) => pattern.test(value)).map((pattern) => pattern.source);
}

function concreteAction(value) {
  return typeof value === "string" && !NON_ACTION_VALUES.has(value.trim().toLowerCase());
}

function checkFinding(row, index, errors) {
  const path = `findings[${index}]`;
  if (!exactKeys(row, FINDING_KEYS, path, errors)) return null;
  const finding = {};
  for (const key of FINDING_KEYS) finding[key] = text(row[key], `${path}.${key}`, errors);
  if (finding.id !== null && !FINDING_ID_RE.test(finding.id)) errors.push(`${path}.id must match DEV-2497-*`);
  if (finding.severity !== null && !SEVERITIES.has(finding.severity)) {
    errors.push(`${path}.severity must be P0, P1, P2, P3, critical, high, medium, or low`);
  }
  if (finding.status !== null && !STATUSES.has(finding.status)) errors.push(`${path}.status must be open or closed`);
  if (finding.owning_card !== null && !CARD_RE.test(finding.owning_card)) errors.push(`${path}.owning_card must match #N`);
  if (finding.status === "open" && !concreteAction(finding.action)) {
    errors.push(`${path}.action must name the next action while status is open`);
  }

  const evidence = [finding.command, finding.expected, finding.actual, finding.source, finding.receipt]
    .filter((value) => value !== null)
    .join("\n");
  if (UNSUPPORTED_RE.test(evidence) && (finding.owning_card === null || !CARD_RE.test(finding.owning_card))) {
    errors.push(`${path} records an unsupported run without a valid owning_card`);
  }

  const visibleWorkaround = finding.workaround ?? "";
  const hiddenMarkers = fallbackMarkers(evidence);
  for (const marker of hiddenMarkers) {
    const pattern = new RegExp(marker, "iu");
    if (!pattern.test(visibleWorkaround)) {
      errors.push(`${path} contains a fallback or substitute that is not visible in workaround`);
    }
  }
  if (finding.status === "open" && visibleWorkaround.trim().length === 0) {
    errors.push(`${path}.workaround must remain visible while status is open`);
  }
  return finding;
}

function checkDuplicate(row, index, errors) {
  const path = `duplicates[${index}]`;
  if (!exactKeys(row, DUPLICATE_KEYS, path, errors)) return null;
  const duplicate = {};
  for (const key of DUPLICATE_KEYS) duplicate[key] = text(row[key], `${path}.${key}`, errors);
  if (duplicate.id !== null && !FINDING_ID_RE.test(duplicate.id)) errors.push(`${path}.id must match DEV-2497-*`);
  if (duplicate.duplicate_of !== null && !FINDING_ID_RE.test(duplicate.duplicate_of)) {
    errors.push(`${path}.duplicate_of must match DEV-2497-*`);
  }
  const markers = fallbackMarkers(duplicate.receipt ?? "");
  if (markers.length > 0) errors.push(`${path}.receipt contains an unmodelled fallback or substitute`);
  return duplicate;
}

function validateLedger(value) {
  const errors = [];
  if (!exactKeys(value, TOP_LEVEL_KEYS, "ledger", errors)) return { errors, ledger: null };
  if (value.schema !== SCHEMA) errors.push(`ledger.schema must be ${SCHEMA}`);
  if (value.card !== "#2497") errors.push("ledger.card must be #2497");
  if (value.campaign !== "#2386") errors.push("ledger.campaign must be #2386");
  if (value.portfolio !== "#217") errors.push("ledger.portfolio must be #217");

  exactKeys(value.program, PROGRAM_KEYS, "program", errors);
  const program = isRecord(value.program) ? {
    package_path: text(value.program.package_path, "program.package_path", errors),
    source_sha256: text(value.program.source_sha256, "program.source_sha256", errors),
    toolchain: text(value.program.toolchain, "program.toolchain", errors),
  } : null;
  if (program?.package_path !== null && (
    isAbsolute(program.package_path)
    || program.package_path.includes("\\")
    || program.package_path.split("/").includes("..")
  )) {
    errors.push("program.package_path must be a relative POSIX path without ..");
  }
  if (program?.source_sha256 !== null && !SHA256_RE.test(program.source_sha256)) {
    errors.push("program.source_sha256 must be 64 lowercase hexadecimal characters");
  }

  if (!Array.isArray(value.findings)) errors.push("findings must be an array");
  if (!Array.isArray(value.duplicates)) errors.push("duplicates must be an array");
  const findings = Array.isArray(value.findings)
    ? value.findings.map((row, index) => checkFinding(row, index, errors)).filter(Boolean)
    : [];
  const duplicates = Array.isArray(value.duplicates)
    ? value.duplicates.map((row, index) => checkDuplicate(row, index, errors)).filter(Boolean)
    : [];
  if (findings.length === 0 && Array.isArray(value.findings)) errors.push("findings must contain at least one row");
  sortedById(value.findings ?? [], "findings", errors);
  sortedById(value.duplicates ?? [], "duplicates", errors);
  const findingIds = duplicateIds(findings, "findings", errors);
  const duplicateIdSet = duplicateIds(duplicates, "duplicates", errors);
  for (const id of duplicateIdSet) {
    if (findingIds.has(id)) errors.push(`id ${id} appears in findings and duplicates; duplicate links replace copied findings`);
  }
  const allIds = new Set([...findingIds, ...duplicateIdSet]);
  const duplicateTargets = new Map();
  for (const duplicate of duplicates) {
    if (!duplicate.id || !duplicate.duplicate_of) continue;
    if (duplicate.id === duplicate.duplicate_of) errors.push(`duplicates.${duplicate.id} cannot duplicate itself`);
    if (!allIds.has(duplicate.duplicate_of)) {
      errors.push(`duplicates.${duplicate.id}.duplicate_of targets missing id ${duplicate.duplicate_of}`);
    }
    duplicateTargets.set(duplicate.id, duplicate.duplicate_of);
  }
  for (const id of duplicateTargets.keys()) {
    const seen = new Set([id]);
    let target = duplicateTargets.get(id);
    while (target && duplicateTargets.has(target)) {
      if (seen.has(target)) {
        errors.push(`duplicate link cycle includes ${id}`);
        break;
      }
      seen.add(target);
      target = duplicateTargets.get(target);
    }
  }
  if (errors.length > 0) return { errors, ledger: null };

  const canonical = {
    schema: value.schema,
    card: value.card,
    campaign: value.campaign,
    portfolio: value.portfolio,
    program,
    findings: findings.sort((left, right) => compareIds(left.id, right.id)),
    duplicates: duplicates.sort((left, right) => compareIds(left.id, right.id)),
  };
  return { errors: [], ledger: canonical };
}

function readLedger(input) {
  if (!existsSync(input)) throw new Error(`canonical input is missing: ${input}`);
  let value;
  try {
    value = JSON.parse(readFileSync(input, "utf8"));
  } catch (error) {
    throw new Error(`cannot parse canonical input ${input}: ${error.message}`);
  }
  const result = validateLedger(value);
  if (result.errors.length > 0) throw new Error(result.errors.join("\n"));
  return result.ledger;
}

function reportPathFor(input) {
  if (input === DEFAULT_INPUT) return DEFAULT_REPORT;
  if (input.endsWith(".json")) return `${input.slice(0, -".json".length)}.md`;
  return `${input}.md`;
}

function resolvePath(value, base = process.cwd()) {
  return isAbsolute(value) ? value : resolve(base, value);
}

function setMode(options, mode) {
  if (options.mode !== "check" && options.mode !== mode) {
    throw new Error(`modes --${options.mode} and --${mode} are mutually exclusive`);
  }
  options.mode = mode;
}

function parseArgs(argv) {
  const options = {
    help: false,
    mode: "check",
    input: DEFAULT_INPUT,
    report: DEFAULT_REPORT,
    reportExplicit: false,
    payload: null,
    updateId: null,
  };
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    if (argument === "--help" || argument === "-h") {
      options.help = true;
    } else if (argument === "--check") {
      setMode(options, "check");
    } else if (argument === "--json") {
      setMode(options, "json");
    } else if (argument === "--write" || argument === "--generate-report") {
      setMode(options, "write");
    } else if (argument === "--append") {
      setMode(options, "append");
      const payload = argv[++index];
      if (!payload || payload.startsWith("-")) throw new Error("--append requires a complete finding JSON object or JSON path");
      options.payload = payload;
    } else if (argument === "--update") {
      setMode(options, "update");
      const id = argv[++index];
      if (!id || id.startsWith("-")) throw new Error("--update requires a stable finding ID");
      const payload = argv[++index];
      if (!payload || payload.startsWith("-")) throw new Error("--update requires a JSON patch or JSON patch path");
      options.updateId = id;
      options.payload = payload;
    } else if (argument === "--input") {
      const candidate = argv[++index];
      if (!candidate || candidate.startsWith("-")) throw new Error("--input requires PATH");
      options.input = resolvePath(candidate);
      if (!options.reportExplicit) options.report = reportPathFor(options.input);
    } else if (argument === "--report") {
      const candidate = argv[++index];
      if (!candidate || candidate.startsWith("-")) throw new Error("--report requires PATH");
      options.report = resolvePath(candidate);
      options.reportExplicit = true;
    } else {
      throw new Error(`unknown option ${argument}`);
    }
  }
  if (options.help && options.mode !== "check") throw new Error("--help cannot be combined with a mutation or output mode");
  return options;
}

function readPayload(value, label) {
  const sourcePath = resolvePath(value);
  const source = existsSync(sourcePath) ? readFileSync(sourcePath, "utf8") : value;
  let parsed;
  try {
    parsed = JSON.parse(source);
  } catch (error) {
    throw new Error(`cannot parse ${label}: ${error.message}`);
  }
  if (!isRecord(parsed)) throw new Error(`${label} must be a JSON object`);
  return parsed;
}

function requireValid(value) {
  const result = validateLedger(value);
  if (result.errors.length > 0) throw new Error(result.errors.join("\n"));
  return result.ledger;
}

function appendFinding(ledger, row) {
  if (!isRecord(row)) throw new Error("finding to append must be a JSON object");
  const findings = [...ledger.findings, row].sort((left, right) => compareIds(left?.id ?? "", right?.id ?? ""));
  return requireValid({ ...ledger, findings });
}

function updateFinding(ledger, id, patch) {
  if (typeof id !== "string" || !FINDING_ID_RE.test(id)) throw new Error("update ID must match DEV-2497-*");
  if (!isRecord(patch)) throw new Error("finding patch must be a JSON object");
  const index = ledger.findings.findIndex((finding) => finding.id === id);
  if (index < 0) throw new Error(`cannot update missing finding ${id}`);
  if (Object.hasOwn(patch, "id") && patch.id !== id) throw new Error("finding IDs are stable and cannot be changed");
  const findings = ledger.findings.map((finding, rowIndex) => rowIndex === index ? { ...finding, ...patch, id } : finding);
  return requireValid({ ...ledger, findings });
}

function jsonText(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function markdownCell(value) {
  return String(value ?? "")
    .replaceAll("\\", "\\\\")
    .replaceAll("|", "\\|")
    .replace(/\r?\n/gu, "<br>");
}

function commandCell(command) {
  return `\`${markdownCell(command)}\` / \`DevtoolsDogfood\``;
}

function dispositionTarget(finding) {
  return `${finding.owning_card} owns this ${finding.domain} action: ${finding.action}.`;
}

function renderReport(value) {
  const ledger = requireValid(value);
  const lines = [
    "# Devtools dogfood friction ledger — 2026-09-03",
    "",
    REPORT_MARKER,
    "",
    `Card: ${ledger.card} (Devtools built in Jet: dogfood anchor 3 friction ledger).`,
    `Campaign portfolio: ${ledger.portfolio}. Five-anchor pattern: ${ledger.campaign}.`,
    "",
    "Program under test: `DevtoolsDogfood`, package `examples/features/devtools/`.",
    "The package is Jet-authored. It uses `core.ui` for the panel tree and",
    "`core.devtools` for explicit event publication. It has no external frontend",
    "runtime or fallback implementation.",
    "",
    "## Ledger contract",
    "",
    "Each row names the exact command and program, the expected and actual result,",
    "the source or missing seam, a replayable evidence receipt, severity, domain,",
    "action, owner, status, and any visible workaround. A workaround is not",
    "closure: the row keeps the underlying seam named until its owning card proves it.",
    "",
    "| ID | Command / program | Expected | Actual | Source / missing seam | Evidence receipt | Severity | Owner | Anchor links | Visible workaround | Disposition | Domain | Action | Status |",
    "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|",
  ];
  for (const finding of ledger.findings) {
    lines.push(`| ${markdownCell(finding.id)} | ${commandCell(finding.command)} | ${markdownCell(finding.expected)} | ${markdownCell(finding.actual)} | ${markdownCell(finding.source)} | ${markdownCell(finding.receipt)} | ${markdownCell(finding.severity)} | ${markdownCell(finding.owning_card)} | #217 portfolio; #2386 five-anchor pattern | ${markdownCell(finding.workaround)} | ${markdownCell(finding.action)} | ${markdownCell(finding.domain)} | ${markdownCell(finding.action)} | ${markdownCell(finding.status)} |`);
  }
  lines.push(
    "",
    "## Cross-anchor disposition",
    "",
    "The package exercises the five-anchor rule from #2386: a real source program,",
    "its public API calls, a host-visible panel, an own-check path, and a concrete",
    "friction receipt. Every row remains linked to the #217 portfolio and the",
    "#2386 pattern through this report header. The package records the workaround",
    "beside the friction instead of silently promoting it to a second mechanism.",
    "",
    "The integrated gate is `scripts/agent/jet-env cargo test --test",
    "devtools_dogfood`. This lane records source receipts only; the parent",
    "integration lane owns that command and any host or tier failure it exposes.",
    "",
    "<!-- audit-dispositions:v1 -->",
    "| finding | disposition | target or reason |",
    "|---|---|---|",
  );
  for (const finding of ledger.findings) {
    lines.push(`| ${markdownCell(finding.id)} | card | ${markdownCell(dispositionTarget(finding))} |`);
  }
  lines.push("<!-- /audit-dispositions -->", "");
  return lines.join("\n");
}

function writeArtifacts(input, report, ledger) {
  mkdirSync(dirname(input), { recursive: true });
  mkdirSync(dirname(report), { recursive: true });
  writeFileSync(input, jsonText(ledger));
  writeFileSync(report, renderReport(ledger));
}

function checkReport(report, ledger) {
  if (!existsSync(report)) throw new Error(`generated report is missing: ${report}`);
  const expected = renderReport(ledger);
  const actual = readFileSync(report, "utf8");
  if (actual !== expected) throw new Error(`generated report is stale: ${report}`);
}

function main(argv = process.argv.slice(2)) {
  let options;
  try {
    options = parseArgs(argv);
  } catch (error) {
    process.stderr.write(`devtools dogfood: ${error.message}\n\n${usage()}\n`);
    return 2;
  }
  if (options.help) {
    process.stdout.write(`${usage()}\n`);
    return 0;
  }
  try {
    let ledger = readLedger(options.input);
    if (options.mode === "json") {
      process.stdout.write(jsonText(ledger));
      return 0;
    }
    if (options.mode === "append") {
      ledger = appendFinding(ledger, readPayload(options.payload, "append row"));
      writeArtifacts(options.input, options.report, ledger);
      process.stdout.write(`devtools dogfood: APPEND OK (${ledger.findings.length} findings)\n`);
      return 0;
    }
    if (options.mode === "update") {
      ledger = updateFinding(ledger, options.updateId, readPayload(options.payload, "update patch"));
      writeArtifacts(options.input, options.report, ledger);
      process.stdout.write(`devtools dogfood: UPDATE OK (${options.updateId})\n`);
      return 0;
    }
    if (options.mode === "write") {
      writeArtifacts(options.input, options.report, ledger);
      process.stdout.write(`devtools dogfood: WRITE OK (${relative(ROOT, options.input)}; findings=${ledger.findings.length}; duplicates=${ledger.duplicates.length})\n`);
      return 0;
    }
    if (options.mode === "check") {
      checkReport(options.report, ledger);
      process.stdout.write(`devtools dogfood: OK (${relative(ROOT, options.input)}; findings=${ledger.findings.length}; duplicates=${ledger.duplicates.length})\n`);
      return 0;
    }
    throw new Error(`unsupported mode ${options.mode}`);
  } catch (error) {
    if (options.mode === "json") {
      process.stdout.write(`${JSON.stringify({ ok: false, errors: String(error.message).split("\n") }, null, 2)}\n`);
    } else {
      process.stderr.write(`devtools dogfood: CHECK FAILED\n${error.message}\n`);
    }
    return 1;
  }
}

export {
  DEFAULT_INPUT,
  DEFAULT_REPORT,
  SCHEMA,
  appendFinding,
  checkReport,
  parseArgs,
  readLedger,
  renderReport,
  updateFinding,
  validateLedger,
  usage,
  writeArtifacts,
};

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  process.exitCode = main();
}
