#!/usr/bin/env node
// Render the owner-controlled lexical ledger into the syntax decisions spec.
//
// Syntax.rs is the authority. This tool only reads its Rust table literal and
// replaces a marked Markdown block; it does not maintain a second spelling
// inventory or consult generated snapshots.
//
// Usage: node scripts/agent/lexical-ledger.mjs [--check|--write]

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const SYNTAX = "crates/jet-foundation/src/Syntax.rs";
const SPEC = "docs/spec/syntax-decisions.md";
const OPEN = "<!-- BEGIN GENERATED LEXICAL LEDGER -->";
const CLOSE = "<!-- END GENERATED LEXICAL LEDGER -->";
const TABLE_RE = /pub const LEXICAL_LEDGER: &\[LexicalEntry\] = &\[[\s\S]*?\n\];/;
const ROW_RE = /LexicalEntry\s*\{\s*spelling:\s*("(?:\\.|[^"\\])*")\s*,\s*meaning:\s*("(?:\\.|[^"\\])*")\s*,\s*decision:\s*("(?:\\.|[^"\\])*")\s*\}/g;

function fail(message) {
  throw new Error(`lexical ledger: ${message}`);
}

function readSource(path) {
  try {
    return readFileSync(resolve(ROOT, path), "utf8");
  } catch (error) {
    fail(`could not read ${path}: ${error instanceof Error ? error.message : String(error)}`);
  }
}

function rustString(literal, field) {
  try {
    return JSON.parse(literal);
  } catch (error) {
    fail(`invalid ${field} string literal ${literal}: ${error instanceof Error ? error.message : String(error)}`);
  }
}

export function readLedger() {
  const source = readSource(SYNTAX);
  const table = source.match(TABLE_RE)?.[0];
  if (!table) fail(`missing ${SYNTAX}::LEXICAL_LEDGER table`);

  const rows = [];
  ROW_RE.lastIndex = 0;
  for (const match of table.matchAll(ROW_RE)) {
    rows.push({
      spelling: rustString(match[1], "spelling"),
      meaning: rustString(match[2], "meaning"),
      decision: rustString(match[3], "decision"),
    });
  }
  const literalCount = (table.match(/\bLexicalEntry\s*\{/g) ?? []).length;
  if (rows.length === 0 || rows.length !== literalCount) {
    fail(`could not parse every LexicalEntry row in ${SYNTAX} (parsed ${rows.length}, found ${literalCount})`);
  }
  return rows;
}

function escapeHtml(value) {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
}

function cell(value) {
  const flat = String(value).replaceAll("|", "\\|").replaceAll(/\r?\n/g, " ");
  // A single backtick spelling cannot be represented by a one-backtick code
  // span. Use the equivalent inline HTML code element for those rows.
  return flat.includes("`") ? `<code>${escapeHtml(flat)}</code>` : `\`${flat}\``;
}

export function renderLedger(rows = readLedger()) {
  return [
    OPEN,
    "",
    `Generated by \`scripts/agent/lexical-ledger.mjs\` from \`${SYNTAX}::LEXICAL_LEDGER\`.`,
    "Do not hand-edit these rows. Add or change a spelling in Syntax.rs, recording its ratified decision ID when one exists, then rerun the renderer.",
    "",
    "| Spelling | Meaning | Decision |",
    "| --- | --- | --- |",
    ...rows.map((row) => `| ${cell(row.spelling)} | ${String(row.meaning).replaceAll("|", "\\|")} | ${row.decision ? cell(row.decision) : "—"} |`),
    "",
    CLOSE,
  ].join("\n");
}

function replaceBlock(spec, body) {
  const start = spec.indexOf(OPEN);
  const end = spec.indexOf(CLOSE);
  if ((start === -1) !== (end === -1)) fail("spec has only one lexical-ledger marker");
  if (start !== -1) {
    if (end < start) fail("spec lexical-ledger markers are out of order");
    return `${spec.slice(0, start)}${body}${spec.slice(end + CLOSE.length)}`;
  }

  const heading = "## Ratified\n";
  const anchor = spec.indexOf(heading);
  if (anchor === -1) fail("spec is missing the `## Ratified` insertion heading");
  const at = anchor + heading.length;
  return `${spec.slice(0, at)}\n${body}\n${spec.slice(at)}`;
}

function usage() {
  return [
    "usage: node scripts/agent/lexical-ledger.mjs [--check|--write]",
    "",
    "--check  fail when the rendered block is absent or stale",
    "--write  render the block from Syntax.rs into docs/spec/syntax-decisions.md",
  ].join("\n");
}

export function main(argv = process.argv.slice(2)) {
  try {
    if (argv.includes("--help") || argv.includes("-h")) {
      process.stdout.write(`${usage()}\n`);
      return 0;
    }
    const unknown = argv.find((argument) => !["--check", "--write"].includes(argument));
    if (unknown) fail(`unknown option ${unknown}`);
    if (argv.includes("--check") && argv.includes("--write")) fail("choose --check or --write");

    const body = renderLedger();
    const spec = readSource(SPEC);
    const next = replaceBlock(spec, body);
    if (next === spec) {
      process.stdout.write(`lexical ledger up to date (${readLedger().length} rows)\n`);
      return 0;
    }
    if (argv.includes("--check")) {
      process.stderr.write("lexical ledger is stale; run: node scripts/agent/lexical-ledger.mjs --write\n");
      return 1;
    }
    writeFileSync(resolve(ROOT, SPEC), next);
    process.stdout.write(`wrote lexical ledger: ${readLedger().length} rows\n`);
    return 0;
  } catch (error) {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    return 1;
  }
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  process.exitCode = main();
}
