#!/usr/bin/env bash
# Focused self-check for the agent workload report validator.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
scratch_root="${TMPDIR:-$HOME/.cache/jet-test-scratch}"
mkdir -p "$scratch_root"
tmp="$(mktemp -d "$scratch_root/agent-workload-gate-test.XXXXXX")"
trap 'rm -rf "$tmp"' EXIT

hash_stdin() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 | awk '{print $1}'
  else
    echo "agent workload gate self-check: no SHA-256 command available" >&2
    return 1
  fi
}

report="$tmp/linux.tsv"
policy_digest="$(LC_ALL=C awk 'NR > 1 { printf "\n" } { printf "%s", $0 }' tests/agent_workloads/policy.tsv | hash_stdin)"
awk -F '\t' -v OFS='\t' -v policy_digest="$policy_digest" '
  NR == 1 {
    print "# generated by test-agent-workload-gate.sh"
    print "version\tos\tarch\ttask\tdomain\tcase\tjet\tbash\tpython\tnode\tjet_vs_baselines\tloss_owner\trun_exit\tjet_source_tokens\tbash_source_tokens\tpython_source_tokens\tnode_source_tokens\tjet_cold_ns\tbash_cold_ns\tpython_cold_ns\tnode_cold_ns\tjet_warm_ns\tbash_warm_ns\tpython_warm_ns\tnode_warm_ns\tpolicy_digest"
    next
  }
  {
    printf "1\tlinux\tx86_64\t%s\t%s\t%s\tpass\tpass\tpass\tpass\tpass\t%s\t0", $2, $3, $4, $13
    for (metric = 1; metric <= 12; metric++) printf "\t1"
    print "\t" policy_digest
  }
' tests/agent_workloads/manifest.tsv >"$report"

check() {
  local name="$1" expected="$2" path="$3"
  set +e
  output=$(JET_AGENT_WORKLOAD_BASELINE="$ROOT/tests/agent_workloads/jet_baseline.tsv" bash tools/ci/agent-workload-gate.sh --check "$path" 2>&1)
  status=$?
  set -e
  if [ "$status" -ne "$expected" ]; then
    printf '%s: expected rc=%s, got rc=%s\n%s\n' "$name" "$expected" "$status" "$output" >&2
    exit 1
  fi
  printf '%s\n' "$output"
}

check passing-report 0 "$report" | grep -Fq 'agent workload gate: pass'

awk -F '\t' -v OFS='\t' '$4 == "repository-marker-scan" {$7 = "loss"; $11 = "loss"} {print}' "$report" >"$tmp/regression.tsv"
check regression-report 1 "$tmp/regression.tsv" | grep -Fq 'Jet regression: task=repository-marker-scan'

awk -F '\t' -v OFS='\t' '$4 == "repository-marker-scan" {$12 = "default-run=#999"} {print}' "$report" >"$tmp/owner-drift.tsv"
check owner-drift-report 1 "$tmp/owner-drift.tsv" | grep -Fq 'loss owner drifted from manifest: repository-marker-scan'

awk -F '\t' -v OFS='\t' '$1 == "1" {$2 = "windows"} {print}' "$report" >"$tmp/excluded.tsv"
check excluded-os-report 1 "$tmp/excluded.tsv" | grep -Fq 'OS is excluded by frozen matrix: windows'

awk -F '\t' -v OFS='\t' '$1 == "1" {$26 = substr($26, 1, 63) "0"} {print}' "$report" >"$tmp/bad-policy.tsv"
check bad-policy-report 1 "$tmp/bad-policy.tsv" | grep -Fq 'policy digest is not the frozen policy'

awk -F '\t' -v OFS='\t' '$4 == "repository-marker-scan" {$13 = 1} {print}' "$report" >"$tmp/nonzero-exit.tsv"
check nonzero-exit-report 1 "$tmp/nonzero-exit.tsv" | grep -Fq 'corpus command exited 1'

awk -F '\t' -v OFS='\t' '$4 == "repository-marker-scan" {$8 = "loss"} {print}' "$report" >"$tmp/inconsistent-score.tsv"
check inconsistent-score-report 1 "$tmp/inconsistent-score.tsv" | grep -Fq 'corpus score drifted: repository-marker-scan'

check missing-report 1 "$tmp/missing.tsv" | grep -Fq 'missing report'

mkdir "$tmp/reports"
cp "$report" "$tmp/reports/linux.tsv"
awk -F '\t' -v OFS='\t' '$1 == "1" {$2 = "macos"; $3 = "any"} {print}' "$report" >"$tmp/reports/macos.tsv"
matrix_output=$(bash tools/ci/agent-workload-matrix.sh "$tmp/reports" 2>&1)
printf '%s\n' "$matrix_output" | grep -Fq 'agent workload matrix: pass required_os=2'

echo "agent workload gate self-check: pass"
