[package]
name = "jet-semindex"
version = "0.1.0"
edition = "2021"

[lib]
name = "jet_semindex"
path = "src/lib.rs"

[dependencies]
jet-foundation = { path = "../jet-foundation" }
jet-lexer = { path = "../jet-lexer" }
jet-driver = { path = "../jet-driver" }
jet-pkg-model = { path = "../jet-pkg-model" }
jet-sema = { path = "../jet-sema" }
