//! E2-M3 (D-DX4) — the single in-code command/flag registry.
//!
//! One source of truth for:
//!   - shell completions (bash / zsh / fish), generated by hand (no clap — I6);
//!   - the `jet` man page;
//!   - the no-args greeting and "did you mean" suggestions (E2101/E2102).
//!
//! The CLI surface is *not* language syntax, so per invariant I7 it does not
//! live in `src/syntax.rs` (Wave A added no CLI flags there; we match that).
//! It lives here so the generators, the greeting, and the typo-finder can never
//! drift apart.

// Stable IDs bind public command families to reviewed capability depth.
// CAPABILITY_CLAIMS:BEGIN
// CAPABILITY_CLAIM: claim.tooling-cli | One coherent beginner-first CLI.
// CAPABILITY_CLAIM: claim.ide-debug | Editor and debugger consume shared semantic facts.
// CAPABILITY_CLAIM: claim.format-test | Formatting and tests have deterministic workflows.
// CAPABILITY_CLAIM: claim.package-build | Build/package/environment commands have canonical ownership.
// CAPABILITY_CLAIMS:END

use crate::Syntax::BINARY_NAME;

/// One global flag that applies across commands.
pub struct FlagSpec {
    /// Long form, e.g. `--json` (always present).
    pub long: &'static str,
    /// One-line help, used in completions and the man page.
    pub help: &'static str,
}

/// One subcommand of `jet`.
pub struct CommandSpec {
    pub name: &'static str,
    /// One-line summary (man + completion description).
    pub summary: &'static str,
    /// Whether this is one of the three "commands that matter" shown when argv
    /// is flags-only with no subcommand (bare `jet` starts the REPL instead).
    pub headline: bool,
}

/// D-CLI-SURFACE1=B / D-CLI-SURFACE2=A: authoritative nested command registry.
pub struct CommandGroup {
    pub name: &'static str,
    pub summary: &'static str,
    pub actions: &'static [NestedCommandSpec],
}

/// One canonical nested spelling and the real legacy dispatcher seam it reaches.
/// `HandlerKey::Store` keeps the group because that handler consumes the group word
/// itself (`store verify`, `store rollback`, and `store generations`).
pub struct NestedCommandSpec {
    pub name: &'static str,
    pub summary: &'static str,
    pub handler: HandlerKey,
}

/// Closed set of real dispatcher seams reachable from nested commands.
/// Adding a handler requires updating this exhaustive mapping and its route test.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum HandlerKey {
    Publish, Yank, Keygen, Key, Vendor,
    Graph, Query, ExplainBuild, Impact, Dossier, Semindex, Expand, Schema, Codemod, Audit, Sbom, Bind,
    Store, Gc, Fetch, Lock,
    Toolchain, Upgrade, Doctor, Completions, Man, Devtools, Lsp,
}

impl HandlerKey {
    pub const fn dispatch_word(self) -> &'static str {
        match self {
            Self::Publish => "publish", Self::Yank => "yank", Self::Keygen => "keygen",
            Self::Key => "key", Self::Vendor => "vendor", Self::Graph => "graph",
            Self::Query => "query", Self::ExplainBuild => "explain-build", Self::Impact => "impact",
            Self::Dossier => "dossier", Self::Semindex => "semindex", Self::Expand => "expand",
            Self::Schema => "schema", Self::Codemod => "codemod", Self::Audit => "audit",
            Self::Sbom => "sbom", Self::Bind => "bind", Self::Store => "store", Self::Gc => "gc",
            Self::Fetch => "fetch", Self::Lock => "lock", Self::Toolchain => "toolchain",
            Self::Upgrade => "upgrade", Self::Doctor => "doctor", Self::Completions => "completions",
            Self::Man => "man", Self::Devtools => "devtools", Self::Lsp => "lsp",
        }
    }

    pub const fn keeps_group(self) -> bool {
        matches!(self, Self::Store)
    }
}

const REGISTRY_ACTIONS: &[NestedCommandSpec] = &[
    NestedCommandSpec { name: "publish", summary: "publish the current package to the registry", handler: HandlerKey::Publish },
    NestedCommandSpec { name: "yank", summary: "mark a published version as yanked", handler: HandlerKey::Yank },
    NestedCommandSpec { name: "keygen", summary: "create the key that signs published packages", handler: HandlerKey::Keygen },
    NestedCommandSpec { name: "key", summary: "manage the package signing key", handler: HandlerKey::Key },
    NestedCommandSpec { name: "vendor", summary: "copy all dependencies into vendor/", handler: HandlerKey::Vendor },
];
const INSPECT_ACTIONS: &[NestedCommandSpec] = &[
    NestedCommandSpec { name: "graph", summary: "print the typed programmable-build graph", handler: HandlerKey::Graph },
    NestedCommandSpec { name: "query", summary: "query typed semantic and build facts", handler: HandlerKey::Query },
    NestedCommandSpec { name: "explain-build", summary: "explain one build target, action, or file", handler: HandlerKey::ExplainBuild },
    NestedCommandSpec { name: "impact", summary: "report a symbol's blast radius", handler: HandlerKey::Impact },
    NestedCommandSpec { name: "dossier", summary: "explain a file or symbol through semantic facts", handler: HandlerKey::Dossier },
    NestedCommandSpec { name: "semindex", summary: "query the stable semantic index", handler: HandlerKey::Semindex },
    NestedCommandSpec { name: "expand", summary: "print sema facts for one or every lens", handler: HandlerKey::Expand },
    NestedCommandSpec { name: "schema", summary: "inspect or re-baseline published schema snapshots", handler: HandlerKey::Schema },
    NestedCommandSpec { name: "codemod", summary: "run replayable semantic codemods", handler: HandlerKey::Codemod },
    NestedCommandSpec { name: "audit", summary: "check dependencies against the advisory database", handler: HandlerKey::Audit },
    NestedCommandSpec { name: "sbom", summary: "emit a software bill of materials", handler: HandlerKey::Sbom },
    NestedCommandSpec { name: "bind", summary: "generate a C binding cache from a header", handler: HandlerKey::Bind },
];
const STORE_ACTIONS: &[NestedCommandSpec] = &[
    NestedCommandSpec { name: "verify", summary: "verify store objects and references", handler: HandlerKey::Store },
    NestedCommandSpec { name: "rollback", summary: "roll back a store generation", handler: HandlerKey::Store },
    NestedCommandSpec { name: "generations", summary: "list store generations", handler: HandlerKey::Store },
    NestedCommandSpec { name: "gc", summary: "remove unreferenced store entries", handler: HandlerKey::Gc },
    NestedCommandSpec { name: "fetch", summary: "download and link all dependencies", handler: HandlerKey::Fetch },
    NestedCommandSpec { name: "lock", summary: "lock a script's inline dependencies", handler: HandlerKey::Lock },
];
const SELF_ACTIONS: &[NestedCommandSpec] = &[
    NestedCommandSpec { name: "toolchain", summary: "show the project's pinned Jet toolchain", handler: HandlerKey::Toolchain },
    NestedCommandSpec { name: "upgrade", summary: "show how to download a newer release", handler: HandlerKey::Upgrade },
    NestedCommandSpec { name: "doctor", summary: "diagnose the toolchain and offer fixes", handler: HandlerKey::Doctor },
    NestedCommandSpec { name: "completions", summary: "print shell completions", handler: HandlerKey::Completions },
    NestedCommandSpec { name: "man", summary: "print the Jet manual page", handler: HandlerKey::Man },
    NestedCommandSpec { name: "devtools", summary: "run checked developer generators", handler: HandlerKey::Devtools },
    NestedCommandSpec { name: "lsp", summary: "run the language server", handler: HandlerKey::Lsp },
];

pub const COMMAND_GROUPS: &[CommandGroup] = &[
    CommandGroup { name: "registry", summary: "publishing, signing, yanking, and vendoring", actions: REGISTRY_ACTIONS },
    CommandGroup { name: "inspect", summary: "semantic, build, schema, supply, and binding inspection", actions: INSPECT_ACTIONS },
    CommandGroup { name: "store", summary: "package-store integrity and lifecycle", actions: STORE_ACTIONS },
    CommandGroup { name: "self", summary: "Jet installation, diagnostics, completions, and machine tooling", actions: SELF_ACTIONS },
];

pub fn command_group(name: &str) -> Option<&'static CommandGroup> {
    COMMAND_GROUPS.iter().find(|group| group.name == name)
}

pub fn nested_command(group: &str, action: &str) -> Option<(&'static CommandGroup, &'static NestedCommandSpec)> {
    let group = command_group(group)?;
    group.actions.iter().find(|spec| spec.name == action).map(|action| (group, action))
}

pub fn moved_command(name: &str) -> Option<(&'static CommandGroup, &'static NestedCommandSpec)> {
    COMMAND_GROUPS.iter().find_map(|group| {
        group.actions.iter().find(|action| action.name == name).map(|action| (group, action))
    })
}

pub fn moved_command_group(name: &str) -> Option<&'static str> {
    moved_command(name).map(|(group, _)| group.name)
}

/// Every built-in subcommand. Order here is the order shown in the man page and
/// completions; the greeting picks the `headline` ones.
pub const COMMANDS: &[CommandSpec] = &[
    CommandSpec { name: "registry", summary: "publishing, signing, yanking, and vendoring", headline: false },
    CommandSpec { name: "inspect", summary: "semantic, build, schema, supply, and binding inspection", headline: false },
    CommandSpec { name: "self", summary: "Jet installation, diagnostics, completions, and machine tooling", headline: false },
    CommandSpec {
        name: "diff",
        summary: "compare checked Jet programs by semantic structure",
        headline: false,
    },
    CommandSpec {
        name: "merge",
        summary: "three-way merge checked Jet programs by semantic identity",
        headline: false,
    },
    CommandSpec {
        name: "run",
        summary: "build, then run a program (or a project)",
        headline: true,
    },
    CommandSpec {
        name: "check",
        summary: "look for problems, build nothing",
        headline: true,
    },
    CommandSpec {
        name: "test",
        summary: "compile and run top-level test blocks",
        headline: true,
    },
    CommandSpec {
        name: "build",
        summary: "compile to a native binary in ./build/",
        headline: false,
    },
    CommandSpec {
        name: "dev",
        summary: "watch a file and re-run it on every save",
        headline: false,
    },
    CommandSpec {
        name: "devtools",
        summary: "run checked developer generators (grammars)",
        headline: false,
    },
    CommandSpec {
        name: "serve",
        summary: "watch a resident program and hot-swap type-stable edits",
        headline: false,
    },
    CommandSpec {
        name: "debug",
        summary: "step through a program at the Jet source level (D-DBG3)",
        headline: false,
    },
    CommandSpec {
        name: "repl",
        summary: "interactive REPL — try Jet expressions without a file",
        headline: false,
    },
    CommandSpec {
        name: "new",
        summary: "create a new project folder",
        headline: false,
    },
    CommandSpec {
        name: "fmt",
        summary: "rewrite a file to canonical style",
        headline: false,
    },
    CommandSpec {
        name: "fix",
        summary: "apply all auto-fixable diagnostics in place",
        headline: false,
    },
    CommandSpec {
        name: "lint",
        summary: "opt-in lint categories, never blocking (--a11y: D-A11YGATE1)",
        headline: false,
    },
    CommandSpec {
        name: "explain",
        summary: "print the offline essay for a diagnostic code",
        headline: false,
    },
    CommandSpec {
        name: "doctor",
        summary: "diagnose the toolchain and offer fixes",
        headline: false,
    },
    CommandSpec {
        name: "env",
        summary: "enter the project dev shell",
        headline: false,
    },
    CommandSpec {
        name: "push",
        summary: "deploy a fleet through Jetpack",
        headline: false,
    },
    CommandSpec {
        name: "trust",
        summary: "list, explain, grant, and revoke Jet trust authority (D-JPK-GRANTCMD1)",
        headline: false,
    },
    CommandSpec {
        name: "bridge",
        summary: "translate a foreign environment description into Jetpack form",
        headline: false,
    },
    CommandSpec {
        name: "services",
        summary: "manage project-local dev services",
        headline: false,
    },
    CommandSpec {
        name: "image",
        summary: "build a declared OCI image",
        headline: false,
    },
    CommandSpec {
        name: "os",
        summary: "check, build, switch, rollback, list, lift, init, or image a jetos host",
        headline: false,
    },
    CommandSpec {
        name: "bind",
        summary: "generate a C binding cache from a header",
        headline: false,
    },
    CommandSpec {
        name: "add",
        summary: "add a dependency and fetch it",
        headline: false,
    },
    CommandSpec {
        name: "remove",
        summary: "remove a dependency",
        headline: false,
    },
    CommandSpec {
        name: "fetch",
        summary: "download and link all dependencies",
        headline: false,
    },
    CommandSpec {
        name: "update",
        summary: "refresh moving dependency selectors (`update jet` moves the toolchain pin)",
        headline: false,
    },
    CommandSpec {
        name: "toolchain",
        summary: "show the project's pinned jet self toolchain and its locked version (D-JPK-TOOLCHAIN1)",
        headline: false,
    },
    CommandSpec {
        name: "init",
        summary: "create a pkg.jet here, pinning the running jet's channel (add <script.jet> to lift its inline deps)",
        headline: false,
    },
    CommandSpec {
        name: "lock",
        summary: "resolve a manifest-less script's inline `use pkg#version;` deps and write its .lock sidecar (D-JPK-SCRIPTDEP1)",
        headline: false,
    },
    CommandSpec {
        name: "store",
        summary: "inspect or verify the package store",
        headline: false,
    },
    CommandSpec {
        name: "config",
        summary: "manage jet configuration (`config trust add/list/remove`, U19)",
        headline: false,
    },
    CommandSpec {
        name: "gc",
        summary: "remove unreferenced store entries",
        headline: false,
    },
    CommandSpec {
        name: "outdated",
        summary: "report Jetpack channel refs with newer locks available",
        headline: false,
    },
    CommandSpec {
        name: "search",
        summary: "search the local offline Jetpack package index",
        headline: false,
    },
    CommandSpec {
        name: "info",
        summary: "show local offline Jetpack package metadata",
        headline: false,
    },
    CommandSpec {
        name: "logs",
        summary: "show latest Jetpack build logs",
        headline: false,
    },
    CommandSpec {
        name: "clean",
        summary: "optimize and collect stale Jetpack hangar entries",
        headline: false,
    },
    CommandSpec {
        name: "publish",
        summary: "publish the current package to the registry",
        headline: false,
    },
    CommandSpec {
        name: "yank",
        summary: "mark a published version as yanked (D-VERSION1)",
        headline: false,
    },
    CommandSpec {
        name: "keygen",
        summary: "create the Ed25519 key that signs published packages (D-PKGSIGN1)",
        headline: false,
    },
    CommandSpec {
        name: "key",
        summary: "manage the package signing key (key backup)",
        headline: false,
    },
    CommandSpec {
        name: "schema",
        summary: "inspect or re-baseline @PublishedSchema snapshots (status | squash)",
        headline: false,
    },
    CommandSpec {
        name: "semindex",
        summary: "query the stable semantic index for a project entry file",
        headline: false,
    },
    CommandSpec {
        name: "dossier",
        summary: "explain a file or symbol through stable semantic fact lenses",
        headline: false,
    },
    CommandSpec {
        name: "impact",
        summary: "report blast radius for a symbol (callers, references, callees)",
        headline: false,
    },
    CommandSpec {
        name: "graph",
        summary: "print typed programmable-build graph (D-BUILDQUERY1)",
        headline: false,
    },
    CommandSpec {
        name: "query",
        summary: "query typed facts; `jet inspect query build <file>` inspects build graph",
        headline: false,
    },
    CommandSpec {
        name: "explain-build",
        summary: "explain one build target, action, or file (D-BUILDQUERY1)",
        headline: false,
    },
    CommandSpec {
        name: "codemod",
        summary: "dry-run, apply, or undo replayable semantic codemods",
        headline: false,
    },
    CommandSpec {
        name: "expand",
        summary: "print sema's facts for one lens (--facts <lens>) or every lens (D-EXPANDCLI1)",
        headline: false,
    },
    CommandSpec {
        name: "vendor",
        summary: "copy all dependencies into vendor/",
        headline: false,
    },
    CommandSpec {
        name: "audit",
        summary: "check dependencies against the advisory database",
        headline: false,
    },
    CommandSpec {
        name: "sbom",
        summary: "emit a software bill of materials from the lockfile",
        headline: false,
    },
    CommandSpec {
        name: "emit",
        summary: "emit generated output (--rust: print Rust source)",
        headline: false,
    },
    CommandSpec {
        name: "eval",
        summary: "evaluate a pure Jet program to stable JSON (--pure required)",
        headline: false,
    },
    CommandSpec {
        name: "bench",
        summary: "benchmark a Jet program with honest stats",
        headline: false,
    },
    CommandSpec {
        name: "fuzz",
        summary: "fuzz a property `#Test fn` — corpus, minimization, seeded PRNG",
        headline: false,
    },
    CommandSpec {
        name: "completions",
        summary: "print shell completions (bash | zsh | fish)",
        headline: false,
    },
    CommandSpec {
        name: "man",
        summary: "print the jet self man page (roff)",
        headline: false,
    },
    CommandSpec {
        name: "lsp",
        summary: "language server (stdio JSON-RPC)",
        headline: false,
    },
    CommandSpec {
        name: "version",
        summary: "print compiler version",
        headline: false,
    },
    CommandSpec {
        name: "upgrade",
        summary: "how to download a newer release",
        headline: false,
    },
    CommandSpec {
        name: "help",
        summary: "print the help text",
        headline: false,
    },
];

/// D-CLI-SURFACE1=B / D-CLI-SURFACE2=A: canonical top-level frequency ring.
/// Moved handler names remain in the internal registry only so normalized
/// grouped argv reaches the real dispatcher; generators must never advertise
/// those retired bare spellings.
pub fn is_canonical_top_level(name: &str) -> bool {
    moved_command_group(name).is_none()
}

/// Every global flag the driver understands. Used to flag-check and to suggest
/// on a typo (E2102), and to complete after `--`.
pub const FLAGS: &[FlagSpec] = &[
    FlagSpec { long: "--structural", help: "with diff/merge: compare checked definitions by semantic identity" },
    FlagSpec { long: "--out", help: "with structural merge: write the checked result to this path" },
    FlagSpec { long: "--report", help: "with structural diff/merge: text, json, or editor report" },
    FlagSpec { long: "--repo", help: "with merge install-driver: Git worktree to configure" },
    FlagSpec { long: "--json", help: "emit machine-readable diagnostics" },
    FlagSpec { long: "--color", help: "color: auto | always | never" },
    FlagSpec { long: "--version", help: "print compiler version" },
    FlagSpec { long: "--emit-rust", help: "also print the generated Rust code" },
    FlagSpec { long: "--check", help: "with fmt: exit 1 if any file would change (CI gate)" },
    FlagSpec { long: "--diff", help: "with fmt --check: also print unified diffs for each changed file" },
    FlagSpec { long: "--changed", help: "with fmt: format only VCS-changed .jet files (requires git)" },
    FlagSpec { long: "--stdin-path", help: "with fmt -: path label used in diagnostics when reading from stdin" },
    FlagSpec { long: "--small", help: "with build/run: smallest binary (S15)" },
    FlagSpec { long: "--locked", help: "with fetch: verify only, refuse network" },
    FlagSpec { long: "--annotated", help: "with new: include commented example deps" },
    FlagSpec { long: "--force", help: "with publish: bypass pre-publish gate (with warning)" },
    FlagSpec { long: "--message", help: "with yank: human-readable reason for yanking the version" },
    FlagSpec { long: "--before", help: "with schema squash: re-baseline migrations before this version" },
    FlagSpec { long: "--spdx", help: "with sbom: emit SPDX tag-value format (default)" },
    FlagSpec { long: "--cyclonedx", help: "with sbom: emit CycloneDX JSON format" },
    FlagSpec { long: "--advisory-db", help: "with audit: path to advisory database file" },
    FlagSpec { long: "--vendor-dir", help: "with vendor: directory to copy dependencies into (default vendor/)" },
    FlagSpec { long: "--sbom", help: "with build: also write an SPDX SBOM next to the binary" },
    FlagSpec { long: "--verbose", help: "with build: print the bridge steps" },
    FlagSpec { long: "--online", help: "with doctor: allow network checks" },
    FlagSpec { long: "--fix", help: "with doctor: apply auto-fixable problems" },
    FlagSpec { long: "--dry-run", help: "with fix: show changes without writing" },
    FlagSpec { long: "--try-anyway", help: "with dev: interpret past unsupported features (no guarantees)" },
    FlagSpec { long: "--restart", help: "with dev/serve: always rerun from scratch on save (c77)" },
    FlagSpec { long: "--swap", help: "with dev/serve: hot-swap type-stable edits, restart on type change (c77)" },
    FlagSpec { long: "--watch", help: "with dev/serve: --watch=off runs once and exits (c77)" },
    // E2-M18 REPL flags.
    FlagSpec { long: "--project", help: "with repl: load pkg.jet from this directory for import context (D-REPL10)" },
    // E2-M16 flags.
    FlagSpec { long: "--pure", help: "with eval: require the program to be pure (S60 / D-PURE2)" },
    FlagSpec { long: "--freestanding", help: "with build/run: no OS; rejects std-only APIs (E2-M15)" },
    // D-CTEFFECT1: comptime effect tier gate.
    FlagSpec { long: "--allow-impure", help: "with build/run: allow Tier-2 ambient comptime effects inside #Impure gates (D-CTEFFECT1)" },
    // D-BUILDFLAGS1=A: per-effect grants for one programmable-build run.
    FlagSpec { long: "--allow-exec", help: "with build: grant declared Exec actions for this run (D-BUILDFLAGS1)" },
    FlagSpec { long: "--allow-fs", help: "with build: grant declared Fs actions for this run (D-BUILDFLAGS1)" },
    FlagSpec { long: "--allow-net", help: "with build: grant declared Net actions for this run (D-BUILDFLAGS1)" },
    FlagSpec { long: "--allow-env", help: "with build: grant declared Env actions for this run (D-BUILDFLAGS1)" },
    FlagSpec { long: "--allow-io", help: "with build: grant declared Io actions for this run (D-BUILDFLAGS1)" },
    FlagSpec { long: "--allow-db", help: "with build: grant declared Db actions for this run (D-BUILDFLAGS1)" },
    FlagSpec { long: "--allow-time", help: "with build: grant declared Time actions for this run (D-BUILDFLAGS1)" },
    FlagSpec { long: "--allow-rand", help: "with build: grant declared Rand actions for this run (D-BUILDFLAGS1)" },
    FlagSpec { long: "--allow-log", help: "with build: grant declared Log actions for this run (D-BUILDFLAGS1)" },
    FlagSpec { long: "--allow-gpu", help: "with build: grant declared Gpu actions for this run (D-BUILDFLAGS1)" },
    FlagSpec { long: "--target", help: "with build: cross-compile for a rustc target triple (E2-M15)" },
    FlagSpec {
        long: "--explain-partition",
        help: "with build --target=web: print the JS/WASM partition report (D-WASM1)",
    },
    // E2-M11 flags.
    FlagSpec { long: "--capabilities-json", help: "with build: emit capability summary as JSON (D-TOOL5)" },
    FlagSpec { long: "--update-snapshots", help: "with test: update snapshot golden files (D-TOOL4)" },
    FlagSpec { long: "--coverage", help: "with test: report per-function / per-line coverage (D-COV1)" },
    FlagSpec { long: "--rust", help: "with emit: print the generated Rust source (D-TOOL3)" },
    FlagSpec { long: "-u", help: "short form of --update-snapshots" },
    // D-BUILDPROFILE1 (ratified 2026-06-25): named build profiles.
    FlagSpec { long: "--release", help: "with build/run: use the release profile (D-BUILDPROFILE1)" },
    FlagSpec { long: "--profile", help: "with build/run: named build profile --profile=<name> (D-BUILDPROFILE1)" },
    // D-A11YGATE1=B (c134 Phase 6): accessibility is an opt-in lint category.
    FlagSpec { long: "--a11y", help: "with lint: check accessibility — missing roles, unlabeled controls (D-A11YGATE1)" },
    FlagSpec { long: "--scope", help: "with trust grant: grant scope, user or repo (D-JPK-GRANTCMD1)" },
    // D-TESTKIT1=A (c308 pass 2): filter/shuffle/serial for `jet test`.
    FlagSpec { long: "--filter", help: "with test: only run tests whose name contains --filter=<substr>" },
    FlagSpec { long: "--shuffle", help: "with test: run tests in random (or --shuffle=<seed>) order" },
    FlagSpec { long: "--serial", help: "with test: run tests one at a time instead of the parallel default" },
    // D-TESTKIT1=A: `jet fuzz` (its own bespoke flags below are validated by
    // `owns_flag_vocabulary`; these two are listed for completions/the man page).
    FlagSpec { long: "--iterations", help: "with fuzz: case budget --iterations=<n> (default 1000)" },
    FlagSpec { long: "--time", help: "with fuzz: wall-clock budget in seconds --time=<n>" },
    FlagSpec { long: "--seed", help: "with fuzz: base PRNG seed --seed=<n> (default: fixed, reproducible)" },
    FlagSpec { long: "--corpus", help: "with fuzz: corpus directory --corpus=<dir> (default: .jet/fuzz/<test>)" },
];

/// Is `name` a built-in command?
pub fn is_builtin(name: &str) -> bool {
    COMMANDS.iter().any(|c| c.name == name)
        // E0043 teaching path: `jet install` is intentionally not advertised in
        // help/completions, but dispatch must reach its bespoke "use fetch"
        // diagnostic instead of generic unknown-command E2101.
        || name == "install"
}

/// Commands that own a bespoke flag vocabulary or forward flags downstream.
/// Main dispatch still reads the command set from `COMMANDS`; this only decides
/// whether the generic E2102 checker should run.
pub fn owns_flag_vocabulary(name: &str) -> bool {
    matches!(
        name,
        "env"
            | "dev"
            | "devtools"
            | "serve"
            | "push"
            | "trust"
            | "bridge"
            | "services"
            | "image"
            | "os"
            | "add"
            | "remove"
            | "bind"
            | "lsp"
            | "store"
            | "config"
            | "update"
            | "outdated"
            | "search"
            | "info"
            | "explain"
            | "logs"
            | "clean"
            | "fetch"
            | "publish"
            | "yank"
            | "keygen"
            | "key"
            | "vendor"
            | "audit"
            | "sbom"
            | "repl"
            | "schema"
            | "semindex"
            | "dossier"
            | "impact"
            | "codemod"
            | "expand"
            | "diff"
            | "merge"
    )
}

/// Is `flag` (e.g. `--json` or `--color=always`) a known flag?
pub fn is_known_flag(flag: &str) -> bool {
    let head = flag.split('=').next().unwrap_or(flag);
    FLAGS.iter().any(|f| f.long == head)
}

/// Levenshtein edit distance — the same shape used by sema's S14 suggestions.
pub fn edit_distance(a: &str, b: &str) -> usize {
    let a: Vec<char> = a.chars().collect();
    let b: Vec<char> = b.chars().collect();
    let mut prev: Vec<usize> = (0..=b.len()).collect();
    for i in 1..=a.len() {
        let mut cur = vec![i];
        for j in 1..=b.len() {
            let cost = if a[i - 1] == b[j - 1] { 0 } else { 1 };
            cur.push((prev[j] + 1).min(cur[j - 1] + 1).min(prev[j - 1] + cost));
        }
        prev = cur;
    }
    prev[b.len()]
}

/// Closest built-in command to `name` within edit distance 3, or `None`.
pub fn closest_command(name: &str) -> Option<&'static str> {
    closest(name, COMMANDS.iter().map(|c| c.name))
}

/// Closest known flag to `flag` within edit distance 3, or `None`.
pub fn closest_flag(flag: &str) -> Option<&'static str> {
    let head = flag.split('=').next().unwrap_or(flag);
    closest(head, FLAGS.iter().map(|f| f.long))
}

fn closest<'a, I: Iterator<Item = &'a str>>(needle: &str, hay: I) -> Option<&'a str> {
    let mut best: Option<(&str, usize)> = None;
    for cand in hay {
        let d = edit_distance(needle, cand);
        if best.map(|(_, bd)| d < bd).unwrap_or(true) {
            best = Some((cand, d));
        }
    }
    // Cap: only suggest when reasonably close (allow ~half the word length).
    best.filter(|(c, d)| *d <= 3 && *d <= c.len())
        .map(|(c, _)| c)
}

// ──────────────────────────────────────────────
// Generators (hand-rolled — invariant I6, no clap_complete)
// ──────────────────────────────────────────────

/// bash completion script for `jet`.
pub fn completions_bash() -> String {
    let cmds = COMMANDS
        .iter()
        .filter(|c| is_canonical_top_level(c.name))
        .map(|c| c.name)
        .collect::<Vec<_>>()
        .join(" ");
    let flags = FLAGS.iter().map(|f| f.long).collect::<Vec<_>>().join(" ");
    let nested = COMMAND_GROUPS.iter().map(|g| format!("        {}) COMPREPLY=( $(compgen -W \"{}\" -- \"$cur\") ); return 0 ;;", g.name, g.actions.iter().map(|a| a.name).collect::<Vec<_>>().join(" "))).collect::<Vec<_>>().join("\n");
    format!(
        "# bash completion for {bin} (generated by `{bin} self completions bash`)\n\
_{bin}() {{\n\
    local cur prev cmds flags\n\
    COMPREPLY=()\n\
    cur=\"${{COMP_WORDS[COMP_CWORD]}}\"\n\
    cmds=\"{cmds}\"\n\
    flags=\"{flags}\"\n\
    if [[ \"$cur\" == -* ]]; then\n\
        COMPREPLY=( $(compgen -W \"$flags\" -- \"$cur\") )\n\
        return 0\n\
    fi\n\
    if [[ $COMP_CWORD -eq 1 ]]; then\n\
        COMPREPLY=( $(compgen -W \"$cmds\" -- \"$cur\") )\n\
        return 0\n\
    fi\n\
    if [[ $COMP_CWORD -eq 2 ]]; then\n\
        case \"${{COMP_WORDS[1]}}\" in\n{nested}\n        esac\n\
    fi\n\
    COMPREPLY=( $(compgen -f -- \"$cur\") )\n\
}}\n\
complete -F _{bin} {bin}\n",
        bin = BINARY_NAME,
        cmds = cmds,
        flags = flags,
        nested = nested,
    )
}

/// zsh completion script for `jet`.
pub fn completions_zsh() -> String {
    let mut cmd_lines = String::new();
    for c in COMMANDS {
        if !is_canonical_top_level(c.name) { continue; }
        cmd_lines.push_str(&format!("        '{}:{}'\n", c.name, escape_zsh(c.summary)));
    }
    let nested = COMMAND_GROUPS.iter().map(|g| format!("            {}) _values 'action' {} ;;", g.name, g.actions.iter().map(|a| format!("'{}:{}'", a.name, escape_zsh(a.summary))).collect::<Vec<_>>().join(" "))).collect::<Vec<_>>().join("\n");
    let mut flag_lines = String::new();
    for f in FLAGS {
        flag_lines.push_str(&format!("        '{}[{}]'\n", f.long, escape_zsh(f.help)));
    }
    format!(
        "#compdef {bin}\n\
# zsh completion for {bin} (generated by `{bin} self completions zsh`)\n\
_{bin}() {{\n\
    local -a commands flags\n\
    commands=(\n{cmds}    )\n\
    flags=(\n{flags}    )\n\
    if (( CURRENT == 2 )); then\n\
        _describe -t commands 'command' commands\n\
    elif (( CURRENT == 3 )); then\n\
        case $words[2] in\n{nested}\n        esac\n\
    else\n\
        _values 'flag' $flags\n\
        _files\n\
    fi\n\
}}\n\
_{bin} \"$@\"\n",
        bin = BINARY_NAME,
        cmds = cmd_lines,
        flags = flag_lines,
        nested = nested,
    )
}

/// fish completion script for `jet`.
pub fn completions_fish() -> String {
    let mut out = format!(
        "# fish completion for {bin} (generated by `{bin} self completions fish`)\n",
        bin = BINARY_NAME
    );
    // Only complete subcommands when none has been seen yet.
    let seen = "__fish_use_subcommand";
    for c in COMMANDS {
        if !is_canonical_top_level(c.name) { continue; }
        out.push_str(&format!(
            "complete -c {bin} -n '{seen}' -a {name} -d '{desc}'\n",
            bin = BINARY_NAME,
            seen = seen,
            name = c.name,
            desc = escape_fish(c.summary),
        ));
    }
    for group in COMMAND_GROUPS {
        for action in group.actions {
            out.push_str(&format!("complete -c {bin} -n '__fish_seen_subcommand_from {group}' -a {action} -d '{desc}'\n", bin=BINARY_NAME, group=group.name, action=action.name, desc=escape_fish(action.summary)));
        }
    }
    for f in FLAGS {
        out.push_str(&format!(
            "complete -c {bin} -l {long} -d '{desc}'\n",
            bin = BINARY_NAME,
            long = f.long.trim_start_matches("--"),
            desc = escape_fish(f.help),
        ));
    }
    out
}

/// PowerShell completion script, derived from the same nested registry.
pub fn completions_powershell() -> String {
    let top = COMMANDS.iter().filter(|c| is_canonical_top_level(c.name)).map(|c| format!("'{}'", c.name)).collect::<Vec<_>>().join(",");
    let groups = COMMAND_GROUPS.iter().map(|g| format!("'{}' = @({})", g.name, g.actions.iter().map(|a| format!("'{}'", a.name)).collect::<Vec<_>>().join(","))).collect::<Vec<_>>().join("; ");
    let flags = FLAGS.iter().map(|f| format!("'{}'", f.long)).collect::<Vec<_>>().join(",");
    format!("# PowerShell completion for {bin} (generated by `{bin} self completions powershell`)\n$JetCommands = @({top})\n$JetFlags = @({flags})\n$JetGroups = @{{ {groups} }}\nRegister-ArgumentCompleter -Native -CommandName {bin} -ScriptBlock {{ param($wordToComplete,$commandAst,$cursorPosition) $words = @($commandAst.CommandElements | ForEach-Object {{ $_.Extent.Text }}); $choices = if ($wordToComplete.StartsWith('-')) {{ $JetFlags }} elseif ($words.Count -ge 2 -and $JetGroups.ContainsKey($words[1])) {{ $JetGroups[$words[1]] }} else {{ $JetCommands }}; $choices | Where-Object {{ $_ -like \"$wordToComplete*\" }} | ForEach-Object {{ [System.Management.Automation.CompletionResult]::new($_,$_,\"ParameterValue\",$_) }} }}\n", bin=BINARY_NAME, top=top, flags=flags, groups=groups)
}

/// roff man page for `jet`, section 1.
pub fn man_page(version: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        ".TH {bin_up} 1 \"\" \"{bin} {ver}\" \"Jet Manual\"\n",
        bin_up = BINARY_NAME.to_uppercase(),
        bin = BINARY_NAME,
        ver = version,
    ));
    out.push_str(".SH NAME\n");
    out.push_str(&format!(
        "{bin} \\- the Jet compiler and project tool\n",
        bin = BINARY_NAME
    ));
    out.push_str(".SH SYNOPSIS\n");
    out.push_str(&format!(
        ".B {bin}\n.RI [ command ] \" \" [ args ...]\n",
        bin = BINARY_NAME
    ));
    out.push_str(".SH DESCRIPTION\n");
    out.push_str(&format!(
        "{bin} builds, checks, runs, and tests Jet programs, and manages Jet projects \
and their dependencies. Output is plain when piped and colored on a terminal.\n",
        bin = BINARY_NAME
    ));
    out.push_str(".SH COMMANDS\n");
    for c in COMMANDS {
        if !is_canonical_top_level(c.name) { continue; }
        out.push_str(&format!(".TP\n.B {}\n{}\n", c.name, roff_escape(c.summary)));
        if let Some(group) = command_group(c.name) {
            for action in group.actions {
                out.push_str(&format!(".TP\n.B {} {}\n{}\n", group.name, action.name, roff_escape(action.summary)));
            }
        }
    }
    out.push_str(".SH FLAGS\n");
    for f in FLAGS {
        out.push_str(&format!(".TP\n.B {}\n{}\n", f.long, roff_escape(f.help)));
    }
    out.push_str(".SH FILES\n");
    out.push_str(&format!(
        ".TP\n.B {manifest}\nThe project manifest.\n",
        manifest = crate::Syntax::PAYLOAD_FILE
    ));
    out.push_str(".SH SEE ALSO\n");
    out.push_str(&format!("{bin}-explain(1)\n", bin = BINARY_NAME));
    out
}

fn escape_zsh(s: &str) -> String {
    s.replace('\'', "'\\''")
        .replace(':', "\\:")
        .replace('[', "\\[")
        .replace(']', "\\]")
}
fn escape_fish(s: &str) -> String {
    s.replace('\'', "\\'")
}
fn roff_escape(s: &str) -> String {
    // Lines beginning with `'` or `.` are roff control lines; escape and also
    // neutralize backslashes.
    s.replace('\\', "\\\\")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn typo_finds_closest_command() {
        assert_eq!(closest_command("buld"), Some("build"));
        assert_eq!(closest_command("chekc"), Some("check"));
        assert_eq!(closest_command("rnu"), Some("run"));
        // Nonsense gets no suggestion.
        assert_eq!(closest_command("zxqwvbn"), None);
    }

    #[test]
    fn typo_finds_closest_flag() {
        assert_eq!(closest_flag("--jsn"), Some("--json"));
        assert_eq!(closest_flag("--colr"), Some("--color"));
    }

    #[test]
    fn known_flag_ignores_value() {
        assert!(is_known_flag("--color=always"));
        assert!(is_known_flag("--json"));
        assert!(!is_known_flag("--nonsense"));
    }

    #[test]
    fn completions_mention_every_command() {
        for shell_out in [completions_bash(), completions_zsh(), completions_fish(), completions_powershell()] {
            for c in COMMANDS.iter().filter(|c| is_canonical_top_level(c.name)) {
                assert!(
                    shell_out.contains(c.name),
                    "completion missing command {}",
                    c.name
                );
            }
            for group in COMMAND_GROUPS {
                assert!(shell_out.contains(group.name), "completion missing group {}", group.name);
                for action in group.actions {
                    assert!(shell_out.contains(action.name), "completion missing {} {}", group.name, action.name);
                }
            }
        }
    }

    #[test]
    fn moved_commands_are_not_canonical_top_level() {
        for group in COMMAND_GROUPS {
            for action in group.actions {
                assert!(!is_canonical_top_level(action.name), "moved bare command leaked: {}", action.name);
                assert_eq!(moved_command_group(action.name), Some(group.name));
            }
        }
    }

    #[test]
    fn every_nested_action_routes_to_a_real_dispatch_seam() {
        use HandlerKey::*;
        let expected = [
            ("registry", "publish", Publish, "publish", false), ("registry", "yank", Yank, "yank", false),
            ("registry", "keygen", Keygen, "keygen", false), ("registry", "key", Key, "key", false),
            ("registry", "vendor", Vendor, "vendor", false), ("inspect", "graph", Graph, "graph", false),
            ("inspect", "query", Query, "query", false), ("inspect", "explain-build", ExplainBuild, "explain-build", false),
            ("inspect", "impact", Impact, "impact", false), ("inspect", "dossier", Dossier, "dossier", false),
            ("inspect", "semindex", Semindex, "semindex", false), ("inspect", "expand", Expand, "expand", false),
            ("inspect", "schema", Schema, "schema", false), ("inspect", "codemod", Codemod, "codemod", false),
            ("inspect", "audit", Audit, "audit", false), ("inspect", "sbom", Sbom, "sbom", false),
            ("inspect", "bind", Bind, "bind", false), ("store", "verify", Store, "store", true),
            ("store", "rollback", Store, "store", true), ("store", "generations", Store, "store", true),
            ("store", "gc", Gc, "gc", false), ("store", "fetch", Fetch, "fetch", false),
            ("store", "lock", Lock, "lock", false), ("self", "toolchain", Toolchain, "toolchain", false),
            ("self", "upgrade", Upgrade, "upgrade", false), ("self", "doctor", Doctor, "doctor", false),
            ("self", "completions", Completions, "completions", false), ("self", "man", Man, "man", false),
            ("self", "devtools", Devtools, "devtools", false), ("self", "lsp", Lsp, "lsp", false),
        ];
        assert_eq!(COMMAND_GROUPS.iter().map(|g| g.actions.len()).sum::<usize>(), expected.len());
        for (group_name, action_name, handler, dispatch_word, keeps_group) in expected {
            let (_, action) = nested_command(group_name, action_name).unwrap_or_else(|| panic!("missing {group_name} {action_name}"));
            assert_eq!(action.handler, handler, "wrong handler for {group_name} {action_name}");
            assert_eq!(action.handler.dispatch_word(), dispatch_word, "wrong dispatcher for {group_name} {action_name}");
            assert_eq!(action.handler.keeps_group(), keeps_group, "wrong argv policy for {group_name} {action_name}");
            let mut normalized = vec![group_name, action_name, "tail"];
            if !action.handler.keeps_group() {
                normalized[0] = action.handler.dispatch_word();
                normalized.remove(1);
            }
            let expected_argv = if keeps_group {
                vec![group_name, action_name, "tail"]
            } else {
                vec![dispatch_word, "tail"]
            };
            assert_eq!(normalized, expected_argv, "wrong normalized argv for {group_name} {action_name}");
        }
        for group in COMMAND_GROUPS {
            for action in group.actions {
                assert!(!action.summary.trim().is_empty(), "missing summary for {} {}", group.name, action.name);
                assert!(is_builtin(action.handler.dispatch_word()), "{} {} routes to missing handler {}", group.name, action.name, action.handler.dispatch_word());
                assert_eq!(nested_command(group.name, action.name).map(|(_, a)| a.handler), Some(action.handler));
                if action.handler.keeps_group() {
                    assert_eq!(action.handler.dispatch_word(), group.name, "kept group must own its dispatcher");
                }
            }
        }
    }

    #[test]
    fn man_mentions_every_command_and_flag() {
        let m = man_page("0.0.0");
        for c in COMMANDS.iter().filter(|c| is_canonical_top_level(c.name)) {
            assert!(m.contains(c.name), "man missing command {}", c.name);
        }
        for f in FLAGS {
            assert!(m.contains(f.long), "man missing flag {}", f.long);
        }
    }
}
