//! E2-M3 (D-DX4) — the single in-code command/flag registry.
//!
//! One source of truth for:
//!   - shell completions (bash / zsh / fish), generated by hand (no clap — I6);
//!   - the `jet` man page;
//!   - the no-args greeting and "did you mean" suggestions (E2101/E2102).
//!
//! The CLI surface is *not* language syntax, so per invariant I7 it does not
//! live in `src/syntax.rs` (Wave A added no CLI flags there; we match that).
//! It lives here so the generators, the greeting, and the typo-finder can never
//! drift apart.

// Stable IDs bind public command families to reviewed capability depth.
// CAPABILITY_CLAIM: claim.tooling-cli | One coherent beginner-first CLI.
// CAPABILITY_CLAIM: claim.ide-debug | Editor and debugger consume shared semantic facts.
// CAPABILITY_CLAIM: claim.format-test | Formatting and tests have deterministic workflows.
// CAPABILITY_CLAIM: claim.package-build | Build/package/environment commands have canonical ownership.

use crate::Syntax::BINARY_NAME;

/// One global flag that applies across commands.
pub struct FlagSpec {
    /// Long form, e.g. `--json` (always present).
    pub long: &'static str,
    /// One-line help, used in completions and the man page.
    pub help: &'static str,
}

/// One subcommand of `jet`.
pub struct CommandSpec {
    pub name: &'static str,
    /// One-line summary (man + completion description).
    pub summary: &'static str,
    /// Whether this is one of the three "commands that matter" shown when argv
    /// is flags-only with no subcommand (bare `jet` starts the REPL instead).
    pub headline: bool,
}

/// Every built-in subcommand. Order here is the order shown in the man page and
/// completions; the greeting picks the `headline` ones.
pub const COMMANDS: &[CommandSpec] = &[
    CommandSpec {
        name: "run",
        summary: "build, then run a program (or a project)",
        headline: true,
    },
    CommandSpec {
        name: "check",
        summary: "look for problems, build nothing",
        headline: true,
    },
    CommandSpec {
        name: "test",
        summary: "compile and run top-level test blocks",
        headline: true,
    },
    CommandSpec {
        name: "build",
        summary: "compile to a native binary in ./build/",
        headline: false,
    },
    CommandSpec {
        name: "dev",
        summary: "watch a file and re-run it on every save",
        headline: false,
    },
    CommandSpec {
        name: "devtools",
        summary: "run checked developer generators (grammars)",
        headline: false,
    },
    CommandSpec {
        name: "serve",
        summary: "watch a resident program and hot-swap type-stable edits",
        headline: false,
    },
    CommandSpec {
        name: "debug",
        summary: "step through a program at the Jet source level (D-DBG3)",
        headline: false,
    },
    CommandSpec {
        name: "repl",
        summary: "interactive REPL — try Jet expressions without a file",
        headline: false,
    },
    CommandSpec {
        name: "new",
        summary: "create a new project folder",
        headline: false,
    },
    CommandSpec {
        name: "fmt",
        summary: "rewrite a file to canonical style",
        headline: false,
    },
    CommandSpec {
        name: "fix",
        summary: "apply all auto-fixable diagnostics in place",
        headline: false,
    },
    CommandSpec {
        name: "lint",
        summary: "opt-in lint categories, never blocking (--a11y: D-A11YGATE1)",
        headline: false,
    },
    CommandSpec {
        name: "explain",
        summary: "print the offline essay for a diagnostic code",
        headline: false,
    },
    CommandSpec {
        name: "doctor",
        summary: "diagnose the toolchain and offer fixes",
        headline: false,
    },
    CommandSpec {
        name: "env",
        summary: "enter the project dev shell",
        headline: false,
    },
    CommandSpec {
        name: "push",
        summary: "deploy a fleet through Jetpack",
        headline: false,
    },
    CommandSpec {
        name: "trust",
        summary: "list, explain, grant, and revoke Jet trust authority (D-JPK-GRANTCMD1)",
        headline: false,
    },
    CommandSpec {
        name: "bridge",
        summary: "translate a foreign environment description into Jetpack form",
        headline: false,
    },
    CommandSpec {
        name: "services",
        summary: "manage project-local dev services",
        headline: false,
    },
    CommandSpec {
        name: "image",
        summary: "build a declared OCI image",
        headline: false,
    },
    CommandSpec {
        name: "os",
        summary: "check, build, switch, rollback, list, lift, init, or image a jetos host",
        headline: false,
    },
    CommandSpec {
        name: "bind",
        summary: "generate a C binding cache from a header",
        headline: false,
    },
    CommandSpec {
        name: "add",
        summary: "add a dependency and fetch it",
        headline: false,
    },
    CommandSpec {
        name: "remove",
        summary: "remove a dependency",
        headline: false,
    },
    CommandSpec {
        name: "fetch",
        summary: "download and link all dependencies",
        headline: false,
    },
    CommandSpec {
        name: "update",
        summary: "refresh moving dependency selectors (`update jet` moves the toolchain pin)",
        headline: false,
    },
    CommandSpec {
        name: "toolchain",
        summary: "show the project's pinned jet toolchain and its locked version (D-JPK-TOOLCHAIN1)",
        headline: false,
    },
    CommandSpec {
        name: "init",
        summary: "create a pkg.jet here, pinning the running jet's channel (add <script.jet> to lift its inline deps)",
        headline: false,
    },
    CommandSpec {
        name: "lock",
        summary: "resolve a manifest-less script's inline `use pkg#version;` deps and write its .lock sidecar (D-JPK-SCRIPTDEP1)",
        headline: false,
    },
    CommandSpec {
        name: "store",
        summary: "inspect or verify the package store",
        headline: false,
    },
    CommandSpec {
        name: "config",
        summary: "manage jet configuration (`config trust add/list/remove`, U19)",
        headline: false,
    },
    CommandSpec {
        name: "gc",
        summary: "remove unreferenced store entries",
        headline: false,
    },
    CommandSpec {
        name: "outdated",
        summary: "report Jetpack channel refs with newer locks available",
        headline: false,
    },
    CommandSpec {
        name: "search",
        summary: "search the local offline Jetpack package index",
        headline: false,
    },
    CommandSpec {
        name: "info",
        summary: "show local offline Jetpack package metadata",
        headline: false,
    },
    CommandSpec {
        name: "logs",
        summary: "show latest Jetpack build logs",
        headline: false,
    },
    CommandSpec {
        name: "clean",
        summary: "optimize and collect stale Jetpack hangar entries",
        headline: false,
    },
    CommandSpec {
        name: "publish",
        summary: "publish the current package to the registry",
        headline: false,
    },
    CommandSpec {
        name: "yank",
        summary: "mark a published version as yanked (D-VERSION1)",
        headline: false,
    },
    CommandSpec {
        name: "keygen",
        summary: "create the Ed25519 key that signs published packages (D-PKGSIGN1)",
        headline: false,
    },
    CommandSpec {
        name: "key",
        summary: "manage the package signing key (key backup)",
        headline: false,
    },
    CommandSpec {
        name: "schema",
        summary: "inspect or re-baseline @PublishedSchema snapshots (status | squash)",
        headline: false,
    },
    CommandSpec {
        name: "semindex",
        summary: "query the stable semantic index for a project entry file",
        headline: false,
    },
    CommandSpec {
        name: "dossier",
        summary: "explain a file or symbol through stable semantic fact lenses",
        headline: false,
    },
    CommandSpec {
        name: "impact",
        summary: "report blast radius for a symbol (callers, references, callees)",
        headline: false,
    },
    CommandSpec {
        name: "codemod",
        summary: "dry-run, apply, or undo replayable semantic codemods",
        headline: false,
    },
    CommandSpec {
        name: "expand",
        summary: "print sema's facts for one lens (--facts <lens>) or every lens (D-EXPANDCLI1)",
        headline: false,
    },
    CommandSpec {
        name: "vendor",
        summary: "copy all dependencies into vendor/",
        headline: false,
    },
    CommandSpec {
        name: "audit",
        summary: "check dependencies against the advisory database",
        headline: false,
    },
    CommandSpec {
        name: "sbom",
        summary: "emit a software bill of materials from the lockfile",
        headline: false,
    },
    CommandSpec {
        name: "emit",
        summary: "emit generated output (--rust: print Rust source)",
        headline: false,
    },
    CommandSpec {
        name: "eval",
        summary: "evaluate a pure Jet program to stable JSON (--pure required)",
        headline: false,
    },
    CommandSpec {
        name: "bench",
        summary: "benchmark a Jet program with honest stats",
        headline: false,
    },
    CommandSpec {
        name: "completions",
        summary: "print shell completions (bash | zsh | fish)",
        headline: false,
    },
    CommandSpec {
        name: "man",
        summary: "print the jet man page (roff)",
        headline: false,
    },
    CommandSpec {
        name: "lsp",
        summary: "language server (stdio JSON-RPC)",
        headline: false,
    },
    CommandSpec {
        name: "version",
        summary: "print compiler version",
        headline: false,
    },
    CommandSpec {
        name: "upgrade",
        summary: "how to download a newer release",
        headline: false,
    },
    CommandSpec {
        name: "help",
        summary: "print the help text",
        headline: false,
    },
];

/// Every global flag the driver understands. Used to flag-check and to suggest
/// on a typo (E2102), and to complete after `--`.
pub const FLAGS: &[FlagSpec] = &[
    FlagSpec { long: "--json", help: "emit machine-readable diagnostics" },
    FlagSpec { long: "--color", help: "color: auto | always | never" },
    FlagSpec { long: "--version", help: "print compiler version" },
    FlagSpec { long: "--emit-rust", help: "also print the generated Rust code" },
    FlagSpec { long: "--check", help: "with fmt: exit 1 if the file would change" },
    FlagSpec { long: "--small", help: "with build/run: smallest binary (S15)" },
    FlagSpec { long: "--locked", help: "with fetch: verify only, refuse network" },
    FlagSpec { long: "--annotated", help: "with new: include commented example deps" },
    FlagSpec { long: "--force", help: "with publish: bypass pre-publish gate (with warning)" },
    FlagSpec { long: "--message", help: "with yank: human-readable reason for yanking the version" },
    FlagSpec { long: "--before", help: "with schema squash: re-baseline migrations before this version" },
    FlagSpec { long: "--spdx", help: "with sbom: emit SPDX tag-value format (default)" },
    FlagSpec { long: "--cyclonedx", help: "with sbom: emit CycloneDX JSON format" },
    FlagSpec { long: "--advisory-db", help: "with audit: path to advisory database file" },
    FlagSpec { long: "--vendor-dir", help: "with vendor: directory to copy dependencies into (default vendor/)" },
    FlagSpec { long: "--sbom", help: "with build: also write an SPDX SBOM next to the binary" },
    FlagSpec { long: "--verbose", help: "with build: print the bridge steps" },
    FlagSpec { long: "--online", help: "with doctor: allow network checks" },
    FlagSpec { long: "--fix", help: "with doctor: apply auto-fixable problems" },
    FlagSpec { long: "--dry-run", help: "with fix: show changes without writing" },
    FlagSpec { long: "--try-anyway", help: "with dev: interpret past unsupported features (no guarantees)" },
    FlagSpec { long: "--restart", help: "with dev/serve: always rerun from scratch on save (c77)" },
    FlagSpec { long: "--swap", help: "with dev/serve: hot-swap type-stable edits, restart on type change (c77)" },
    FlagSpec { long: "--watch", help: "with dev/serve: --watch=off runs once and exits (c77)" },
    // E2-M18 REPL flags.
    FlagSpec { long: "--project", help: "with repl: load pkg.jet from this directory for import context (D-REPL10)" },
    // E2-M16 flags.
    FlagSpec { long: "--pure", help: "with eval: require the program to be pure (S60 / D-PURE2)" },
    FlagSpec { long: "--freestanding", help: "with build/run: no OS; rejects std-only APIs (E2-M15)" },
    // D-CTEFFECT1: comptime effect tier gate.
    FlagSpec { long: "--allow-impure", help: "with build/run: allow Tier-2 ambient comptime effects inside #Impure gates (D-CTEFFECT1)" },
    FlagSpec { long: "--target", help: "with build: cross-compile for a rustc target triple (E2-M15)" },
    FlagSpec {
        long: "--explain-partition",
        help: "with build --target=web: print the JS/WASM partition report (D-WASM1)",
    },
    // E2-M11 flags.
    FlagSpec { long: "--capabilities-json", help: "with build: emit capability summary as JSON (D-TOOL5)" },
    FlagSpec { long: "--update-snapshots", help: "with test: update snapshot golden files (D-TOOL4)" },
    FlagSpec { long: "--coverage", help: "with test: report per-function / per-line coverage (D-COV1)" },
    FlagSpec { long: "--rust", help: "with emit: print the generated Rust source (D-TOOL3)" },
    FlagSpec { long: "-u", help: "short form of --update-snapshots" },
    // D-BUILDPROFILE1 (ratified 2026-06-25): named build profiles.
    FlagSpec { long: "--release", help: "with build/run: use the release profile (D-BUILDPROFILE1)" },
    FlagSpec { long: "--profile", help: "with build/run: named build profile --profile=<name> (D-BUILDPROFILE1)" },
    // D-A11YGATE1=B (c134 Phase 6): accessibility is an opt-in lint category.
    FlagSpec { long: "--a11y", help: "with lint: check accessibility — missing roles, unlabeled controls (D-A11YGATE1)" },
    FlagSpec { long: "--scope", help: "with trust grant: grant scope, user or repo (D-JPK-GRANTCMD1)" },
];

/// Is `name` a built-in command?
pub fn is_builtin(name: &str) -> bool {
    COMMANDS.iter().any(|c| c.name == name)
        // E0043 teaching path: `jet install` is intentionally not advertised in
        // help/completions, but dispatch must reach its bespoke "use fetch"
        // diagnostic instead of generic unknown-command E2101.
        || name == "install"
}

/// Commands that own a bespoke flag vocabulary or forward flags downstream.
/// Main dispatch still reads the command set from `COMMANDS`; this only decides
/// whether the generic E2102 checker should run.
pub fn owns_flag_vocabulary(name: &str) -> bool {
    matches!(
        name,
        "env"
            | "dev"
            | "devtools"
            | "serve"
            | "push"
            | "trust"
            | "bridge"
            | "services"
            | "image"
            | "os"
            | "add"
            | "remove"
            | "bind"
            | "lsp"
            | "store"
            | "config"
            | "update"
            | "outdated"
            | "search"
            | "info"
            | "explain"
            | "logs"
            | "clean"
            | "fetch"
            | "publish"
            | "yank"
            | "keygen"
            | "key"
            | "vendor"
            | "audit"
            | "sbom"
            | "repl"
            | "schema"
            | "semindex"
            | "dossier"
            | "impact"
            | "codemod"
            | "expand"
    )
}

/// Is `flag` (e.g. `--json` or `--color=always`) a known flag?
pub fn is_known_flag(flag: &str) -> bool {
    let head = flag.split('=').next().unwrap_or(flag);
    FLAGS.iter().any(|f| f.long == head)
}

/// Levenshtein edit distance — the same shape used by sema's S14 suggestions.
pub fn edit_distance(a: &str, b: &str) -> usize {
    let a: Vec<char> = a.chars().collect();
    let b: Vec<char> = b.chars().collect();
    let mut prev: Vec<usize> = (0..=b.len()).collect();
    for i in 1..=a.len() {
        let mut cur = vec![i];
        for j in 1..=b.len() {
            let cost = if a[i - 1] == b[j - 1] { 0 } else { 1 };
            cur.push((prev[j] + 1).min(cur[j - 1] + 1).min(prev[j - 1] + cost));
        }
        prev = cur;
    }
    prev[b.len()]
}

/// Closest built-in command to `name` within edit distance 3, or `None`.
pub fn closest_command(name: &str) -> Option<&'static str> {
    closest(name, COMMANDS.iter().map(|c| c.name))
}

/// Closest known flag to `flag` within edit distance 3, or `None`.
pub fn closest_flag(flag: &str) -> Option<&'static str> {
    let head = flag.split('=').next().unwrap_or(flag);
    closest(head, FLAGS.iter().map(|f| f.long))
}

fn closest<'a, I: Iterator<Item = &'a str>>(needle: &str, hay: I) -> Option<&'a str> {
    let mut best: Option<(&str, usize)> = None;
    for cand in hay {
        let d = edit_distance(needle, cand);
        if best.map(|(_, bd)| d < bd).unwrap_or(true) {
            best = Some((cand, d));
        }
    }
    // Cap: only suggest when reasonably close (allow ~half the word length).
    best.filter(|(c, d)| *d <= 3 && *d <= c.len())
        .map(|(c, _)| c)
}

// ──────────────────────────────────────────────
// Generators (hand-rolled — invariant I6, no clap_complete)
// ──────────────────────────────────────────────

/// bash completion script for `jet`.
pub fn completions_bash() -> String {
    let cmds = COMMANDS
        .iter()
        .map(|c| c.name)
        .collect::<Vec<_>>()
        .join(" ");
    let flags = FLAGS.iter().map(|f| f.long).collect::<Vec<_>>().join(" ");
    format!(
        "# bash completion for {bin} (generated by `{bin} completions bash`)\n\
_{bin}() {{\n\
    local cur prev cmds flags\n\
    COMPREPLY=()\n\
    cur=\"${{COMP_WORDS[COMP_CWORD]}}\"\n\
    cmds=\"{cmds}\"\n\
    flags=\"{flags}\"\n\
    if [[ \"$cur\" == -* ]]; then\n\
        COMPREPLY=( $(compgen -W \"$flags\" -- \"$cur\") )\n\
        return 0\n\
    fi\n\
    if [[ $COMP_CWORD -eq 1 ]]; then\n\
        COMPREPLY=( $(compgen -W \"$cmds\" -- \"$cur\") )\n\
        return 0\n\
    fi\n\
    COMPREPLY=( $(compgen -f -- \"$cur\") )\n\
}}\n\
complete -F _{bin} {bin}\n",
        bin = BINARY_NAME,
        cmds = cmds,
        flags = flags,
    )
}

/// zsh completion script for `jet`.
pub fn completions_zsh() -> String {
    let mut cmd_lines = String::new();
    for c in COMMANDS {
        cmd_lines.push_str(&format!("        '{}:{}'\n", c.name, escape_zsh(c.summary)));
    }
    let mut flag_lines = String::new();
    for f in FLAGS {
        flag_lines.push_str(&format!("        '{}[{}]'\n", f.long, escape_zsh(f.help)));
    }
    format!(
        "#compdef {bin}\n\
# zsh completion for {bin} (generated by `{bin} completions zsh`)\n\
_{bin}() {{\n\
    local -a commands flags\n\
    commands=(\n{cmds}    )\n\
    flags=(\n{flags}    )\n\
    if (( CURRENT == 2 )); then\n\
        _describe -t commands 'command' commands\n\
    else\n\
        _values 'flag' $flags\n\
        _files\n\
    fi\n\
}}\n\
_{bin} \"$@\"\n",
        bin = BINARY_NAME,
        cmds = cmd_lines,
        flags = flag_lines,
    )
}

/// fish completion script for `jet`.
pub fn completions_fish() -> String {
    let mut out = format!(
        "# fish completion for {bin} (generated by `{bin} completions fish`)\n",
        bin = BINARY_NAME
    );
    // Only complete subcommands when none has been seen yet.
    let seen = "__fish_use_subcommand";
    for c in COMMANDS {
        out.push_str(&format!(
            "complete -c {bin} -n '{seen}' -a {name} -d '{desc}'\n",
            bin = BINARY_NAME,
            seen = seen,
            name = c.name,
            desc = escape_fish(c.summary),
        ));
    }
    for f in FLAGS {
        out.push_str(&format!(
            "complete -c {bin} -l {long} -d '{desc}'\n",
            bin = BINARY_NAME,
            long = f.long.trim_start_matches("--"),
            desc = escape_fish(f.help),
        ));
    }
    out
}

/// roff man page for `jet`, section 1.
pub fn man_page(version: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        ".TH {bin_up} 1 \"\" \"{bin} {ver}\" \"Jet Manual\"\n",
        bin_up = BINARY_NAME.to_uppercase(),
        bin = BINARY_NAME,
        ver = version,
    ));
    out.push_str(".SH NAME\n");
    out.push_str(&format!(
        "{bin} \\- the Jet compiler and project tool\n",
        bin = BINARY_NAME
    ));
    out.push_str(".SH SYNOPSIS\n");
    out.push_str(&format!(
        ".B {bin}\n.RI [ command ] \" \" [ args ...]\n",
        bin = BINARY_NAME
    ));
    out.push_str(".SH DESCRIPTION\n");
    out.push_str(&format!(
        "{bin} builds, checks, runs, and tests Jet programs, and manages Jet projects \
and their dependencies. Output is plain when piped and colored on a terminal.\n",
        bin = BINARY_NAME
    ));
    out.push_str(".SH COMMANDS\n");
    for c in COMMANDS {
        out.push_str(&format!(".TP\n.B {}\n{}\n", c.name, roff_escape(c.summary)));
    }
    out.push_str(".SH FLAGS\n");
    for f in FLAGS {
        out.push_str(&format!(".TP\n.B {}\n{}\n", f.long, roff_escape(f.help)));
    }
    out.push_str(".SH FILES\n");
    out.push_str(&format!(
        ".TP\n.B {manifest}\nThe project manifest.\n",
        manifest = crate::Syntax::PAYLOAD_FILE
    ));
    out.push_str(".SH SEE ALSO\n");
    out.push_str(&format!("{bin}-explain(1)\n", bin = BINARY_NAME));
    out
}

fn escape_zsh(s: &str) -> String {
    s.replace('\'', "'\\''")
        .replace(':', "\\:")
        .replace('[', "\\[")
        .replace(']', "\\]")
}
fn escape_fish(s: &str) -> String {
    s.replace('\'', "\\'")
}
fn roff_escape(s: &str) -> String {
    // Lines beginning with `'` or `.` are roff control lines; escape and also
    // neutralize backslashes.
    s.replace('\\', "\\\\")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn typo_finds_closest_command() {
        assert_eq!(closest_command("buld"), Some("build"));
        assert_eq!(closest_command("chekc"), Some("check"));
        assert_eq!(closest_command("rnu"), Some("run"));
        // Nonsense gets no suggestion.
        assert_eq!(closest_command("zxqwvbn"), None);
    }

    #[test]
    fn typo_finds_closest_flag() {
        assert_eq!(closest_flag("--jsn"), Some("--json"));
        assert_eq!(closest_flag("--colr"), Some("--color"));
    }

    #[test]
    fn known_flag_ignores_value() {
        assert!(is_known_flag("--color=always"));
        assert!(is_known_flag("--json"));
        assert!(!is_known_flag("--nonsense"));
    }

    #[test]
    fn completions_mention_every_command() {
        for shell_out in [completions_bash(), completions_zsh(), completions_fish()] {
            for c in COMMANDS {
                assert!(
                    shell_out.contains(c.name),
                    "completion missing command {}",
                    c.name
                );
            }
        }
    }

    #[test]
    fn man_mentions_every_command_and_flag() {
        let m = man_page("0.0.0");
        for c in COMMANDS {
            assert!(m.contains(c.name), "man missing command {}", c.name);
        }
        for f in FLAGS {
            assert!(m.contains(f.long), "man missing flag {}", f.long);
        }
    }
}
