//! Semantic source importer framework (D-MIGRATE-SRC1=A).
//!
//! Output is ordinary editable Jet. Unsupported source is never discarded or
//! represented by fake behavior: each gap is recorded in the omissions report.

use std::collections::BTreeSet;
use std::fs;
use std::path::{Component, Path, PathBuf};

use jet::ExitCodes;
use jet_foundation::JSON::json_escape;

const TODO_CODE: &str = "JT0101";
const HEADER: &str =
    "// Generated by jet import py (D-MIGRATE-SRC1). Editable Jet source.\n";

#[derive(Clone, Copy, PartialEq, Eq)]
enum Mode {
    Create,
    Update,
    DryRun,
}

struct Todo {
    what: String,
    why: String,
    fix: String,
    source: String,
    target: String,
    status: &'static str,
}

struct Generated {
    relative: PathBuf,
    contents: String,
}

struct Plan {
    source: PathBuf,
    target: PathBuf,
    generated: Vec<Generated>,
    todos: Vec<Todo>,
    functions: usize,
    tests: usize,
}

pub(crate) fn run(raw: &[String], json: bool) -> i32 {
    let (lang, source, mode) = match parse_args(raw) {
        Ok(args) => args,
        Err((what, fix)) => return usage_error(&what, &fix, json),
    };
    if lang != "py" {
        return usage_error(
            &format!("source importer '{lang}' is not installed"),
            "use jet import py <dir>; language importers ship as semantic translators",
            json,
        );
    }
    let cwd = match std::env::current_dir() {
        Ok(path) => path,
        Err(error) => return operation_error("read current directory", &error.to_string(), json),
    };
    let source = if source.is_absolute() {
        source
    } else {
        cwd.join(source)
    };
    let source = match source.canonicalize() {
        Ok(path) if path.is_dir() => path,
        Ok(_) => return operation_error("import Python source", "source is not a directory", json),
        Err(error) => return operation_error("import Python source", &error.to_string(), json),
    };
    let name = source
        .file_name()
        .and_then(|name| name.to_str())
        .filter(|name| !name.is_empty())
        .unwrap_or("imported");
    let target = cwd.join("jet").join(name);
    match build_plan(&source, &target) {
        Ok(plan) => apply_plan(plan, mode, json),
        Err(error) => operation_error("import Python source", &error, json),
    }
}

fn parse_args(raw: &[String]) -> Result<(String, PathBuf, Mode), (String, String)> {
    let mut positionals = Vec::new();
    let mut mode = Mode::Create;
    for arg in raw.iter().skip(1) {
        match arg.as_str() {
            "--dry-run" if mode == Mode::Create => mode = Mode::DryRun,
            "--update" if mode == Mode::Create => mode = Mode::Update,
            "--dry-run" | "--update" => {
                return Err((
                    "--dry-run and --update cannot be combined".into(),
                    "choose preview (--dry-run) or merge (--update)".into(),
                ))
            }
            value if value.starts_with('-') => {
                return Err((
                    format!("'{value}' is not an import flag"),
                    "use jet import py <dir> [--dry-run|--update]".into(),
                ))
            }
            value => positionals.push(value.to_string()),
        }
    }
    if positionals.len() != 2 {
        return Err((
            "source import needs a language and directory".into(),
            "use jet import py <dir> [--dry-run|--update]".into(),
        ));
    }
    Ok((
        positionals.remove(0),
        PathBuf::from(positionals.remove(0)),
        mode,
    ))
}

fn build_plan(source: &Path, target: &Path) -> Result<Plan, String> {
    let mut files = Vec::new();
    collect_python(source, source, &mut files)?;
    if files.is_empty() {
        return Err(format!("no .py files found under {}", source.display()));
    }
    files.sort();
    let mut plan = Plan {
        source: source.to_path_buf(),
        target: target.to_path_buf(),
        generated: Vec::new(),
        todos: Vec::new(),
        functions: 0,
        tests: 0,
    };
    for path in files {
        let relative = path.strip_prefix(source).map_err(|e| e.to_string())?;
        let mut output = relative.to_path_buf();
        output.set_extension("jet");
        let raw = fs::read_to_string(&path)
            .map_err(|e| format!("read {}: {e}", path.display()))?;
        let translation = translate_file(&raw, relative, &output);
        plan.functions += translation.functions;
        plan.tests += translation.tests;
        plan.todos.extend(translation.todos);
        plan.generated.push(Generated {
            relative: output,
            contents: translation.source,
        });
    }
    Ok(plan)
}

fn collect_python(root: &Path, dir: &Path, out: &mut Vec<PathBuf>) -> Result<(), String> {
    let mut entries = fs::read_dir(dir)
        .map_err(|e| format!("read {}: {e}", dir.display()))?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| format!("read {}: {e}", dir.display()))?;
    entries.sort_by_key(|entry| entry.file_name());
    for entry in entries {
        let ty = entry.file_type().map_err(|e| e.to_string())?;
        let path = entry.path();
        if ty.is_symlink() {
            continue;
        }
        if ty.is_dir() {
            collect_python(root, &path, out)?;
        } else if ty.is_file() && path.extension().and_then(|v| v.to_str()) == Some("py") {
            let relative = path.strip_prefix(root).map_err(|e| e.to_string())?;
            if relative.components().any(|part| {
                matches!(
                    part,
                    Component::ParentDir | Component::RootDir | Component::Prefix(_)
                )
            }) {
                return Err(format!("unsafe source path {}", relative.display()));
            }
            out.push(path);
        }
    }
    Ok(())
}

struct Translation {
    source: String,
    todos: Vec<Todo>,
    functions: usize,
    tests: usize,
}

struct Function {
    name: String,
    params: Vec<(String, String)>,
    result: String,
    body: Vec<(usize, String)>,
}

fn translate_file(raw: &str, source: &Path, target: &Path) -> Translation {
    let lines: Vec<&str> = raw.lines().collect();
    let mut rendered = Vec::new();
    let mut todos = Vec::new();
    let mut functions = 0;
    let mut tests = 0;
    let mut at = 0;
    while at < lines.len() {
        let line = lines[at];
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            at += 1;
            continue;
        }
        if indentation(line) != 0 || !trimmed.starts_with("def ") {
            todos.push(gap(
                format!("unsupported Python top-level construct '{}'", shorten(trimmed)),
                "first Python importer translates annotated functions only",
                "port construct into ordinary Jet; no source was silently emitted",
                source,
                target,
                at + 1,
            ));
            at += 1;
            continue;
        }
        let header_line = at + 1;
        let parsed = parse_header(trimmed);
        at += 1;
        let mut body = Vec::new();
        while at < lines.len() {
            if !lines[at].trim().is_empty() && indentation(lines[at]) == 0 {
                break;
            }
            if !lines[at].trim().is_empty() {
                body.push((at + 1, lines[at].to_string()));
            }
            at += 1;
        }
        let Ok((name, params, result)) = parsed else {
            todos.push(gap(
                format!("Python function signature at line {header_line} is not type-safe"),
                parsed.unwrap_err(),
                "add supported parameter and return annotations, then rerun import",
                source,
                target,
                header_line,
            ));
            continue;
        };
        let function = Function {
            name,
            params,
            result,
            body,
        };
        match translate_body(&function) {
            Ok(body) => {
                let marker = if function.name.starts_with("test_") && function.params.is_empty() {
                    tests += 1;
                    "@Test "
                } else {
                    ""
                };
                rendered.push(render_function(marker, &function, &body));
                functions += 1;
            }
            Err((line, reason)) => todos.push(gap(
                format!("Python body '{}' was not translated", function.name),
                reason,
                "port body into ordinary Jet; source remains in omissions report",
                source,
                target,
                line,
            )),
        }
    }
    let mut output = String::from(HEADER);
    for item in rendered {
        output.push_str(&item);
        output.push('\n');
    }
    if functions == 0 {
        output.push_str("// No construct was safe to translate. See import-report.json.\n");
    }
    Translation {
        source: output,
        todos,
        functions,
        tests,
    }
}

fn parse_header(line: &str) -> Result<(String, Vec<(String, String)>, String), String> {
    let body = line
        .strip_prefix("def ")
        .and_then(|value| value.strip_suffix(':'))
        .ok_or_else(|| "expected def name(args) -> Type:".to_string())?;
    let open = body.find('(').ok_or_else(|| "function needs (".to_string())?;
    let close = body.rfind(')').ok_or_else(|| "function needs )".to_string())?;
    let name = body[..open].trim();
    if close < open || !identifier(name) {
        return Err("function name is not a safe Jet identifier".into());
    }
    let result = body[close + 1..]
        .trim()
        .strip_prefix("->")
        .ok_or_else(|| "function needs a return annotation".to_string())?;
    let result = map_type(result.trim())?;
    let mut params = Vec::new();
    let raw_params = body[open + 1..close].trim();
    if !raw_params.is_empty() {
        for raw in split_commas(raw_params) {
            let (param, ty) = raw
                .split_once(':')
                .ok_or_else(|| format!("parameter {raw} needs a type annotation"))?;
            let param = param.trim();
            if !identifier(param) || param == "self" || param.contains('=') {
                return Err(format!("parameter {param} has no safe importer mapping"));
            }
            params.push((param.to_string(), map_type(ty.trim())?));
        }
    }
    Ok((name.to_string(), params, result))
}

fn map_type(ty: &str) -> Result<String, String> {
    match ty {
        "int" => Ok("Int".into()),
        "float" => Ok("Float".into()),
        "str" => Ok("String".into()),
        "bool" => Ok("Bool".into()),
        "None" => Ok("Void".into()),
        _ => Err(format!("Python type {ty} has no proven Jet mapping")),
    }
}

fn split_commas(raw: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let mut start = 0;
    let mut depth = 0;
    for (index, ch) in raw.char_indices() {
        match ch {
            '(' | '[' => depth += 1,
            ')' | ']' => depth -= 1,
            ',' if depth == 0 => {
                out.push(raw[start..index].trim());
                start = index + 1;
            }
            _ => {}
        }
    }
    out.push(raw[start..].trim());
    out
}

fn translate_body(function: &Function) -> Result<Vec<String>, (usize, String)> {
    if function.body.is_empty() {
        return Err((1, "function body is empty".into()));
    }
    let base = function
        .body
        .iter()
        .map(|(_, line)| indentation(line))
        .min()
        .unwrap_or(0);
    let mut bindings = BTreeSet::new();
    let mut output = Vec::new();
    for (line_no, raw) in &function.body {
        if indentation(raw) != base {
            return Err((
                *line_no,
                "nested control flow has no proven equivalent in this importer".into(),
            ));
        }
        let line = raw.trim();
        if line == "pass" && function.result == "Void" {
            continue;
        }
        if let Some(value) = line.strip_prefix("return ") {
            output.push(format!(
                "return {}",
                parse_expression(value).map_err(|why| (*line_no, why))?
            ));
            continue;
        }
        if line == "return" && function.result == "Void" {
            output.push("return".into());
            continue;
        }
        if let Some(value) = line.strip_prefix("assert ") {
            let (left, right) = split_top(value, "==").ok_or_else(|| {
                (
                    *line_no,
                    "only equality assertions have a proven Jet test mapping".into(),
                )
            })?;
            output.push(format!(
                "require_eq({}, {})",
                parse_expression(left).map_err(|why| (*line_no, why))?,
                parse_expression(right).map_err(|why| (*line_no, why))?
            ));
            continue;
        }
        if let Some((name, value)) = assignment(line) {
            if !identifier(name) {
                return Err((*line_no, "assignment target is not a local name".into()));
            }
            let value = parse_expression(value).map_err(|why| (*line_no, why))?;
            let operator = if bindings.insert(name.to_string()) {
                ":="
            } else {
                "="
            };
            output.push(format!("{name} {operator} {value}"));
            continue;
        }
        output.push(parse_expression(line).map_err(|why| (*line_no, why))?);
    }
    Ok(output)
}

#[derive(Clone)]
enum Token {
    Word(String),
    Number(String),
    Text(String),
    Op(String),
    Open,
    Close,
    Comma,
}

fn parse_expression(raw: &str) -> Result<String, String> {
    let tokens = lex(raw)?;
    if tokens.is_empty() {
        return Err("empty expression".into());
    }
    let mut depth = 0;
    let mut expect_value = true;
    let mut output = String::new();
    for token in tokens {
        match token {
            Token::Word(word) => {
                if !expect_value && !matches!(word.as_str(), "and" | "or") {
                    return Err(format!("unsupported expression near {word}"));
                }
                let word = match word.as_str() {
                    "True" => "true",
                    "False" => "false",
                    "and" => "&&",
                    "or" => "||",
                    "None" => return Err("None needs an explicit Option mapping".into()),
                    _ => word.as_str(),
                };
                push_piece(&mut output, word);
                expect_value = matches!(word, "&&" | "||");
            }
            Token::Number(value) | Token::Text(value) => {
                if !expect_value {
                    return Err("two adjacent expression values".into());
                }
                push_piece(&mut output, &value);
                expect_value = false;
            }
            Token::Op(op) => {
                if expect_value && op != "-" && op != "!" {
                    return Err(format!("operator {op} needs a left operand"));
                }
                push_piece(&mut output, &op);
                expect_value = true;
            }
            Token::Open => {
                output.push('(');
                depth += 1;
                expect_value = true;
            }
            Token::Close => {
                if depth == 0 || expect_value {
                    return Err("unbalanced expression parentheses".into());
                }
                output.push(')');
                depth -= 1;
                expect_value = false;
            }
            Token::Comma => {
                if depth == 0 || expect_value {
                    return Err("comma outside a call".into());
                }
                output.push_str(", ");
                expect_value = true;
            }
        }
    }
    if depth != 0 || expect_value {
        return Err("incomplete expression".into());
    }
    Ok(output)
}

fn lex(raw: &str) -> Result<Vec<Token>, String> {
    let bytes = raw.as_bytes();
    let mut out = Vec::new();
    let mut at = 0;
    while at < bytes.len() {
        if bytes[at].is_ascii_whitespace() {
            at += 1;
            continue;
        }
        let start = at;
        if bytes[at].is_ascii_alphabetic() || bytes[at] == b'_' {
            at += 1;
            while at < bytes.len()
                && (bytes[at].is_ascii_alphanumeric() || bytes[at] == b'_')
            {
                at += 1;
            }
            out.push(Token::Word(raw[start..at].to_string()));
        } else if bytes[at].is_ascii_digit() {
            at += 1;
            while at < bytes.len() && (bytes[at].is_ascii_digit() || bytes[at] == b'.') {
                at += 1;
            }
            out.push(Token::Number(raw[start..at].to_string()));
        } else if matches!(bytes[at], b'\'' | b'"') {
            let quote = bytes[at];
            at += 1;
            let content = at;
            while at < bytes.len() && bytes[at] != quote {
                if bytes[at] == b'\\' {
                    at += 1;
                }
                at += 1;
            }
            if at >= bytes.len() {
                return Err("unterminated Python string".into());
            }
            let value = raw[content..at].replace('"', "\\\"");
            at += 1;
            out.push(Token::Text(format!("\"{value}\"")));
        } else {
            let two = raw.get(at..at + 2).unwrap_or("");
            if matches!(two, "==" | "!=" | "<=" | ">=") {
                out.push(Token::Op(two.into()));
                at += 2;
                continue;
            }
            out.push(match bytes[at] as char {
                '(' => Token::Open,
                ')' => Token::Close,
                ',' => Token::Comma,
                '+' | '-' | '*' | '/' | '%' | '<' | '>' => {
                    Token::Op((bytes[at] as char).to_string())
                }
                other => return Err(format!("unsupported Python expression token {other}")),
            });
            at += 1;
        }
    }
    Ok(out)
}

fn push_piece(output: &mut String, piece: &str) {
    if !output.is_empty() && !output.ends_with(['(', ' ']) {
        output.push(' ');
    }
    output.push_str(piece);
}

fn render_function(marker: &str, function: &Function, body: &[String]) -> String {
    let params = function
        .params
        .iter()
        .map(|(name, ty)| format!("{name}: {ty}"))
        .collect::<Vec<_>>()
        .join(", ");
    let result = if function.result == "Void" {
        String::new()
    } else {
        format!(" -> {}", function.result)
    };
    let mut output = format!("{marker}fn {}({params}){result} {{\n", function.name);
    for line in body {
        output.push_str("    ");
        output.push_str(line);
        output.push('\n');
    }
    output.push_str("}\n");
    output
}

fn apply_plan(plan: Plan, mode: Mode, json: bool) -> i32 {
    let report = report(&plan);
    let baseline_root = plan.target.join(".jet-import/baseline");
    let mut writes = Vec::new();
    let mut conflicts = Vec::new();
    for generated in &plan.generated {
        let target = plan.target.join(&generated.relative);
        let baseline = baseline_root.join(&generated.relative);
        let existing = fs::read_to_string(&target).ok();
        let prior = fs::read_to_string(&baseline).ok();
        match (mode, existing.as_deref(), prior.as_deref()) {
            (Mode::DryRun, _, _) => {}
            (_, None, _) => writes.push((target.clone(), generated.contents.clone())),
            (_, Some(current), _) if current == generated.contents => {}
            (Mode::Create, Some(_), _) => conflicts.push(target),
            (Mode::Update, Some(current), Some(old)) if current == old => {
                writes.push((target, generated.contents.clone()))
            }
            (Mode::Update, Some(_), Some(old)) if generated.contents == old => {}
            (Mode::Update, Some(_), _) => conflicts.push(target),
        }
        if mode != Mode::DryRun && prior.as_deref() != Some(generated.contents.as_str()) {
            writes.push((baseline, generated.contents.clone()));
        }
    }
    let report_path = plan.target.join("import-report.json");
    if mode != Mode::DryRun
        && fs::read_to_string(&report_path).ok().as_deref() != Some(report.as_str())
    {
        writes.push((report_path, report.clone()));
    }
    if !conflicts.is_empty() {
        if json {
            println!(
                "{{\"code\":\"JT0199\",\"what\":\"source import conflict\",\"paths\":[{}]}}",
                conflicts
                    .iter()
                    .map(|path| format!("\"{}\"", json_escape(&path.display().to_string())))
                    .collect::<Vec<_>>()
                    .join(",")
            );
        } else {
            eprintln!("error[JT0199]: source import conflict");
            for path in conflicts {
                eprintln!("  {path}", path = path.display());
            }
            eprintln!("  why: generated source and editable Jet both changed");
            eprintln!("  fix: reconcile file, then rerun with --update");
        }
        return ExitCodes::USER_ERROR;
    }
    for (path, contents) in writes {
        if let Some(parent) = path.parent() {
            if let Err(error) = fs::create_dir_all(parent) {
                return operation_error("create import output", &error.to_string(), json);
            }
        }
        if let Err(error) = fs::write(path, contents) {
            return operation_error("write import output", &error.to_string(), json);
        }
    }
    if json {
        print!("{report}");
    } else {
        let verb = if mode == Mode::DryRun {
            "would import"
        } else {
            "imported"
        };
        println!(
            "{verb} {} -> {}",
            plan.source.display(),
            plan.target.display()
        );
        println!(
            "  {} functions, {} carried tests, {} TODO diagnostics",
            plan.functions,
            plan.tests,
            plan.todos.len()
        );
        for todo in &plan.todos {
            println!("  {TODO_CODE} {}  {}", todo.source, todo.what);
            println!("    why: {}", todo.why);
            println!("    fix: {}", todo.fix);
            println!("    target: {}  status: {}", todo.target, todo.status);
        }
    }
    ExitCodes::OK
}

fn report(plan: &Plan) -> String {
    let mut output = format!(
        "{{\"schema\":\"jet.source-import.v1\",\"language\":\"py\",\"source\":\"{}\",\"target\":\"{}\",\"summary\":{{\"files\":{},\"translated_functions\":{},\"carried_tests\":{},\"omissions\":{}}},\"omissions\":[",
        json_escape(&plan.source.display().to_string()),
        json_escape(&plan.target.display().to_string()),
        plan.generated.len(),
        plan.functions,
        plan.tests,
        plan.todos.len()
    );
    for (index, todo) in plan.todos.iter().enumerate() {
        if index > 0 {
            output.push(',');
        }
        output.push_str(&format!(
            "{{\"code\":\"{TODO_CODE}\",\"what\":\"{}\",\"why\":\"{}\",\"fix\":\"{}\",\"source\":\"{}\",\"generated_target\":\"{}\",\"migration_status\":\"{}\"}}",
            json_escape(&todo.what),
            json_escape(&todo.why),
            json_escape(&todo.fix),
            json_escape(&todo.source),
            json_escape(&todo.target),
            todo.status
        ));
    }
    output.push_str("]}\n");
    output
}

fn gap(
    what: String,
    why: impl Into<String>,
    fix: impl Into<String>,
    source: &Path,
    target: &Path,
    line: usize,
) -> Todo {
    Todo {
        what,
        why: why.into(),
        fix: fix.into(),
        source: format!("{}:{line}", source.display()),
        target: target.display().to_string(),
        status: "omitted-reported",
    }
}

fn assignment(line: &str) -> Option<(&str, &str)> {
    let (left, right) = split_top(line, "=")?;
    if right.starts_with('=') || left.ends_with(['!', '<', '>']) {
        return None;
    }
    Some((left.trim(), right.trim()))
}

fn split_top<'a>(raw: &'a str, needle: &str) -> Option<(&'a str, &'a str)> {
    let bytes = raw.as_bytes();
    let needle = needle.as_bytes();
    let mut depth = 0;
    let mut quote = None;
    let mut at = 0;
    while at + needle.len() <= bytes.len() {
        if let Some(active) = quote {
            if bytes[at] == active {
                quote = None;
            } else if bytes[at] == b'\\' {
                at += 1;
            }
            at += 1;
            continue;
        }
        match bytes[at] {
            b'\'' | b'"' => quote = Some(bytes[at]),
            b'(' | b'[' => depth += 1,
            b')' | b']' => depth -= 1,
            _ => {}
        }
        if depth == 0 && &bytes[at..at + needle.len()] == needle {
            return Some((&raw[..at], &raw[at + needle.len()..]));
        }
        at += 1;
    }
    None
}

fn indentation(line: &str) -> usize {
    line.len() - line.trim_start_matches([' ', '\t']).len()
}

fn identifier(value: &str) -> bool {
    let mut chars = value.chars();
    matches!(chars.next(), Some(ch) if ch.is_ascii_alphabetic() || ch == '_')
        && chars.all(|ch| ch.is_ascii_alphanumeric() || ch == '_')
}

fn shorten(value: &str) -> String {
    if value.chars().count() <= 48 {
        value.to_string()
    } else {
        format!("{}...", value.chars().take(48).collect::<String>())
    }
}

fn usage_error(what: &str, fix: &str, json: bool) -> i32 {
    if json {
        println!(
            "{{\"code\":\"E2102\",\"what\":\"{}\",\"why\":\"D-MIGRATE-SRC1 keeps source import arguments explicit\",\"fix\":\"{}\"}}",
            json_escape(what),
            json_escape(fix)
        );
    } else {
        eprintln!("error[E2102]: {what}");
        eprintln!("  why: D-MIGRATE-SRC1 keeps source import arguments explicit");
        eprintln!("  fix: {fix}");
    }
    ExitCodes::USAGE
}

fn operation_error(what: &str, why: &str, json: bool) -> i32 {
    if json {
        println!(
            "{{\"code\":\"JT0198\",\"what\":\"{}\",\"why\":\"{}\",\"fix\":\"check source path and write permissions, then rerun\"}}",
            json_escape(what),
            json_escape(why)
        );
    } else {
        eprintln!("error[JT0198]: {what}");
        eprintln!("  why: {why}");
        eprintln!("  fix: check source path and write permissions, then rerun");
    }
    ExitCodes::USER_ERROR
}
