use crate::Syntax;

/// Canonical Core module member names (completion, help, diagnostics).
pub fn core_module_items(module: &str) -> Vec<String> {
    let normalized_module =
        Syntax::normalize_core_module(module).unwrap_or_else(|| module.to_string());
    let module = normalized_module.as_str();
    if module == "core.lang" {
        return crate::Policy::RULE_ARG_DECLARATIONS
            .iter()
            .map(|declaration| declaration.name.to_string())
            .collect();
    }
    let items: &[&str] = match module {
        "core.io" => &[
            "Reader",
            "Writer",
            "args",
            "input",
            "confirm",
            "choose",
            "input_secret",
            "read_all_input",
            "print",
            "eprint",
            "stdin",
            "stdout",
            "stderr",
            "terminal_width",
            "terminal_height",
            "style",
            "style_force",
            "progress",
        ],
        "core.env" => &["get", "set", "unset", "vars", "current_dir", "home_dir"],
        "core.os" => &[
            "name",
            "family",
            "arch",
            "cpu_count",
            "temp_dir",
            "executable",
            "pid",
            "hostname",
            "username",
            "set_current_dir",
            "on_interrupt",
        ],
        "core.process" => &["exit", "run", "cmd", "pipeline"],
        "core.math" => &[
            "sqrt",
            "pow",
            "abs",
            "min",
            "max",
            "floor",
            "ceil",
            "round",
            "pi",
            "e",
            "tau",
            "infinity",
            "nan",
            "clamp",
            "sin",
            "cos",
            "tan",
            "asin",
            "acos",
            "atan",
            "atan2",
            "sinh",
            "cosh",
            "tanh",
            "exp",
            "decimal",
            "ln",
            "log2",
            "log10",
            "hypot",
            "trunc",
            "fract",
            "sign",
            "is_nan",
            "is_inf",
            "is_finite",
            "to_bits",
            "from_bits",
            "degrees",
            "radians",
            "lerp",
            "checked_add",
            "checked_sub",
            "checked_mul",
            "checked_pow",
            "saturating_add",
            "saturating_sub",
            "saturating_mul",
            "wrapping_add",
            "wrapping_sub",
            "wrapping_mul",
            "int_pow",
            "gcd",
            "lcm",
        ],
        // D-DET1: `rng` builds a deterministic injected RNG capability.
        // D-RANDSPLIT1=A: `bytes(n)` returns n PRNG bytes — fast, NOT crypto-safe.
        "core.random" => &[
            "int",
            "float",
            "float_range",
            "bool",
            "normal",
            "exponential",
            "pick",
            "weighted_pick",
            "sample",
            "shuffle",
            "seed",
            "rng",
            "split",
            "bytes",
        ],
        // D-RANDSPLIT1=A: CSPRNG namespace — cryptographically secure random bytes.
        "core.crypto.random" => &["bytes"],
        "core.time" => &[
            "now",
            "sleep",
            "milliseconds",
            "seconds",
            "minutes",
            "hours",
            "start",
            "instant",
            "now_utc",
            "from_unix_ms",
            "today",
            "parse_rfc3339",
            "local_time",
            "parse_time",
            "period",
            "period_days",
            "period_months",
            "period_years",
            "zone",
            "utc",
            "zoned",
            "zoned_local",
        ],
        // D-ENC1: unified serialization. `core.encoding` is the library root (no direct
        // verbs — formats are submodules); each format submodule carries the verbs.
        "core.encoding" => &[
            "DataTree",
            "EncodingLimits",
            "EncodingError",
            "EncodingCause",
            "EncodingFormat",
            "EncodingErrorKind",
            "DataEvent",
        ],
        // D-JSONVERB1: `to_string`/`to_string_pretty` (compact/pretty); `parse` → dynamic
        // JSON value; `decode` → lenient typed decode (D-JSON3). D-MIGRATE3=A:
        // `decode_traced<T>` rides alongside `decode` on every format.
        "core.encoding.json" => &[
            "JSONReader",
            "JSONWriter",
            "parse",
            "decode",
            "decode_traced",
            "to_string",
            "to_string_pretty",
            "canonical",
            "events",
            "reader",
            "writer",
        ],
        "core.encoding.jsonl" => &[
            "JSONLReader",
            "JSONLWriter",
            "parse",
            "to_string",
            "reader",
            "writer",
        ],
        // D-SERDE6: typed `decode<T>` rides every format submodule alongside `parse`.
        "core.encoding.csv" => &[
            "CSVReader",
            "CSVWriter",
            "parse",
            "decode",
            "decode_traced",
            "to_string",
            "reader",
            "writer",
        ],
        "core.encoding.toml" => &["parse", "decode", "decode_traced", "to_string"],
        "core.encoding.yaml" => &["parse", "decode", "decode_traced", "to_string"],
        "core.encoding.xml" => &[
            "XMLLimits", "XMLParseOptions", "XMLRenderOptions", "XMLEncoding",
            "XMLLexicalPolicy", "XMLCanonical", "XMLCanonicalMode", "XMLError", "XMLReason", "XMLEntityPolicy",
            "parse", "parse_with", "parse_bytes", "to_string", "to_bytes", "canonical",
            "decode", "decode_bytes", "root", "expanded_name", "attribute", "content",
            "reader", "writer", "XMLReader", "XMLWriter",
        ],
        "core.encoding.cbor" => &[
            "CBOROptions", "CBORError", "CBORErrorKind", "CBORReader", "CBORWriter",
            "parse", "decode", "to_bytes", "to_bytes_canonical", "reader", "writer",
        ],
        // D-UUIDENC1=A: hex/base64 codecs and UUID generator.
        "core.encoding.hex" => &["encode", "decode"],
        "core.encoding.base64" => &["encode", "decode", "encode_url", "decode_url"],
        "core.encoding.base32" => &["encode", "decode"],
        // D-TEXTUNICODE1: std-only Unicode scalar helpers.
        "core.text.unicode" => &[
            "scalar_count",
            "byte_count",
            "is_ascii",
            "lower",
            "upper",
            "scalars",
        ],
        "core.uuid" => &["v4", "v7"],
        "core.mem" => &[
            "Ptr",
            "from_addr",
            "volatile_read",
            "volatile_write",
            "address_of",
            // D-PIN1=A: the address-stability contract.
            "pin",
            "Pin",
            "Arena",
            "Bump",
            "Pool",
            "Fixed",
        ],
        // D-ALLOC-C (ratified 2026-06-19): wider allocator API bucket.
        "core.mem.alloc" => &["Arena", "Bump", "Pool", "Fixed"],
        "core.solve" => &["Solver"],
        "core.game" => &["Scene", "Replay", "Backend", "run"],
        "core.data" => &[
            "csv",
            "json",
            "csv_reader",
            "json_reader",
            "DataLimits",
            "DataError",
            "DataErrorKind",
            "DataStream",
            "DataPivotCell",
            "count",
            "table",
            "rows",
            "series",
            "values",
            "schema",
            "missing_count",
            "lazy",
            "lazy_filter",
            "lazy_sort_by",
            "collect",
            "plan",
            "filter",
            "sort_by",
            "inner_join",
            "left_join",
            "pivot_sum",
            "sum",
            "mean",
            "min",
            "max",
            "median",
            "quantile",
            "rolling_mean",
            "variance",
            "stddev",
            "describe",
            "group_count",
            "group_sum",
            "group_mean",
            "status",
            "require_bridge",
            "bar_text",
            "bar_svg",
            "line_text",
            "line_svg",
        ],
        // D-COMPUTE1=D / D-COMPUTE-TYPE1=D (#443): one compute family; Tensor owns storage.
        "core.compute" => &[
            "zeros",
            "ones",
            "full",
            "from_list",
            "matrix",
            "vec",
            "add",
            "mul",
            "sub",
            "div",
            "maximum",
            "minimum",
            "matmul",
            "matmul_f32_tile",
            "eye",
            "det",
            "inv",
            "solve",
            "fft",
            "reshape",
            "broadcast_to",
            "transpose",
            "sum_axis",
            "negate",
            "abs",
            "exp",
            "log",
            "sqrt",
            "get",
            "set",
            "shape",
            "rank",
            "numel",
            "to_list",
            "device",
            "placement",
            "on_device",
            "device_cpu",
            "device_auto",
            "stream_new",
            "stream_sync",
            "stream_show",
            "transfer",
            "transfer_show",
            "kernel_bounds_ok",
            "jvp_add",
            "jvp_mul",
            "jvp_matmul",
            "vjp_add",
            "vjp_mul",
            "vjp_matmul",
            "value_and_grad_mul",
            "grad_value",
            "grad_a",
            "grad_b",
            "grad_show",
            "mse_loss",
            "sgd_step",
            "serialize",
            "deserialize",
            "to_sparse",
            "sparse_nnz",
            "sparse_mv",
            "sparse_show",
            "profile_f32_strict",
            "profile_show",
            "Tensor",
            "SparseTensor",
            "GradTriple",
            "ComputeStream",
            "ComputeError",
            "ComputeDevice",
        ],
        // D-SERVICE1=D: structured service tree over taskgroups.
        "core.services" => &[
            "tree",
            "worker",
            "group",
            "start",
            "stop",
            "send",
            "send_durable",
            "receive",
            "mailbox_depth",
            "fail_worker",
            "restarts",
            "set_restart",
            "set_delivery",
            "restart_one_for_one",
            "restart_one_for_all",
            "restart_rest_for_one",
            "delivery_at_most_once",
            "delivery_durable",
            "dead_letter_count",
            "drain_dead_letters",
            "set_state_empty",
            "set_state_snapshot",
            "set_state_event_log",
            "commit_snapshot",
            "restore_snapshot",
            "append_event",
            "event_count",
            "replay_events",
            "workflow_start",
            "workflow_step",
            "workflow_history",
            "directory_register",
            "directory_resolve",
            "directory_generation",
            "drain_worker",
            "handoff_generation",
            "rollback_generation",
            "upgrade_receipt",
            "chaos_fail",
            "observe",
            "endpoint_show",
            "tree_show",
            "runtime",
            "state_store",
            "ServiceRuntime",
            "ServiceStateStore",
            "ServiceReceipt",
            "ServiceUpgradeReceipt",
            "ServiceTree",
            "ServiceEndpoint",
            "ServiceError",
            "ServiceRestart",
            "ServiceDelivery",
        ],
        "core.tasks" => &["spawn", "spawn_group", "join_all", "channel", "after", "interval"],
        "core.testing" => &[
            "snap",
            "golden",
            "fixture",
            "temp_dir",
            "corpus",
            "fake_clock",
            "fake_rng",
        ],
        // D-FILES-WRITE1 (merge, was `core.fs` + `core.files`): one module for
        // both whole-file convenience helpers and streaming handle constructors.
        // D-FILES-APPEND1=A: whole-file one-shot append is `append_all`, kept
        // distinct from the streaming handle's `.append(text)` method.
        "core.files" => &[
            "read",
            "read_bytes",
            "write",
            "append_all",
            "exists",
            "remove",
            "remove_dir",
            "remove_all",
            "list_dir",
            "create_dir",
            "create_dir_all",
            "is_dir",
            "copy",
            "copy_dir",
            "symlink",
            "read_link",
            "hard_link",
            "rename",
            "stat",
            "canonicalize",
            "absolute",
            "walk",
            "glob",
            "read_at",
            "write_at",
            "fsync",
            "write_atomic",
            "temp_dir",
            "temp_file",
            "lock",
            "open",
            "create",
            "append",
        ],
        "core.watcher" => &["files", "process_pid", "port", "set"],
        "core.path" => &["join", "parent", "extension", "normalize"],
        "core.url" => &[
            "parse",
            "from_parts",
            "file",
            "data",
            "query",
            "percent_encode",
            "percent_decode",
        ],
        "core.mime" => &["parse", "from_extension", "extension"],
        // D-EMAIL1=A / D-EMAIL-SMTP-SURFACE1=A: exact ungated email values.
        "core.email" => &[
            Syntax::TYPE_EMAIL_ADDRESS, Syntax::TYPE_EMAIL_MESSAGE, Syntax::TYPE_EMAIL_ATTACHMENT,
            Syntax::TYPE_EMAIL_ENVELOPE, Syntax::TYPE_EMAIL_SMTP_SECURITY,
            Syntax::TYPE_EMAIL_RECIPIENT_POLICY, Syntax::TYPE_EMAIL_RECIPIENT_REPORT,
            Syntax::TYPE_EMAIL_SEND_REPORT, Syntax::TYPE_EMAIL_ERROR,
            Syntax::TYPE_EMAIL_LIMITS, Syntax::TYPE_EMAIL_SMTP_AUTH,
            Syntax::TYPE_EMAIL_TLS_TRUST, Syntax::TYPE_EMAIL_SMTP_CONFIG,
            Syntax::TYPE_EMAIL_MAILER,
            Syntax::CORE_EMAIL_ADDRESS_FN, Syntax::CORE_EMAIL_ATTACHMENT_FN,
            Syntax::CORE_EMAIL_MESSAGE_FN, Syntax::CORE_EMAIL_ENVELOPE_FN,
            Syntax::CORE_EMAIL_SERIALIZE_FN,
            Syntax::CORE_EMAIL_SMTP_FN, Syntax::CORE_EMAIL_SMTP_FROM_ENV_FN,
        ],
        // D-DEFER1 option B: scope-exit guard.
        "core.scope" => &["guard"],
        // D-ARGS1 (ratified 2026-06-22): declarative CLI arg parsing.
        "core.args" => &["spec"],
        // D-ANY-JAI1 (c7jaiany §6): the runtime reflection floor.
        "core.reflect" => &["of"],
        // D-FRONTENDAPI1=A: stable read-only front-end values. The calls are
        // compile-time-only; their value methods are listed in core_types and
        // dispatched by the comptime evaluator.
        "core.compiler" => &["lex", "parse", "check", "source_map"],
        // D-SHIFT1 (c7shift): `Reader.over(bytes)`/`Cursor.over(s)` are bare
        // static constructors (no import needed, D-PATHFS1's `Path.from`
        // shape) — these module entries exist for discoverability/docs only.
        "core.binary" => &["Reader"],
        "core.text" => &[
            "Cursor",
            "nfc",
            "nfd",
            "nfkc",
            "nfkd",
            "casefold",
            "caseless_eq",
            "lower",
            "upper",
            "graphemes",
            "words",
            "sentences",
            "display_width",
            "scalar_count",
            "byte_count",
            "is_alphabetic",
            "is_numeric",
            "is_whitespace",
            "is_ascii",
            "scalars",
            "splitn",
            "rsplitn",
            "trim",
            "trim_start",
            "trim_end",
            "pad_start",
            "pad_end",
            "center",
            "starts_any",
            "ends_any",
            "char_indices",
        ],
        "core.fmt" => &[
            "number",
            "decimal",
            "percent",
            "bytes",
            "duration",
            "ordinal",
            "plural",
            "pad_left",
            "pad_right",
            "pad_center",
        ],
        // D-TERM1 (ratified 2026-06-22): terminal direct-input primitive.
        "core.term" => &["read_key"],
        "core" => &[],
        // D-CORENS-CANON1: ring packages normalize to `jet.*` internal key via
        // normalize_core_module; `core.*` is only the user-facing spelling.
        "jet.log" => &[
            "info",
            "warn",
            "error",
            "debug",
            "field",
            "int",
            "float",
            "bool",
            "redact",
            "info_fields",
            "warn_fields",
            "error_fields",
            "debug_fields",
            "span",
            "enter",
            "close",
            "set_sink",
            "sample_every",
            "counter",
            "otlp_file",
            "set_level",
            "set_trace_id",
            "setup",
        ],
        "jet.crypto" => &[
            "Secret",
            "SigningKey",
            "VerifyKey",
            "X25519SecretKey",
            "X25519PublicKey",
            "SharedSecret",
            "Signature",
            "Sealed",
            "WrappedKey",
            "PasswordHash",
            "Digest256",
            "Digest512",
            "CryptoError",
            "FileCryptoError",
            "sha256",
            "sha256_bytes",
            "sha512_bytes",
            "blake3_bytes",
            "constant_time_equal_bytes",
            "hkdf_sha256",
            "x25519_public",
            "x25519_shared",
            "password_hash",
            "password_hash_with_salt",
            "password_verify",
            "seal",
            "open",
            "file_seal",
            "file_open",
            "sign",
            "verify",
            "wrap",
            "unwrap",
            "x25519",
            "blake3",
            "sha512",
            "constant_time_equal",
        ],
        // D-CRYPTO-API1=A: exact expert surface — every call is #Unsafe-gated.
        "core.crypto.expert" => &[
            "xchacha20poly1305_seal",
            "xchacha20poly1305_open",
            "aes256gcm_seal",
            "aes256gcm_open",
            "open_v1",
            "migrate_v1",
            "ed25519_sign",
            "ed25519_verify_strict",
            "x25519",
            "hkdf_sha256",
            "argon2id",
            "secret_bytes",
            "signing_key_bytes",
            "x25519_secret_bytes",
            "shared_secret_bytes",
        ],
        // D-CORE-SECRETS1=A: generic TTL remains separate from secret lifecycle.
        "core.time.expiring" => &[],
        // E2-M10: networking modules.
        "core.net" => &[
            "ip_addr",
            "ip_to_string",
            "ip_is_ipv4",
            "socket_addr",
            "socket_addr_parse",
            "socket_host",
            "socket_port",
            "socket_to_string",
            "tcp_listen",
            "tcp_listen_addr",
            "tcp_accept",
            "tcp_connect",
            "tcp_connect_addr",
            "tcp_connect_timeout",
            "tcp_connect_happy",
            "tcp_read",
            "tcp_write",
            "tcp_read_bytes",
            "tcp_read_text",
            "tcp_write_bytes",
            "tcp_write_all_bytes",
            "tcp_write_text",
            "tcp_shutdown",
            "tcp_close",
            "tcp_ready",
            "ready_readable",
            "ready_writable",
            "error_operation",
            "error_address",
            "error_name",
            "error_message",
            "error_os_code",
            "tcp_local_addr",
            "tcp_peer_addr",
            "tcp_local_socket_addr",
            "tcp_peer_socket_addr",
            "listener_local_socket_addr",
            "set_timeout",
            "set_read_timeout",
            "set_write_timeout",
            "tcp_reply",
            "udp_bind",
            "udp_bind_addr",
            "udp_local_addr",
            "udp_set_timeout",
            "udp_send_to",
            "udp_recv_from",
            "udp_send_bytes_to",
            "udp_receive",
            "udp_packet_data",
            "udp_packet_addr",
            "udp_packet_bytes",
            "udp_packet_original_len",
            "udp_packet_truncated",
            "unix_listen",
            "unix_accept",
            "unix_connect",
            "unix_read",
            "unix_write",
            "unix_read_bytes",
            "unix_write_all_bytes",
            "unix_shutdown",
            "unix_close",
            "dns_a",
            "dns_aaaa",
            "dns_a_at",
            "dns_aaaa_at",
            "dns_txt",
            "dns_txt_at",
            "dns_srv",
            "dns_srv_at",
            "dns_srv_target",
            "dns_srv_port",
            "dns_srv_priority",
            "dns_srv_weight",
            "tls_connect",
            "tls_read",
            "tls_write",
            "tls_close",
        ],
        "core.tls" => &[
            "ClientConfig", "RootCertificates", "ClientIdentity", "TLSVersion",
            "client", "read", "read_text", "write", "write_all", "write_text", "close",
        ],
        "jet.http" => &["get", "post", "serve"],
        // D-REGEXENGINE1=A: std-only linear regex package.
        "jet.regex" => &[
            "flags",
            "compile",
            "compile_with",
            "is_match",
            "match",
            "find",
            "find_all",
            "matches",
            "replace",
            "replace_all",
            "split",
            "split_limit",
        ],
        // D-CORE-COMPRESS1=A: archive owns containers; stream codecs live in
        // core.compress with no archive re-export.
        "core.archive" => &[
            "zip_compress",
            "zip_decompress",
            "tar_add",
            "tar_get",
            "tar_names_json",
        ],
        // D-RAYLIB1=A: typed graphics bridge.
        "core.raylib" => &[
            "window_open",
            "window_should_close",
            "window_ready",
            "begin_drawing",
            "clear_background",
            "draw_rectangle",
            "draw_text",
            "end_drawing",
            "close_window",
            "key_down",
            "set_target_fps",
            "color",
            "load_sound",
            "play_sound",
        ],
        // D-CORE-COMPRESS1=A / D-CODECS1: canonical stream codecs.
        "core.compress.gzip" => &["compress", "decompress"],
        "core.compress.zstd" => &["compress", "decompress"],
        // D-DEP-DB1: SQLite ring package.
        // D-DBDRIVER1: `close`/`query`/`query_one`/`execute`/`begin`/`commit`/
        // `rollback` are `DBConnection` instance methods, not module items.
        "jet.db" => &[
            "open",
            "open_memory",
            "policy",
            "params",
            "row_value",
            "row_int",
            "row_float",
            "row_text",
            "row_bool",
            "transaction",
            "migrate",
        ],
        // D-DEP-WASM1=A: sandboxed WASM plugin loader ring package.
        "jet.plugin" => &["load"],
        // D-REACT1=B: opt-in reactive library — signals/derived/effects.
        // D-SIGNAL1: "computed" is the canonical alias for "derived".
        "jet.reactive" => &["signal", "derived", "computed", "effect"],
        // D-EVENT1=D: first-party typed Event/Hook family.
        "core.event" => &[
            "new",
            "with_policy",
            "hook",
            "decision_hook",
            "scope",
            "policy_sync",
            "async_result",
        ],
        // D-HONESTNUM1=A: Measurement<T> constructor.
        "core.science.measurement" => &["from"],
        // D-PENDING1=B: Loadable<T,E> constructors.
        "core.reactive.loadable" => &["idle", "loading", "loaded", "failed"],
        // D-FIDELITY-API1=A: runtime-global fidelity signal.
        "core.perf" => &[
            "Perf",
            "fidelity",
            "default_fidelity",
            "override_fidelity",
            "reset_fidelity",
        ],
        // D-RENDERTGT2=A (c133 M1): UI backend seam.
        "core.ui" => &[
            "null_backend",
            "tui_backend",
            // D-UIDEVSHELL1=A (c134 Phase 8): native Linux GTK4 backend.
            "gtk_backend",
            "reactive_render",
            // D-UI-MOUNT1=A: one-call measure→layout→paint.
            "mount",
            "point",
            "size",
            "rect",
            "constraint",
            "node",
            "key_event",
            "resize_event",
            // D-A11YGATE1=B (c134 Phase 6): accessible-role node + role constants.
            "node_role",
            "aria_role_button",
            "aria_role_text_input",
            "aria_role_label",
            "aria_role_container",
            // D-STYLESHAPE1=A (c134 Phase 3/7 wiring): a typed-Color-backed node —
            // the paint pipeline's fill color is no longer hardcoded.
            "node_color",
            // D-UITREE1=A: one typed component tree for every backend.
            "text",
            "box",
            "button",
        ],
        // D-FLAGSHIP-WEBAPI1=A: browser events and storage. The intermediate
        // `storage` module exists so `web.storage.local.get(...)` resolves as a
        // real nested core module, not a magic field.
        // D-WEBAPP1=D / D-WEBAUTHOR1=D: full-stack application builder + browser APIs.
        "core.web" => &[
            "on", "value", "storage", "app", "page", "App", "Page", "Context", "Mount",
            "live", "subscribe", "invalidate", "transact_invalidate", "signal_push",
            "live_get", "live_show", "live_stats",
            "auth", "auth_oauth", "auth_routes", "auth_show", "sync_over", "sync",
            "LiveQuery", "Auth", "Session",
        ],
        // D-LIVEQUERY1=A / D-AUTH1=A: application live-query + auth surface.
        "app" => &[
            "live", "subscribe", "invalidate", "transact_invalidate", "signal_push",
            "live_get", "live_show", "live_stats",
            "auth", "auth_oauth", "auth_routes", "auth_show", "sync_over", "sync",
            "LiveQuery", "Auth", "Session",
        ],
        "core.web.storage" => &["local", "session"],
        "core.web.storage.local" | "core.web.storage.session" => &["get", "set", "remove", "clear"],
        // c-devserver (owner-directed 2026-07-01): `jet dev` server builder.
        "core.web.devserver" => &["for_app", "app"],
        // D-APPROX1=A: approximate sketch data structures.
        "core.sketch.hll" => &["new"],
        "core.sketch.tdigest" => &["new"],
        "core.sketch.cms" => &["new"],
        "core.sketch.reservoir" => &["new"],
        // D-TIMEDEPTH1=A: civil-time constructors.
        "core.time.date" => &["new", "today", "parse"],
        "core.time.datetime" => &["from_timestamp", "now"],
        // D-NETDEP1=A / D-HTTPLIB1=A / D-HTTPLIB2=B: HTTP library.
        "core.http.client" => &["Client", "Proxy", "RedirectPolicy", "get", "post", "request"],
        "core.http.server" => &[
            "bind",
            "mux",
            "serve",
            "serve_once",
            "serve_once_listener",
            "response",
            "tls",
            "sse",
            "static_file",
            "static_file_range",
            "access_log",
            "request_id",
            // D-HTTP-JSON1=A / D-HTTP-STATIC-FILES1=A / D-HTTP-CORS1=A: the
            // everyday web-service defaults.
            "json",
            "static_files",
            "cors",
            "cors_policy",
        ],
        // D-WS1=B: standalone RFC6455 client/server entry points.
        "core.ws" => &["connect", "upgrade"],
        // D-BROWSER-AUTO1=A: native BiDi profile/session entry points.
        "core.browser" => &[
            "Browser", "BrowserContext", "BrowserPage", "BrowserFrame", "BrowserLocator",
            "BrowserIntercept",
            "BrowserEvent", "BrowserTrace", "BrowserReceipt", "BrowserPrivacy", "BrowserError",
            "BrowserCapabilities",
            "BrowserProfile", "BrowserTimeout", "BrowserProtocol", "BrowserLocked",
            "profile", "timeout", "locked", "connect", "connect_profile",
        ],
        // U13 (D-JPK-SECRETCRYPTO1): decrypted-repo-secret read, age-style
        // crypto FFI bridge.
        // D-CORE-SECRETS1=A: one home for encrypted storage and lifecycle.
        "core.vault" => &[
            "ExpiringSecret", "KeyRef", "MutationPlan", "VaultWrite", "Rotation", "WrappedImportPlan",
            "KeyStatus", "VaultError", "WrappedVaultKey", "KeyUnlock", "KeyWrapError",
            "get", "current", "versions", "load", "status",
            "prepare_generate", "prepare_store", "prepare_rotate", "prepare_retire", "prepare_revoke",
            "authorize_write", "commit_generate", "commit_store", "commit_rotate", "commit_retire", "commit_revoke",
            "export_to_recipients", "export_to_passphrase", "prepare_import_wrapped",
            "authorize_wrapped_import", "commit_import_wrapped",
        ],
        "core.vault.expert" => &["prepare_import_signing", "prepare_import_x25519", "commit_import_signing", "commit_import_x25519"],
        // D-AUTH1=A / D-AUTH2=A: token verify + session batteries.
        "core.auth" => &[
            "verify_jwt",
            "verify_paseto",
            "register_user",
            "password_login",
            "session_validate",
            "session_show",
            "session_user",
            "session_cookie",
            "session_id",
            "magic_link_issue",
            "magic_link_consume",
            "oauth_begin",
            "oauth_finish",
            "Claims",
            "AuthError",
            "Session",
            "Auth",
        ],
        // D-SYNC1=A / D-DBPOLICY1=A.
        "core.sync" => &[
            "text_new",
            "text_set",
            "text_merge",
            "text_show",
            "counter_new",
            "counter_inc",
            "counter_merge",
            "counter_value",
            "map_new",
            "map_set",
            "map_get",
            "map_merge",
            "map_show",
            "list_new",
            "list_push",
            "list_merge",
            "list_show",
            "policy_new",
            "policy_allows",
            "policy_show",
            "SyncText",
            "SyncCounter",
            "SyncMap",
            "SyncList",
            "RowPolicy",
        ],
        _ => &[],
    };
    items.iter().map(|s| s.to_string()).collect()
}

/// Ratified nominal types exported by a Core module. Separate from callable
/// items so `alias.Type.method()` is a static type call, not a nested module.
pub(crate) fn core_module_type_item(module: &str, item: &str) -> bool {
    let module = Syntax::normalize_core_module(module).unwrap_or_else(|| module.to_string());
    if module == "core.lang" {
        return crate::Policy::rule_arg_declaration(item).is_some();
    }
    matches!(
        (module.as_str(), item),
        ("jet.crypto", "Secret" | "SigningKey" | "VerifyKey" | "X25519SecretKey"
            | "X25519PublicKey" | "SharedSecret" | "Signature" | "Sealed" | "WrappedKey"
            | "PasswordHash" | "Digest256" | "Digest512" | "CryptoError" | "FileCryptoError")
        // D-AUTH-TOKENPOLICY1=A: typed verifier result and error records.
        | ("core.auth", "Claims" | "AuthError" | "Session" | "Auth")
        | ("core.sync", "SyncText" | "SyncCounter" | "SyncMap" | "SyncList" | "RowPolicy")
        | ("core.vault", "ExpiringSecret" | "KeyRef" | "MutationPlan" | "VaultWrite" | "Rotation" | "WrappedImportPlan"
            | "KeyStatus" | "VaultError" | "WrappedVaultKey" | "KeyUnlock" | "KeyWrapError")
        | ("core.tls", "ClientConfig" | "RootCertificates" | "ClientIdentity" | "TLSVersion")
        | ("jet.http" | "core.http.client" | "core.http.server",
            "Method" | "Status" | "Version" | "HeaderName" | "HeaderValue"
            | "Headers" | "Request" | "Response" | "Body" | "Handler" | "HTTPError" | "Client" | "Proxy")
        | ("core.browser",
            "Browser" | "BrowserContext" | "BrowserPage" | "BrowserFrame" | "BrowserLocator"
            | "BrowserIntercept"
            | "BrowserEvent" | "BrowserTrace" | "BrowserReceipt" | "BrowserPrivacy" | "BrowserError"
            | "BrowserCapabilities"
            | "BrowserProfile" | "BrowserTimeout" | "BrowserProtocol" | "BrowserLocked")
        // D-WEBAPP1=D: namespaced `web.App` / `web.Page` / `web.Context` / `web.Mount`.
        | ("core.web", "App" | "Page" | "Context" | "Mount")
    )
}
