use crate::AST::Type;
use crate::Diagnostics::{Diagnostic, Span};
use super::alloc_ptrs::result_ty;
use super::core_types::{u8_ty, unit_ty};

/// E2-M10: type-check a method call on a networking opaque type.
/// Returns `Some(return_type)` when the method is valid.
pub fn net_method_return(
    type_name: &str,
    method: &str,
    n_args: usize,
    _span: Span,
    _diags: &mut Vec<Diagnostic>,
) -> Option<Option<Type>> {
    let str_ty = Type::String;
    let unit = unit_ty();
    let err = Type::Named("NetError".to_string());
    match (type_name, method) {
        // HttpResponse field accessors (via method-style read, auto-generated by codegen).
        ("HttpResponse", "status") => Some(Some(str_ty.clone())),
        ("HttpResponse", "body") => Some(Some(str_ty.clone())),
        ("HttpResponse", "header") => Some(Some(Type::Option(Box::new(str_ty.clone())))),
        // HttpRequest field accessors.
        ("HttpRequest", "method") => Some(Some(str_ty.clone())),
        ("HttpRequest", "path") => Some(Some(str_ty.clone())),
        ("HttpRequest", "body") => Some(Some(str_ty.clone())),
        ("HttpRequest", "header") => Some(Some(Type::Option(Box::new(str_ty.clone())))),
        // D-ROUTE1=A: req.param("name") → String? (none if not a param route or name absent).
        ("HttpRequest", "param") => Some(Some(Type::Option(Box::new(str_ty.clone())))),
        // D-ROUTE1=A: HttpRouter registration methods.
        ("HttpRouter", "get" | "post" | "put" | "delete") => Some(Some(unit.clone())),
        // TcpListener methods.
        ("TcpListener", "accept") => Some(Some(result_ty(
            Type::Named("TcpStream".to_string()),
            err.clone(),
        ))),
        ("TcpListener", "local_addr") => Some(Some(result_ty(str_ty.clone(), err.clone()))),
        // TcpStream methods.
        ("TcpStream", "read") if n_args == 0 => Some(Some(result_ty(str_ty.clone(), err.clone()))),
        ("TcpStream", "read") if n_args == 1 => Some(Some(result_ty(
            Type::List(Box::new(u8_ty())),
            Type::Named("NetError".to_string()),
        ))),
        ("TcpStream", "read_text") if n_args == 1 => Some(Some(result_ty(
            str_ty.clone(),
            Type::Named("NetError".to_string()),
        ))),
        ("TcpStream", "write") if n_args == 1 => Some(Some(result_ty(
            Type::Int,
            Type::Named("NetError".to_string()),
        ))),
        ("TcpStream", "write_all" | "write_text" | "shutdown") if n_args == 1 => Some(Some(result_ty(
            unit.clone(),
            Type::Named("NetError".to_string()),
        ))),
        ("TcpStream", "ready") if n_args == 2 => Some(Some(result_ty(
            Type::Named("NetReady".to_string()),
            Type::Named("NetError".to_string()),
        ))),
        ("TcpStream", "peer_addr") => Some(Some(result_ty(str_ty.clone(), err.clone()))),
        ("TcpStream", "local_addr") => Some(Some(result_ty(str_ty.clone(), err.clone()))),
        ("TcpStream", "close") => Some(Some(result_ty(
            unit,
            Type::Named("NetError".to_string()),
        ))),
        _ => None,
    }
}

/// D-REGEXENGINE1=A: method return types for std-only regex values.
pub fn regex_method_return(
    ty: &Type,
    method: &str,
    args: &[crate::AST::CallArg],
) -> Option<Option<Type>> {
    let argc = args.len();
    match ty {
        Type::Named(n) if n == "Regex" => match method {
            "is_match" if argc == 1 => Some(Some(Type::Bool)),
            "match" if argc == 1 => Some(Some(Type::Option(Box::new(Type::Named(
                "Match".to_string(),
            ))))),
            "find" if argc == 1 => Some(Some(Type::Option(Box::new(Type::String)))),
            "find_all" | "split" if argc == 1 => Some(Some(Type::List(Box::new(Type::String)))),
            "matches" if argc == 1 => {
                Some(Some(Type::List(Box::new(Type::Named("Match".to_string())))))
            }
            "replace" | "replace_all" if argc == 2 => Some(Some(Type::String)),
            "split_limit" if argc == 2 => Some(Some(Type::List(Box::new(Type::String)))),
            "replace_all_with" if argc == 2 => Some(Some(Type::String)),
            _ => None,
        },
        Type::Named(n) if n == "Match" => match method {
            "group" | "name" if argc == 1 => Some(Some(Type::Option(Box::new(Type::String)))),
            "start" | "end" if argc == 0 => Some(Some(Type::Int)),
            "group_start" | "group_end" if argc == 1 => {
                Some(Some(Type::Option(Box::new(Type::Int))))
            }
            _ => None,
        },
        _ => None,
    }
}

/// D-PATHFS1: return type for `Path` instance method calls.
/// D-PENDING1=B: instance methods on `Loadable<T, E>`.
/// Returns `Some(Some(T))` for a valid method, `None` if not a Loadable method.
pub fn loadable_method_return(
    type_apply: &Type,
    method: &str,
    _n_args: usize,
) -> Option<Option<Type>> {
    let (val_ty, _err_ty) = match type_apply {
        Type::Apply { name, args } if name == "Loadable" && args.len() == 2 => {
            (args[0].clone(), args[1].clone())
        }
        _ => return None,
    };
    match method {
        "is_loading" => Some(Some(Type::Bool)),
        "is_loaded" => Some(Some(Type::Bool)),
        "is_failed" => Some(Some(Type::Bool)),
        "is_idle" => Some(Some(Type::Bool)),
        // loaded() → T? — returns the value if in Loaded state, null otherwise.
        "loaded" => Some(Some(Type::Option(Box::new(val_ty)))),
        // or_else(default: T) → T
        "or_else" => Some(Some(val_ty)),
        _ => None,
    }
}

/// D-TTLVAL1=A: instance methods on `Expiring<T>` / `Rotting<T>`.
pub fn expiring_method_return(
    type_apply: &Type,
    method: &str,
    _n_args: usize,
) -> Option<Option<Type>> {
    let val_ty = match type_apply {
        Type::Apply { name, args } if name == "Expiring" && args.len() == 1 => args[0].clone(),
        _ => return None,
    };
    match method {
        "get" => Some(Some(Type::Result {
            ok: Box::new(val_ty),
            err: Box::new(Type::Named("Expired".to_string())),
        })),
        "is_valid" => Some(Some(Type::Bool)),
        "force" => Some(Some(val_ty)), // sema rejects the call site separately (E0511)
        _ => None,
    }
}

pub fn rotting_method_return(
    type_apply: &Type,
    method: &str,
    _n_args: usize,
) -> Option<Option<Type>> {
    let val_ty = match type_apply {
        Type::Apply { name, args } if name == "Rotting" && args.len() == 1 => args[0].clone(),
        _ => return None,
    };
    match method {
        "get" => Some(Some(Type::Result {
            ok: Box::new(val_ty),
            err: Box::new(Type::Named("Expired".to_string())),
        })),
        "is_valid" => Some(Some(Type::Bool)),
        "force" => Some(Some(val_ty)),
        _ => None,
    }
}

/// D-NETDEP1=A / D-HTTPLIB1=A: method return types for HTTP types.
pub fn http_type_method_return(
    ty: &Type,
    method: &str,
    _args: &[crate::AST::CallArg],
) -> Option<Option<Type>> {
    let mk = |n: &str| Some(Some(Type::Named(n.to_string())));
    let mk_str = || Some(Some(Type::String));
    let mk_int = || Some(Some(Type::Int));
    let mk_opt_str = || Some(Some(Type::Option(Box::new(Type::String))));
    match ty {
        Type::Named(n) if n == "HttpClientReq" => match method {
            "header" | "body" | "timeout" | "connect_timeout" | "read_timeout"
            | "total_timeout" | "redirects" | "proxy" | "cookie" | "form" | "multipart_text" => {
                mk("HttpClientReq")
            }
            "send" => Some(Some(Type::Result {
                ok: Box::new(Type::Named("HttpClientResp".to_string())),
                err: Box::new(Type::String),
            })),
            _ => None,
        },
        Type::Named(n) if n == "HttpClientResp" => match method {
            "status" => mk_int(),
            "body" => mk_str(),
            "header" => mk_opt_str(),
            "cookies" => Some(Some(Type::List(Box::new(Type::String)))),
            _ => None,
        },
        Type::Named(n) if n == "HttpMux" => match method {
            "get" | "post" | "put" | "delete" | "patch" | "head" | "options" | "middleware" => Some(None),
            _ => None,
        },
        Type::Named(n) if n == "HttpHandler" => match method {
            "handle" => mk("HttpSrvResp"),
            _ => None,
        },
        Type::Named(n) if n == "HttpSrvReq" => match method {
            "method" | "path" | "body" => mk_str(),
            "param" | "header" => mk_opt_str(),
            "body_len" => mk_int(),
            "under_limit" => Some(Some(Type::Bool)),
            _ => None,
        },
        Type::Named(n) if n == "HttpSrvResp" => match method {
            "header" => mk("HttpSrvResp"),
            "status" => mk_int(),
            "body" => mk_str(),
            _ => None,
        },
        Type::Named(n) if n == "HttpServer" => match method {
            "local_addr" => Some(Some(Type::Result { ok: Box::new(Type::String), err: Box::new(Type::String) })),
            "serve" | "shutdown" => Some(Some(Type::Result {
                ok: Box::new(Type::Named("HttpShutdownReport".to_string())),
                err: Box::new(Type::String),
            })),
            _ => None,
        },
        _ => None,
    }
}

/// D-URL1=A: method return types for typed URL and MIME values.
pub fn url_mime_method_return(
    ty: &Type,
    method: &str,
    args: &[crate::AST::CallArg],
) -> Option<Option<Type>> {
    let argc = args.len();
    match ty {
        Type::Named(n) if n == "Url" => match method {
            "scheme" | "path" | "query" | "to_string" if argc == 0 => Some(Some(Type::String)),
            "host" | "fragment" if argc == 0 => Some(Some(Type::Option(Box::new(Type::String)))),
            "port" if argc == 0 => Some(Some(Type::Option(Box::new(Type::Int)))),
            "path_segments" if argc == 0 => Some(Some(Type::List(Box::new(Type::String)))),
            "query_pairs" if argc == 0 => Some(Some(Type::List(Box::new(Type::List(Box::new(
                Type::String,
            )))))),
            "normalize" if argc == 0 => Some(Some(Type::Named("Url".to_string()))),
            "join" if argc == 1 => Some(Some(result_ty(
                Type::Named("Url".to_string()),
                Type::String,
            ))),
            "set_query" | "add_query" if argc == 2 => Some(Some(Type::Named("Url".to_string()))),
            _ => None,
        },
        Type::Named(n) if n == "Mime" => match method {
            "media_type" | "subtype" | "essence" | "to_string" if argc == 0 => {
                Some(Some(Type::String))
            }
            "param" if argc == 1 => Some(Some(Type::Option(Box::new(Type::String)))),
            "params" if argc == 0 => Some(Some(Type::List(Box::new(Type::List(Box::new(
                Type::String,
            )))))),
            _ => None,
        },
        _ => None,
    }
}

/// D-TIMEDEPTH1/D-TIME-CALENDAR1: method return types for civil-time values.
pub fn civil_time_method_return(
    ty: &Type,
    method: &str,
    args: &[crate::AST::CallArg],
) -> Option<Option<Type>> {
    let argc = args.len();
    match ty {
        Type::Named(n) if n == "Date" || n == "LocalDate" => match method {
            "year" | "month" | "day" | "weekday" | "iso_weekday" | "day_of_year" | "iso_week"
                if argc == 0 =>
            {
                Some(Some(Type::Int))
            }
            "diff_days" if argc == 1 => Some(Some(Type::Int)),
            "add_days" | "add_months" | "truncate" if argc == 1 => {
                Some(Some(Type::Named("LocalDate".to_string())))
            }
            "add_period" if argc == 1 => Some(Some(Type::Named("LocalDate".to_string()))),
            "to_string" if argc == 0 => Some(Some(Type::String)),
            "format" if argc == 1 => Some(Some(Type::String)),
            _ => None,
        },
        Type::Named(n) if n == "LocalTime" => match method {
            "hour" | "minute" | "second" if argc == 0 => Some(Some(Type::Int)),
            "to_string" if argc == 0 => Some(Some(Type::String)),
            _ => None,
        },
        Type::Named(n) if n == "DateTime" => match method {
            "hour" | "minute" | "second" | "to_timestamp" | "to_unix_ms" if argc == 0 => {
                Some(Some(Type::Int))
            }
            "date" if argc == 0 => Some(Some(Type::Named("LocalDate".to_string()))),
            "time" if argc == 0 => Some(Some(Type::Named("LocalTime".to_string()))),
            "plus_duration" | "truncate" | "round" if argc == 1 => {
                Some(Some(Type::Named("DateTime".to_string())))
            }
            "in_zone" if argc == 1 => Some(Some(Type::Named("ZonedDateTime".to_string()))),
            "to_string" | "format_rfc3339" if argc == 0 => Some(Some(Type::String)),
            "format" if argc == 1 => Some(Some(Type::String)),
            _ => None,
        },
        Type::Named(n) if n == "Instant" => match method {
            "elapsed_millis" if argc == 0 => Some(Some(Type::Int)),
            _ => None,
        },
        Type::Named(n) if n == "Period" => match method {
            "to_string" if argc == 0 => Some(Some(Type::String)),
            _ => None,
        },
        Type::Named(n) if n == "Zone" => match method {
            "name" if argc == 0 => Some(Some(Type::String)),
            _ => None,
        },
        Type::Named(n) if n == "ZonedDateTime" => match method {
            "date" if argc == 0 => Some(Some(Type::Named("LocalDate".to_string()))),
            "time" if argc == 0 => Some(Some(Type::Named("LocalTime".to_string()))),
            "offset_seconds" if argc == 0 => Some(Some(Type::Int)),
            "to_datetime" if argc == 0 => Some(Some(Type::Named("DateTime".to_string()))),
            "zone" if argc == 0 => Some(Some(Type::Named("Zone".to_string()))),
            "add_duration" | "add_period" if argc == 1 => {
                Some(Some(Type::Named("ZonedDateTime".to_string())))
            }
            "to_string" if argc == 0 => Some(Some(Type::String)),
            "format" if argc == 1 => Some(Some(Type::String)),
            _ => None,
        },
        _ => None,
    }
}

/// D-APPROX1=A: return the type name string for a sketch receiver type.
pub fn sketch_type_name(ty: &Type) -> Option<&'static str> {
    match ty {
        Type::Named(n) => match n.as_str() {
            "HyperLogLog" => Some("HyperLogLog"),
            "TDigest" => Some("TDigest"),
            "CountMinSketch" => Some("CountMinSketch"),
            "ReservoirSampler" => Some("ReservoirSampler"),
            _ => None,
        },
        _ => None,
    }
}

/// D-APPROX1=A: method return types for sketch data structures.
pub fn sketch_method_return(
    ty: &Type,
    method: &str,
    _args: &[crate::AST::CallArg],
) -> Option<Option<Type>> {
    let name = sketch_type_name(ty)?;
    match (name, method) {
        ("HyperLogLog", "add") => Some(None), // void
        ("HyperLogLog", "count") => Some(Some(Type::Int)),
        ("TDigest", "add") => Some(None),
        ("TDigest", "quantile") => Some(Some(Type::Float)),
        ("CountMinSketch", "add") => Some(None),
        ("CountMinSketch", "count") => Some(Some(Type::Int)),
        ("ReservoirSampler", "add") => Some(None),
        ("ReservoirSampler", "sample") => Some(Some(Type::List(Box::new(Type::String)))),
        _ => None,
    }
}

pub fn path_method_return(
    type_name: &str,
    method: &str,
    _n_args: usize,
    _span: Span,
    _diags: &mut Vec<Diagnostic>,
) -> Option<Option<Type>> {
    if type_name != "Path" {
        return None;
    }
    let path = || Type::Named("Path".to_string());
    match method {
        "join" => Some(Some(path())),
        "parent" => Some(Some(Type::Option(Box::new(path())))),
        "extension" => Some(Some(Type::Option(Box::new(Type::String)))),
        "stem" => Some(Some(Type::Option(Box::new(Type::String)))),
        "to_string" => Some(Some(Type::String)),
        "write_atomic" => Some(Some(result_ty(unit_ty(), Type::String))),
        "walk" => Some(Some(Type::List(Box::new(path())))),
        _ => None,
    }
}

/// D-SHIFT1 (c7shift): a Jet-sized unsigned int type (`U8`/`U16`/`U32`/`U64`),
/// the return type of `Reader`'s width-specific reads.
fn uintn_ty(bits: u8) -> Type {
    Type::IntN {
        signed: false,
        bits,
    }
}

/// D-SHIFT1 (c7shift): method calls on `binary.Reader` (`Reader.over(bytes)`
/// static constructor is handled in `CheckerInfer/calls.rs`, mirroring
/// `Path.from`). Every read is fallible — a bounds miss is an ordinary `?`
/// error value (`Result<T, String>`, `path_method_return`'s exact error-type
/// convention above), never a panic or silent truncation (I1/L2).
pub fn binary_reader_method_return(
    type_name: &str,
    method: &str,
    n_args: usize,
) -> Option<Option<Type>> {
    if type_name != "Reader" {
        return None;
    }
    let bytes = || Type::List(Box::new(u8_ty()));
    match (method, n_args) {
        ("read_u8", 0) => Some(Some(result_ty(uintn_ty(8), Type::String))),
        ("read_u16_le" | "read_u16_be", 0) => Some(Some(result_ty(uintn_ty(16), Type::String))),
        ("read_u32_le" | "read_u32_be", 0) => Some(Some(result_ty(uintn_ty(32), Type::String))),
        ("read_u64_le" | "read_u64_be", 0) => Some(Some(result_ty(uintn_ty(64), Type::String))),
        ("take", 1) => Some(Some(result_ty(bytes(), Type::String))),
        ("remaining", 0) => Some(Some(Type::Int)),
        ("is_at_end", 0) => Some(Some(Type::Bool)),
        _ => None,
    }
}

/// D-SHIFT1 (c7shift): method calls on `text.Cursor` (`Cursor.over(s)` static
/// constructor is handled in `CheckerInfer/calls.rs`). `take_pattern` is NOT
/// listed here — it needs its pattern-literal argument's hole types to
/// compute a return type, so it's dispatched directly at the call site
/// (`CheckerInfer/calls.rs`), for the same reason `Arena.alloc` is
/// resolved outside their generic method-return tables.
pub fn text_cursor_method_return(
    type_name: &str,
    method: &str,
    n_args: usize,
) -> Option<Option<Type>> {
    if type_name != "Cursor" {
        return None;
    }
    match (method, n_args) {
        ("take_until", 1) => Some(Some(result_ty(Type::String, Type::String))),
        ("skip_ws", 0) => Some(Some(unit_ty())),
        _ => None,
    }
}
